SELECT 
ROWNUM AS COL1,
DENUMIRE AS COL2,
CUIIO AS COL3,
COL4,
COL5,
COL6,
COL7,
COL8
FROM

(
SELECT 
D.CUIIO,
R.DENUMIRE,
D.CUATM_FULL,
SUM(D.COL1) AS COL4,
SUM(D.COL2) AS COL5,
SUM(D.COL12) AS COL6,
SUM(D.COL13) AS COL7,
SUM(D.COL14) AS COL8


    FROM CIS2.VW_DATA_ALL D
                INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
    
    WHERE 
    D.FORM IN (:pFORM)
    AND D.PERIOADA IN (:pPERIOADA)
    AND D.CAPITOL = 1058
    AND D.RIND IN ('040')
    
    GROUP BY 
    D.CUIIO,
    R.DENUMIRE,
    D.CUATM_FULL
    
    ORDER BY
    D.CUATM_FULL
 )   
    
    
    