INSERT INTO TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW, 
  COL1,  
  COL2,
  COL3
)


SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  R.CUIIO AS NR_SECTIE,
  R.CUIIO||'-'||MAX(R.DENUMIRE) AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   RD.RIND AS NR_ROW,
   RD.ORDINE AS ORDINE,
  '111' AS DECIMAL_POS,
   REPLACE(REPLACE(REPLACE(RD.DENUMIRE,'&nbsp;'),'&'),'nbsp') AS NUME_ROW, 
   NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) THEN D.COL1 ELSE NULL END)) AS COL1,
   NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-1) THEN D.COL1 ELSE NULL END)) AS COL2,
   NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) THEN D.COL1 ELSE NULL END)) AS COL3

 FROM
              VW_DATA_ALL D
                INNER JOIN RENIM R ON (R.CUIIO= D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
                INNER JOIN MD_CAPITOL C ON (D.CAPITOL=C.CAPITOL AND D.CAPITOL_VERS=C.CAPITOL_VERS)
--                INNER JOIN VW_CL_CUATM  C ON (C.CODUL = R.CUATM AND C.FULL_CODE LIKE '%'||:pCOD_CUATM||';%')                
                INNER JOIN MD_RIND RD ON D.RIND=RD.RIND AND D.RIND_VERS=RD.RIND_VERS  AND D.CAPITOL=RD.CAPITOL 
               
WHERE
  D.FORM IN (5)                              AND 
  D.FORM_VERS = :pFORM_VERS                  AND    
  D.CAPITOL IN (310)                         AND 
  D.PERIOADA IN (:pPERIOADA, :pPERIOADA-1, :pPERIOADA-4) AND 
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' 
 -- R.CUIIO =
  --MINISTERUL TRANSPORTURILOR SI INFRASTRUCTURII DRUMURILOR
      
       
GROUP BY 
  R.CUIIO,
--  R.DENUMIRE, 
--  C.CAPITOL,
--  C.DEN_SHORT,
  RD.RIND,
  RD.ORDINE,
  RD.DENUMIRE