--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
-- -- ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
-- COL1
--)


SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  VVC.CODUL AS NR_SECTIE,
  VVC.CODUL||' '||VVC.DENUMIRE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   RD.RIND AS NR_ROW,
  '1' AS DECIMAL_POS,
   RD.DENUMIRE AS NUME_ROW, 
   SUM( D.COL1) AS COL1
  
 

 FROM
              VW_DATA_ALL D
                --INNER JOIN RENIM R ON (R.CUIIO= D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
                --INNER JOIN VW_CL_CUATM  C ON (C.CODUL = R.CUATM AND C.FULL_CODE LIKE '%'||:pCOD_CUATM||';%') 
                INNER JOIN VW_CL_CFP VC  ON (VC.CODUL = D.CFP)   
                INNER JOIN VW_CL_CFP VVC ON (VC.FULL_CODE LIKE '%'||VVC.CODUL||';%' )            
                INNER JOIN MD_RIND RD ON D.RIND=RD.RIND AND D.RIND_VERS=RD.RIND_VERS  AND D.CAPITOL=RD.CAPITOL 
               
WHERE
  D.FORM IN (5)                              AND 
  D.FORM_VERS = :pFORM_VERS                  AND    
  D.CAPITOL IN (309)                         AND 
  D.PERIOADA=:pPERIOADA AND 
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'
      
       
GROUP BY  VVC.CODUL , VVC.DENUMIRE,RD.RIND, RD.DENUMIRE

UNION

SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  VVC.CODUL AS NR_SECTIE,
  VVC.CODUL||' '||VVC.DENUMIRE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   '800' AS NR_ROW,
  '1' AS DECIMAL_POS,
   'Numarul de intreprinderi' AS NUME_ROW, 
   COUNT(DISTINCT D.CUIIO) AS COL1
  
 

 FROM
              VW_DATA_ALL D
                --INNER JOIN RENIM R ON (R.CUIIO= D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
                --INNER JOIN VW_CL_CUATM  C ON (C.CODUL = R.CUATM AND C.FULL_CODE LIKE '%'||:pCOD_CUATM||';%') 
                INNER JOIN VW_CL_CFP VC  ON (VC.CODUL = D.CFP)   
                INNER JOIN VW_CL_CFP VVC ON (VC.FULL_CODE LIKE '%'||VVC.CODUL||';%' )                  
                INNER JOIN MD_RIND RD ON D.RIND=RD.RIND AND D.RIND_VERS=RD.RIND_VERS  AND D.CAPITOL=RD.CAPITOL 
               
WHERE
  D.FORM IN (5)                              AND 
  D.FORM_VERS = :pFORM_VERS                  AND    
  D.CAPITOL IN (309)                         AND 
  D.PERIOADA=:pPERIOADA AND 
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'
      
       
GROUP BY  VVC.CODUL,VVC.DENUMIRE