--Rînd 201 col.3 (1-A-SC) ≥ Rînd 2002 col.1 (1-B-SC)  
SELECT DISTINCT
   SUM(CASE WHEN D.RIND IN('201')    THEN CIS2.NVAL(D.COL3) ELSE 0 END) ||'<'||
   SUM(CASE WHEN  D.PERIOADA IN (:PERIOADA) AND  D.RIND IN('2002')   THEN CIS2.NVAL(D.COL1) ELSE 0 END)  
   
   AS REZULTAT
  
  FROM
  CIS2.VW_DATA_ALL D INNER JOIN
  (
    SELECT P.PERIOADA FROM CIS2.VW_MD_PERIOADA P 
    WHERE P.PERIOADA = :PERIOADA 
    
    UNION   
   
   SELECT P.PERIOADA -1 FROM CIS2.VW_MD_PERIOADA P INNER JOIN CIS2.VW_MD_PERIOADA T ON(P.ANUL=T.ANUL AND P.TIP_PERIOADA=7) 
   WHERE T.PERIOADA = :PERIOADA
   
  ) P ON(D.PERIOADA=P.PERIOADA)
WHERE
  (:PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO              OR :CUIIO = -1) AND
  (:CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (:FORM = :FORM               OR :FORM = -1) AND
  (:FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (:CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (:ID_MD=:ID_MD               OR :ID_MD = -1) AND 
   
  D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('20.1011.201','19.1018.2002')
HAVING

 SUM(CASE WHEN D.RIND IN('201')  THEN CIS2.NVAL(D.COL3) ELSE 0 END) <
   
   SUM(CASE WHEN   D.PERIOADA IN (:PERIOADA) AND  D.RIND IN('2002')  THEN CIS2.NVAL(D.COL1) ELSE 0 END)