SELECT 
   'Rind. '||D.RIND||' Col 9 - ' ||
   
   CASE WHEN 
   (
  SUM(CASE WHEN D.CAPITOL IN (1034) THEN NVAL(D.COL9)  ELSE 0 END ) > 0 
  AND  
  (
  SUM(CASE WHEN D.CAPITOL IN (1035) THEN NVAL(D.COL8)  ELSE 0 END ) = 0 
  AND  
  SUM(CASE WHEN D.CAPITOL IN (1035) THEN NVAL(D.COL9)  ELSE 0 END ) = 0 
  )
  
  )
   
   THEN 'CAP.1 COL9 - ' ||SUM(CASE WHEN D.CAPITOL IN (1034) THEN NVAL(D.COL9)  ELSE 0 END )
   
   ELSE 
   'CAP.1 COL9 = 0 dar CAP 2 COL8 - '|| SUM(CASE WHEN D.CAPITOL IN (1035) THEN NVAL(D.COL8)  ELSE 0 END )
   ||' CAP 2 - COL9 - ' || SUM(CASE WHEN D.CAPITOL IN (1035) THEN NVAL(D.COL9)  ELSE 0 END )
   END 
   
   
   
 AS REZULTAT

 

FROM
  CIS2.VW_DATA_ALL D 
WHERE
 (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <>  :CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS  OR :CAPITOL_VERS <>  :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (47)  AND
  D.CAPITOL IN (1034,1035)
  GROUP BY D.RIND

HAVING
  
  (
  SUM(CASE WHEN D.CAPITOL IN (1034) THEN NVAL(D.COL9)  ELSE 0 END ) > 0 
  AND  
  (
  SUM(CASE WHEN D.CAPITOL IN (1035) THEN NVAL(D.COL8)  ELSE 0 END ) = 0 
  AND  
  SUM(CASE WHEN D.CAPITOL IN (1035) THEN NVAL(D.COL9)  ELSE 0 END ) = 0 
  )
  
  )
  
  OR 
  
  (
  SUM(CASE WHEN D.CAPITOL IN (1034) THEN NVAL(D.COL9)  ELSE 0 END ) = 0 
  AND  
  (
  SUM(CASE WHEN D.CAPITOL IN (1035) THEN NVAL(D.COL8)  ELSE 0 END ) > 0 
  AND  
  SUM(CASE WHEN D.CAPITOL IN (1035) THEN NVAL(D.COL9)  ELSE 0 END ) > 0 
  )
  
  )
  
  
  
