SELECT
   CC.CODUL,
   CC.DENUMIRE,
   CC.FULL_CODE,
   NVAL(SUM(CASE WHEN D.CAPITOL IN (1130) AND D.RIND IN ('01') THEN D.COL1 ELSE NULL END)) AS COL1,
   NVAL(SUM(CASE WHEN D.CAPITOL IN (1130) AND D.RIND IN ('02') THEN D.COL1 ELSE NULL END)) AS COL2,
   NVAL(SUM(CASE WHEN D.CAPITOL IN (1130) AND D.RIND IN ('03') THEN D.COL1 ELSE NULL END)) AS COL3,
   NVAL(SUM(CASE WHEN D.CAPITOL IN (1130) AND D.RIND IN ('04') THEN D.COL1 ELSE NULL END)) AS COL4,
   NVAL(SUM(CASE WHEN D.CAPITOL IN (1130) AND D.RIND IN ('05') THEN D.COL1 ELSE NULL END)) AS COL5,
   NVAL(SUM(CASE WHEN D.CAPITOL IN (1130) AND D.RIND IN ('06') THEN D.COL1 ELSE NULL END)) AS COL6,
   NVAL(SUM(CASE WHEN D.CAPITOL IN (1130) AND D.RIND IN ('07') THEN D.COL1 ELSE NULL END)) AS COL7,
   NVAL(SUM(CASE WHEN D.CAPITOL IN (1130) AND D.RIND IN ('08') THEN D.COL1 ELSE NULL END)) AS COL8,
   NVAL(SUM(CASE WHEN D.CAPITOL IN (1130) AND D.RIND IN ('09') THEN D.COL1 ELSE NULL END)) AS COL9,
   NVAL(SUM(CASE WHEN D.CAPITOL IN (1131) AND D.RIND IN ('01') THEN D.COL1 ELSE NULL END)) AS COL10,
   NVAL(SUM(CASE WHEN D.CAPITOL IN (1131) AND D.RIND IN ('02') THEN D.COL1 ELSE NULL END)) AS COL11,
   NVAL(SUM(CASE WHEN D.CAPITOL IN (1131) AND D.RIND IN ('03') THEN D.COL1 ELSE NULL END)) AS COL12,
   NVAL(SUM(CASE WHEN D.CAPITOL IN (1131) AND D.RIND IN ('04') THEN D.COL1 ELSE NULL END)) AS COL13,
   NVAL(SUM(CASE WHEN D.CAPITOL IN (1131) AND D.RIND IN ('05') THEN D.COL1 ELSE NULL END)) AS COL14,
   NVAL(SUM(CASE WHEN D.CAPITOL IN (1131) AND D.RIND IN ('06') THEN D.COL1 ELSE NULL END)) AS COL15
   
  
FROM
  VW_DATA_ALL D
  INNER JOIN VW_CL_CUATM C ON C.CODUL = D.CUATM
  INNER JOIN VW_CL_CUATM CC ON C.FULL_CODE LIKE '%'||CC.CODUL||';%'
WHERE
  D.FORM IN (65) AND 
  D.FORM_VERS = :pFORM_VERS AND
  D.PERIOADA IN (:pPERIOADA) AND     
  D.CAPITOL IN (1130,1131) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' 
  AND (CC.PRGS IN ('2','3','5') AND CC.CODUL NOT IN ('0101000'))
GROUP BY 
  CC.CODUL,
  CC.DENUMIRE,
  CC.FULL_CODE
--ORDER BY
--  CC.FULL_CODE