SELECT 
  TR.NUME_ROW,
 SUM(CASE WHEN D.PERIOADA IN (1043) AND D.RIND IN ('1631') AND D.COL1 BETWEEN(SUBSTR(TR.NR_ROW,0,INSTR(NR_ROW,'-')-1)) AND (SUBSTR(TR.NR_ROW,INSTR(TR.NR_ROW,'-')+1,LENGTH(TR.NR_ROW))) THEN D.COL1 ELSE 0 END) AS SUPRAFATA_2019,
 COUNT(DISTINCT CASE WHEN D.PERIOADA IN (1043) AND D.RIND IN ('1631') AND D.COL1 BETWEEN(SUBSTR(TR.NR_ROW,0,INSTR(NR_ROW,'-')-1)) AND (SUBSTR(TR.NR_ROW,INSTR(TR.NR_ROW,'-')+1,LENGTH(TR.NR_ROW))) THEN D.CUIIO END) AS NR_INTREPRINDERI_2019,

  SUM(CASE WHEN D.PERIOADA IN (1047) AND D.RIND IN ('1631') AND D.COL1 BETWEEN(SUBSTR(TR.NR_ROW,0,INSTR(NR_ROW,'-')-1)) AND (SUBSTR(TR.NR_ROW,INSTR(TR.NR_ROW,'-')+1,LENGTH(TR.NR_ROW))) THEN D.COL1 ELSE 0 END) AS SUPRAFATA_2020,
  COUNT(DISTINCT CASE WHEN D.PERIOADA IN (1047) AND D.RIND IN ('1631') AND D.COL1 BETWEEN(SUBSTR(TR.NR_ROW,0,INSTR(NR_ROW,'-')-1)) AND (SUBSTR(TR.NR_ROW,INSTR(TR.NR_ROW,'-')+1,LENGTH(TR.NR_ROW))) THEN D.CUIIO END) AS NR_INTREPRINDERI_2020
FROM
  VW_DATA_ALL D
CROSS JOIN
 (
SELECT '0-999999999' AS NR_ROW,'Total, ha' AS NUME_ROW, 1 AS ORDINE FROM DUAL UNION
SELECT '0-20' AS NR_ROW, 'pina la 20' AS NUME_ROW, 2 AS ORDINE FROM DUAL UNION
SELECT '21-50' AS NR_ROW, '21-50' AS NUME_ROW,3 AS ORDINE FROM DUAL UNION
SELECT '51-100' AS NR_ROW, '51-100' AS NUME_ROW, 4 AS ORDINE FROM DUAL UNION
SELECT '101-500' AS NR_ROW, '101-500' AS NUME_ROW, 5 AS ORDINE FROM DUAL UNION
SELECT '500-999999999' AS NR_ROW, 'mai mult de 500' AS NUME_ROW, 6 AS ORDINE FROM DUAL

) TR
WHERE
  D.PERIOADA IN (1047,1043) AND
  D.FORM IN (45) AND
  D.CAPITOL IN (399) 
  AND  D.CUIIO IN (484156)
GROUP BY
  TR.NUME_ROW,
  TR.ORDINE
ORDER BY
  TR.ORDINE

