SELECT DISTINCT
  TR.RIND_DENUMIRE,
  TR.NUME_ROW,
  TR.ORDINE,
  SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN (TR.RIND) AND D.COL1 BETWEEN(SUBSTR(TR.NR_ROW,0,INSTR(NR_ROW,'-')-1)) AND (SUBSTR(TR.NR_ROW,INSTR(TR.NR_ROW,'-')+1,LENGTH(TR.NR_ROW))) THEN D.COL1 ELSE 0 END) AS SUPRAFATA_2019,
  COUNT(DISTINCT  CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN (TR.RIND) AND D.COL1 BETWEEN(SUBSTR(TR.NR_ROW,0,INSTR(NR_ROW,'-')-1)) AND (SUBSTR(TR.NR_ROW,INSTR(TR.NR_ROW,'-')+1,LENGTH(TR.NR_ROW))) THEN D.CUIIO END) AS NR_INTREPRINDERI_2019,
  SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN (TR.RIND) AND D.COL1 BETWEEN(SUBSTR(TR.NR_ROW,0,INSTR(NR_ROW,'-')-1)) AND (SUBSTR(TR.NR_ROW,INSTR(TR.NR_ROW,'-')+1,LENGTH(TR.NR_ROW))) THEN D.COL1 ELSE 0 END) AS SUPRAFATA_2020,
  COUNT(DISTINCT  CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN (TR.RIND) AND D.COL1 BETWEEN(SUBSTR(TR.NR_ROW,0,INSTR(NR_ROW,'-')-1)) AND (SUBSTR(TR.NR_ROW,INSTR(TR.NR_ROW,'-')+1,LENGTH(TR.NR_ROW))) THEN D.CUIIO END) AS NR_INTREPRINDERI_2020
FROM
  VW_DATA_ALL D
CROSS JOIN
 (
SELECT '0-999999999' AS NR_ROW,'Total, ha' AS NUME_ROW, '1631' AS RIND, 'Teren agricol arabil' AS RIND_DENUMIRE, 1 AS ORDINE FROM DUAL UNION
SELECT '0-20' AS NR_ROW, 'pina la 20' AS NUME_ROW, '1631' AS RIND,  'Teren agricol arabil' AS RIND_DENUMIRE,2 AS ORDINE FROM DUAL UNION
SELECT '21-50' AS NR_ROW, '21-50' AS NUME_ROW, '1631' AS RIND,  'Teren agricol arabil' AS RIND_DENUMIRE,3 AS ORDINE FROM DUAL UNION
SELECT '51-100' AS NR_ROW, '51-100' AS NUME_ROW, '1631' AS RIND,  'Teren agricol arabil' AS RIND_DENUMIRE,4 AS ORDINE FROM DUAL UNION
SELECT '101-500' AS NR_ROW, '101-500' AS NUME_ROW, '1631' AS RIND,  'Teren agricol arabil' AS RIND_DENUMIRE,5 AS ORDINE FROM DUAL UNION
SELECT '500-999999999' AS NR_ROW, 'mai mult de 500' AS NUME_ROW, '1631' AS RIND,  'Teren agricol arabil' AS RIND_DENUMIRE,6 AS ORDINE FROM DUAL UNION
SELECT '0-999999999' AS NR_ROW,'Total, ha' AS NUME_ROW, '2100' AS RIND, 'Livezi, vii, arbusti - total' AS RIND_DENUMIRE, 7 AS ORDINE FROM DUAL UNION
SELECT '0-20' AS NR_ROW, 'pina la 20' AS NUME_ROW, '2100' AS RIND,  'Livezi, vii, arbusti - total' AS RIND_DENUMIRE,8 AS ORDINE FROM DUAL UNION
SELECT '21-50' AS NR_ROW, '21-50' AS NUME_ROW, '2100' AS RIND,  'Livezi, vii, arbusti - total' AS RIND_DENUMIRE,9 AS ORDINE FROM DUAL UNION
SELECT '51-100' AS NR_ROW, '51-100' AS NUME_ROW, '2100' AS RIND,  'Livezi, vii, arbusti - total' AS RIND_DENUMIRE,10 AS ORDINE FROM DUAL UNION
SELECT '101-500' AS NR_ROW, '101-500' AS NUME_ROW, '2100' AS RIND,  'Livezi, vii, arbusti - total' AS RIND_DENUMIRE,11 AS ORDINE FROM DUAL UNION
SELECT '500-999999999' AS NR_ROW, 'mai mult de 500' AS NUME_ROW, '2100' AS RIND,  'Livezi, vii, arbusti - total' AS RIND_DENUMIRE,12 AS ORDINE FROM DUAL

) TR
WHERE
  D.PERIOADA IN (:pPERIOADA-4, :pPERIOADA) AND
  D.FORM IN (45) AND
  D.CAPITOL IN (399,401) --AND
--  D.CUIIO IN (41002643)

 AND  D.CUIIO IN (484156)
GROUP BY
  TR.RIND_DENUMIRE,
  TR.NUME_ROW,
  TR.ORDINE
ORDER BY
  TR.ORDINE


