SELECT 
D.CUIIO,
RE.DENUMIRE,
D.RIND,
SUM(D.COL10) AS COL10
  FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM RE ON (D.CUIIO=RE.CUIIO AND D.CUIIO_VERS=RE.CUIIO_VERS)
  
  
  WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (27)                 AND 
  D.CAPITOL IN (371)  
  
  AND D.RIND IN ('89')  
  GROUP BY 
D.CUIIO,
RE.DENUMIRE,
D.RIND
  
  