

SELECT 
D.RIND,
SUM(CASE WHEN   D.RIND IN ('1631') THEN D.COL1 ELSE NULL END ) AS COL1
 

 FROM cis2.VW_DATA_ALL D

WHERE
  D.PERIOADA IN (:pPERIOADA) AND -- PERIOADA - 1047 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND

  D.FORM IN (45)AND   
  D.CAPITOL IN (399) 
  AND
  D.RIND IN ('1631')
  
  group BY 
  D.RIND