DECLARE

  CURSOR C IS

SELECT 
    DF.PERIOADA,
    DF.FORM,
    DF.FORM_VERS,
    DF.ID_MDTABLE,
    DF.COD_CUATM,
    DF.NR_SECTIE,
    DF.NUME_SECTIE,
    DF.NR_SECTIE1,
    DF.NUME_SECTIE1,
    DF.NR_SECTIE2,
    DF.NUME_SECTIE2,
    DF.NR_ROW NR_ROW,
    DF.ORDINE,
    DF.DECIMAL_POS,
    DF.NUME_ROW,
    DF.COL1,
    DF.COL2,
    DF.COL3,
    DF.COL4,
    DF.COL5,
    DF.COL6
     
FROM 
(



 


 SELECT
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
    '0' AS NR_SECTIE,
    '0' AS NUME_SECTIE,
    '0' AS NR_SECTIE1,
    '0' AS NUME_SECTIE1,
    '0' AS NR_SECTIE2,
    '0' AS NUME_SECTIE2,
     rind||'~'||ROWNUM AS NR_ROW,   
     ROWNUM ORDINE,
    '000000' AS DECIMAL_POS,
    DENUMIRE NUME_ROW,
      COL1,
      COL2,
      COL3,
      COL4,
      COL5,
      COL6
    

    FROM
  
(
SELECT 
    0 ORDINE,
    '00' rind,
    'Total gospodării cu animale, păsări și familii de albine' DENUMIRE,
    SUM(COL1) AS COL1,
    SUM(COL2) AS COL2,
    SUM(COL3) AS COL3,
    SUM(COL4) AS COL4,
    SUM(COL5) AS COL5,
    SUM(COL6) AS COL6
    
FROM 
    
(
SELECT
         2 ORDINE,    
         '01' rind, 
         'Total gospodării cu animale, păsări și familii de albine' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('010')
  
  
  UNION 
  
  SELECT
         3 ORDINE,    
         '02' rind, 
         'numai cu porcine' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('020')
  
  
  UNION 
  
  SELECT
         4 ORDINE,    
         '03' rind, 
         'numai cu ovine  ' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('030')
  
  
  UNION 
  
  SELECT
         5 ORDINE,    
         '04' rind, 
         'numai cu caprine' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('040')
  
  
  
  UNION 
  
  SELECT
         6 ORDINE,    
         '05' rind, 
         'numai cu cabaline' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('050')
  
  
  
  
  
  UNION 
  
  SELECT
         7 ORDINE,    
         '06' rind, 
         'numai cu păsări' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('060','070','080','090')
  
  
  
  
  UNION 
  
  SELECT
         8 ORDINE,    
         '07' rind, 
         'nimai cu iepuri de casă' DENUMIRE,
        COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('100')
  
  
  
  UNION 
  
  SELECT
         9 ORDINE,    
         '08' rind, 
         'numai cu familii de albine' DENUMIRE,
        COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('200')
  ) 
  
  
  UNION 
  
  SELECT
         1 ORDINE,    
         ' ' rind, 
         'din care cu o singură specie:' DENUMIRE,
         SUM(CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')   THEN NULL ELSE NULL END) AS COL1,
         SUM(CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')   THEN NULL  ELSE NULL END) AS COL2,
         SUM(CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')   THEN NULL ELSE NULL END) AS COL3,
         SUM(CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')   THEN NULL ELSE NULL END) AS COL4,
         SUM(CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')   THEN NULL ELSE NULL END) AS COL5,     
         SUM(CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN NULL ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('010')
  
  
    UNION 
  
  
  SELECT
         2 ORDINE,    
         '01' rind, 
         'Total gospodării cu animale, păsări și familii de albine' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('010')
  
  
  UNION 
  
  SELECT
         3 ORDINE,    
         '02' rind, 
         'numai cu porcine' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('020')
  
  
  UNION 
  
  SELECT
         4 ORDINE,    
         '03' rind, 
         'numai cu ovine  ' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('030')
  
  
  UNION 
  
  SELECT
         5 ORDINE,    
         '04' rind, 
         'numai cu caprine' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('040')
  
  
  
  UNION 
  
  SELECT
         6 ORDINE,    
         '05' rind, 
         'numai cu cabaline' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('050')
  
  
  
  
  
  UNION 
  
  SELECT
         7 ORDINE,    
         '06' rind, 
         'numai cu păsări' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('060','070','080','090')
  
  
  
  UNION 
  
  ---
  SELECT
         7.1 ORDINE,    
         '06.1' rind, 
         'numai  găini' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('060')
  
  
  UNION 
  
  
  SELECT
         7.2 ORDINE,    
         '06.2' rind, 
         'numai  găște' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('070')
  
  
  UNION 
  
  
  SELECT
         7.3 ORDINE,    
         '06.3' rind, 
         'numai  rațe' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('080')
  
  
  UNION 
  
  ------------------
  SELECT
         7.4 ORDINE,    
         '06.4' rind, 
         'curci' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('090')
  
  ---------
  UNION 
  
  SELECT
         8 ORDINE,    
         '07' rind, 
         'nimai cu iepuri de casă' DENUMIRE,
        COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('100')
  
  
  
  UNION 
  
  SELECT
         9 ORDINE,    
         '08' rind, 
         'numai cu familii de albine' DENUMIRE,
        COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('200')
  
  
  ORDER BY 
  ORDINE,
  RIND
  )
  
  
  

  ) DF
  
  ;
   
    BEGIN

  FOR CR IN C
  
  LOOP
   
    INSERT INTO  CIS2.TABLE_OUT
    (
      PERIOADA,
      FORM,
      FORM_VERS,
      ID_MDTABLE,
      COD_CUATM,
      NR_SECTIE,
      NUME_SECTIE,
      NR_SECTIE1,
      NUME_SECTIE1,
      NR_SECTIE2,
      NUME_SECTIE2,
      NR_ROW,
      ORDINE,
      DECIMAL_POS,
      NUME_ROW,
       
      COL1, COL2, COL3,  COL4, COL5 , COL6
    )
    VALUES
    (
      CR.PERIOADA,
      CR.FORM,
      CR.FORM_VERS,
      CR.ID_MDTABLE,
      CR.COD_CUATM,
      CR.NR_SECTIE,
      CR.NUME_SECTIE,
      CR.NR_SECTIE1,
      CR.NUME_SECTIE1,
      CR.NR_SECTIE2,
      CR.NUME_SECTIE2,
      CR.NR_ROW,
      CR.ORDINE,
      CR.DECIMAL_POS,
      CR.NUME_ROW,
       
      CR.COL1, CR.COL2, CR.COL3, CR.COL4 , CR.COL5 , CR.COL6
    );
  END LOOP;
END;
  
  