SELECT 
 
    
    
     DISTINCT D.CUIIO,  
     MAX(R.DENUMIRE)  DENUMIRE,  
     D.RIND,
     SUM(D.COL12)  COL12
      
     
FROM   CIS2.VW_DATA_ALL D 
                     INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS  = D.CUIIO_VERS    
    INNER JOIN CIS2.MD_RIND MR ON (MR.ID_MD = D.ID_MD)



WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 49 AND 
  D.CAPITOL IN (1049) 
  AND D.RIND IN ('050')
  
  GROUP BY 
  D.CUIIO,
  D.RIND  
  
--  HAVING 
--  
--  SUM(D.COL12)  IS NOT NULL 