SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,    
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   CODUL AS NR_ROW,
   ROWNUM AS ORDINE,
  '1111111111' AS DECIMAL_POS,
   REPLACE(DENUMIRE,'R-UL ') AS NUME_ROW,
   COL1, COL2, COL3,COL4,COL5,COL6,COL7,COL8,COL9,COL10
   
FROM
  (
SELECT
 C.FULL_CODE,
 C.DENUMIRE,
 C.CODUL,
 (SUM(CASE WHEN D.RIND IN '100' THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN D.RIND IN '100' THEN D.COL2 ELSE 0 END)) AS COL1,
 
  SUM(CASE WHEN D.RIND IN '100' THEN D.COL1 ELSE 0 END) AS COL2,
  
  SUM(CASE WHEN D.RIND IN '100' THEN D.COL2 ELSE 0 END) AS COL3,
  
 (SUM(CASE WHEN D.RIND IN '200' THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN D.RIND IN '200' THEN D.COL2 ELSE 0 END)) AS COL4,
  
  SUM(CASE WHEN D.RIND IN '200' THEN D.COL1 ELSE 0 END) AS COL5,
  
  SUM(CASE WHEN D.RIND IN '200' THEN D.COL2 ELSE 0 END) AS COL6,
  
 (SUM(CASE WHEN D.RIND IN '300' THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN D.RIND IN '300' THEN D.COL2 ELSE 0 END)) AS COL7,
 
  SUM(CASE WHEN D.RIND IN '300' THEN D.COL1 ELSE 0 END) AS COL8,
  
  SUM(CASE WHEN D.RIND IN '300' THEN D.COL2 ELSE 0 END) AS COL9,
  
ROUND((((SUM(CASE WHEN D.RIND IN '100' THEN D.COL1 ELSE 0 END)+
   SUM(CASE WHEN D.RIND IN '100' THEN D.COL2 ELSE 0 END))/
 
  NOZERO(SUM(CASE WHEN D.RIND IN '100' THEN D.COL3 ELSE 0 END)+
   SUM(CASE WHEN D.RIND IN '100' THEN D.COL4 ELSE 0 END)))/
  
  P.COL1)*100,1) AS COL10
  
FROM
  VW_DATA_ALL D
  INNER JOIN VW_CL_CUATM B ON (D.CUATM=B.CODUL)
  INNER JOIN VW_CL_CUATM C ON (B.FULL_CODE LIKE '%'||C.CODUL||';%')
  CROSS JOIN (
  
  SELECT DISTINCT 
  COL1 
  
FROM 
  VW_DATA_ALL D
  
  

  
WHERE 
  D.FORM = 100 AND
  D.CUIIO = 2 AND
  D.PERIOADA IN :pPERIOADA AND
  D.CAPITOL = 330 AND
  D.RIND IN '01' ) P
  
  
  
  
WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  D.PERIOADA IN :pPERIOADA AND
  D.FORM = 8 AND
  D.CAPITOL = 323 AND
  C.PRGS IN 2
  
GROUP BY
  C.FULL_CODE,
  C.DENUMIRE,
  C.CODUL,
  P.COL1 
  
ORDER BY
  C.FULL_CODE)