--BEGIN
--
--INSERT INTO TABLE_OUT 
--(
--    PERIOADA,
--    FORM,
--    FORM_VERS,
--    ID_MDTABLE,
--    COD_CUATM,
--    NR_SECTIE,
--    NUME_SECTIE,
--    NR_SECTIE1,
--    NUME_SECTIE1,
--    NR_SECTIE2,
--    NUME_SECTIE2,
--    NR_ROW,
--    ORDINE,
--    DECIMAL_POS,
--    NUME_ROW,
--          
--    COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11,COL12,COL13
--)
SELECT 
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
    NR_SECTIE,
    NUME_SECTIE,
    NR_SECTIE1,
    NUME_SECTIE1,
    NR_SECTIE2,  
    NUME_SECTIE2,
    NR_ROW,
    ROWNUM AS ORDINE,
    DECIMAL_POS,
    NUME_ROW,
    COL1,
    COL2,
    COL3,
    COL4,
    COL5,
    COL6,
    COL7,
    COL8,
    COL9,
    COL10,
    COL11,
    COL12,
     COL13
FROM
(

SELECT

    A.NR_SECTIE,
    A.NUME_SECTIE,
    A.NR_SECTIE1,
    A.NUME_SECTIE1,
    A.NR_SECTIE2,  
    A.NUME_SECTIE2,
    A.NR_ROW,
    ROWNUM AS ORDINE,
    A.DECIMAL_POS,
    A.NUME_ROW,
    A.COL1,
    A.COL2,
    A.COL3,
    A.COL4,
    A.COL5,
    A.COL6,
    A.COL7,
    A.COL8,
    A.COL9,
    A.COL10,
    A.COL11,
    ROUND((TT.COL11),1) AS COL12,
    (A.COL11/NOZERO((TT.COL11)))*100 AS COL13
FROM
(
SELECT 
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
                 
    T.NR_SECTIE,
    T.NUME_SECTIE,
    T.NR_SECTIE1,
    T.NUME_SECTIE1,
    T.NR_SECTIE2,              
    T.NUME_SECTIE2,
    T.NR_ROW,
    --T.ORDINE,
    '0011111111111' AS DECIMAL_POS,
    T.NUME_ROW,
          
    ROUND(SUM(T.COL3)/NOZERO(MAX(P.NUM)/3),0) AS COL1,
    ROUND(SUM(T.COL4)/(MAX(P.NUM)/3),0) AS COL2,
    SUM(ROUND(T.COL5,1)) AS COL3,
    SUM(ROUND(T.COL6,1)) AS COL4,
    SUM(ROUND(T.COL7,1)) AS COL5,
    ROUND(SUM(T.COL8)/(MAX(P.NUM)/3),1) AS COL6,
    SUM(ROUND(T.COL9,1)) AS COL7,
    SUM(ROUND(T.COL10,1)) AS COL8,
    SUM(ROUND(T.COL11,1)) AS COL9,
    SUM(ROUND(T.COL12,1)) AS COL10,
    ((1000*SUM(T.COL9)/(SUM(T.COL3)/NOZERO(MAX(P.NUM)/3)))/MAX(P.NUM)) AS COL11,
    NULL AS COL12
  
    FROM TABLE_OUT T
      INNER JOIN MD_PERIOADA P ON (T.PERIOADA=P.PERIOADA)
--      INNER JOIN VW_DATA_ALL D ON (D.RIND = T.NR_ROW AND (D.PERIOADA) = T.PERIOADA AND D.CAPITOL IN (92) AND D.CUIIO = 3)
  

WHERE
    T.ID_MDTABLE IN (CASE WHEN T.PERIOADA <= 425 THEN 2036 ELSE 2144 END) AND
    -- T.ID_MDTABLE IN (2036) AND --TABLE 1.3
    T.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA AND
    T.FORM IN (:pFORM) AND
    T.FORM_VERS IN (:pFORM_VERS) AND
    T.COD_CUATM IN (:pCOD_CUATM)

GROUP BY
    T.NR_SECTIE,
    T.NUME_SECTIE,
    T.NR_SECTIE1,
    T.NUME_SECTIE1,
    T.NR_SECTIE2,              
    T.NUME_SECTIE2,
    T.NR_ROW,
    --T.ORDINE,
    T.NUME_ROW
    
ORDER BY
    T.NR_ROW
)A
INNER JOIN (
   SELECT
     NR_ROW, ORDINE, COL11, ID_MDTABLE
   FROM
     TABLE_OUT T
   WHERE
    T.ID_MDTABLE IN (CASE WHEN PERIOADA <= 425 THEN 2049 ELSE TO_NUMBER(:pID_MDTABLE) END) AND
    (T.PERIOADA IN (:pPERIOADA-12)) AND
    T.FORM IN (:pFORM) AND
    T.FORM_VERS IN (:pFORM_VERS) AND
    T.COD_CUATM IN (:pCOD_CUATM)
   ) TT ON (A.NR_ROW=TT.NR_ROW)
    
   ) 
   
   
   
--END;