SELECT DISTINCT
   'Fililal='|| D.FILIAL ||'; Rindul '|| SUBSTR(D.RIND,0,2) ||'(T-F):'||
ROUND((
   NVAL(SUM(CASE WHEN D.CAPITOL IN ('303') AND D.RIND LIKE ('%-T') THEN  NVAL(D.COL2) ELSE 0 END -
            CASE WHEN D.CAPITOL IN ('303') AND D.RIND LIKE ('%-F') THEN  NVAL(D.COL2) ELSE 0 END
            ))*1000 /
   NOZERO(NVAL(SUM(CASE WHEN D.CAPITOL IN ('301') AND D.RIND LIKE ('%-T') THEN  NVAL(D.COL3) ELSE 0 END -
                   CASE WHEN D.CAPITOL IN ('301') AND D.RIND LIKE ('%-F') THEN  NVAL(D.COL3) ELSE 0 END
                   ))))/12 
   )
  ||'  nu apartine intervalului [2200-15000]'  
 AS REZULTAT
        
 --  Cap. II col. 1(T-F)*1000/Cap. I Col.2(T-F)/12=>2200<15000 daca BUGET 1         
 
FROM
  VW_DATA_ALL D               
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <> :CAPITOL)  AND
   D.CAPITOL IN (301,303) AND 
  (:FORM = :FORM) AND D.FORM IN (3) AND D.BUGET IN('1')
GROUP BY
  SUBSTR(D.RIND,0,2),
  D.FILIAL
  
  

HAVING
( 
ROUND((
   NVAL(SUM(CASE WHEN D.CAPITOL IN ('303') AND D.RIND LIKE ('%-T') THEN  NVAL(D.COL2) ELSE 0 END -
            CASE WHEN D.CAPITOL IN ('303') AND D.RIND LIKE ('%-F') THEN  NVAL(D.COL2) ELSE 0 END
            ))*1000 /
   NOZERO(NVAL(SUM(CASE WHEN D.CAPITOL IN ('301') AND D.RIND LIKE ('%-T') THEN  NVAL(D.COL3) ELSE 0 END -
                   CASE WHEN D.CAPITOL IN ('301') AND D.RIND LIKE ('%-F') THEN  NVAL(D.COL3) ELSE 0 END
                   ))))/12) > 15000
 
AND
 
ROUND((
   NVAL(SUM(CASE WHEN D.CAPITOL IN ('303') AND D.RIND LIKE ('%-T') THEN  NVAL(D.COL2) ELSE 0 END -
            CASE WHEN D.CAPITOL IN ('303') AND D.RIND LIKE ('%-F') THEN  NVAL(D.COL2) ELSE 0 END
            ))*1000 /
   NOZERO(NVAL(SUM(CASE WHEN D.CAPITOL IN ('301') AND D.RIND LIKE ('%-T') THEN  NVAL(D.COL3) ELSE 0 END -
                   CASE WHEN D.CAPITOL IN ('301') AND D.RIND LIKE ('%-F') THEN  NVAL(D.COL3) ELSE 0 END
                   ))))/12)> 0
)
   
  OR 
   
(

ROUND((
   NVAL(SUM(CASE WHEN D.CAPITOL IN ('303') AND D.RIND LIKE ('%-T') THEN  NVAL(D.COL2) ELSE 0 END -
            CASE WHEN D.CAPITOL IN ('303') AND D.RIND LIKE ('%-F') THEN  NVAL(D.COL2) ELSE 0 END
            ))*1000 /
   NOZERO(NVAL(SUM(CASE WHEN D.CAPITOL IN ('301') AND D.RIND LIKE ('%-T') THEN  NVAL(D.COL3) ELSE 0 END -
                   CASE WHEN D.CAPITOL IN ('301') AND D.RIND LIKE ('%-F') THEN  NVAL(D.COL3) ELSE 0 END
                   ))))/12) <2200 
   
   AND
  
ROUND((
   NVAL(SUM(CASE WHEN D.CAPITOL IN ('303') AND D.RIND LIKE ('%-T') THEN  NVAL(D.COL2) ELSE 0 END -
            CASE WHEN D.CAPITOL IN ('303') AND D.RIND LIKE ('%-F') THEN  NVAL(D.COL2) ELSE 0 END
            ))*1000 /
   NOZERO(NVAL(SUM(CASE WHEN D.CAPITOL IN ('301') AND D.RIND LIKE ('%-T') THEN  NVAL(D.COL3) ELSE 0 END -
                   CASE WHEN D.CAPITOL IN ('301') AND D.RIND LIKE ('%-F') THEN  NVAL(D.COL3) ELSE 0 END
                   ))))/12)> 0)
