SELECT
  'RIND '||D.RIND||' - col.3 : '||
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1133) AND D.PERIOADA IN (:PERIOADA)   THEN  NVAL(D.COL1) ELSE NULL END)) ||' <> : col.4 - '||
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1133) AND D.PERIOADA IN (:PERIOADA-1)  THEN  NVAL(D.COL2) ELSE NULL END))   
  AS REZULTAT
  
FROM VW_DATA_ALL_FR D


WHERE
   (D.PERIOADA IN (:PERIOADA,:PERIOADA-1 ))   AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND 
  (D.CUIIO_VERS=:CUIIO_VERS     OR  D.CUIIO_VERS <>  :CUIIO_VERS) AND
  (:FORM = :FORM                OR :FORM <>  :FORM) AND  
  (:FORM_VERS = :FORM_VERS      OR :FORM_VERS <> :FORM_VERS) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS  OR :CAPITOL_VERS <>  :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (66)
and D.CAPITOL IN (1133) 
 
 
 
GROUP BY 
D.RIND
  


HAVING
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1133) AND D.PERIOADA IN (:PERIOADA)   THEN   NVAL(D.COL1) ELSE NULL END)) <> 
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1133) AND D.PERIOADA IN (:PERIOADA-1)  THEN  NVAL(D.COL2) ELSE NULL END))   





AND
  (
 SELECT
  DISTINCT
  D.CUIIO
FROM
  CIS2.VW_DATA_ALL_FR D
WHERE
  (D.PERIOADA IN (:PERIOADA-1)) AND
  (D.CUIIO=:CUIIO OR :CUIIO = -1) AND
   D.FORM  IN(59)
   
   
   
   ) IS NOT NULL

ORDER BY 
D.RIND