SELECT   
  'Rind. SUM(Col.7,8) '||CIS2.D.RIND||': '||'['||  
  CIS2.NVAL(SUM(NVAL(D.COL7) + NVAL(D.COL8))) ||' < '||  
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('010','020','030','040','041','042') THEN D.COL9 ELSE 0 END ))
  ||'] (Col.9)(Rând.010-042)'
   
  AS REZULTAT

FROM
  CIS2.VW_DATA_ALL_TEMP D
 

WHERE
  (CIS2.D.PERIOADA =:PERIOADA        OR :PERIOADA=  -1) AND
  (CIS2.D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (CIS2.D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (CIS2.D.FORM = :FORM               OR :FORM = -1) AND
  (CIS2.D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (CIS2.D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (CIS2.D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (CIS2.D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  CIS2.D.FORM IN (17)  AND
  CIS2.D.CAPITOL in (1004)
 
GROUP BY CIS2.D.RIND

HAVING

 CIS2.NVAL(SUM(NVAL(D.COL7) + NVAL(D.COL8)))  <  
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('010','020','030','040','041','042') THEN D.COL9 ELSE 0 END ))