SELECT   

  '(Rind.040) (Col.8) -  '||SUM(CASE WHEN CIS2.D.RIND IN ('040') THEN CIS2.NVAL(D.COL8) ELSE 0 END) ||' <>   '||
  SUM(CASE WHEN CIS2.D.RIND IN ('090','110') THEN CIS2.NVAL(D.COL1) ELSE 0  END)||' - SUM (Rind.090,110) (Col.1)' 
 
  
      
  
  
  AS REZULTAT

FROM
  CIS2.VW_DATA_ALL D            
       
WHERE
  (CIS2.D.PERIOADA =:PERIOADA        OR :PERIOADA=  -1) AND
  (CIS2.D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (CIS2.D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (CIS2.D.FORM = :FORM               OR :FORM = -1) AND
  (CIS2.D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (CIS2.D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (CIS2.D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (CIS2.D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  CIS2.D.FORM IN (17)  AND
  CIS2.D.CAPITOL in (1004) 
  
  HAVING 


  (SUM(CASE WHEN CIS2.D.RIND IN ('040') THEN CIS2.NVAL(D.COL1) ELSE NULL END) =
  
  SUM(CASE WHEN CIS2.D.RIND IN ('040') THEN CIS2.NVAL(D.COL2) ELSE NULL END))   
 
  AND 

  (SUM(CASE WHEN CIS2.D.RIND IN ('040') THEN CIS2.NVAL(D.COL8) ELSE 0  END) 
  
  <>
  
  SUM(CASE WHEN CIS2.D.RIND IN ('090','110') THEN CIS2.NVAL(D.COL1) ELSE 0  END)
  
  )
  
  
  
  