
SELECT 


CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND  IN  ('17.1001.040') THEN CIS2.NVAL(D.COL1)  ELSE 0 END)) = 0 THEN

'trebue sa fie completat (Cap.1) (Rind.040) (Col.4) ' 
ELSE
'trebue sa fie completat (Cap.4 (Rind.042) (Col.1)'
END 
AS REZULTAT
FROM 
CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL            OR  :CAPITOL<>:CAPITOL) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND          
  
  D.FORM||'.'||D.CAPITOL||'.'||D.RIND  IN  ('17.1001.040','17.1004.042') 
  
  
HAVING
  (
  CIS2.NVAL(SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND  IN  ('17.1001.040')  THEN CIS2.NVAL(D.COL1) ELSE 0 END)) > 0
  AND
  CIS2.NVAL(SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND  IN  ('17.1004.042') THEN CIS2.NVAL(D.COL1) ELSE 0 END)) = 0 
  )
  
 -- OR
  --(
  --CIS2.NVAL(SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND  IN  ('17.1001.040')  THEN CIS2.NVAL(D.COL1) ELSE 0 END)) = 0
 -- AND
 -- CIS2.NVAL(SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND  IN  ('17.1004.042') THEN CIS2.NVAL(D.COL1) ELSE 0 END)) > 0 
  --)