SELECT   
  A.CONTROL,
  MC.DEN_SHORT,
  A.CONTROL_VERS,
  A.CAPITOL,
  A.FORM,
  A.FORM_VERS,
  A.CAPITOL_VERS,
  A.FORMULA,
  A.PRIORITATEA    
 
 

FROM CIS2.MD_CONTROL A 

INNER JOIN (


    SELECT 
    
     CONTROL,
     MAX(CONTROL_VERS)  CONTROL_VERS
     
    FROM CIS2.MD_CONTROL
    
    
    GROUP BY 
    CONTROL  ) B  ON A.CONTROL = B.CONTROL  AND  A.CONTROL_VERS = B.CONTROL_VERS
    
    
    INNER JOIN CIS2.MD_CAPITOL MC ON MC.CAPITOL = A.CAPITOL  AND MC.CAPITOL_VERS = A.CAPITOL_VERS 
    
    WHERE 
    
    A.FORM = 40
    
    AND 
    
    A.STATUT <> '3'
    
    ORDER BY   
    A.CAPITOL,
    A.CONTROL