--INSERT INTO CIS2.TABLE_OUT
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
--  COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14, COL15, COL16, COL17, COL18, COL19, COL20, COL21, COL22
--)

SELECT
  :pPERIOADA,
  :pFORM,
  :pFORM_VERS,
  :pID_MDTABLE,
  :pCOD_CUATM,
  '0' AS NR_SECTIE,
  '0' NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  MR.RIND AS NR_ROW, 
  MR.ORDINE AS ORDINE,
  '0000000000000000000000' AS DECIMAL_POS,
  REPLACE(REPLACE(REPLACE(MR.DENUMIRE,'<b>',''),'</b>',''),'<br>','') NUME_ROW,
  
  ROUND(SUM(D.COL1),0) AS COL1,
  ROUND(SUM(D.COL2),0) AS COL2,
  ROUND(SUM(D.COL3),0) AS COL3,
  ROUND(SUM(D.COL4),0) AS COL4,
  ROUND(SUM(D.COL5),0) AS COL5,
  ROUND(SUM(D.COL6),0) AS COL6,
  ROUND(SUM(D.COL7),0) AS COL7,
  ROUND(SUM(D.COL8),0) AS COL8,
  ROUND(SUM(D.COL9),0) AS COL9,
  ROUND(SUM(D.COL10),0) AS COL10,
  ROUND(SUM(D.COL11),0) AS COL11,
  ROUND(SUM(D.COL12),0) AS COL12,
  ROUND(SUM(D.COL13),0) AS COL13,
  ROUND(SUM(D.COL14),0) AS COL14,
  ROUND(SUM(D.COL15),0) AS COL15,
  ROUND(SUM(D.COL16),0) AS COL16,
  ROUND(SUM(D.COL17),0) AS COL17,
  ROUND(SUM(D.COL18),0) AS COL18,
  ROUND(SUM(D.COL19),0) AS COL19,
  ROUND(SUM(D.COL20),0) AS COL20,
  ROUND(SUM(D.COL21),0) AS COL21,
  ROUND(SUM(D.COL22),0) AS COL22
 
  
        FROM CIS2.VW_DATA_ALL D
                    INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD =  D.ID_MD
        
        WHERE
          D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (69)                 AND 
  D.CAPITOL IN (1175)  AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'
        
                
  GROUP BY 
  MR.RIND,
  MR.ORDINE,
  MR.DENUMIRE