--INSERT INTO  TABLE_OUT
--(   
--    PERIOADA,
--    FORM,
--    FORM_VERS,
--    ID_MDTABLE,
--    COD_CUATM,
--    NR_SECTIE,
--    NUME_SECTIE,
--    NR_SECTIE1,
--    NUME_SECTIE1,
--    NR_SECTIE2,
--    NUME_SECTIE2,
--    NR_ROW,
--    ORDINE,
--    DECIMAL_POS,
--    NUME_ROW,
--    COL1,
--    COL2,
--    COL3,
--    COL4,
--    COL5,
--    COL6,
--    COL7,
--    COL8,
--    COL9,
--    COL10,
--    COL11,
--    COL12,
--    COL13
--   
--)


SELECT
:pPERIOADA AS PERIOADA,
:pFORM AS FORM,
:pFORM_VERS AS FORM_VERS,
:pID_MDTABLE AS ID_MDTABLE,
:pCOD_CUATM AS COD_CUATM, 
 CFP.CODUL AS NR_SECTIE,
 CFP.DENUMIRE AS NUME_SECTIE,
 
'0' AS NR_SECTIE1,
'0' AS NUME_SECTIE1,
'0' AS NR_SECTIE2,
'0' AS NUME_SECTIE2,
 MR.RIND||'~'||CFP.CODUL AS NR_ROW,
 MR.RIND AS ORDINE,
'0000000000000' AS DECIMAL_POS, 
 MR.DENUMIRE AS NUME_ROW,
 SUM(CASE WHEN MR.RIND  = D.RIND THEN  D.COL1 ELSE NULL END)  AS COL1,
 SUM(CASE WHEN MR.RIND  = D.RIND THEN  D.COL2 ELSE NULL END)  AS COL2,
 SUM(CASE WHEN MR.RIND  = D.RIND THEN  D.COL3 ELSE NULL END)  AS COL3,
 SUM(CASE WHEN MR.RIND  = D.RIND THEN  D.COL4 ELSE NULL END)  AS COL4,
 SUM(CASE WHEN MR.RIND  = D.RIND THEN  D.COL5 ELSE NULL END)  AS COL5,
 SUM(CASE WHEN MR.RIND  = D.RIND THEN  D.COL6 ELSE NULL END)  AS COL6,
 SUM(CASE WHEN MR.RIND  = D.RIND THEN  D.COL7 ELSE NULL END)  AS COL7,
 SUM(CASE WHEN MR.RIND  = D.RIND THEN  D.COL8 ELSE NULL END)  AS COL8,
 SUM(CASE WHEN MR.RIND  = D.RIND THEN  D.COL9 ELSE NULL END)  AS COL9,
 SUM(CASE WHEN MR.RIND  = D.RIND THEN  D.COL10 ELSE NULL END) AS COL10, 
 SUM(CASE WHEN MR.RIND  = D.RIND THEN  D.COL11 ELSE NULL END) AS COL11,
 SUM(CASE WHEN MR.RIND  = D.RIND THEN  D.COL12 ELSE NULL END ) AS COL12,
 SUM(CASE WHEN MR.RIND  = D.RIND THEN  D.COL13 ELSE NULL END) AS COL13

  
FROM CIS2.VW_DATA_ALL D

CROSS JOIN 
(
        SELECT 
             MR.RIND,
             MR.DENUMIRE,
             MR.RIND_VERS
            
            FROM CIS2.MD_RIND MR
            
            WHERE
            MR.CAPITOL IN (1004)
            AND MR.RIND_VERS IN (2007)
            
            AND 
            ASCII(MR.RIND) <> 45 
            
) MR
 
 INNER JOIN CIS2.VW_CL_CFP CC ON (CC.CODUL=D.CFP)
INNER JOIN CIS2.VW_CL_CFP CFP ON (CC.FULL_CODE LIKE '%'||CFP.CODUL||';%')
        

WHERE
(D.PERIOADA =:pPERIOADA) AND
(D.FORM =:pFORM) AND 
(D.FORM_VERS =:pFORM_VERS) AND
(:pID_MDTABLE=:pID_MDTABLE) AND 
(D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
D.FORM = 17   
AND D.CAPITOL IN (1004)
AND CFP.GRUPA IN (10)


   GROUP BY 
MR.RIND,
MR.DENUMIRE,
CFP.CODUL,
CFP.DENUMIRE


     
    ORDER BY
    
    MR.RIND 