INSERT INTO CIS2.TABLE_OUT
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
  COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12
)

SELECT
  :pPERIOADA,
  :pFORM,
  :pFORM_VERS,
  :pID_MDTABLE,
  :pCOD_CUATM,
  '0' AS NR_SECTIE,
  '0' NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  NR_ROW AS NR_ROW, 
  ROWNUM AS ORDINE,
  '00000010010010' AS DECIMAL_POS,
  NUME_ROW,
  
  ROUND(SUM(D.COL1),1) AS COL1,
  ROUND(SUM(D.COL2),1) AS COL2,
  ROUND(SUM(D.COL3),1) AS COL3,
  ROUND(SUM(D.COL4),1) AS COL4,
  ROUND(SUM(D.COL5),1) AS COL5,
  ROUND(SUM(D.COL6),1) AS COL6,
  ROUND(SUM(D.COL7),1) AS COL7,
  ROUND(SUM(D.COL8),1) AS COL8,
  ROUND(SUM(D.COL9),1) AS COL9,
  ROUND(SUM(D.COL10),1) AS COL10,
  ROUND(SUM(D.COL11),1) AS COL11,
  ROUND(SUM(D.COL12),1) AS COL12

  
        FROM CIS2.VW_DATA_ALL D
        
                