INSERT INTO TABLE_OUT 
(
  PERIOADA,
  ID_MDTABLE, 
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  NUME_ROW,
  ORDINE,
  COL1,
  COL2,
  COL3,
  COL4,
  COL5,
  COL6,
  COL7,
  COL8,
  COL9,
  COL10,
  COL11,
  COL12,
  COL13
)

SELECT  DISTINCT
 :pPERIOADA,
 :pID_MDTABLE,
 :pCOD_CUATM,
  CI.CODUL AS NR_SECTIE,
  CI.DENUMIRE AS NUME_SECTIE,
 '0' AS NR_SECTIE1,
 '0' AS NUME_SECTIE1,
 '0' AS NR_SECTIE2,
 '0' AS NUME_SECTIE2, 
  RD.RIND AS NR_ROW,
  RD.DENUMIRE AS NUME_ROW,
  RD.ORDINE AS ORDINE,
  ROUND(SUM(D.COL1),1) AS COL1,
  ROUND(SUM(D.COL2),1) AS COL2,
  ROUND(SUM(D.COL3),1) AS COL3,
  ROUND(SUM(D.COL4),1) AS COL4,
  ROUND(SUM(D.COL5),1) AS COL5,
  ROUND(SUM(D.COL6),1) AS COL6,
  ROUND(SUM(D.COL7),1) AS COL7,
  ROUND(SUM(D.COL8),1) AS COL8,
  ROUND(SUM(D.COL9),1) AS COL9,
  ROUND(SUM(D.COL10),1) AS COL10,
  ROUND(SUM(D.COL11),1) AS COL11,
  ROUND(SUM(D.COL12),1) AS COL12,
  ROUND(SUM(D.COL13),1) AS COL13
FROM
  M53.MD_RIND RD
  INNER JOIN M53.VW_DATA_ALL D ON (D.ID_MD=RD.ID_MD)
  INNER JOIN M53.RENIM R ON (R.CUIIO= D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
  INNER JOIN 
  (
    SELECT '10' AS CODUL_INV, '10'       AS CODUL, 'Scolile primare' AS DENUMIRE FROM DUAL UNION
    SELECT '20' AS CODUL_INV, '20+21'    AS CODUL, 'Gimnazii' AS DENUMIRE FROM DUAL UNION
    SELECT '21' AS CODUL_INV, '20+21'    AS CODUL, 'Gimnazii' AS DENUMIRE FROM DUAL UNION
    SELECT '30' AS CODUL_INV, '30+31'    AS CODUL, 'Licee' AS DENUMIRE FROM DUAL UNION
    SELECT '31' AS CODUL_INV, '30+31'    AS CODUL, 'Licee' AS DENUMIRE FROM DUAL UNION
    SELECT '40' AS CODUL_INV, '40'    AS CODUL, 'Scolile pentru copii cu deficiente în dezvoltarea intelectuala sau fizica' AS DENUMIRE FROM DUAL UNION
    --SELECT '41' AS CODUL_INV, '40+41'    AS CODUL, 'Scolile megii generale' AS DENUMIRE FROM DUAL UNION
 --   SELECT '50' AS CODUL_INV, '50+51'    AS CODUL, 'Scolile pentru copii cu deficiente in dezvoltarea intelectuala sau fizica' AS DENUMIRE FROM DUAL UNION
  --  SELECT '51' AS CODUL_INV, '50+51'    AS CODUL, 'Scolile pentru copii cu deficiente in dezvoltarea intelectuala sau fizica' AS DENUMIRE FROM DUAL UNION
  --  SELECT '60' AS CODUL_INV, '60'       AS CODUL, 'Scoile sanatoriale' AS DENUMIRE FROM DUAL UNION
    SELECT '71' AS CODUL_INV, '71+72+73' AS CODUL, 'Clase pe linga colegii' AS DENUMIRE FROM DUAL UNION
    SELECT '72' AS CODUL_INV, '71+72+73' AS CODUL, 'Clase pe linga colegii' AS DENUMIRE FROM DUAL UNION
    SELECT '73' AS CODUL_INV, '71+72+73' AS CODUL, 'Clase pe linga colegii' AS DENUMIRE FROM DUAL UNION
    SELECT '80' AS CODUL_INV, '80'       AS CODUL, 'Clase pe linga institutii de invatamint superior' AS DENUMIRE FROM DUAL
  ) CI ON R.TIP_INV = CI.CODUL_INV
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (:pFORM=:pFORM) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  RD.FORM IN (39) AND
  RD.FORM_VERS = :pFORM_VERS AND    
  RD.CAPITOL IN (3) 
   AND D.CUIIO NOT IN (7032055,5696207,5689503) 
GROUP BY
  RD.ORDINE,
  RD.RIND,
  RD.DENUMIRE,
  CI.CODUL,
  CI.DENUMIRE
ORDER BY
  CI.CODUL,
  RD.RIND