INSERT INTO TABLE_OUT(
    PERIOADA,
    ID_MDTABLE, 
    COD_CUATM,
    NR_SECTIE,
    NUME_SECTIE,
    NR_SECTIE1,
    NUME_SECTIE1,
    NR_SECTIE2,
    NUME_SECTIE2,
    NR_ROW,
    NUME_ROW,
    ORDINE,
    COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13
    )

SELECT  DISTINCT
 :pPERIOADA,
 :pID_MDTABLE,
 :pCOD_CUATM,
  CD.NR_ROW AS NR_SECTIE,
  CD.NUME_ROW AS NUME_SECTIE,
 '0' AS NR_SECTIE1,
 '0' AS NUME_SECTIE1,
 '0' AS NR_SECTIE2,
 '0' AS NUME_SECTIE2, 
  RD.RIND AS NR_ROW,
  RD.DENUMIRE AS NUME_ROW,
  RD.ORDINE AS ORDINE,
  
  
  
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL1 END),1) AS COL1, 
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL2 END),1) AS COL2,
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL3 END),1) AS COL3,  
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL4 END),1) AS COL4,
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL5 END),1) AS COL5,
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL6 END),1) AS COL6,
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL7 END),1) AS COL7,
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL8 END),1) AS COL8,
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL9 END),1) AS COL9,
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL10 END),1) AS COL10,
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL11 END),1) AS COL11,
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL12 END),1) AS COL12,
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL13 END),1) AS COL13
FROM
  MD_RIND RD
  INNER JOIN VW_DATA_ALL D ON (D.ID_MD=RD.ID_MD)
  INNER JOIN RENIM R ON (R.CUIIO= D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
   INNER JOIN VW_CL_CFP CP ON (R.CFP = CP.CODUL) 
  CROSS JOIN
  (     
    SELECT 'Forme de Proprietate- Total pe Republica' AS NUME_ROW,            '01' AS NR_ROW, '11-12-13-14-15-16-17-18-19-20-22-23-24-25-26-27-28-29' AS CFP FROM DUAL UNION
    SELECT 'Proprietate proprietatea publica' AS NUME_ROW,                    '02' AS NR_ROW, '11-12-13'          AS CFP FROM DUAL UNION 
    SELECT 'Proprietate proprietatea privata - total' AS NUME_ROW,            '03' AS NR_ROW, '14-15-16-17-18-19-29' AS CFP FROM DUAL UNION     
    SELECT 'Proprietate proprietatea mixta (publica si privata)' AS NUME_ROW, '04' AS NR_ROW, '20'                AS CFP FROM DUAL UNION 
    SELECT 'Proprietate proprietatea straina' AS NUME_ROW,                    '05' AS NR_ROW, '22-23-24-25-26-27' AS CFP FROM DUAL UNION 
    SELECT 'Proprietate a intreprinderilor mixte' AS NUME_ROW,                '06' AS NR_ROW, '28'                AS CFP FROM DUAL    

  ) CD
    
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (:pFORM=:pFORM) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  RD.FORM IN (39) AND
  RD.FORM_VERS = :pFORM_VERS AND    
  RD.CAPITOL IN (3) 
   AND D.CUIIO NOT IN (7032055,5696207,5689503) 
GROUP BY
  RD.ORDINE,
  RD.RIND,
  RD.DENUMIRE,
  CD.NR_ROW,   
  CD.NUME_ROW

  
  HAVING 
  
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL1 END),1) >0 OR 
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL2 END),1) >0 OR 
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL3 END),1) >0 OR   
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL4 END),1) >0 OR 
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL5 END),1) >0 OR 
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL6 END),1) >0 OR 
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL7 END),1) >0 OR 
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL8 END),1) >0 OR 
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL9 END),1) >0 OR 
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL10 END),1) >0 OR 
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL11 END),1) >0 OR 
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL12 END),1) >0 OR 
   ROUND(SUM(CASE WHEN CD.CFP LIKE '%'||R.CFP||'%'  THEN  D.COL13 END),1) >0  