DROP TABLE USER_BANCU.CIS2_RENIM CASCADE CONSTRAINTS;

CREATE TABLE USER_BANCU.CIS2_RENIM
(
  CUIIO           NUMBER,
  DENUMIRE        VARCHAR2(255 BYTE),
  CUATM           VARCHAR2(7 BYTE),
  CFP             VARCHAR2(2 BYTE),
  CFOJ            VARCHAR2(3 BYTE),
  CAEM2           VARCHAR2(6 BYTE),
  IDNO            VARCHAR2(13 BYTE)
)
TABLESPACE TBS_DTI_USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
