SELECT
  'Numarul de rinduri introduse: '||SUM(CASE WHEN D.CAPITOL NOT IN (100) AND D.CAPITOL IS NOT NULL THEN 1 ELSE 0 END)
  AS REZULTAT

FROM
  VW_DATA_ALL_TEMP D

WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS) AND
  (:ID_MD=:ID_MD)
  
  AND D.FORM NOT IN(1,2)
  AND D.FILIAL IN (0)
  
HAVING
  (SUM(CASE WHEN  D.CAPITOL=100 AND D.RIND IN('00','01','02','03','04','05','06','07') AND D.COL1=1 THEN 1 ELSE 0 END)>0) AND
  (
   (NVAL(SUM(CASE WHEN D.CAPITOL||'.'||D.RIND||'.'||D.COL1='100.01.1' THEN 1 ELSE 0 END))>0 AND NVAL(SUM(CASE WHEN D.CAPITOL NOT IN (100) AND D.CAPITOL IS NOT NULL THEN 1 ELSE 0 END))=0) OR
   (NVAL(SUM(CASE WHEN D.CAPITOL||'.'||D.RIND||'.'||D.COL1='100.01.1' THEN 1 ELSE 0 END))=0 AND NVAL(SUM(CASE WHEN D.CAPITOL NOT IN (100) AND D.CAPITOL IS NOT NULL THEN 1 ELSE 0 END))>0)
  )