SELECT DISTINCT
'Ancheta: '||D.FILIAL||'; Rind  '||D.RIND||': '||
ROUND(
   NVAL(SUM(CASE WHEN D.CAPITOL IN('301') THEN  D.COL8 ELSE 0 END))*1000/
   NOZERO( nval(SUM(CASE WHEN D.CAPITOL IN('301') THEN  D.COL6 ELSE 0 END) )))
 
  ||' nu apartine intervalului [1500-2300]'  
  
  AS REZULTAT

FROM
  VW_DATA_ALL D      
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL=-1)  AND
  
   D.CAPITOL=301 and
  (:FORM = :FORM) AND D.FORM IN (3) 
  
 GROUP BY D.RIND,D.FILIAL

  
HAVING
( 

 NVAL(SUM(CASE WHEN D.CAPITOL IN('301') THEN  D.COL8 ELSE 0 END))*1000/
   NOZERO( nval(SUM(CASE WHEN D.CAPITOL IN('301') THEN  D.COL6 ELSE 0 END) ))>2300

 
  
  )
  
  OR
  
  (  NVAL(SUM(CASE WHEN D.CAPITOL IN('301') THEN  D.COL8 ELSE 0 END))*1000/
   NOZERO( nval(SUM(CASE WHEN D.CAPITOL IN('301') THEN  D.COL6 ELSE 0 END) )) <1500

)

