SELECT DISTINCT
'RIND.3.1.1:'||SUM(CASE WHEN D.RIND IN ('3.1.1') THEN  NVAL(D.COL1) ELSE 0 END)||' > '||
'RIND.3.1:'||SUM((CASE WHEN D.RIND IN ('3.1') THEN  NVAL(D.COL1) ELSE 0 END))
 
 AS REZULTAT

FROM
VW_DATA_ALL D
                                
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  :CAPITOL = :CAPITOL AND :FORM = :FORM AND
  (:FORM = :FORM) AND
  D.CAPITOL = 307 AND 
  D.FORM = 3


HAVING 
SUM(CASE WHEN D.RIND IN ('3.1.1') THEN  NVAL(D.COL1) ELSE 0 END)>
SUM(CASE WHEN D.RIND IN ('3.1') THEN  NVAL(D.COL1) ELSE 0 END)