DROP USER BACKUP CASCADE;

CREATE USER BACKUP
  IDENTIFIED BY ORACLE
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for BACKUP 
  GRANT CONNECT TO BACKUP;
  GRANT RESOURCE TO BACKUP;
  ALTER USER BACKUP DEFAULT ROLE ALL;
  -- 7 System Privileges for BACKUP 
  GRANT ALTER SESSION TO BACKUP;
  GRANT CREATE DATABASE LINK TO BACKUP;
  GRANT CREATE SEQUENCE TO BACKUP;
  GRANT CREATE SESSION TO BACKUP;
  GRANT CREATE SYNONYM TO BACKUP;
  GRANT CREATE VIEW TO BACKUP;
  GRANT UNLIMITED TABLESPACE TO BACKUP;
  -- 1 Tablespace Quota for BACKUP 
  ALTER USER BACKUP QUOTA UNLIMITED ON USERS;
  -- 1 Object Privilege for BACKUP 
    GRANT EXECUTE ON SYS.DBMS_STATS TO BACKUP;