CREATE DATABASE LINK BNS
CONNECT TO USER_BANCU IDENTIFIED BY vbglove
USING'(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 172.20.0.10)(PORT = 1521))(CONNECT_DATA = (SERVICE_NAME = BNSDB)))';


SELECT * FROM employees@BNS;




 CREATE TABLE CIS2_MD_TABLES11261119
 
 AS 
 
  
 SELECT * FROM CIS2_MD_TABLES11261119@BNS;
 
 
 
 