DECLARE

  CURSOR C IS
  SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  
         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   CUATM AS NR_ROW,
   ROWNUM AS ORDINE,
  '1111111111111' AS DECIMAL_POS,
   DENUMIRE AS NUME_ROW,
   ROUND(COL1,1) AS COL1,
   ROUND(COL2,1) AS COL2,
   NULL AS COL3,
   NULL AS COL4,
   NULL AS COL5,
   NULL AS COL6,
   ROUND(COL7,1) AS COL7,
   ROUND(COL8,1) AS COL8,
   ROUND(COL9,1) AS COL9,
   ROUND(COL10,1) AS COL10, 
   ROUND((((NOZERO(COL2)/NOZERO(COL1))*1000)/12),1) AS COL11,
   ROUND(T2.COL11,1) AS COL12,
   ROUND(NOZERO((((NOZERO(COL2)/NOZERO(COL1))*1000)/12))/NOZERO(T2.COL11)*100,1) AS COL13

FROM
(SELECT
    D.CUATM,
    D.DENUMIRE,
    D.FULL_CODE,    
    SUM(D.COL1) AS COL1,
    SUM(D.COL2) AS COL2,
    SUM(D.COL3) AS COL3,
    SUM(D.COL4) AS COL4,
    SUM(D.COL5) AS COL5,
    SUM(D.COL6) AS COL6,
    SUM(D.COL7) AS COL7,
    SUM(D.COL8) AS COL8,
    SUM(D.COL9) AS COL9,
    SUM(D.COL10) AS COL10
FROM
(

(
SELECT 
  CR.CODUL AS CUATM,
  CR.DENUMIRE,
  CR.FULL_CODE,
  SUM(NVAL(CASE WHEN CAPITOL IN (301) AND COL=2 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
      NVAL(CASE WHEN CAPITOL IN (301) AND COL=2 AND RIND LIKE '%F' THEN VAL ELSE NULL END)) AS COL1,
     
--  SUM((NVAL(CASE WHEN CAPITOL IN (303) AND COL=2 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
--      NVAL(CASE WHEN CAPITOL IN (303) AND COL=2 AND RIND LIKE '%F' THEN VAL ELSE NULL END))+
--      (NVAL(CASE WHEN CAPITOL IN (303) AND COL=4 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
--      NVAL(CASE WHEN CAPITOL IN (303) AND COL=4 AND RIND LIKE '%F' THEN VAL ELSE NULL END))+
--      (NVAL(CASE WHEN CAPITOL IN (303) AND COL=5 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
--      NVAL(CASE WHEN CAPITOL IN (303) AND COL=5 AND RIND LIKE '%F' THEN VAL ELSE NULL END))) AS COL2,
      
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=1 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
      NVAL(CASE WHEN CAPITOL IN (303) AND COL=1 AND RIND LIKE '%F' THEN VAL ELSE NULL END)) AS COL2,
      
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=2 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
      NVAL(CASE WHEN CAPITOL IN (303) AND COL=2 AND RIND LIKE '%F' THEN VAL ELSE NULL END)) AS COL3,
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=3 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
      NVAL(CASE WHEN CAPITOL IN (303) AND COL=3 AND RIND LIKE '%F' THEN VAL ELSE NULL END)) AS COL4,
      
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=4 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
      NVAL(CASE WHEN CAPITOL IN (303) AND COL=4 AND RIND LIKE '%F' THEN VAL ELSE NULL END)) AS COL5,
      
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=5 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
      NVAL(CASE WHEN CAPITOL IN (303) AND COL=5 AND RIND LIKE '%F' THEN VAL ELSE NULL END)) AS COL6,
      
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=6 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
      NVAL(CASE WHEN CAPITOL IN (303) AND COL=6 AND RIND LIKE '%F' THEN VAL ELSE NULL END)) AS COL7,
      
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=7 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
      NVAL(CASE WHEN CAPITOL IN (303) AND COL=7 AND RIND LIKE '%F' THEN VAL ELSE NULL END)) AS COL8,
      
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=8 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
      NVAL(CASE WHEN CAPITOL IN (303) AND COL=8 AND RIND LIKE '%F' THEN VAL ELSE NULL END)) AS COL9,
      
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=9 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
      NVAL(CASE WHEN CAPITOL IN (303) AND COL=9 AND RIND LIKE '%F' THEN VAL ELSE NULL END)) AS COL10
FROM
(
-------------------------------------------------------------------------------
SELECT
    DISTINCT A.CUIIO,
    A.FILIAL,
    A.CAPITOL,
    A.CAPITOL_DEN,
    A.CUATM,
    A.CUATM_FULL,
    A.COL,
    A.RIND,
    A.CAEM2,
    CASE WHEN A.ANCHETA_A='1' AND A.ANCHETA_B='0' THEN A.VAL ELSE NULL END AS VAL
FROM
(SELECT DISTINCT
  D.CUIIO,
  D.FILIAL,
  D.CAPITOL,
  D.CAPITOL_DEN,
  D.PERIOADA,
  D.CUATM,
  D.CUATM_FULL,
  C.COL-1 AS COL,
  MAX(CASE WHEN D.FILIAL='0' THEN 1 ELSE 0 END) AS ANCHETA_A,
  MAX(CASE WHEN D.FILIAL='0' THEN 0 ELSE 1 END) AS ANCHETA_B,
  CASE WHEN D.RIND LIKE '%T' AND S.SEX LIKE 'F' THEN SUBSTR(D.RIND,1,3)||'F' ELSE D.RIND END AS RIND, 
  MAX(CASE WHEN D.RIND LIKE '00%' THEN 0 WHEN D.RIND LIKE '01%' THEN TO_NUMBER(SUBSTR(D.CAEM2,2,5)) ELSE D.COL1 END) AS CAEM2,
  SUM(CASE WHEN D.RIND LIKE '%'||S.SEX THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2, 3,D.COL3, 4,D.COL4, 5,D.COL5, 6,D.COL6, 7,D.COL7, 8,D.COL8, 9,D.COL9, 10,D.COL10, 11,D.COL11, NULL) ELSE NULL END) AS VAL
FROM 
  VW_DATA_ALL_COEF D,
  (
    SELECT  2 AS COL FROM DUAL UNION
    SELECT  3 AS COL FROM DUAL UNION
    SELECT  4 AS COL FROM DUAL UNION
    SELECT  5 AS COL FROM DUAL UNION
    SELECT  6 AS COL FROM DUAL UNION
    SELECT  7 AS COL FROM DUAL UNION
    SELECT  8 AS COL FROM DUAL UNION
    SELECT  9 AS COL FROM DUAL UNION
    SELECT 10 AS COL FROM DUAL UNION
    SELECT 11 AS COL FROM DUAL
  ) C,
  (
    SELECT 'T' AS SEX FROM DUAL UNION
    SELECT 'F' AS SEX FROM DUAL
  ) S
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM = 3 AND
  D.CAPITOL IN(301,303) 
GROUP BY
  D.CUIIO,
  D.FILIAL,
  D.CAPITOL,
  D.CAPITOL_DEN,
  D.PERIOADA,
  D.CUATM,
  D.CUATM_FULL,
  C.COL,
  CASE WHEN D.RIND LIKE '%T' AND S.SEX LIKE 'F' THEN SUBSTR(D.RIND,1,3)||'F' ELSE D.RIND END
  ) A
  INNER JOIN
  (
  SELECT
    D.PERIOADA,
    D.CUIIO AS CUIIO_1,
    MAX(CASE WHEN D.FILIAL='0' THEN 1 ELSE 0 END) AS ANCHETA_A,
    MAX(CASE WHEN D.FILIAL='0' THEN 0 ELSE 1 END) AS ANCHETA_B
FROM 
    VW_DATA_ALL_COEF D
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.FORM = 3 AND
  D.CAPITOL IN(301,303)
GROUP BY
    D.PERIOADA,
    D.CUIIO
    ) B ON (A.CUIIO=B.CUIIO_1)
WHERE
  A.CAEM2<>'0' AND (A.CUATM<>'0501000' OR A.CUATM<>'0510000') AND B.ANCHETA_B='0'
-------------------------------------------------------------------------------
) D 
  INNER JOIN VW_CL_CUATM C  ON(D.CUATM=C.CODUL)
  INNER JOIN VW_CL_CUATM CR ON(C.FULL_CODE LIKE '%'||CR.CODUL||';%') 
WHERE 
  (LENGTH(CR.FULL_CODE)<=16 OR (CR.FULL_CODE NOT LIKE '%0100000;%' AND CR.FULL_CODE NOT LIKE '%9600000;%' AND LENGTH(CR.FULL_CODE)<=24))
GROUP BY
  CR.DENUMIRE,
  CR.FULL_CODE,
  CR.CODUL
)
UNION ALL
(
SELECT 
  CR.CODUL AS CUATM,
  CR.DENUMIRE,
  CR.FULL_CODE,
  SUM(NVAL(CASE WHEN CAPITOL IN (301) AND COL=2 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
      NVAL(CASE WHEN CAPITOL IN (301) AND COL=2 AND RIND LIKE '%F' THEN VAL ELSE NULL END)) AS COL1,
     
--  SUM((NVAL(CASE WHEN CAPITOL IN (303) AND COL=2 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
--      NVAL(CASE WHEN CAPITOL IN (303) AND COL=2 AND RIND LIKE '%F' THEN VAL ELSE NULL END))+
--      (NVAL(CASE WHEN CAPITOL IN (303) AND COL=4 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
--      NVAL(CASE WHEN CAPITOL IN (303) AND COL=4 AND RIND LIKE '%F' THEN VAL ELSE NULL END))+
--      (NVAL(CASE WHEN CAPITOL IN (303) AND COL=5 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
--      NVAL(CASE WHEN CAPITOL IN (303) AND COL=5 AND RIND LIKE '%F' THEN VAL ELSE NULL END))) AS COL2,
      
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=1 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
      NVAL(CASE WHEN CAPITOL IN (303) AND COL=1 AND RIND LIKE '%F' THEN VAL ELSE NULL END)) AS COL2,
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=2 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
      NVAL(CASE WHEN CAPITOL IN (303) AND COL=2 AND RIND LIKE '%F' THEN VAL ELSE NULL END)) AS COL3,
      
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=3 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
      NVAL(CASE WHEN CAPITOL IN (303) AND COL=3 AND RIND LIKE '%F' THEN VAL ELSE NULL END)) AS COL4,
      
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=4 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
      NVAL(CASE WHEN CAPITOL IN (303) AND COL=4 AND RIND LIKE '%F' THEN VAL ELSE NULL END)) AS COL5,
      
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=5 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
      NVAL(CASE WHEN CAPITOL IN (303) AND COL=5 AND RIND LIKE '%F' THEN VAL ELSE NULL END)) AS COL6,
      
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=6 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
      NVAL(CASE WHEN CAPITOL IN (303) AND COL=6 AND RIND LIKE '%F' THEN VAL ELSE NULL END)) AS COL7,
      
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=7 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
      NVAL(CASE WHEN CAPITOL IN (303) AND COL=7 AND RIND LIKE '%F' THEN VAL ELSE NULL END)) AS COL8,
      
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=8 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
      NVAL(CASE WHEN CAPITOL IN (303) AND COL=8 AND RIND LIKE '%F' THEN VAL ELSE NULL END)) AS COL9,
      
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=9 AND RIND LIKE '%T' THEN VAL ELSE NULL END)-
      NVAL(CASE WHEN CAPITOL IN (303) AND COL=9 AND RIND LIKE '%F' THEN VAL ELSE NULL END)) AS COL10 
FROM
(
SELECT
    DISTINCT A.CUIIO,
    A.FILIAL,
    A.CAPITOL,
    A.CAPITOL_DEN,
    A.CUATM,
    A.CUATM_FULL,
    A.COL,
    A.RIND,
    A.CAEM2,
    CASE WHEN A.ANCHETA_A='0' AND A.ANCHETA_B='1' THEN A.VAL ELSE NULL END AS VAL
FROM
(-------------------------------------------------------------------------------
SELECT DISTINCT
  D.CUIIO,
  D.FILIAL,
  CA.FULL_CODE AS FILIAL_FULL,
  D.CAPITOL,
  D.CAPITOL_DEN,
  D.PERIOADA,
  D.CUATM,
  D.CUATM_FULL,
  C.COL-1 AS COL,
  MAX(CASE WHEN D.FILIAL='0' THEN 1 ELSE 0 END) AS ANCHETA_A,
  MAX(CASE WHEN D.FILIAL='0' THEN 0 ELSE 1 END) AS ANCHETA_B,
  CASE WHEN D.RIND LIKE '%T' AND S.SEX LIKE 'F' THEN SUBSTR(D.RIND,1,3)||'F' ELSE D.RIND END AS RIND, 
  MAX(CASE WHEN D.RIND LIKE '00%' THEN 0 WHEN D.RIND LIKE '01%' THEN TO_NUMBER(SUBSTR(D.CAEM2,2,5)) ELSE D.COL1 END) AS CAEM2,
  SUM(CASE WHEN D.RIND LIKE '%'||S.SEX THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2, 3,D.COL3, 4,D.COL4, 5,D.COL5, 6,D.COL6, 7,D.COL7, 8,D.COL8, 9,D.COL9, 10,D.COL10, 11,D.COL11, NULL) ELSE NULL END) AS VAL
FROM 
  VW_DATA_ALL_COEF D
  LEFT JOIN VW_CL_CUATM CA ON (D.FILIAL=CA.CODUL),
  (
    SELECT  2 AS COL FROM DUAL UNION
    SELECT  3 AS COL FROM DUAL UNION
    SELECT  4 AS COL FROM DUAL UNION
    SELECT  5 AS COL FROM DUAL UNION
    SELECT  6 AS COL FROM DUAL UNION
    SELECT  7 AS COL FROM DUAL UNION
    SELECT  8 AS COL FROM DUAL UNION
    SELECT  9 AS COL FROM DUAL UNION
    SELECT 10 AS COL FROM DUAL UNION
    SELECT 11 AS COL FROM DUAL
  ) C,
  (
    SELECT 'T' AS SEX FROM DUAL UNION
    SELECT 'F' AS SEX FROM DUAL
  ) S
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (CA.FULL_CODE LIKE '%'||:pCOD_CUATM||';%') AND 
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND 
  D.FORM = 3 AND
  D.CAPITOL IN(301,303) 
GROUP BY
  D.CUIIO,
  D.FILIAL,
  CA.FULL_CODE,
  D.CAPITOL,
  D.CAPITOL_DEN,
  D.PERIOADA,
  D.CUATM,
  D.CUATM_FULL,
  C.COL,
  CASE WHEN D.RIND LIKE '%T' AND S.SEX LIKE 'F' THEN SUBSTR(D.RIND,1,3)||'F' ELSE D.RIND END
-------------------------------------------------------------------------------
) A
INNER JOIN
  (
  SELECT
    D.PERIOADA,
    D.CUIIO,
    MAX(CASE WHEN D.FILIAL='0' THEN 1 ELSE 0 END) AS ANCHETA_A,
    MAX(CASE WHEN D.FILIAL='0' THEN 0 ELSE 1 END) AS ANCHETA_B
FROM 
    VW_DATA_ALL_COEF D
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.FORM = 3 AND
  D.CAPITOL IN(301,303)
GROUP BY
    D.PERIOADA,
    D.CUIIO
    ) B ON (A.CUIIO=B.CUIIO)
  WHERE
  A.CAEM2<>'0' AND (A.CUATM<>'0501000' OR A.CUATM<>'0510000') AND B.ANCHETA_B='1'
) D 
  INNER JOIN VW_CL_CUATM C  ON(D.FILIAL=C.CODUL)
  INNER JOIN VW_CL_CUATM CR ON(C.FULL_CODE LIKE '%'||CR.CODUL||';%') 
WHERE 
  (LENGTH(CR.FULL_CODE)<=16 OR (CR.FULL_CODE NOT LIKE '%0100000;%' AND CR.FULL_CODE NOT LIKE '%9600000;%' AND LENGTH(CR.FULL_CODE)<=24))
GROUP BY
  CR.DENUMIRE,
  CR.FULL_CODE,
  CR.CODUL
)
)D
GROUP BY
    D.CUATM,
    D.DENUMIRE,
    D.FULL_CODE
ORDER BY
    D.FULL_CODE
  ) D
  LEFT JOIN (
 SELECT NR_ROW, COL11, ID_MDTABLE FROM TABLE_OUT  
  
  WHERE  
    ID_MDTABLE=(CASE WHEN :pPERIOADA<=2002 THEN 449 ELSE 5815 END) AND
    PERIOADA = :pPERIOADA-1  AND
    FORM IN (3)              AND 
    FORM_VERS = :PFORM_VERS  AND    
    COD_CUATM IN (:pCOD_CUATM)  
  ORDER BY
    ORDINE
    ) T2
     
  ON (D.CUATM=T2.NR_ROW)
  
  ;
BEGIN

  FOR CR IN C
  LOOP
    INSERT INTO TABLE_OUT
    (
      PERIOADA,
      FORM,
      FORM_VERS,
      ID_MDTABLE,
      COD_CUATM,
      NR_SECTIE,
      NUME_SECTIE,
      NR_SECTIE1,
      NUME_SECTIE1,
      NR_SECTIE2,
      NUME_SECTIE2,
      NR_ROW,
      ORDINE,
      DECIMAL_POS,
      NUME_ROW,
       
      COL1, COL2, COL3,  COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13
    )
    VALUES
    (
      CR.PERIOADA,
      CR.FORM,
      CR.FORM_VERS,
      CR.ID_MDTABLE,
      CR.COD_CUATM,
      CR.NR_SECTIE,
      CR.NUME_SECTIE,
      CR.NR_SECTIE1,
      CR.NUME_SECTIE1,
      CR.NR_SECTIE2,
      CR.NUME_SECTIE2,
      CR.NR_ROW,
      CR.ORDINE,
      CR.DECIMAL_POS,
      CR.NUME_ROW,
       
      CR.COL1, CR.COL2, CR.COL3, CR.COL4, CR.COL5, CR.COL6, CR.COL7, CR.COL8, CR.COL9, CR.COL10, CR.COL11, CR.COL12, CR.COL13
    );
  END LOOP;
END;