INSERT INTO TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,
  
  COL1, COL2, COL3,  COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14, COL15, COL16, COL17, COL18, COL19, COL20, COL21, COL22, COL23
)
----------------------------------------------------
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  
         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   CAEM2 AS NR_ROW,
   CASE WHEN CAEM2 IN ('00000') THEN 0 ELSE ROWNUM END AS ORDINE,
  '11111111111111111111111' AS DECIMAL_POS,
   DENUMIRE AS NUME_ROW,
   ROUND(NVAL(D.COL2)+NVAL(D.COL7),1) AS COL1,
   ROUND(D.COL2,1) AS COL2,
   ROUND(D.COL3,1) AS COL3, --
   ROUND(D.COL4,1) AS COL4, -- 
   ROUND(D.COL5,1) AS COL5, --5
   ROUND(D.COL6,1) AS COL6, --
   ROUND(D.COL7,1) AS COL7,--
   ROUND(D.COL8,1) AS COL8, --
   ROUND(D.COL9,1) AS COL9, --
   ROUND(D.COL10,1) AS COL10, --
   ROUND(D.COL11,1) AS COL11, --
   ROUND(D.COL12,1) AS COL12, --
   ROUND(D.COL13,1) AS COL13,-- 
   ROUND(D.COL14,1) AS COL14,-- 
   ROUND(D.COL15,1) AS COL15, --
   ROUND(D.COL16,1) AS COL16, --
   ROUND(D.COL17,1) AS COL17, --
   ROUND(D.COL18,1) AS COL18, --
   ROUND(D.COL19,1) AS COL19, --
   ROUND(D.COL20,1) AS COL20,  --
   ROUND(D.COL21,1) AS COL21, -- 
   ROUND(NOZERO(NVAL(D.COL2)+NVAL(COL7))/NOZERO(COL22)*1000/12,1) AS COL22,
   ROUND(NOZERO(NVAL(D.COL2)+NVAL(COL7))/NOZERO(NVAL(COL23_6)+NVAL(COL23_7)+NVAL(COL23_8)+NVAL(COL23_9)),1) AS COL23
--   ROUND(NOZERO(NVAL(D.COL2)+NVAL(COL7)+NVAL(COL15))/NOZERO(T1.COL1)*1000/12,1) AS COL22,
--   ROUND(NOZERO(NVAL(D.COL2)+NVAL(COL7)+NVAL(COL15))/NOZERO(NVAL(T2.COL6)+NVAL(T2.COL9)),1) AS COL23

FROM(
SELECT 
  CR.CODUL AS CAEM2,
  CR.DENUMIRE,
  SUM((NVAL(CASE WHEN CAPITOL IN (303) AND COL='2' THEN VAL ELSE NULL END))+
      (NVAL(CASE WHEN CAPITOL IN (303) AND COL='4' THEN VAL ELSE NULL END))+
      (NVAL(CASE WHEN CAPITOL IN (303) AND COL='5' THEN VAL ELSE NULL END))) AS COL2,
  SUM(CASE WHEN CAPITOL IN (303) AND COL='2' THEN VAL ELSE NULL END) AS COL3,
  SUM(CASE WHEN CAPITOL IN (303) AND COL='3' THEN VAL ELSE NULL END) AS COL4,
  SUM(CASE WHEN CAPITOL IN (303) AND COL='4' THEN VAL ELSE NULL END) AS COL5,
  SUM(CASE WHEN CAPITOL IN (303) AND COL='5' THEN VAL ELSE NULL END) AS COL6,
  
--  SUM(NVAL(CASE WHEN CAPITOL IN (307) AND RIND='2' THEN VAL ELSE NULL END)+
--      NVAL(CASE WHEN CAPITOL IN (307) AND RIND='3' THEN VAL ELSE NULL END)+
--      NVAL(NVAL(CASE WHEN CAPITOL IN (307) AND RIND IN('4.1') THEN VAL ELSE NULL END)+
--           NVAL(CASE WHEN CAPITOL IN (307) AND RIND IN('4.2') THEN VAL ELSE NULL END))+
--      NVAL(CASE WHEN CAPITOL IN (307) AND RIND='5' THEN VAL ELSE NULL END) +
--  NVAL(CASE WHEN CAPITOL IN (307) AND RIND='7' THEN VAL ELSE NULL END)+
--      NVAL(CASE WHEN CAPITOL IN (307) AND RIND='8' THEN VAL ELSE NULL END)+
--      NVAL(CASE WHEN CAPITOL IN (307) AND RIND='9' THEN VAL ELSE NULL END)+
--      NVAL(CASE WHEN CAPITOL IN (307) AND RIND='10' THEN VAL ELSE NULL END)+
--      NVAL(CASE WHEN CAPITOL IN (307) AND RIND='11' THEN VAL ELSE NULL END)) AS COL7,
  
  SUM(CASE WHEN CAPITOL IN (307) AND RIND='1' THEN VAL ELSE NULL END) AS COL7,
  SUM(CASE WHEN CAPITOL IN (307) AND RIND='2' THEN VAL ELSE NULL END) AS COL8,
  SUM(CASE WHEN CAPITOL IN (307) AND RIND='3' THEN VAL ELSE NULL END) AS COL9,
  
  SUM(NVAL(CASE WHEN CAPITOL IN (307) AND RIND='4.1' THEN VAL ELSE NULL END)+
      NVAL(CASE WHEN CAPITOL IN (307) AND RIND='4.2' THEN VAL ELSE NULL END)) AS COL10,
  
  SUM(CASE WHEN CAPITOL IN (307) AND RIND='4.1' THEN VAL ELSE NULL END) AS COL11,
  SUM(CASE WHEN CAPITOL IN (307) AND RIND='4.1.1' THEN VAL ELSE NULL END) AS COL12,
  SUM(CASE WHEN CAPITOL IN (307) AND RIND='4.2' THEN VAL ELSE NULL END) AS COL13,
  SUM(CASE WHEN CAPITOL IN (307) AND RIND='5' THEN VAL ELSE NULL END) AS COL14,

  SUM(CASE WHEN CAPITOL IN (307) AND RIND='6' THEN VAL ELSE NULL END) AS COL15,
--  SUM(NVAL(CASE WHEN CAPITOL IN (307) AND RIND='7' THEN VAL ELSE NULL END)+
--      NVAL(CASE WHEN CAPITOL IN (307) AND RIND='8' THEN VAL ELSE NULL END)+
--      NVAL(CASE WHEN CAPITOL IN (307) AND RIND='9' THEN VAL ELSE NULL END)+
--      NVAL(CASE WHEN CAPITOL IN (307) AND RIND='10' THEN VAL ELSE NULL END)+
--      NVAL(CASE WHEN CAPITOL IN (307) AND RIND='11' THEN VAL ELSE NULL END)) AS COL15,

  SUM(CASE WHEN CAPITOL IN (307) AND RIND='7' THEN VAL ELSE NULL END) AS COL16,
  SUM(CASE WHEN CAPITOL IN (307) AND RIND='8' THEN VAL ELSE NULL END) AS COL17, 
  SUM(CASE WHEN CAPITOL IN (307) AND RIND='9' THEN VAL ELSE NULL END) AS COL18,
  SUM(CASE WHEN CAPITOL IN (307) AND RIND='10' THEN VAL ELSE NULL END) AS COL19,
  SUM(CASE WHEN CAPITOL IN (307) AND RIND='11' THEN VAL ELSE NULL END) AS COL20,
  SUM(CASE WHEN CAPITOL IN (307) AND RIND='12' THEN VAL ELSE NULL END) AS COL21,
  SUM(CASE WHEN CAPITOL IN (301) AND RIND='00-T' AND COL=2 THEN VAL ELSE NULL END) AS COL22,
  SUM(CASE WHEN CAPITOL IN (301) AND RIND='00-T' AND COL=6 THEN VAL ELSE NULL END) AS COL23_6,
  SUM(CASE WHEN CAPITOL IN (301) AND RIND='00-T' AND COL=7 THEN VAL ELSE NULL END) AS COL23_7,
  SUM(CASE WHEN CAPITOL IN (301) AND RIND='00-T' AND COL=8 THEN VAL ELSE NULL END) AS COL23_8,
  SUM(CASE WHEN CAPITOL IN (301) AND RIND='00-T' AND COL=9 THEN VAL ELSE NULL END) AS COL23_9
  
FROM
(
----------------------------------------------------------------------------------------------------
SELECT DISTINCT
  D.CUIIO,
  D.FILIAL,
  D.CAPITOL,
  D.CAPITOL_DEN,
  D.CUATM_FULL,
  C.COL-1 AS COL,
  CASE WHEN D.RIND LIKE '%T' AND S.SEX LIKE 'F' THEN SUBSTR(D.RIND,1,3)||'F' ELSE D.RIND END AS RIND, 
  MAX(CASE WHEN D.RIND LIKE '00%' THEN TO_NUMBER(SUBSTR(D.CAEM2,2,5)) END) AS CAEM2,
  SUM(CASE WHEN D.RIND LIKE '%'||S.SEX THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2, 3,D.COL3, 4,D.COL4, 5,D.COL5, 6,D.COL6, 7,D.COL7, 8,D.COL8, 9,D.COL9, 10,D.COL10, 11,D.COL11, NULL) ELSE NULL END) AS VAL
FROM 
  VW_DATA_ALL D,
  (
    SELECT  2 AS COL FROM DUAL UNION
    SELECT  3 AS COL FROM DUAL UNION
    SELECT  4 AS COL FROM DUAL UNION
    SELECT  5 AS COL FROM DUAL UNION
    SELECT  6 AS COL FROM DUAL UNION
    SELECT  7 AS COL FROM DUAL UNION
    SELECT  8 AS COL FROM DUAL UNION
    SELECT  9 AS COL FROM DUAL UNION
    SELECT 10 AS COL FROM DUAL UNION
    SELECT 11 AS COL FROM DUAL
  ) C,
  (
    SELECT 'T' AS SEX FROM DUAL UNION
    SELECT 'F' AS SEX FROM DUAL
  ) S
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  
  D.FORM = 3 AND
  D.CAPITOL IN(303,301)
GROUP BY
  D.CUIIO,
  D.FILIAL,
  D.CAPITOL,
  D.CAPITOL_DEN,
  D.CUATM_FULL,
  C.COL,
  CASE WHEN D.RIND LIKE '%T' AND S.SEX LIKE 'F' THEN SUBSTR(D.RIND,1,3)||'F' ELSE D.RIND END
  
UNION
    
   
SELECT DISTINCT
    D.CUIIO,
    D.FILIAL,
    D.CAPITOL,
    D.CAPITOL_DEN,
    D.CUATM_FULL,
    NULL AS COL,
    D.RIND AS RIND,
    TO_NUMBER(SUBSTR(D.CAEM2,2,5)) AS CAEM2,
    D.COL1 AS VAL
FROM
    VW_DATA_ALL D
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  
  D.FORM = 3 AND
  D.CAPITOL IN(307)
GROUP BY
  D.CUIIO,
  D.FILIAL,
  D.CAEM2,
  D.CAPITOL,
  D.CAPITOL_DEN,
  D.CUATM_FULL,
  D.COL1,
  D.RIND
-------------------------------------------------------------------------------
) D 
  INNER JOIN VW_CL_CAEM2 C  ON(D.CAEM2=C.NUM_CODE)
  INNER JOIN VW_CL_CAEM2 CR ON(C.FULL_CODE LIKE '%'||CR.CODUL||';%') 
WHERE 
  D.CAEM2 <> '0' AND 
  FILIAL = '0'   AND (RIND LIKE '%T' OR RIND IN ('1','2','3','4','4.1','4.1.1','4.2','5','6','7','8','9','10','11','12')) AND D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  (CR.CODUL LIKE '%00' OR (SUBSTR(C.CODUL,1,3) IN('C11') OR (SUBSTR(C.CODUL,1,3) IN('A01','C10','O84','P85','Q86') AND CR.CODUL LIKE '%0')))
GROUP BY
  CR.DENUMIRE,
  CR.CODUL
ORDER BY
  CR.CODUL    
  ) D
  
--LEFT JOIN (SELECT NR_ROW, COL1, ID_MDTABLE FROM TABLE_OUT  
--  
--  WHERE  ID_MDTABLE IN (5699) AND
--    FORM IN (3)              AND 
--    FORM_VERS = :PFORM_VERS  AND    
--    COD_CUATM IN (:pCOD_CUATM) AND
--    PERIOADA = :pPERIOADA
--    ) T1
--     
--  ON (D.CAEM2=T1.NR_ROW)
--    LEFT JOIN (SELECT NR_ROW, COL6, COL9, ID_MDTABLE FROM TABLE_OUT  
--  
--  WHERE  ID_MDTABLE IN (5649) AND
--    FORM IN (3)              AND 
--    FORM_VERS = :PFORM_VERS  AND    
--    COD_CUATM IN (:pCOD_CUATM) AND
--    PERIOADA = :pPERIOADA
--    ) T2
--     
--  ON (D.CAEM2=T2.NR_ROW)