--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,
--  
--  COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14, COL15, COL16
--)

SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  'B+C+D+E' AS NR_ROW,
  (N.ORDINE - 0.5)  AS ORDINE,
  '0111111111100001' AS DECIMAL_POS,
  'Industrie:(B+C+D+E)' AS NUME_ROW,
  SUM(R.COL1) AS COL1,
  SUM(R.COL2) AS COL2,
  SUM(R.COL3) AS COL3,
  SUM(R.COL4) AS COL4,
  SUM(R.COL5) AS COL5,
  SUM(R.COL6) AS COL6,
  SUM(R.COL7) AS COL7,
  SUM(R.COL8) AS COL8,
  SUM(R.COL9) AS COL9,
  SUM(R.COL10) AS COL10, 
  SUM(R.COL11) AS COL11,
  SUM(R.COL12) AS COL12,
  SUM(R.COL13) AS COL13,
  SUM(R.COL14) AS COL14,
  SUM(R.COL15) AS COL15,
  SUM(R.COL16) AS COL16

FROM TABLE_OUT R,
   ( SELECT MIN(ORDINE) AS ORDINE
   FROM TABLE_OUT 
   WHERE  COD_CUATM IN (:pCOD_CUATM) AND 
   PERIOADA IN (:pPERIOADA) AND 
   ID_MDTABLE IN (:pID_MDTABLE) AND
   FORM IN (:pFORM) AND
   SUBSTR(NR_ROW,1,5) IN ('B0000','C0000','D0000','E0000')) N

WHERE
  R.COD_CUATM IN (:pCOD_CUATM) AND 
  R.PERIOADA IN (:pPERIOADA) AND 
  R.ID_MDTABLE IN (:pID_MDTABLE) AND
  R.FORM IN (:pFORM) AND
  SUBSTR(R.NR_ROW,1,5) IN ('B0000','C0000','D0000','E0000')
GROUP BY
  N.ORDINE