
----------------------------------------------------------------
SELECT
--  :pPERIOADA AS PERIOADA,
--  :pFORM AS FORM,
--  :pFORM_VERS AS FORM_VERS,
--  :pID_MDTABLE AS ID_MDTABLE,
--  :pCOD_CUATM AS COD_CUATM,
--  
--         
--  '0' AS NR_SECTIE,
--  '0' AS NUME_SECTIE,
--  '0' AS NR_SECTIE1,
--  '0' AS NUME_SECTIE1,
--  '0' AS NR_SECTIE2,
--  '0' AS NUME_SECTIE2,
  NR_ROW,
  ROWNUM AS ORDINE,
  DECIMAL_POS,
  NUME_ROW,
  COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14, COL15, COL16
FROM
(
SELECT
   CAEM2 AS NR_ROW,
  '1111111111111111' AS DECIMAL_POS,
   DENUMIRE AS NUME_ROW,  
    ROUND(T1.COL2,1) AS COL1,
    ROUND(D.COL2,1) AS COL2,
    ROUND(D.COL3,1) AS COL3,
    ROUND(COL4,1) AS COL4,
    ROUND(COL5,1) AS COL5,
    ROUND(COL6,1) AS COL6,
    ROUND(COL7,1) AS COL7,
    ROUND(COL8,1) AS COL8,
    ROUND(COL9,1) AS COL9,
    ROUND(COL10,1) AS COL10,
    ROUND(NOZERO(D.COL2)/NOZERO(T1.COL2)*1000/12,1) AS COL11,
    ROUND(T2.COL11,1) AS COL12,
    ROUND(((NOZERO(D.COL2)/NOZERO(T1.COL2)*1000/12)/NOZERO(T2.COL11))*100,1) AS COL13,
    ROUND(NOZERO(NVAL(D.COL2)-NVAL(COL7)-NVAL(COL8)-NVAL(COL9))/NOZERO(T1.COL2)*1000/12,1) AS COL14,
    ROUND(T2.COL14,1) AS COL15,
    ROUND(NOZERO(NOZERO(NVAL(D.COL2)-NVAL(COL7)-NVAL(COL8)-NVAL(COL9))/NOZERO(T1.COL2)*1000/12)/NOZERO(T2.COL14)*100,1) AS COL16
FROM
(
SELECT 
  CR.CODUL AS CAEM2,
  CR.DENUMIRE,
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=2 THEN VAL ELSE NULL END)+
      NVAL(CASE WHEN CAPITOL IN (303) AND COL=4 THEN VAL ELSE NULL END)+
      NVAL(CASE WHEN CAPITOL IN (303) AND COL=5 THEN VAL ELSE NULL END)) COL2,
      
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=2 THEN VAL ELSE NULL END)) COL3,
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=3 THEN VAL ELSE NULL END)) COL4,
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=4 THEN VAL ELSE NULL END)) COL5,
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=5 THEN VAL ELSE NULL END)) COL6,
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=6 THEN VAL ELSE NULL END)) COL7,
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=7 THEN VAL ELSE NULL END)) COL8,
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=8 THEN VAL ELSE NULL END)) COL9,
  SUM(NVAL(CASE WHEN CAPITOL IN (303) AND COL=9 THEN VAL ELSE NULL END)) COL10
 
FROM
(
-------------------------------------------------------------------------------

SELECT DISTINCT
  D.CUIIO,
  D.FILIAL,
  D.CAPITOL,
  D.CAPITOL_DEN,
  D.CUATM_FULL,
  C.COL-1 AS COL,
  CASE WHEN D.RIND LIKE '%T' AND S.SEX LIKE 'F' THEN SUBSTR(D.RIND,1,3)||'F' ELSE D.RIND END AS RIND, 
  MAX(CASE WHEN D.RIND LIKE '00%' THEN 0 WHEN D.RIND LIKE '01%' THEN TO_NUMBER(SUBSTR(D.CAEM2,2,5)) ELSE D.COL1 END) AS CAEM2,
  SUM(CASE WHEN D.RIND LIKE '%'||S.SEX THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2, 3,D.COL3, 4,D.COL4, 5,D.COL5, 6,D.COL6, 7,D.COL7, 8,D.COL8, 9,D.COL9, 10,D.COL10, 11,D.COL11, NULL) ELSE NULL END) AS VAL
FROM 
  VW_DATA_ALL D,
  (
    SELECT  2 AS COL FROM DUAL UNION
    SELECT  3 AS COL FROM DUAL UNION
    SELECT  4 AS COL FROM DUAL UNION
    SELECT  5 AS COL FROM DUAL UNION
    SELECT  6 AS COL FROM DUAL UNION
    SELECT  7 AS COL FROM DUAL UNION
    SELECT  8 AS COL FROM DUAL UNION
    SELECT  9 AS COL FROM DUAL UNION
    SELECT 10 AS COL FROM DUAL UNION
    SELECT 11 AS COL FROM DUAL
  ) C,
  (
    SELECT 'T' AS SEX FROM DUAL UNION
    SELECT 'F' AS SEX FROM DUAL
  ) S
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  
  D.FORM = 3 AND
  D.CAPITOL IN(301,303)
  
  AND D.CUIIO = 9202
GROUP BY
  D.CUIIO,
  D.FILIAL,
  D.CAPITOL,
  D.CAPITOL_DEN,
  D.CUATM_FULL,
  C.COL,
  CASE WHEN D.RIND LIKE '%T' AND S.SEX LIKE 'F' THEN SUBSTR(D.RIND,1,3)||'F' ELSE D.RIND END
-------------------------------------------------------------------------------
) D 
  INNER JOIN VW_CL_CAEM2 C  ON(D.CAEM2=C.NUM_CODE)
  INNER JOIN VW_CL_CAEM2 CR ON(C.FULL_CODE LIKE '%'||CR.CODUL||';%')
 
WHERE 
  D.CAEM2 <> '0' AND FILIAL = '0' AND (RIND LIKE '%T')  AND D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  (CR.CODUL LIKE '%00' OR (SUBSTR(C.CODUL,1,3) IN('C11') OR (SUBSTR(C.CODUL,1,3) IN('A01','C10','O84','P85','Q86') AND CR.CODUL LIKE '%0')))
GROUP BY
  CR.DENUMIRE,
  CR.CODUL
ORDER BY
  CR.CODUL     
    ) D 
  LEFT JOIN (
  
  SELECT NR_ROW, COL2, ID_MDTABLE FROM TABLE_OUT  
  
  WHERE  ID_MDTABLE =(5649) AND
    FORM IN (3)              AND 
    FORM_VERS = :PFORM_VERS  AND    
    COD_CUATM IN (:pCOD_CUATM) AND
    PERIOADA = :pPERIOADA
    
    
    ) T1
     
  ON (D.CAEM2=T1.NR_ROW)
 
 LEFT JOIN (
 SELECT NR_ROW, COL11, COL14, ID_MDTABLE FROM TABLE_OUT  
  
  WHERE  
    ID_MDTABLE=(5699) AND
    PERIOADA = :pPERIOADA-1  AND
    FORM IN (3)              AND 
    FORM_VERS = :PFORM_VERS  AND    
    COD_CUATM IN (:pCOD_CUATM)
    
   
    ) T2
     
  ON (D.CAEM2=T2.NR_ROW)
  
  
  LEFT JOIN (
    SELECT
    D.RIND AS L_RIND,
    D.COL1 AS COL12
FROM 
    VW_DATA_ALL_COEF D
    INNER JOIN VW_CL_CAEM C ON (D.RIND=C.CODUL)
  ) L ON (D.CAEM2=L.L_RIND)
  
ORDER BY NR_ROW
)