SELECT
  
   'Rind: '||D.RIND||
' Col3 - '||CASE WHEN SUM(NVAL(COL3)) = 0 THEN NULL ELSE SUM(NVAL(COL3)) END  ||' <> ' || 'Rind: '||D.RIND||' (Col4+Col5+Col6) - '||CASE WHEN SUM(NVAL(COL4) + NVAL(COL5) +NVAL(COL6)) = 0 THEN NULL ELSE  SUM(NVAL(COL4) + NVAL(COL5) +NVAL(COL6)) END 
  AS REZULTAT

FROM
  VW_DATA_ALL D

WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS) AND
  (:ID_MD=:ID_MD) AND 
  D.FORM IN (54) AND 
  
  D.CAPITOL IN (1076)
  
   GROUP BY 
   D.RIND
  
HAVING
SUM(NVAL(COL3)) <>

  SUM(NVAL(COL4) + NVAL(COL5) +NVAL(COL6) )
  
  
  