SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  
  MR.RIND AS NR_ROW,
  MR.ORDINE AS ORDINE,
  '00000000000' AS DECIMAL_POS, 
   REPLACE(REPLACE(REPLACE(MR.DENUMIRE,'<br>'),'nbsp'),'&;') AS NUME_ROW,
     SUM(D.COL1)  AS COL1,
    SUM(D.COL2)  AS COL2,
    SUM(CIS2.NVAL(D.COL4)+ CIS2.NVAL(D.COL5) + CIS2.NVAL(D.COL6) )  AS COL3, 
    SUM(D.COL4)  AS COL4,
    SUM(D.COL5)  AS COL5,
    SUM(D.COL6)  AS COL6,
    SUM(D.COL7)  AS COL7,
    SUM(D.COL8)  AS COL8,
    SUM(D.COL9)  AS COL9
FROM 
  VW_DATA_ALL D
  RIGHT JOIN MD_RIND MR ON (D.FORM=MR.FORM AND D.ID_MD=MR.ID_MD AND D.CAPITOL=MR.CAPITOL AND 
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' )

  
WHERE
  MR.FORM IN (54)                 AND 
  MR.CAPITOL IN (1076) 
GROUP BY
  MR.RIND,
  MR.DENUMIRE,
  MR.ORDINE