INSERT INTO  TABLE_OUT
    (
      
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
  COL1,COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11
  
    )

SELECT
   :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
   :pCOD_CUATM AS COD_CUATM,         
   CC.CODUL||'~'||CC.FULL_CODE AS NR_SECTIE,
   CC.DENUMIRE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
    MR.RIND||'~'||SUM(ROWNUM) AS NR_ROW,
    MR.RIND ORDINE,
   '00000000000' AS DECIMAL_POS, 
    MR.DENUMIRE  AS NUME_ROW,
    SUM(CIS2.NVAL(D.COL1) + CIS2.NVAL(D.COL3))  AS COL1,
    SUM(CIS2.NVAL(D.COL4) + CIS2.NVAL(D.COL2) )  AS COL2,
    ROUND(SUM(CIS2.NVAL(D.COL4) + CIS2.NVAL(D.COL2)) / CIS2.NOZERO(SUM(CIS2.NVAL(D.COL1) + CIS2.NVAL(D.COL3))),2) AS COL3,  
    SUM( CIS2.NVAL(D.COL1))  AS COL4,
    SUM( CIS2.NVAL(D.COL2))  AS COL5, 
    ROUND(SUM( CIS2.NVAL(D.COL2)) / CIS2.NOZERO(SUM(CIS2.NVAL(D.COL1))),2) AS COL6, 
    SUM(CIS2.NVAL(D.COL3))  AS COL7,
    SUM(CIS2.NVAL(D.COL4))  AS COL8, 
    ROUND(SUM(CIS2.NVAL(D.COL4)) / CIS2.NOZERO(SUM(CIS2.NVAL(D.COL3))),2) AS COL9, 
    SUM( CIS2.NVAL(D.COL5) )  AS COL10, 
    SUM( ROUND(CIS2.NVAL(D.COL6),2)   )  AS COL11 
    
FROM   CIS2.VW_DATA_ALL D
      
         INNER JOIN CIS2.MD_RIND MR ON (MR.ID_MD = D.ID_MD)
         
         INNER JOIN CIS2.VW_CL_CUATM C ON (C.CODUL = D.CUATM)
         INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE  '%'||CC.CODUL||';%')
          
  WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 53 AND 
  D.CAPITOL IN (1074) 
  
  AND CC.PRGS IN ('2')
  
  GROUP BY
  CC.CODUL,
  CC.DENUMIRE,
  CC.FULL_CODE,
  MR.RIND,
  MR.RIND_VERS,
  MR.DENUMIRE