SELECT DISTINCT 
     'Rind = '|| D.RIND|| ' .COL12 - '||
     SUM(NVAL(D.COL12))|| '  -   COL13 - ' || SUM(NVAL(D.COL13))
    
  
  AS REZULTAT

FROM
  CIS2.VW_DATA_ALL_TEMP D           
 
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (40)  AND
  D.CAPITOL IN (1027) AND
  D.RIND IN ('12','13','14','15','16','17','18')
GROUP BY
  D.RIND
HAVING
SUM(NVAL(D.COL12)) > 0 

AND 
  
SUM(NVAL(D.COL13)) =  0 