--UPDATE CIS2.MD_CONTROL 
--
--SET SQL_TEXT = REPLACE(SQL_TEXT,'VW_DATA_ALL','VW_DATA_ALL_TEMP')

SELECT *

FROM CIS2.MD_CONTROL
WHERE 

FORM NOT IN (58,61,62,57,59,63,66) 
       AND 
        
        SQL_TEXT NOT LIKE '%VW_DATA_ALL_TEMP%'
        
        