--UPDATE CIS2.MD_CONTROL 
--
--
--SET SQL_TEXT = 
--
--
--REPLACE(REPLACE(REPLACE(REPLACE(SQL_TEXT,'D.FORM_VERS=:FORM_VERS       OR','D.FORM_VERS=:FORM_VERS'),'D.FORM_VERS=:FORM_VERS  D.FORM_VERS <>  :FORM_VERS','D.FORM_VERS=:FORM_VERS OR  D.FORM_VERS <>  :FORM_VERS')
--,'D.FORM_VERS=:FORM_VERS :FORM_VERS = -1','D.FORM_VERS=:FORM_VERS  OR :FORM_VERS = -1' ),':FORM_VERS=:FORM_VERS       OR',':FORM_VERS=:FORM_VERS       ') 


--SELECT 
--CONTROL,
--REPLACE(REPLACE(REPLACE(SQL_TEXT,'OR :PERIOADA = -1',' '),'OR :CUIIO = -1',' '),'OR :FORM = -1','') AS SQL,
--
--REPLACE(SQL_TEXT,'D.FORM_VERS=:FORM_VERS       OR','D.FORM_VERS=:FORM_VERS ')  AS COL2
-- FROM CIS2.MD_CONTROL
---- 
SELECT *
FROM CIS2.MD_CONTROL 

WHERE 
(SQL_TEXT LIKE '%D.FORM_VERS=:FORM_VERS       OR%'    
OR 
SQL_TEXT LIKE '%D.FORM_VERS=:FORM_VERS  D.FORM_VERS <>  :FORM_VERS%'

OR 
SQL_TEXT LIKE '%D.FORM_VERS=:FORM_VERS :FORM_VERS = -1%'

OR 
SQL_TEXT LIKE '%:FORM_VERS=:FORM_VERS       OR%'

)

AND FORM IN  (

SELECT FORM
FROM CIS2.MD_FORM

WHERE 
FORM_VERS = 2000
AND FORM NOT IN (64,57,59,63,64) 
)
