--UPDATE CIS.MD_CONTROL
--set  SQL_TEXT = REPLACE(SQL_TEXT,'OR :PERIOADA = -1',' ')

SELECT D.CONTROL,
       REPLACE(D.SQL_TEXT,'OR :PERIOADA = -1',' ')   SQL_TEXT


    FROM CIS.MD_CONTROL D
    
    WHERE 
    
    FORM = 2
    
    AND SQL_TEXT  LIKE '%OR :PERIOADA = -1%'