UPDATE CIS2.MD_CONTROL 
--
--SET SQL_TEXT = REPLACE(REPLACE(REPLACE(REPLACE(SQL_TEXT,'OR :PERIOADA = -1',' '),'OR :CUIIO = -1',' '),'OR :FORM = -1',''),':FORM_VERS = -1','')

SET SQL_TEXT = REPLACE(SQL_TEXT,'D.FORM_VERS=:FORM_VERS       OR','D.FORM_VERS=:FORM_VERS ')  


--SELECT 
--CONTROL,
--REPLACE(REPLACE(REPLACE(SQL_TEXT,'OR :PERIOADA = -1',' '),'OR :CUIIO = -1',' '),'OR :FORM = -1','') AS SQL,
--
--REPLACE(SQL_TEXT,'D.FORM_VERS=:FORM_VERS       OR','D.FORM_VERS=:FORM_VERS ')  AS COL2
-- FROM CIS2.MD_CONTROL
 
WHERE 
SQL_TEXT LIKE '%D.FORM_VERS=:FORM_VERS       OR%'  
AND FORM = 8
AND CONTROL_VERS = 2010
--AND CONTROL IN ('44-0002')