--UPDATE USER_EREPORTING.MD_CONTROL 
--
--SET SQL_TEXT = REPLACE(REPLACE(REPLACE(REPLACE(SQL_TEXT,'OR :PERIOADA = -1',' '),'OR :CUIIO = -1',' '),'OR :FORM = -1',''),'OR :FORM_VERS = -1','')


SELECT * 
from USER_EREPORTING.MD_CONTROL

WHERE 
--FORM = 57 AND CONTROL_VERS = 2010


--
--AND  
SQL_TEXT NOT LIKE '%VW_DATA_ALL_FR_TEMP%'

AND FORM IN (67)
--AND CONTROL_VERS = 2010