



SELECT 
SUBSTR(SQL_TEXT,1,INSTR(SQL_TEXT,'VW_DATA_ALL_TEMP') -1) part1

    FROM CIS2.MD_CONTROL D
    
    WHERE 
    
    D.FORM = 45
    
    AND D.SQL_TEXT LIKE '%VW_DATA_ALL_TEMP%';
    
    SELECT 
    REPLACE(SQL_TEXT,'VW_DATA_ALL','VW_DATA_ALL_TEMP')  