SELECT 

     
     NVAL(L.COL1)||' <> '|| NVAL(R.COL1)||' <> '||NVAL(R.COL2) 
     
     AS REZULTAT
FROM

(
SELECT
D.CUIIO,


SUM(CASE WHEN  D.RIND IN ('400') 
   AND D.CAPITOL IN (1127) THEN NVAL(D.COL4) else 0 END ) AS COL1
    FROM
 CIS2.VW_DATA_ALL D 
 

WHERE
  (D.PERIOADA=:PERIOADA        ) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
   D.FORM IN (64)  
--   D.RIND IN ('400') 
--   AND D.CAPITOL IN (1127)
   
   
GROUP BY 
D.CUIIO


) L LEFT JOIN (

SELECT
D.CUIIO,
SUM(CASE WHEN   D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('63.1119.10') THEN  nval(D.COL1) ELSE 0 END ) AS COL1,
SUM(CASE WHEN   D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('57.1091.10') THEN  nval(D.COL1) ELSE 0 END ) AS COL2
    
    FROM
 CIS2.VW_DATA_ALL_FR D 
 --40637090

WHERE
  (D.PERIOADA=:PERIOADA        ) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (:CUIIO_VERS=:CUIIO_VERS      OR :CUIIO_VERS <> CUIIO_VERS) AND
  (:FORM = :FORM                OR :FORM <> :FORM) AND
  (:FORM_VERS=:FORM_VERS        OR :FORM_VERS <>:FORM_VERS) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS = :CAPITOL_VERS OR :CAPITOL_VERS <> :CAPITOL_VERS) AND
  (:ID_MD=:ID_MD                 OR :ID_MD<>:ID_MD) AND
  

   
    D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('63.1119.10','57.1091.10')
    
    GROUP BY
    D.CUIIO

) R ON R.CUIIO = L.CUIIO 



GROUP BY
L.COL1,
R.COL1,
R.COL2

HAVING

(CASE 


      
      
      WHEN (L.COL1 <> R.COL2 OR  L.COL1 <> R.COL1) THEN 2
      
     END ) = 2
