SELECT

SUM(CASE WHEN   D.RIND IN ('010') AND D.CAPITOL IN (1120) AND D.FORM = 63 THEN  D.COL1 ELSE NULL END ) AS COL1,
SUM(CASE WHEN   D.RIND IN ('010') AND D.CAPITOL IN (1093) AND D.FORM_VERS = 2009 AND D.FORM = 57 THEN  D.COL1 ELSE NULL END ) AS COL2
    
    FROM
 CIS2.VW_DATA_ALL_FR D 
 --40637090

WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (:CUIIO_VERS=:CUIIO_VERS      OR :CUIIO_VERS <> CUIIO_VERS) AND
  (:FORM = :FORM                OR :FORM <> :FORM) AND
  (:FORM_VERS=:FORM_VERS        OR :FORM_VERS <>:FORM_VERS) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS = :CAPITOL_VERS OR :CAPITOL_VERS <> :CAPITOL_VERS) AND
  (:ID_MD=:ID_MD                 OR :ID_MD<>:ID_MD) AND
  
 (  D.RIND IN ('010') 
   AND D.CAPITOL IN (1120)
   AND D.FORM = 63 )
   
   OR 
   
   (  D.RIND IN ('010') 
   AND D.CAPITOL IN (1093)
   AND D.FORM = 57 )
   
