SELECT 
    L.CUIIO,
     
     L.COL1||' <> '||nval(ROUND(R.COL1,1))||' <> '||nval(ROUND (R.COL2,1)) 
     
     AS REZULTAT
FROM

(

SELECT
D.CUIIO,
SUM(CASE WHEN  D.RIND IN ('320') 
   AND D.CAPITOL IN (1126) THEN NVAL(D.COL2) else 0 END ) AS COL1
    FROM
 CIS2.VW_DATA_ALL D 
 --40637090

WHERE
  (D.PERIOADA=:PERIOADA         ) AND
 -- (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) 
  AND
D.FORM IN (64)  
--   D.RIND IN ('320') 
--   AND D.CAPITOL IN (1126)
GROUP BY 
D.CUIIO



) L LEFT JOIN (

SELECT
D.CUIIO,
ROUND(SUM(CASE WHEN   D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('63.1120.060') THEN  NVAL(D.COL2) ELSE 0 END ) /1000,1) AS COL1,
ROUND(SUM(CASE WHEN   D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('57.1090.290') THEN  NVAL(D.COL2) ELSE 0 END ) / 1000,1) AS COL2
    
    FROM
 CIS2.VW_DATA_ALL_FR D 
 --40637090

WHERE
  (D.PERIOADA=:PERIOADA         ) AND
 -- (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (:CUIIO_VERS=:CUIIO_VERS      OR :CUIIO_VERS <> CUIIO_VERS) AND
  (:FORM = :FORM                OR :FORM <> :FORM) AND
  (:FORM_VERS=:FORM_VERS        OR :FORM_VERS <>:FORM_VERS) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS = :CAPITOL_VERS OR :CAPITOL_VERS <> :CAPITOL_VERS) AND
  (:ID_MD=:ID_MD                 OR :ID_MD<>:ID_MD) AND
  

   
    D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('63.1120.060','57.1090.290')
    
    GROUP BY
    D.CUIIO

) R ON R.CUIIO = L.CUIIO 



GROUP BY
L.COL1,
R.COL1,
R.COL2,
L.CUIIO


HAVING

(CASE WHEN  L.COL1 <> R.COL2 THEN 1 ELSE 0 END)

+ 

(CASE WHEN  L.COL1 <> R.COL1  THEN 1 ELSE 0 END) = 2