SELECT 
DISTINCT D.CUIIO 
    FROM VW_KATALOG_ASA_2010 D
            LEFT JOIN USER_BANCU.VW_KATALOG_RSF_PR_2010 R ON R.CUIIO = D.CUIIO
            LEFT JOIN USER_BANCU.VW_KATALOG_ASA_2010 RR ON RR.CUIIO = D.CUIIO
            
            WHERE 
            R.CUIIO IS NOT NULL
            AND 
            RR.CUIIO IS NOT NULL
            
