SELECT 
'RIND ' || D.RIND || 'COL1' ||SUM(D.COL1)|| 'COL2' || SUM(D.COL2 )   AS REZULTAT 


FROM
  CIS2.VW_DATA_ALL_GC D  
        
WHERE
  (D.PERIOADA IN  (:PERIOADA)         OR :PERIOADA = -1) AND
  (D.NR_GOSP=:NR_GOSP               OR :NR_GOSP = -1) AND
  (D.UNIT_CODE_VERS=:UNIT_CODE_VERS    OR :UNIT_CODE_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS OR  :CAPITOL_VERS <>  :CAPITOL_VERS ) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
 
  D.FORM IN (61)  AND
  D.CAPITOL IN (1111)  
  AND D.RIND NOT IN ('100','110','110') 


GROUP BY 

D.RIND