SELECT 
 
  -- TO_DATE(MAX(CASE WHEN D.RIND IN ('2') AND CAPITOL IN (1135) THEN D.COL2 ELSE NULL END),'DD.MM.YYYY')+1 -
 --  TO_DATE(MAX(CASE WHEN D.RIND IN ('2') AND CAPITOL IN (1135) THEN D.COL1 ELSE NULL END),'DD.MM.YYYY')  
  'mai mare de un an' 
  AS REZULTAT
  
FROM
  CIS2.VW_DATA_ALL_FR D  
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
 -- (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (66)  AND
  D.RIND IN ('2') AND CAPITOL IN (1135)
  
  GROUP BY D.COL1
  
  HAVING 
  
 (TO_CHAR(LAST_DAY(TO_DATE( '01-FEB-'|| substr(D.COL1,-4,4), 'DD-MON-YYYY')), 'DD')=28 




AND
  
 (TO_DATE(MAX(CASE WHEN D.RIND IN ('2') AND CAPITOL IN (1135) THEN D.COL2 ELSE NULL END),'DD.MM.YYYY')+1 -
 TO_DATE(MAX(CASE WHEN D.RIND IN ('2') AND CAPITOL IN (1135) THEN D.COL1 ELSE NULL END),'DD.MM.YYYY')  >365) )
 
 OR  
 
 (TO_CHAR(LAST_DAY(TO_DATE( '01-FEB-'|| substr(D.COL1,-4,4), 'DD-MON-YYYY')), 'DD')=29 AND
  
 (TO_DATE(MAX(CASE WHEN D.RIND IN ('2') AND CAPITOL IN (1135) THEN D.COL2 ELSE NULL END),'DD.MM.YYYY')+1 -
 TO_DATE(MAX(CASE WHEN D.RIND IN ('2') AND CAPITOL IN (1135) THEN D.COL1 ELSE NULL END),'DD.MM.YYYY')  >366) )
 