SELECT  
D.NR_GOSP,
'Nu ati introdus toate datele'
 AS REZULTAT
FROM
  CIS2.VW_DATA_ALL_GC D 
        
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.NR_GOSP=:NR_GOSP               OR :NR_GOSP = -1) AND
  (D.UNIT_CODE_VERS=:UNIT_CODE_VERS    OR :UNIT_CODE_VERS = -1) AND
  (:FORM  = :FORM               OR  :FORM  <>  :FORM ) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <> :CAPITOL) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
 
  D.FORM IN (62,58)    
   
 GROUP BY 
D.NR_GOSP
  
HAVING
  
  (CIS2.NVAL(SUM(CASE WHEN D.FORM IN (58) AND   D.CAPITOL IN ('419') AND D.RIND IN ('TIP3')  THEN NVAL(D.COL1)  ELSE NULL END))  >  0
   
   AND 
   CIS2.NVAL(SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN ('1118') AND D.RIND IN 'TIP3'  THEN NVAL(D.COL1)  ELSE NULL END)) =  0 
   
   )
   
 