        SELECT  
            1  ORDINE, 
            'Plata muncii lucrătorilor angagaţi' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6010')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6010')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6010')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6010')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6010')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6010')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
  
  UNION  


SELECT  
            2  ORDINE, 
            'Seminţe şi răsadă procurate' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6015')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6015')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6015')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6015')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6015')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6015')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   UNION  


SELECT  
            3  ORDINE, 
            'Material săditor de plantaţii multianuale procurat' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6020')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6020')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6020')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6020')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6020')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6020')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   UNION  


SELECT  
            4  ORDINE, 
            'Nutreţuri procurate' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6025')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6025')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6025')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6025')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6025')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6025')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   
   UNION  


SELECT  
            5  ORDINE, 
            'Îngrăşăminte minerale' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6030')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6030')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6030')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6030')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6030')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6030')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   
   
   
   UNION  


SELECT  
            6  ORDINE, 
            'Substante chimice şi biologice pentru protecţia plantelor' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6035')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6035')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6035')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6035')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6035')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6035')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   
   UNION  


SELECT  
            7  ORDINE, 
            'Motorină' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6040')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6040')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6040')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6040')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6040')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6040')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   UNION  


SELECT  
            8  ORDINE, 
            'Benzină' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6045')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6045')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6045')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6045')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6045')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6045')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
    
UNION

SELECT  
            9  ORDINE, 
            'Alte produse petroliere' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6050')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6050')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6050')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6050')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6050')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6050')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   
   
   UNION

SELECT  
            10  ORDINE, 
            'Combustibil (fără gaz) ' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6055')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6055')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6055')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6055')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6055')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6055')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   UNION

SELECT  
            11  ORDINE, 
            'Gaz' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6060')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6060')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6060')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6060')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6060')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6060')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   
   UNION

SELECT  
            12  ORDINE, 
            'Energia electrică' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6065')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6065')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6065')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6065')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6065')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6065')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   
   UNION

SELECT  
            13  ORDINE, 
            'Piese de schimb, materiale de reparaţie şi construcţie pentru reparaţia mijloacelor fixe' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6070')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6070')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6070')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6070')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6070')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6070')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   UNION

SELECT  
            14  ORDINE, 
            'Ambalaj şi material pentru ambalare' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6075')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6075')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6075')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6075')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6075')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6075')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   
   UNION

SELECT  
            15  ORDINE, 
            'Consumuri şi cheltuieli pentru asigurarea cu apă pentru irigat, irigarea şi desecarea' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6080')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6080')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6080')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6080')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6080')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6080')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   UNION

SELECT  
            16  ORDINE, 
            'Consumuri şi cheltuieli pentru executarea lucrărilor agricole (prelucrarea solului, însămînţarea, recoltarea, încorporarea îngrăşămintelor şi alte lucrări agrochimice şi altele)' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6085')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6085')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6085')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6085')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6085')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6085')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   UNION

SELECT  
            17  ORDINE, 
            'Consumuri şi cheltuieli pentru deservirea zootehnică şi veterinară, însămînţarea artificială  a vitelor, tunsul oilor etc.' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6090')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6090')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6090')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6090')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6090')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6090')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   UNION

SELECT  
            18  ORDINE, 
            'Consumuri şi cheltuieli aferente serviciilor prestate de terți pentru reparația tehnicii' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6095')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6095')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6095')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6095')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6095')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6095')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   UNION

SELECT  
            19  ORDINE, 
            'Consumuri şi cheltuieli pentru serviciile de transport aferente producţiei agricole' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6100')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6100')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6100')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6100')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6100')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6100')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   UNION

SELECT  
            20  ORDINE, 
            'Consumuri şi cheltuieli pentru alte servicii (de telecomunicaţii, bancare, de audit,  notariale, de reclamă etc.) ' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6105')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6105')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6105')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6105')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6105')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6105')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   UNION

SELECT  
            21  ORDINE, 
            'Plata pentru arenda terenurilor' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6110')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6110')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6110')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6110')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6110')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6110')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   
   UNION

SELECT  
            22  ORDINE, 
            'Procurarea tineretului de animale, păsărilor şi  familiilor de albine ' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6115')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6115')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6115')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6115')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6115')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6115')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   UNION

SELECT  
            23  ORDINE, 
            'Alte consumuri şi cheltuieli privind producţia agricolă' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6120')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6120')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6120')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6120')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6120')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6120')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   
   UNION

SELECT  
            24  ORDINE, 
            'Impozitul funciar ' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6125')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6125')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6125')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6125')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6125')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6125')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   UNION

SELECT  
            25  ORDINE, 
            'Contribuţii privind asigurările sociale de stat obligatorii ' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6130')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6130')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6130')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6130')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6130')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6130')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   UNION

SELECT  
            30  ORDINE, 
            'Alte impozite' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6135')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6135')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6135')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6135')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6135')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6135')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   UNION

SELECT  
            31  ORDINE, 
            'Total  (6010+6015+…+6135)' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6000')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6000')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6000')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6000')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6000')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL3  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6000')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  D.COL1  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   AND D.UNIT_CODE = 60701
   
   
   ORDER BY 
   ORDINE