SELECT 
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
    '0' AS NR_SECTIE,
    '0' AS NUME_SECTIE,
    '0' AS NR_SECTIE1,
    '0' AS NUME_SECTIE1,
    '0' AS NR_SECTIE2,
     '0' AS NUME_SECTIE2,
         A.RIND AS NR_ROW, 
         ROWNUM ORDINE, 
         '222222' AS DECIMAL_POS,  
       
         A.DENUMIRE NUME_ROW, 
         ROUND(A.COL1,2)  AS COL1,
         ROUND(A.COL2,2)  AS COL2,
         ROUND(A.COL3,2)  AS COL3,
         ROUND(A.COL4,2)  AS COL4,
         ROUND(A.COL5,2)  AS COL5,
         ROUND(A.COL6,2)  AS COL6      

   FROM
        (
        SELECT  
            1  ORDINE, 
            '6010' rind,
            'Plata muncii lucratorilor angagati' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6010')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6010')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6010')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6010')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6010')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN   NVAL(D.COL3)  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6010')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
  
  UNION  


SELECT  
            2  ORDINE, 
            '6015' rind,
            'Seminte si rasada procurate' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6015')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6015')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6015')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6015')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6015')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN   NVAL(D.COL3) ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6015')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   UNION  


SELECT  
            3  ORDINE, 
            '6020' rind,
            'Material saditor de plantatii multianuale procurat' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6020')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6020')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6020')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6020')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6020')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN   NVAL(D.COL3)  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6020')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   UNION  


SELECT  
            4  ORDINE, 
            '6025' rind,
            'Nutreturi procurate' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6025')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6025')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6025')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6025')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6025')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN   NVAL(D.COL3) ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6025')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   
   UNION  


SELECT  
            5  ORDINE, 
            '6030' rind,
            'Ingrasaminte minerale' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6030')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6030')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6030')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6030')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6030')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN   NVAL(D.COL3) ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6030')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   
   
   
   UNION  


SELECT  
            6  ORDINE, 
            '6035' rind,
            'Substante chimice si biologice pentru protectia plantelor' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6035')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6035')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6035')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6035')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6035')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN   NVAL(D.COL3) ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6035')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   
   UNION  


SELECT  
            7  ORDINE, 
            '6040' rind,
            'Motorina' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6040')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6040')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6040')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6040')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6040')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  NVAL(D.COL3) ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6040')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   UNION  


SELECT  
            8  ORDINE, 
            '6045' rind,
            'Benzina' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6045')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6045')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6045')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6045')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6045')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  NVAL(D.COL3) ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6045')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
    
UNION

SELECT  
            9  ORDINE, 
            '6050' rind,
            'Alte produse petroliere' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6050')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6050')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6050')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6050')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6050')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN   NVAL(D.COL3)  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6050')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   
   
   UNION

SELECT  
            10  ORDINE, 
            '6055' rind,
            'Combustibil (fara gaz) ' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6055')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6055')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6055')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6055')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6055')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN   NVAL(D.COL3)  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6055')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   UNION

SELECT  
            11  ORDINE, 
            '6060' rind,
            'Gaz' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6060')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6060')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6060')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6060')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6060')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN   NVAL(D.COL3) ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6060')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   
   UNION

SELECT  
            12  ORDINE, 
            '6065' rind,
            'Energia electrica' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6065')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6065')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6065')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6065')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6065')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  NVAL(D.COL3) ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6065')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   
   UNION

SELECT  
            13  ORDINE, 
            '6070' rind,
            'Piese de schimb, materiale de reparatie si constructie pentru reparatia mijloacelor fixe' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6070')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6070')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6070')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6070')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6070')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  NVAL(D.COL3) ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6070')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   UNION

SELECT  
            14  ORDINE, 
            '6075' rind,
            'Ambalaj si material pentru ambalare' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6075')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6075')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6075')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6075')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6075')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  NVAL(D.COL3) ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6075')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   
   UNION

SELECT  
            15  ORDINE, 
            '6080' rind,
            'Consumuri si cheltuieli pentru asigurarea cu apa pentru irigat, irigarea si desecarea' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6080')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6080')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6080')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6080')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6080')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  NVAL(D.COL3) ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6080')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   UNION

SELECT  
            16  ORDINE, 
            '6085' rind,
            'Consumuri si cheltuieli pentru executarea lucrarilor agricole (prelucrarea solului, insamintarea, recoltarea, incorporarea ingrasamintelor si alte lucrari agrochimice si altele)' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6085')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6085')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6085')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6085')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6085')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  NVAL(D.COL3)  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6085')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   UNION

SELECT  
            17  ORDINE, 
            '6090' rind,
            'Consumuri si cheltuieli pentru deservirea zootehnica si veterinara, insamintarea artificiala  a vitelor, tunsul oilor etc.' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6090')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6090')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6090')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6090')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6090')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN   NVAL(D.COL3)  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6090')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   UNION

SELECT  
            18  ORDINE, 
            '6095' rind,
            
            'Consumuri si cheltuieli aferente serviciilor prestate de ter?i pentru repara?ia tehnicii' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6095')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6095')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6095')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6095')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6095')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN   NVAL(D.COL3)  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6095')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   UNION

SELECT  
            19  ORDINE, 
            '6100' rind,
            'Consumuri si cheltuieli pentru serviciile de transport aferente productiei agricole' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6100')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6100')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6100')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6100')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6100')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  NVAL(D.COL3) ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6100')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  NVAL(D.COL1)   ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   UNION

SELECT  
            20  ORDINE, 
            '6105' rind,
            'Consumuri si cheltuieli pentru alte servicii (de telecomunicatii, bancare, de audit,  notariale, de reclama etc.) ' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6105')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6105')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6105')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6105')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6105')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN   NVAL(D.COL3)  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6105')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   UNION

SELECT  
            21  ORDINE, 
            '6110' rind,
            'Plata pentru arenda terenurilor' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6110')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6110')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6110')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6110')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6110')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  NVAL(D.COL3)  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6110')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   
   UNION

SELECT  
            22  ORDINE, 
            '6115' rind,
            'Procurarea tineretului de animale, pasarilor si  familiilor de albine ' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6115')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6115')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6115')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6115')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6115')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  NVAL(D.COL3) ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6115')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   UNION

SELECT  
            23  ORDINE, 
            '6120' rind,
            'Alte consumuri si cheltuieli privind productia agricola' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6120')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6120')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6120')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6120')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6120')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  NVAL(D.COL3)  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6120')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   
   UNION

SELECT  
            24  ORDINE, 
            '6125' rind,
            'Impozitul funciar ' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6125')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6125')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6125')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6125')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6125')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN   NVAL(D.COL3)  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6125')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   UNION

SELECT  
            25  ORDINE, 
            '6130' rind,
            'Contributii privind asigurarile sociale de stat obligatorii ' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6130')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6130')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6130')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6130')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6130')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  NVAL(D.COL3)  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6130')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   UNION

SELECT  
            26  ORDINE, 
            '6135' rind,
            'Alte impozite' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6135')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6135')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6135')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6135')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6135')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  NVAL(D.COL3)  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6135')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   UNION

SELECT  
            27  ORDINE, 
            '6000' rind,
            'Total  (6010+6015+…+6135)' DENUMIRE,
            SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6000')  THEN  D.COL1  ELSE NULL END) AS COL1,
            
            SUM(CASE WHEN D.FORM IN (62) AND D.CAPITOL IN (1115)  AND  MR.RIND IN ('6000')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('0')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL2,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6000')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP2')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL3,
            
            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6000')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1118)  AND  MR.RIND IN ('TIP3')  THEN  NVAL(D.COL1)  ELSE NULL END)) AS COL4,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6000')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN  NVAL(D.COL3)  ELSE NULL END)) AS COL5,

            SUM(CASE WHEN  D.FORM IN (62) AND  D.CAPITOL IN (1115)  AND  MR.RIND IN ('6000')  THEN  NVAL(D.COL1)  ELSE NULL END)/
            NOZERO(SUM(CASE WHEN D.FORM IN (61) AND  D.CAPITOL IN (1110)  AND  MR.RIND IN ('001')  THEN NVAL(D.COL1)  ELSE NULL END)) AS COL6

          
           
  FROM
    VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (:pFORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (62,61)  -- AND D.CAPITOL IN (1115,1118)
   
   
   
   ORDER BY 
   ORDINE
   ) A