SELECT DISTINCT 

DECODE(CC.NR_COLUMN, '1', 'COL.1', '2', 'COL.2')||', Rind.'||D.RIND||': '||

  CIS2.NVAL(SUM(CASE WHEN D.PERIOADA= :PERIOADA AND D.NUM IN (2,3,4) THEN  DECODE(CC.NR_COLUMN, '1', CIS2.NVAL(D.COL1), '2', CIS2.NVAL(D.COL2))   ELSE 0 END))||' < '||

( CIS2.NVAL(SUM(CASE WHEN D.PERIOADA= :PERIOADA-1 AND D.NUM IN (1,2,3) THEN DECODE(CC.NR_COLUMN, '1', CIS2.NVAL(D.COL1), '2', CIS2.NVAL(D.COL2))  ELSE 0 END))) 
 
  AS REZULTAT

FROM
  CIS2.VW_DATA_ALL D,             
       (                                                                        
       SELECT '1' AS NR_COLUMN FROM DUAL UNION                                  
       SELECT '2' AS NR_COLUMN FROM DUAL                                  
       ) CC                                      


WHERE
  (D.PERIOADA IN (:PERIOADA,:PERIOADA-1)) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (:CUIIO_VERS=:CUIIO_VERS     OR  :CUIIO_VERS <>  :CUIIO_VERS) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (6)  AND
  D.CAPITOL IN (316) AND
  D.RIND NOT IN ('001')
  
 GROUP BY 
 CC.NR_COLUMN,
 D.RIND
 HAVING 
 
 CIS2.NVAL(SUM(CASE WHEN D.PERIOADA= :PERIOADA AND D.NUM IN (2,3,4) THEN  DECODE(CC.NR_COLUMN, '1', CIS2.NVAL(D.COL1), '2', CIS2.NVAL(D.COL2)) ELSE 0 END)) < 

( CIS2.NVAL(SUM(CASE WHEN D.PERIOADA= :PERIOADA-1 AND D.NUM IN (1,2,3) THEN DECODE(CC.NR_COLUMN, '1', CIS2.NVAL(D.COL1), '2', CIS2.NVAL(D.COL2))ELSE 0 END)))