SELECT 

     
     CASE WHEN L.COL1 = 0 THEN NULL ELSE L.COL1 END  ||': COL2 - nu ati introdus o valoare'
     
     AS REZULTAT
FROM

(

SELECT
D.CUIIO,
SUM(CASE WHEN  D.RIND IN ('400') 
   AND D.CAPITOL IN (1127) THEN NVAL(D.COL4) else 0 END ) AS COL1
    FROM
 CIS2.VW_DATA_ALL D 
 --40637090

WHERE
  (D.PERIOADA=:PERIOADA       ) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
    
  D.FORM IN (64) 
 
GROUP BY 
D.CUIIO

HAVING 
 SUM( CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400')  THEN  CIS2.NVAL(D.COL3)+ CIS2.NVAL(D.COL4)+ CIS2.NVAL(D.COL5) ELSE 0 END) > 0



) L LEFT JOIN (

SELECT
D.CUIIO,
SUM(CASE WHEN   D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('63.1119.6') THEN  TO_NUMBER(NVAL(D.COL1)) ELSE 0  END ) AS COL1,
SUM(CASE WHEN   D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('57.1091.5') THEN  TO_NUMBER(NVAL(D.COL1)) ELSE 0  END ) AS COL2
    
    FROM
 CIS2.VW_DATA_ALL_FR D 
 --40637090

WHERE
  (D.PERIOADA=:PERIOADA         ) AND
   (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (:CUIIO_VERS=:CUIIO_VERS      OR :CUIIO_VERS <> CUIIO_VERS) AND
  (:FORM = :FORM                OR :FORM <> :FORM) AND
  (:FORM_VERS=:FORM_VERS        OR :FORM_VERS <>:FORM_VERS) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS = :CAPITOL_VERS OR :CAPITOL_VERS <> :CAPITOL_VERS) AND
  (:ID_MD=:ID_MD                 OR :ID_MD<>:ID_MD) AND
  

   
    D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('63.1119.6','57.1091.5')
    
    GROUP BY
    D.CUIIO

) R ON R.CUIIO = L.CUIIO 



GROUP BY
L.COL1,
R.COL1,
R.COL2
 




HAVING

L.COL1 = 0 

AND 

(
R.COL1 = 0  AND R.COL2 = 0 
)