SELECT 
DISTINCT 
'Ati completat eronat Col3.'
--CIS2.NVAL(SUM( CASE WHEN D.CAPITOL IN (1127)  AND D.RIND IS NOT NULL THEN D.COL31  ELSE NULL END)) ,
--CIS2.NVAL(SUM( CASE WHEN D.CAPITOL IN (1127)  AND D.RIND IS NOT NULL THEN D.COL5   ELSE NULL END)) 
  AS REZULTAT
  
FROM

 CIS2.VW_DATA_ALL D  
 
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  D.CAPITOL IN (1127) AND D.RIND NOT IN ('400')
  AND D.FORM = 64
  
GROUP BY D.COL31

 
HAVING
CIS2.NVAL(SUM( CASE WHEN D.CAPITOL IN (1127)  THEN D.COL5  ELSE NULL END)) >0


 
AND  D.COL31 not IN (
SELECT DISTINCT D.COL31 FROM  CIS2.VW_DATA_ALL D 
WHERE 
 (D.COL31 IN ('3514', '3523', '3530') OR (D.COL31 LIKE '451%')  OR (D.COL31 LIKE '453%') OR (D.COL31 LIKE '454%') 
 OR (D.COL31 LIKE '462%') OR (D.COL31 LIKE '463%') OR (D.COL31 LIKE '464%') OR (D.COL31 LIKE '465%') OR (D.COL31 LIKE '466%') 
 OR (D.COL31 LIKE '467%') OR (D.COL31 LIKE '468%') OR (D.COL31 LIKE '469%') OR (D.COL31 LIKE '47%') OR (D.COL31 LIKE '56%')))