SELECT  
D.CUIIO,

'CAP.4 nu ati completat suficiente CAEM, rev.2: ' ||
--CIS2.NVAL(COUNT( CASE WHEN D.CAPITOL IN (1124)   AND D.RIND IN ('100','110','120','130','140') AND D.COL1 >0 THEN CIS2.NVAL(D.RIND)  ELSE NULL END)) ||'>'||
CIS2.NVAL(COUNT( CASE WHEN D.CAPITOL IN (1127)   AND D.COL31 IS NOT NULL      THEN D.COL31  ELSE NULL END))  

  
  AS REZULTAT
FROM
 CIS2.VW_DATA_ALL D  
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  --(D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1)
  
  
  GROUP BY 
  D.CUIIO
  HAVING
  
CIS2.NVAL(COUNT( CASE WHEN D.CAPITOL IN (1124)   AND D.RIND IN ('100','110','120','130','140') AND D.COL1 >0  THEN CIS2.NVAL(D.RIND)  ELSE NULL END))>
CIS2.NVAL(COUNT( CASE WHEN D.CAPITOL IN (1127)   AND D.COL31 IS NOT NULL      THEN D.COL31  ELSE NULL END))  

