SELECT 
--D.CUIIO,
ROUND(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('150') THEN  D.COL1 ELSE null END ),1) AS RIND_150_COL1
 

FROM   
    CIS2.VW_DATA_ALL_COEF D  
WHERE
  D.FORM IN (64)             AND 
  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
  D.CAPITOL IN (1124)
  
 -- AND D.CUIIO IN  (227548,458963)
  
--  GROUP BY 
--  D.CUIIO
 

 
