SELECT
  SUM(CASE WHEN D.CAPITOL IN 327 AND (D.RIND LIKE '6%' OR D.RIND LIKE '7%'  ) THEN D.COL4 ELSE 0 END)||' > '||
 (SUM(CASE WHEN D.CAPITOL IN 420 AND D.RIND IN '750' THEN D.COL1 ELSE 0 END)
  
  
  )  AS REZULTAT
  

FROM
  VW_DATA_ALL D



WHERE
  (D.PERIOADA IN (:PERIOADA)) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
   D.CAPITOL IN (420,327) AND
   D.FORM = :FORM AND
   D.FORM = 8
   
   
   --SUM Rind.(60-76).Col.4) Anexa2 <= (Rind.750)( Col.1+ Col.2) CAP I
HAVING
  SUM(CASE WHEN D.CAPITOL IN 327 AND (D.RIND LIKE '6%' OR D.RIND LIKE '7%'  ) THEN D.COL4 END) > 
 (SUM(CASE WHEN D.CAPITOL IN 420 AND D.RIND IN '750' THEN NVAL(D.COL1) ELSE 0 END))