SELECT

   MR.RIND,
   MR.ORDINE,
   MR.DENUMIRE,
   
  (SUM(CASE WHEN R.RIND = MR.RIND  THEN D.COL1 ELSE 0 END)+
   SUM(CASE WHEN R.RIND = MR.RIND  THEN D.COL2 ELSE 0 END)) AS COL1,
   
  (SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (12,13) THEN D.COL1 ELSE 0 END)+
   SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (12,13) THEN D.COL2 ELSE 0 END)) AS COL2,
   
  ROUND((((SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (12,13) THEN D.COL1 ELSE 0 END)+
              SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (12,13) THEN D.COL2 ELSE 0 END))/
       CIS2.NOZERO(SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (12,13) THEN D.COL3 ELSE 0 END)+
             SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (12,13) THEN D.COL4 ELSE 0 END)))/  
      (P.COL1))*100,1) AS COL3,
      
  (SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (15,16,17,18,19) THEN D.COL1 ELSE 0 END)+
   SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (15,16,17,18,19) THEN D.COL2 ELSE 0 END)) AS COL4,
   
   ROUND((((SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (15,16,17,18,19) THEN D.COL1 ELSE 0 END)+
              SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (15,16,17,18,19) THEN D.COL2 ELSE 0 END))/
       CIS2.NOZERO(SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (15,16,17,18,19) THEN D.COL3 ELSE 0 END)+
              SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (15,16,17,18,19) THEN D.COL4 ELSE 0 END)))/  
       (P.COL1))*100,1)  AS COL5,
           
    
 (SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (20) THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (20) THEN D.COL2 ELSE 0 END)) AS COL6,
  
 ROUND((((SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (20) THEN D.COL1 ELSE 0 END)+
              SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (20) THEN D.COL2 ELSE 0 END))/
       CIS2.NOZERO(SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (20) THEN D.COL3 ELSE 0 END)+
              SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (20) THEN D.COL4 ELSE 0 END)))/  
       (P.COL1))*100,1)  AS COL7,
    
 (SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (24,26) THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (24,26) THEN D.COL2 ELSE 0 END)) AS COL8,
  
  ROUND((((SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (24,26) THEN D.COL1 ELSE 0 END)+
             SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (24,26) THEN D.COL2 ELSE 0 END))/
      CIS2.NOZERO(SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (24,26) THEN D.COL3 ELSE 0 END)+
             SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (24,26) THEN D.COL4 ELSE 0 END)))/  
      (P.COL1 ))*100,1) AS COL9,
    
  
 (SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (28) THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN R.RIND =  MR.RIND AND RR.CFP IN (28) THEN D.COL2 ELSE 0 END)) AS COL10,
  
 ROUND((((SUM(CASE WHEN R.RIND = MR.RIND AND RR.CFP IN (28) THEN D.COL1 ELSE 0 END)+
              SUM(CASE WHEN R.RIND = MR.RIND  AND RR.CFP IN (28) THEN D.COL2 ELSE 0 END))/
       CIS2.NOZERO(SUM(CASE WHEN R.RIND = MR.RIND  AND RR.CFP IN (28) THEN D.COL3 ELSE 0 END)+
              SUM(CASE WHEN R.RIND = MR.RIND  AND RR.CFP IN (28) THEN D.COL4 ELSE 0 END)))/  
       (P.COL1))*100,1) AS COL11
  
  
FROM 
  CIS2.DATA_ALL D
  
                       INNER JOIN CIS2.MD_RIND MR ON (MR.ID_MD=D.ID_MD)
                       INNER JOIN CIS2.RENIM RR ON (RR.CUIIO = D.CUIIO AND RR.CUIIO_VERS = D.CUIIO_VERS)
                       INNER JOIN CIS2.VW_CL_CUATM C ON C.CODUL = RR.CUATM
  
        
  
CROSS JOIN (
    SELECT
      DENUMIRE,
      RIND,
      ORDINE
  
    FROM 
     CIS2.MD_RIND
  
   WHERE
     RIND NOT IN ('440','441','442','450','-','410','420','430') AND
     CAPITOL = 323 AND
     RIND_VERS >= 2006 AND
     STATUT = 1  ) R
     
CROSS JOIN (
    SELECT 
                  
                   SUM(CASE WHEN MR.RIND IN ('01') THEN   D.COL1 ELSE NULL END)  AS COL1
                 
                     FROM CIS2.DATA_ALL D
                
                       INNER JOIN CIS2.MD_RIND MR ON (MR.ID_MD=D.ID_MD)
                       INNER JOIN CIS2.RENIM RR ON (RR.CUIIO = D.CUIIO AND RR.CUIIO_VERS = D.CUIIO_VERS)
                 
                     WHERE 
                     D.FORM=100 AND
                     D.PERIOADA IN :pPERIOADA AND
                     MR.CAPITOL = 330 AND   
                     D.CUIIO = 2 
  

  ) P
     
  
                WHERE 
                
           (D.FORM=:pFORM) AND
           (D.FORM_VERS=:pFORM_VERS) AND
           (:pID_MDTABLE=:pID_MDTABLE) AND
           (C.FULL_CODE LIKE '%'||:pCOD_CUATM||';%') AND   
           D.PERIOADA IN :pPERIOADA AND
           D.FORM = 8 AND
           MR.CAPITOL = 323
  
GROUP BY
  MR.DENUMIRE,
  MR.RIND,
  MR.ORDINE,
  P.COL1