
DECLARE

  CURSOR C IS

SELECT 
    DF.PERIOADA,
    DF.FORM,
    DF.FORM_VERS,
    DF.ID_MDTABLE,
    DF.COD_CUATM,
    DF.NR_SECTIE,
    DF.NUME_SECTIE,
    DF.NR_SECTIE1,
    DF.NUME_SECTIE1,
    DF.NR_SECTIE2,
    DF.NUME_SECTIE2,
    DF.NR_ROW,
    DF.ORDINE,
    DF.DECIMAL_POS,
    DF.NUME_ROW,
    DF.COL1,
    DF.COL2,
    DF.COL3,
    DF.COL4,
    DF.COL5,
    DF.COL6,
    DF.COL7,
    DF.COL8,
    DF.COL9,
    DF.COL10,
    DF.COL11
 
    
  

   
FROM 
(

SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,    
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   R.RIND AS NR_ROW,
   R.ORDINE AS ORDINE,
  '00000000000' AS DECIMAL_POS,
   R.DENUMIRE AS NUME_ROW,
   
  (SUM(CASE WHEN R.RIND = D.RIND  THEN D.COL1 ELSE 0 END)+
   SUM(CASE WHEN R.RIND = D.RIND  THEN D.COL2 ELSE 0 END)) AS COL1,
   
  (SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (12,13) THEN D.COL1 ELSE 0 END)+
   SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (12,13) THEN D.COL2 ELSE 0 END)) AS COL2,
   
  ROUND((((SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (12,13) THEN D.COL1 ELSE 0 END)+
              SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (12,13) THEN D.COL2 ELSE 0 END))/
       CIS2.NOZERO(SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (12,13) THEN D.COL3 ELSE 0 END)+
             SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (12,13) THEN D.COL4 ELSE 0 END)))/  
      (P.COL1))*100,1) AS COL3,
      
  (SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (15,16,17,18,19) THEN D.COL1 ELSE 0 END)+
   SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (15,16,17,18,19) THEN D.COL2 ELSE 0 END)) AS COL4,
   
   ROUND((((SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (15,16,17,18,19) THEN D.COL1 ELSE 0 END)+
              SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (15,16,17,18,19) THEN D.COL2 ELSE 0 END))/
       CIS2.NOZERO(SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (15,16,17,18,19) THEN D.COL3 ELSE 0 END)+
              SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (15,16,17,18,19) THEN D.COL4 ELSE 0 END)))/  
       (P.COL1))*100,1)  AS COL5,
           
    
 (SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (20) THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (20) THEN D.COL2 ELSE 0 END)) AS COL6,
  
 ROUND((((SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (20) THEN D.COL1 ELSE 0 END)+
              SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (20) THEN D.COL2 ELSE 0 END))/
       CIS2.NOZERO(SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (20) THEN D.COL3 ELSE 0 END)+
              SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (20) THEN D.COL4 ELSE 0 END)))/  
       (P.COL1))*100,1)  AS COL7,
    
 (SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (24,26) THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (24,26) THEN D.COL2 ELSE 0 END)) AS COL8,
  
  ROUND((((SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (24,26) THEN D.COL1 ELSE 0 END)+
             SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (24,26) THEN D.COL2 ELSE 0 END))/
      CIS2.NOZERO(SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (24,26) THEN D.COL3 ELSE 0 END)+
             SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (24,26) THEN D.COL4 ELSE 0 END)))/  
      (P.COL1 ))*100,1) AS COL9,
    
  
 (SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (28) THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (28) THEN D.COL2 ELSE 0 END)) AS COL10,
  
 ROUND((((SUM(CASE WHEN R.RIND = D.RIND AND D.CFP IN (28) THEN D.COL1 ELSE 0 END)+
              SUM(CASE WHEN R.RIND = D.RIND  AND D.CFP IN (28) THEN D.COL2 ELSE 0 END))/
       CIS2.NOZERO(SUM(CASE WHEN R.RIND = D.RIND  AND D.CFP IN (28) THEN D.COL3 ELSE 0 END)+
              SUM(CASE WHEN R.RIND = D.RIND  AND D.CFP IN (28) THEN D.COL4 ELSE 0 END)))/  
       (P.COL1))*100,1) AS COL11
  
  
FROM 
  CIS2.VW_DATA_ALL D
  
CROSS JOIN (
    SELECT
      DENUMIRE,
      RIND,
      ORDINE
  
    FROM 
     CIS2.MD_RIND
  
   WHERE
     RIND NOT IN ('440','441','442','450','-','410','420','430') AND
     CAPITOL = 323 AND
     RIND_VERS >= 2006 AND
     STATUT = 1  ) R
     
CROSS JOIN (
---------------------CROSS
       SELECT 
                  
                   SUM(D.COL1)  AS COL1
                 
                     FROM CIS2.DATA_ALL D
                
                       INNER JOIN CIS2.MD_RIND MR ON (MR.ID_MD=D.ID_MD)
                       INNER JOIN CIS2.RENIM RR ON (RR.CUIIO = D.CUIIO AND RR.CUIIO_VERS = D.CUIIO_VERS)
                 
                     WHERE 
                     D.FORM=100 AND
                     D.PERIOADA IN :pPERIOADA AND
                     MR.CAPITOL = 330 AND   
                     D.CUIIO = 2 
                     AND MR.RIND IN ('02')
---------------------CROSS

  ) P
     
WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  D.PERIOADA IN :pPERIOADA AND
  D.FORM = 8 AND
  D.CAPITOL = 323
  
GROUP BY
  R.DENUMIRE,
  R.RIND,
  R.ORDINE,
  P.COL1
  
  )  DF
  
  ;
  
  
  BEGIN

  FOR CR IN C
  
  LOOP
    INSERT INTO   USER_BANCU.TABLE_OUT_TEST 
    
   -- CIS2.TABLE_OUT
    (
      PERIOADA,
      FORM,
      FORM_VERS,
      ID_MDTABLE,
      COD_CUATM,
      NR_SECTIE,
      NUME_SECTIE,
      NR_SECTIE1,
      NUME_SECTIE1,
      NR_SECTIE2,
      NUME_SECTIE2,
      NR_ROW,
      ORDINE,
      DECIMAL_POS,
      NUME_ROW,
       
    COL1, COL2, COL3,COL4,COL5,COL6,COL7,COL8,COL9,COL10, COL11
    )
    VALUES
    (
      CR.PERIOADA,
      CR.FORM,
      CR.FORM_VERS,
      CR.ID_MDTABLE,
      CR.COD_CUATM,
      CR.NR_SECTIE,
      CR.NUME_SECTIE,
      CR.NR_SECTIE1,
      CR.NUME_SECTIE1,
      CR.NR_SECTIE2,
      CR.NUME_SECTIE2,
      CR.NR_ROW,
      CR.ORDINE,
      CR.DECIMAL_POS,
      CR.NUME_ROW,
       
      CR.COL1, CR.COL2, CR.COL3,CR.COL4,
      CR.COL5,CR.COL6,CR.COL7,CR.COL8,CR.COL9,CR.COL10,CR.COL11
    );
  END LOOP;
END;