INSERT INTO TABLE_OUT_TEST 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
 COL1, COL2, COL3
)
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,    
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   NR_ROW,
   ORDINE,
  '000' AS DECIMAL_POS,
   NUME_ROW,
   COL1, COL2, COL3
   
FROM (

SELECT
  
   R.RIND AS NR_ROW,
   R.ORDINE AS ORDINE,
   R.DENUMIRE AS NUME_ROW,
   
  SUM(DISTINCT CASE WHEN R.RIND = D.RIND  THEN D.COL2 ELSE 0 END)AS COL1,
  
   
  
   ROUND((((SUM(CASE WHEN R.RIND =  D.RIND  THEN D.COL2 ELSE 0 END))/
       NOZERO(SUM(CASE WHEN R.RIND =  D.RIND  THEN D.COL4 ELSE 0 END)))/  
      (P.COL1))*100,1) AS COL2,
    
    
    
   
  ROUND(((SUM(CASE WHEN R.RIND = D.RIND  THEN D.COL2 ELSE 0 END))*100)/  
         (SUM(CASE WHEN D.RIND IN '100' THEN D.COL2 ELSE 0 END)),1) AS COL3
  
  
FROM 
  VW_DATA_ALL D
  
CROSS JOIN (
    SELECT
      DENUMIRE,
      RIND,
      ORDINE
  
    FROM 
     MD_RIND
  
   WHERE
     RIND IN ('440') AND
     CAPITOL = 323 AND
     RIND_VERS >= 2006 AND
     STATUT = 1  ) R
     
CROSS JOIN (
    SELECT DISTINCT 
      
      COL1 AS COL1
    
    FROM 
      VW_DATA_ALL D
     
  
WHERE 
  D.FORM = 100 AND
  D.CUIIO = 2 AND
  D.PERIOADA IN :pPERIOADA AND
  D.CAPITOL = 330 AND
  D.RIND IN '03'
  

  ) P
     
WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  D.PERIOADA IN :pPERIOADA AND
  D.FORM = 8 AND
  D.CAPITOL = 323 AND
  D.RIND IN ('100','440')
  
GROUP BY
  R.DENUMIRE,
  R.RIND,
  R.ORDINE,
  P.COL1
  
UNION

SELECT
  
   R.RIND AS NR_ROW,
   R.ORDINE AS ORDINE,
   R.DENUMIRE AS NUME_ROW,
   
  SUM(DISTINCT CASE WHEN R.RIND = D.RIND  THEN D.COL2 ELSE 0 END)AS COL1,
  
   
  
   ROUND((((SUM(CASE WHEN R.RIND =  D.RIND  THEN D.COL2 ELSE 0 END))/
       NOZERO(SUM(CASE WHEN R.RIND =  D.RIND  THEN D.COL4 ELSE 0 END)))/  
      (P.COL1))*100,1) AS COL2,
    
    
    
   
  ROUND(((SUM(CASE WHEN R.RIND = D.RIND  THEN D.COL2 ELSE 0 END))*100)/  
         (SUM(CASE WHEN D.RIND IN '100' THEN D.COL2 ELSE 0 END)),1) AS COL3
  
  
FROM 
  CIS2.VW_DATA_ALL D
  
CROSS JOIN (
    SELECT
      DENUMIRE,
      RIND,
      ORDINE
  
    FROM 
     MD_RIND
  
   WHERE
     RIND IN ('441','442','450') AND
     CAPITOL = 323 AND
     RIND_VERS >= 2006 AND
     STATUT = 1  ) R
     
CROSS JOIN (
    SELECT DISTINCT 
      
      COL1 AS COL1
    
    FROM 
      CIS2.VW_DATA_ALL D
     
  
WHERE 
  D.FORM = 100 AND
  D.CUIIO = 2 AND
  D.PERIOADA IN :pPERIOADA AND
  D.CAPITOL = 330 AND
  D.RIND IN '04'
  

  ) P
     
WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  D.PERIOADA IN :pPERIOADA AND
  D.FORM = 8 AND
  D.CAPITOL = 323 AND
  D.RIND IN ('100','441','442','450')
  
GROUP BY
  R.DENUMIRE,
  R.RIND,
  R.ORDINE,
  P.COL1
  ---------------------------------------------------------------------------------
  
  
  UNION

SELECT
  
   R.RIND AS NR_ROW,
   R.ORDINE AS ORDINE,
   R.DENUMIRE AS NUME_ROW,
   
  SUM(DISTINCT CASE WHEN R.RIND = D.RIND  THEN D.COL2 ELSE 0 END)AS COL1,
  
   
  
   ROUND((((SUM(CASE WHEN R.RIND =  D.RIND  THEN D.COL2 ELSE 0 END))/
       NOZERO(SUM(CASE WHEN R.RIND =  D.RIND  THEN D.COL4 ELSE 0 END)))/  
      (P.COL1))*100,1) AS COL2,
    
    
    
   
  ROUND(((SUM(CASE WHEN R.RIND = D.RIND  THEN D.COL2 ELSE 0 END))*100)/  
         (SUM(CASE WHEN D.RIND IN '100' THEN D.COL2 ELSE 0 END)),1) AS COL3
  
  
FROM 
  CIS2.VW_DATA_ALL D
  
CROSS JOIN (
    SELECT
      DENUMIRE,
      RIND,
      ORDINE
  
    FROM 
     MD_RIND
  
   WHERE
     RIND IN ('410','420','430') AND
     CAPITOL = 323 AND
     RIND_VERS >= 2006 AND
     STATUT = 1  ) R
     
CROSS JOIN (
    SELECT DISTINCT 
      
      COL1 AS COL1
    
    FROM 
      VW_DATA_ALL D
     
  
WHERE 
  D.FORM = 100 AND
  D.CUIIO = 2 AND
  D.PERIOADA IN :pPERIOADA AND
  D.CAPITOL = 330 AND
  D.RIND IN '02'
  

  ) P
     
WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  D.PERIOADA IN :pPERIOADA AND
  D.FORM = 8 AND
  D.CAPITOL = 323 AND
  D.RIND IN ('100','410','420','430')  
  
GROUP BY
  R.DENUMIRE,
  R.RIND,
  R.ORDINE,
  P.COL1
  
)