INSERT INTO TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
 COL1, COL2, COL3,COL4,COL5,COL6,COL7,COL8,COL9,COL10, COL11
)
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,    
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   R.RIND AS NR_ROW,
   R.ORDINE AS ORDINE,
  '00000000000' AS DECIMAL_POS,
   R.DENUMIRE AS NUME_ROW,
   
  (SUM(CASE WHEN R.RIND = D.RIND  THEN D.COL1 ELSE 0 END)+
   SUM(CASE WHEN R.RIND = D.RIND  THEN D.COL2 ELSE 0 END)) AS COL1,
   
  (SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (12,13) THEN D.COL1 ELSE 0 END)+
   SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (12,13) THEN D.COL2 ELSE 0 END)) AS COL2,
   
  ROUND((((SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (12,13) THEN D.COL1 ELSE 0 END)+
              SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (12,13) THEN D.COL2 ELSE 0 END))/
       NOZERO(SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (12,13) THEN D.COL3 ELSE 0 END)+
             SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (12,13) THEN D.COL4 ELSE 0 END)))/  
      (P.COL1))*100,1) AS COL3,
      
  (SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (15,16,17,18,19) THEN D.COL1 ELSE 0 END)+
   SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (15,16,17,18,19) THEN D.COL2 ELSE 0 END)) AS COL4,
   
   ROUND((((SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (15,16,17,18,19) THEN D.COL1 ELSE 0 END)+
              SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (15,16,17,18,19) THEN D.COL2 ELSE 0 END))/
       NOZERO(SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (15,16,17,18,19) THEN D.COL3 ELSE 0 END)+
              SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (15,16,17,18,19) THEN D.COL4 ELSE 0 END)))/  
       (P.COL1))*100,1)  AS COL5,
           
    
 (SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (20) THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (20) THEN D.COL2 ELSE 0 END)) AS COL6,
  
 ROUND((((SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (20) THEN D.COL1 ELSE 0 END)+
              SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (20) THEN D.COL2 ELSE 0 END))/
       NOZERO(SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (20) THEN D.COL3 ELSE 0 END)+
              SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (20) THEN D.COL4 ELSE 0 END)))/  
       (P.COL1))*100,1)  AS COL7,
    
 (SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (24,26) THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (24,26) THEN D.COL2 ELSE 0 END)) AS COL8,
  
  ROUND((((SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (24,26) THEN D.COL1 ELSE 0 END)+
             SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (24,26) THEN D.COL2 ELSE 0 END))/
      NOZERO(SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (24,26) THEN D.COL3 ELSE 0 END)+
             SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (24,26) THEN D.COL4 ELSE 0 END)))/  
      (P.COL1 ))*100,1) AS COL9,
    
  
 (SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (28) THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN R.RIND =  D.RIND AND D.CFP IN (28) THEN D.COL2 ELSE 0 END)) AS COL10,
  
 ROUND((((SUM(CASE WHEN R.RIND = D.RIND AND D.CFP IN (28) THEN D.COL1 ELSE 0 END)+
              SUM(CASE WHEN R.RIND = D.RIND  AND D.CFP IN (28) THEN D.COL2 ELSE 0 END))/
       NOZERO(SUM(CASE WHEN R.RIND = D.RIND  AND D.CFP IN (28) THEN D.COL3 ELSE 0 END)+
              SUM(CASE WHEN R.RIND = D.RIND  AND D.CFP IN (28) THEN D.COL4 ELSE 0 END)))/  
       (P.COL1))*100,1) AS COL11
  
  
FROM 
  VW_DATA_ALL D
  
CROSS JOIN (
    SELECT
      DENUMIRE,
      RIND,
      ORDINE
  
    FROM 
     MD_RIND
  
   WHERE
     RIND  IN ('100','200','210','220','230','240','300','400','460','500','600','700','710','720','810','820','830','840','850','860','870','880','890')  AND
     CAPITOL = 323 AND
     RIND_VERS >= 2006 AND
     STATUT = 1  ) R
     
CROSS JOIN (
    SELECT DISTINCT 
      
      COL1 AS COL1
    
    FROM 
      VW_DATA_ALL D
     
  
WHERE 
  D.FORM = 100 AND
  D.CUIIO = 2 AND
  D.PERIOADA IN :pPERIOADA AND
  D.CAPITOL = 330 AND
  D.RIND IN '01'
  

  ) P
     
WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  D.PERIOADA IN :pPERIOADA AND
  D.FORM = 8 AND
  D.CAPITOL = 323
  
GROUP BY
  R.DENUMIRE,
  R.RIND,
  R.ORDINE,
  P.COL1
  
ORDER BY
  R.ORDINE