--INSERT INTO TABLE_OUT_TEST 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
-- COL1, COL2, COL3,COL4,COL5,COL6, COL7
--)


SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,    
   CFP_ORDINE AS NR_SECTIE,
   CFP_DENUMIRE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   NR_ROW,
   ORDINE,
  '0000000' AS DECIMAL_POS,
   NUME_ROW,
  COL1, 
   
   COL2, 
     
  CASE WHEN NR_ROW IN ('510','520','530') THEN 0 ELSE COL3 END AS COL3,
   
  CASE WHEN NR_ROW IN ('510','520','530') THEN 0 ELSE COL4 END AS COL4,
   
  CASE WHEN NR_ROW IN ('510','520','530') THEN 0 ELSE COL5 END AS COL5,
   
  CASE WHEN NR_ROW IN ('510','520','530') THEN 0 ELSE COL6 END AS COL6, 
   
  CASE WHEN NR_ROW IN ('510','520','530','730','740','750','760') THEN 0 ELSE COL7 END AS COL7
   
 
   

FROM

(
SELECT
  B.CFP_DENUMIRE,
  B.CFP_ORDINE,
  R.RIND AS NR_ROW,
  R.ORDINE AS ORDINE,
  R.DENUMIRE AS NUME_ROW,
 (SUM(CASE WHEN B.CFP LIKE '%'|| D.CFP ||'%' AND R.RIND =  D.RIND THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN B.CFP LIKE '%'|| D.CFP ||'%' AND R.RIND =  D.RIND THEN D.COL2 ELSE 0 END))  AS COL1,
  
  SUM(CASE WHEN B.CFP LIKE '%'|| D.CFP ||'%' AND R.RIND =  D.RIND THEN D.COL1 ELSE 0 END) AS COL2,
  
  SUM(CASE WHEN B.CFP LIKE '%'|| D.CFP ||'%' AND R.RIND =  D.RIND THEN D.COL2 ELSE 0 END) AS COL3,
  
 (SUM(CASE WHEN B.CFP LIKE '%'|| D.CFP ||'%' AND R.RIND =  D.RIND THEN D.COL3 ELSE 0 END)+
  SUM(CASE WHEN B.CFP LIKE '%'|| D.CFP ||'%' AND R.RIND =  D.RIND THEN D.COL4 ELSE 0 END))  AS COL4,
  
  SUM(CASE WHEN B.CFP LIKE '%'|| D.CFP ||'%' AND R.RIND =  D.RIND THEN D.COL3 ELSE 0 END) AS COL5,
  
  SUM(CASE WHEN B.CFP LIKE '%'|| D.CFP ||'%' AND R.RIND =  D.RIND THEN D.COL4 ELSE 0 END) AS COL6,
  
  ROUND((((SUM(CASE WHEN B.CFP LIKE '%'|| D.CFP ||'%' AND R.RIND =  D.RIND THEN D.COL1 ELSE 0 END)+
   SUM(CASE WHEN B.CFP LIKE '%'|| D.CFP ||'%' AND R.RIND =  D.RIND THEN D.COL2 ELSE 0 END))/
 
  CIS2.NOZERO(SUM(CASE WHEN B.CFP LIKE '%'|| D.CFP ||'%' AND R.RIND =  D.RIND THEN D.COL3 ELSE 0 END)+
   SUM(CASE WHEN B.CFP LIKE '%'|| D.CFP ||'%' AND R.RIND =  D.RIND THEN D.COL4 ELSE 0 END)))/
  
  P.COL1)*100,1) AS COL7

FROM 
  CIS2.VW_DATA_ALL D
  CROSS JOIN
    (SELECT 1 AS CFP_ORDINE, '12+13+15+16+17+18+19+20+24+26+28' AS CFP, 'TOTAL imobilizari necorporale si corporale' AS CFP_DENUMIRE FROM DUAL UNION
     SELECT 2 AS CFP_ORDINE, '12+13' AS CFP, 'publica' AS CFP_DENUMIRE FROM DUAL UNION
     SELECT 3 AS CFP_ORDINE, '15+16+17+18+19' AS CFP, 'privata' AS CFP_DENUMIRE FROM DUAL UNION
     SELECT 4 AS CFP_ORDINE, '20' AS CFP, 'mixta (publica si privata), fara participare straina' AS CFP_DENUMIRE FROM DUAL UNION
     SELECT 5 AS CFP_ORDINE, '24+26' AS CFP, 'straina' AS CFP_DENUMIRE FROM DUAL UNION
     SELECT 6 AS CFP_ORDINE, '28' AS CFP, 'a intreprindelor mixte' AS CFP_DENUMIRE FROM DUAL) B
  CROSS JOIN (
  
  SELECT DISTINCT
  COL1 
  
FROM 
  CIS2.VW_DATA_ALL D
  
WHERE 
  D.FORM = 100 AND
  D.CUIIO = 2 AND
  D.PERIOADA IN :pPERIOADA AND
  D.CAPITOL = 330 AND
  D.RIND IN '01' ) P


CROSS JOIN (
    SELECT
      DENUMIRE,
      RIND,
      ORDINE
  
    FROM 
     CIS2.MD_RIND
  
   WHERE
     RIND NOT IN ('440','441','442','450','-') AND
     CAPITOL = 323 AND
     RIND_VERS >= 2006 AND
     STATUT = 1  ) R
     
WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  D.PERIOADA IN :pPERIOADA AND
  D.FORM = 8 AND
  D.CAPITOL = 323
  
GROUP BY
  B.CFP_DENUMIRE,
  B.CFP_ORDINE,
  R.DENUMIRE,
  R.RIND,
  R.ORDINE,
  P.COL1
  
ORDER BY
  B.CFP_ORDINE,
  R.ORDINE
  
)