

SELECT 
--  :pPERIOADA AS PERIOADA,
--  :pFORM AS FORM,
--  :pFORM_VERS AS FORM_VERS,
--  :pID_MDTABLE AS ID_MDTABLE,
--  :pCOD_CUATM AS COD_CUATM,    
--  '0' AS NR_SECTIE,
--  '0' AS NUME_SECTIE,
--  '0' AS NR_SECTIE1,
--  '0' AS NUME_SECTIE1,
--  '0' AS NR_SECTIE2,
--  '0' AS NUME_SECTIE2,
   RIND AS NR_ROW,
   ORDINE,
  '1111111111111' AS DECIMAL_POS,
   DENUMIRE AS NUME_ROW,
   COL1, COL2, COL3,COL4,COL5,COL6,COL7,COL8,COL9,COL10, COL11, COL12, COL13
   
FROM (

SELECT
  R.DENUMIRE,
  R.RIND,
  R.ORDINE,
  SUM(CASE WHEN R.RIND = D.RIND AND D.CAPITOL = 324 THEN NVAL(COL1)+NVAL(D.COL2)+NVAL(D.COL3)+NVAL(D.COL4)+NVAL(D.COL5)+NVAL(D.COL6)+NVAL(D.COL7)+NVAL(COL8)+NVAL(COL9)+NVAL(COL10) ELSE 0 END) AS COL1,
  
  SUM(CASE WHEN R.RIND = D.RIND AND D.CAPITOL = 324 THEN COL1 ELSE 0 END) AS COL2, 
   
  SUM(CASE WHEN R.RIND = D.RIND AND D.CAPITOL = 324 THEN NVAL(D.COL2)+NVAL(D.COL3)+NVAL(D.COL4)+NVAL(D.COL5)+NVAL(D.COL6)+NVAL(D.COL7)+NVAL(COL8)+NVAL(COL9)+NVAL(COL10)ELSE 0 END) AS COL3,
  
  SUM(CASE WHEN R.RIND = D.RIND AND D.CAPITOL = 324 THEN NVAL(D.COL2)+NVAL(D.COL3)+NVAL(D.COL4)+NVAL(D.COL5)+NVAL(D.COL6)+NVAL(D.COL7) ELSE 0 END) AS COL4,
    
  SUM(CASE WHEN R.RIND = D.RIND AND D.CAPITOL = 324 THEN NVAL(D.COL2) ELSE 0 END) AS COL5,
  SUM(CASE WHEN R.RIND = D.RIND AND D.CAPITOL = 324 THEN D.COL3 ELSE 0 END) AS COL6,
  SUM(CASE WHEN R.RIND = D.RIND AND D.CAPITOL = 324 THEN D.COL4 ELSE 0 END) AS COL7,
  SUM(CASE WHEN R.RIND = D.RIND AND D.CAPITOL = 324 THEN D.COL5 ELSE 0 END) AS COL8,
  SUM(CASE WHEN R.RIND = D.RIND AND D.CAPITOL = 324 THEN D.COL6 ELSE 0 END) AS COL9,
  SUM(CASE WHEN R.RIND = D.RIND AND D.CAPITOL = 324 THEN D.COL7 ELSE 0 END) AS COL10,
  SUM(CASE WHEN R.RIND = D.RIND AND D.CAPITOL = 324 THEN D.COL8 ELSE 0 END) AS COL11,
  SUM(CASE WHEN R.RIND = D.RIND AND D.CAPITOL = 324 THEN D.COL9 ELSE 0 END) AS COL12,
  SUM(CASE WHEN R.RIND = D.RIND AND D.CAPITOL = 324 THEN D.COL10 ELSE 0 END) AS COL13

FROM
  VW_DATA_ALL D
  
  
  
  
  CROSS JOIN (
  SELECT
  DENUMIRE,
  RIND,
  ORDINE
  
FROM
  MD_RIND
  
WHERE
  CAPITOL = 324 AND
  STATUT = 1 AND
  RIND_VERS >= 2006 AND
  RIND NOT IN '-'
  
ORDER BY
  ORDINE
  ) R
  
WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  D.PERIOADA IN :pPERIOADA AND
  D.FORM = 8 AND
  D.CAPITOL = 324
  
GROUP BY
  R.DENUMIRE,
  R.RIND,
  R.ORDINE

  )
  
  ORDER BY 
  ORDINE