SELECT
 D.CUIIO,   
  TO_CHAR(SUM(CASE WHEN D.CAPITOL IN (405) AND  D.RIND IN ('1') THEN CIS2.NVAL(D.COL5) ELSE 0 END))  ||'<>'|| 
  TO_CHAR(SUM(CASE WHEN D.CAPITOL IN (405) AND  D.RIND IN ('2') THEN CIS2.NVAL(D.COL5) ELSE 0 END) + 
  SUM(CASE WHEN D.CAPITOL IN (406) AND  D.RIND IN ('1') THEN CIS2.NVAL(D.COL5) ELSE 0 END)) 
              
               AS REZULTAT

FROM
  CIS2.VW_DATA_ALL D
 

WHERE
  (D.PERIOADA =:PERIOADA        OR :PERIOADA=  -1) AND
--  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL           OR :CAPITOL <> :CAPITOL) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (44)  AND
   D.CAPITOL IN (405,406)
  
 
    GROUP BY 
    D.CUIIO




    HAVING 
    
    TO_NUMBER(TO_CHAR(SUM(CASE WHEN D.CAPITOL IN (405) AND  D.RIND IN ('1') THEN CIS2.NVAL(D.COL5) ELSE 0 END)))  <> 
  
    TO_NUMBER(TO_CHAR(SUM(CASE WHEN D.CAPITOL IN (405) AND  D.RIND IN ('2') THEN CIS2.NVAL(D.COL5) ELSE 0 END) + 
        SUM(CASE WHEN D.CAPITOL IN (406) AND  D.RIND IN ('1') THEN CIS2.NVAL(D.COL5) ELSE 0 END)))