--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,
--  
--  COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13
--)

-- FINAL SELECT ===============================================================
SELECT
  DF.PERIOADA,
  DF.FORM,
  DF.FORM_VERS,
  DF.ID_MDTABLE,
  DF.COD_CUATM,
  DF.NR_SECTIE,
  DF.NUME_SECTIE,
  DF.NR_SECTIE1,
  DF.NUME_SECTIE1,
  DF.NR_SECTIE2,
  DF.NUME_SECTIE2,
  (CASE WHEN DF.NR_ROW LIKE '%-%' THEN '~' ELSE '' END)||DF.NR_ROW||'~'||ROWNUM AS NR_ROW,
  ROWNUM AS ORDINE,
  DF.DECIMAL_POS,
  (CASE WHEN DF.NR_ROW LIKE '%-%' THEN '.....' ELSE '' END)||DF.NUME_ROW AS NUME_ROW,  
  DF.COL1, DF.COL2, DF.COL3, DF.COL4, DF.COL5, DF.COL6, DF.COL7, DF.COL8, DF.COL9, DF.COL10, DF.COL11, DF.COL12, DF.COL13

FROM
(
-- ORDER SELECT ---------------------------------------------------------------
SELECT * FROM
(
-- PRIMARY SELECT .............................................................
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  C.CODUL AS NR_ROW,
  C.FULL_CODE AS ORDINE,
 '0111111111111' AS DECIMAL_POS,
  C.DENUMIRE AS NUME_ROW,
  COUNT(DISTINCT CASE WHEN D.PERIOADA = :pPERIOADA THEN D.CUIIO ELSE NULL END) AS COL1,  
  SUM(CASE WHEN D.PERIOADA = :pPERIOADA AND D.CAPITOL||'-'||D.RIND IN('11-10') THEN NVAL(D.COL1) ELSE NULL END) AS COL2,
  SUM(CASE WHEN D.PERIOADA = :pPERIOADA AND D.CAPITOL||'-'||D.RIND IN('11-10') THEN NVAL(D.COL2) ELSE NULL END) AS COL3,
  SUM(CASE WHEN D.PERIOADA = :pPERIOADA AND D.CAPITOL||'-'||D.RIND IN('11-10') THEN NVAL(D.COL3) ELSE NULL END) AS COL4,
  SUM(CASE WHEN D.PERIOADA = :pPERIOADA-12 AND D.CAPITOL||'-'||D.RIND IN('11-10') THEN NVAL(D.COL1) ELSE NULL END) AS COL5,
  SUM(CASE WHEN D.PERIOADA = :pPERIOADA-12 AND D.CAPITOL||'-'||D.RIND IN('11-10') THEN NVAL(D.COL2) ELSE NULL END) AS COL6,
  SUM(CASE WHEN D.PERIOADA = :pPERIOADA-12 AND D.CAPITOL||'-'||D.RIND IN('11-10') THEN NVAL(D.COL3) ELSE NULL END) AS COL7,  
  
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA AND D.CAPITOL||'-'||D.RIND IN('11-10') THEN NVAL(D.COL1) ELSE NULL END) AS COL8,
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA AND D.CAPITOL||'-'||D.RIND IN('11-10') THEN NVAL(D.COL2) ELSE NULL END) AS COL9,
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA AND D.CAPITOL||'-'||D.RIND IN('11-10') THEN NVAL(D.COL3) ELSE NULL END) AS COL10,
  
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 AND D.CAPITOL||'-'||D.RIND IN('11-10') THEN NVAL(D.COL1) ELSE NULL END) AS COL11, 
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 AND D.CAPITOL||'-'||D.RIND IN('11-10') THEN NVAL(D.COL2) ELSE NULL END) AS COL12,
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 AND D.CAPITOL||'-'||D.RIND IN('11-10') THEN NVAL(D.COL3) ELSE NULL END) AS COL13,
  
  SUM(CASE WHEN D.PERIOADA = :pPERIOADA AND D.CAPITOL||'-'||D.RIND IN('11-10')  THEN 1          ELSE NULL END) AS CTRL_CNT, 
  MAX(CASE WHEN D.PERIOADA = :pPERIOADA AND D.CAPITOL||'-'||D.RIND IN('11-10')  THEN NVAL(COL1) ELSE NULL END) / NOZERO(
  SUM(CASE WHEN D.PERIOADA = :pPERIOADA AND D.CAPITOL||'-'||D.RIND IN('11-10')  THEN NVAL(COL1) ELSE NULL END)) * 100 AS CTRL_SUM
FROM
  VW_CL_CAEM2 C
  LEFT  JOIN VW_CL_CAEM2 CD ON(CD.FULL_CODE LIKE '%'||C.CODUL||';%')
  LEFT  JOIN 
  (
    SELECT D.PERIOADA,
  D.ANUL,
  D.NUM,
  D.CUIIO,
  D.CUIIO_VERS,
  D.CUATM,
  D.CUATM_FULL,
  D.CFP,
  D.CFOJ,
  D.COCM,
  D.CAEM,
  CASE WHEN D.CUIIO IN (38470369) THEN 'C2599' 
       WHEN D.CUIIO IN (38946317) THEN 'C2599' 
       WHEN D.CUIIO IN (40099422) THEN 'C2599' 
       WHEN D.CUIIO IN (40614031) THEN 'C2223' 
       WHEN D.CUIIO IN (40627097) THEN 'C2599' 
       WHEN D.CUIIO IN (40797876) THEN 'C2599' 
       WHEN D.CUIIO IN (40860965) THEN 'C2599' 
       WHEN D.CUIIO IN (6817162) THEN 'C2599' 
       WHEN D.CUIIO IN (40796215) THEN 'C2599' 
       ELSE D.CAEM2 END AS CAEM2,
  D.CAEM_IND,
  D.CAEM_IND2,
  D.BUGET,
  D.TIP,
  D.PACHET,
  D.CAPITOL,
  D.CAPITOL_VERS,
  D.TAB,
  D.ID_MD,
  D.RIND,
  D.RIND_VERS,
  D.ID_USER,
  D.COL1,
  D.COL2,
  D.COL3,
  D.COL4,
  D.COL5,
  D.COL6,
  D.COL7,
  D.COL8,
  D.COL9,
  D.COL10,
  D.COL11,
  D.COL12,
  D.COL13,
  D.COL14,
  D.COL15 FROM RENIM R INNER JOIN VW_DATA_ALL D ON(D.CUIIO=R.CUIIO AND D.CUIIO_VERS=R.CUIIO_VERS), VW_MD_PERIOADA P
    WHERE P.PERIOADA IN (:pPERIOADA,:pPERIOADA-12)
      AND D.ANUL     = P.ANUL
      AND D.NUM     <= P.NUM
      AND D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'
      AND D.FORM       IN(3)
      AND D.CAPITOL    IN(11,94)
      AND D.RIND       IN('10','200')
      AND SUBSTR(D.CAEM2,1,1) IN('B','C','D','E')
      AND SUBSTR(D.CAEM2,1,3) NOT IN('E36','E37')
      AND SUBSTR(D.CAEM2,1,4) NOT IN('D352','E381','E382')
      AND R.PROD = '1'
    ORDER BY D.COL1 DESC
  ) D ON(CD.CODUL = D.CAEM2)
WHERE
  SUBSTR(C.CODUL,1,1) IN('0','B','C','D','E')
GROUP BY
  C.CODUL,
  C.FULL_CODE,
  C.DENUMIRE
--.............................................................................
) D
WHERE
  (D.CTRL_CNT > 3 OR (D.CTRL_CNT = 3 AND D.CTRL_SUM <= 85) OR D.NR_ROW LIKE '0%') AND
  (
  NVAL(D.COL1)<>0 OR 
  NVAL(D.COL2)<>0 OR 
  NVAL(D.COL3)<>0 OR 
  NVAL(D.COL4)<>0 OR
  NVAL(D.COL5)<>0 OR 
  NVAL(D.COL6)<>0 OR 
  NVAL(D.COL7)<>0 OR 
  NVAL(D.COL8)<>0 OR
  NVAL(D.COL9)<>0 OR 
  NVAL(D.COL10)<>0 OR 
  NVAL(D.COL11)<>0 OR 
  NVAL(D.COL12)<>0 OR
  NVAL(D.COL13)<>0 
  )
ORDER BY
  D.PERIOADA,
  D.FORM,
  D.FORM_VERS,
  D.ID_MDTABLE,
  D.COD_CUATM,
  D.NR_SECTIE,
  D.NR_SECTIE1,
  D.NR_SECTIE2,
  D.ORDINE,
  D.NR_ROW
-------------------------------------------------------------------------------
) DF
--=============================================================================