SELECT ----
    'Rind '||DD.RIND||' '||
  NVAL(SUM(CASE WHEN DD.PERIOADA IN :PERIOADA AND DD.NUM IN (2,3,4) THEN DD.COL1 ELSE 0 END))||' <> '||
  NVAL(SUM(CASE WHEN D.PERIOADA IN :PERIOADA-1 AND D.NUM IN (1,2,3) THEN D.COL2 ELSE 0 END)) AS REZULTAT
FROM
  CIS.VW_DATA_ALL D 
  INNER JOIN 
  ( 

SELECT 
    D.CUIIO,
    D.ID_MD,
    D.RIND,
    D.RIND_VERS
    

FROM
  CIS.VW_DATA_ALL D
  
  WHERE 
  (D.PERIOADA IN(:PERIOADA-1)) AND
  
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
   D.FORM = 1 AND
   D.CAPITOL = 1
   AND D.RIND NOT IN ('2600')
   AND (D.COL2 <> 0 OR D.COL2 IS NOT NULL) ) 
   
   
  DDD ON (DDD.CUIIO = D.CUIIO  AND DDD.ID_MD = D.ID_MD AND D.RIND = DDD.RIND AND  D.RIND_VERS  = DDD.RIND_VERS)   
   
 --  DDD ON (DDD.CUIIO = D.CUIIO  AND DDD.ID_MD = D.ID_MD)
   
   INNER JOIN USER_EREPORTING.VW_DATA_ALL_FOR_VALIDATE DD ON (D.CUIIO=DD.CUIIO AND DD.ID_SCHEMA IN (1) AND D.FORM=DD.FORM AND D.RIND=DD.RIND AND D.CAPITOL=DD.CAPITOL)
   
   WHERE 
  (D.PERIOADA IN(:PERIOADA-1)) AND
   (DD.PERIOADA IN(:PERIOADA)) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (:CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
   D.FORM = 1 AND
   D.CAPITOL = 1
   
   AND D.RIND NOT IN ('2600')
 
   
   GROUP BY 
   DD.RIND
   
   HAVING (
   (NVAL(SUM(CASE WHEN DD.PERIOADA IN :PERIOADA AND DD.NUM IN (2,3,4) THEN DD.COL1 ELSE 0 END)) <
   (NVAL(SUM(CASE WHEN D.PERIOADA IN :PERIOADA-1 AND D.NUM IN (1,2,3)  THEN D.COL2 ELSE 0 END))*0.9)
  
  OR
  
   NVAL(SUM(CASE WHEN DD.PERIOADA IN :PERIOADA AND DD.NUM IN (2,3,4) THEN DD.COL1 ELSE 0 END)) >
  (NVAL(SUM(CASE WHEN D.PERIOADA IN :PERIOADA-1 AND D.NUM IN (1,2,3) THEN D.COL2 ELSE 0 END))*1.1) ))