SELECT

  'Rind '||D.RIND||'.'||'COL4: ( ' ||   
    
  NVAL(SUM(DISTINCT CASE WHEN DD.PERIOADA=:PERIOADA  THEN DD.COL4  ELSE 0 END)) ||' <> '||
           
           SUM(DISTINCT CASE WHEN D.PERIOADA=:PERIOADA-4  THEN NVAL(D.COL2)  ELSE 0 END)  ||' ) :COL2  '  AS REZULTAT
  
FROM

  CIS.VW_DATA_ALL D
        INNER JOIN USER_EREPORTING.VW_DATA_ALL_FOR_VALIDATE DD ON (D.CUIIO=DD.CUIIO AND DD.ID_SCHEMA IN (1) AND D.FORM=DD.FORM AND D.RIND=DD.RIND AND D.CAPITOL=DD.CAPITOL)


  
  
  WHERE 
  (D.PERIOADA IN(:PERIOADA-4) AND
  DD.PERIOADA IN (:PERIOADA))AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (:CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
    
  D.FORM IN (1)  AND
  D.CAPITOL IN (9)  
  AND  DD.ID_SCHEMA IN (1)
  AND D.RIND IN ('10','20','30','70')

 

 AND DD.COL4 <> D.COL2       
  
  GROUP BY 
    D.RIND 
