CREATE USER ALL_APP_DB
  IDENTIFIED BY oracle
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

-- 2 Roles for ALL_APP_DB 
GRANT CONNECT TO ALL_APP_DB;
GRANT RESOURCE TO ALL_APP_DB;
ALTER USER ALL_APP_DB DEFAULT ROLE ALL;

-- 7 System Privileges for ALL_APP_DB 
GRANT ALTER SESSION TO ALL_APP_DB;
GRANT CREATE DATABASE LINK TO ALL_APP_DB;
GRANT CREATE SEQUENCE TO ALL_APP_DB;
GRANT CREATE SESSION TO ALL_APP_DB;
GRANT CREATE SYNONYM TO ALL_APP_DB;
GRANT CREATE VIEW TO ALL_APP_DB;
GRANT UNLIMITED TABLESPACE TO ALL_APP_DB;

-- 1 Tablespace Quota for ALL_APP_DB 
ALTER USER ALL_APP_DB QUOTA UNLIMITED ON USERS;
GRANT EXECUTE ON SYS.DBMS_STATS TO ALL_APP;