/* Formatted on 21/03/2018 15:30:51 (QP5 v5.252.13127.32867) */
CREATE OR REPLACE FORCE VIEW USER_BANCU.VW_REGISTRU
(
   IDNO,
   DATA_REG,
   DEN_COM,
   FORMA_ORG,
   ADRESA,
   LIST_COND,
   LISTA_FOND,
   GEN_ACT_NE_LIC,
   GEN_ACT_LIC,
   STATUTUL,
   DATA_CREATE,
   FACEBOOK,
   LINKEDIN,
   WEBSITE
)
AS
   SELECT TRIM (VB.IDNO) AS IDNO,
          VB.DATA_REG AS DATA_REG,
          TRIM (VB.DEN_COM) AS DEN_COM,
          TRIM (VB.FORMA_ORG) AS FORMA_ORG,
          TRIM (VB.ADRESA) AS ADRESA,
          TRIM (VB.LIST_COND) AS LIST_COND,
          TRIM (VB.LISTA_FOND) AS LISTA_FOND,
          REPLACE (TRIM (VB.GEN_ACT_NE_LIC), ' ', '') AS GEN_ACT_NE_LIC,
          REPLACE (TRIM (VB.GEN_ACT_LIC), ' ', '') AS GEN_ACT_LIC,
          TRIM (VB.STATUTUL) AS STATUTUL,
          TRIM (DATA_CREATE) AS DATA_CREATE,
          TRIM (FACEBOOK) AS FACEBOOK,
          TRIM (LINKEDIN) AS LINKEDIN,
          TRIM (WEBSITE) AS WEBSITE
     FROM USER_BANCU.REGISTRU_MD_19_03_2018 VB;


















--------------------------------------------------------------------------------
DROP TABLE USER_BANCU.REGISTRU_MD_19_02_2018 CASCADE CONSTRAINTS;

CREATE TABLE USER_BANCU.REGISTRU_MD_19_03_2018
(
  IDNO            NUMBER,
  DATA_REG        DATE,
  DEN_COM         VARCHAR2(1024 BYTE),
  FORMA_ORG       VARCHAR2(1024 BYTE),
  ADRESA          VARCHAR2(1024 BYTE),
  LIST_COND       VARCHAR2(1024 BYTE),
  LISTA_FOND      NVARCHAR2(2000),
  GEN_ACT_NE_LIC  VARCHAR2(1024 BYTE),
  GEN_ACT_LIC     VARCHAR2(1024 BYTE),
  STATUTUL        VARCHAR2(1024 BYTE),
  DATA_CREATE     DATE,
  FACEBOOK        VARCHAR2(1024 BYTE),
  LINKEDIN        VARCHAR2(1024 BYTE),
  WEBSITE         VARCHAR2(1024 BYTE)
)
TABLESPACE TBS_DTI_USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
