

CREATE TABLE USER_BANCU.CL_LICENTIAT
(
  CODUL     VARCHAR2(1024 BYTE),
  GRUPA     VARCHAR2(1024 BYTE),
  CAEM      VARCHAR2(1024 BYTE),
  SECTIA    VARCHAR2(1024 BYTE),
  DENUMIRE  VARCHAR2(1024 BYTE),
  ORDINE    NUMBER,
  MIG       VARCHAR2(1024 BYTE)
)
TABLESPACE TBS_DTI_USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


-------------------------------------------------------------------------------
;
SELECT *

            FROM USER_BANCU.VW_REGISTRU
                    