SELECT 
  L.CUIIO,
  L.CUIIO_VERS,
  L.DENUMIRE,
  L.CUATM,
  L.CFP,
  L.CAEM2  


FROM USER_BANCU.KAT_3_COMERT_2009_FIN L 

                LEFT JOIN CIS2.RENIM R ON R.CUIIO = L.CUIIO AND R.CUIIO_VERS  = L.CUIIO_VERS 
                
                WHERE 
                R.CUIIO IS   NULL 