SELECT
  SUM(CASE WHEN D.CAPITOL IN 324 AND RIND IN '0000' THEN D.COL9 ELSE 0 END) ||' <> '||
  SUM(CASE WHEN D.CAPITOL IN 323 AND RIND IN '600' THEN NVAL(D.COL1)+NVAL(D.COL2) ELSE 0 END) AS REZULTAT
  
FROM 
  VW_DATA_ALL_TEMP D
  
WHERE
  (D.PERIOADA IN (:PERIOADA)) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
   D.CAPITOL IN (323,324) AND
   D.RIND IN ('0000','600') AND
   D.FORM = :FORM AND
   D.FORM = 8
  

HAVING
  SUM(CASE WHEN D.CAPITOL IN 324 AND RIND IN '0000' THEN D.COL9 ELSE 0 END) <> 
  SUM(CASE WHEN D.CAPITOL IN 323 AND RIND IN '600' THEN NVAL(D.COL1)+NVAL(D.COL2) END)
