INSERT INTO CIS2.TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
  COL1, COL2,COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12
)


SELECT
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
    '0' AS NR_SECTIE,
    '0' AS NUME_SECTIE,
    '0' AS NR_SECTIE1,
    '0' AS NUME_SECTIE1,
    '0' AS NR_SECTIE2,
    '0' AS NUME_SECTIE2,
     RIND AS  NR_ROW,   
     ORDINE,
    '333333333333' AS DECIMAL_POS,
    DENUMIRE AS NUME_ROW, 
    COL1, 
    COL2, 
    ROUND(COL3,3) AS COL3, 
    COL4, 
    COL5, 
    ROUND(COL6,3) AS COL6,
    COL7,
    COL8, 
    ROUND(COL9,3) AS COL9, 
    COL10, 
    COL11, 
    ROUND(COL12,3) AS COL12
FROM
(

SELECT 
         RR.ORDINE AS ORDINE, 
         RR.RIND AS RIND,
         RR.DENUMIRE  DENUMIRE, 
         
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND D.CUATM_FULL LIKE '%'||'1111111'||';%' THEN D.COL1 ELSE NULL END)) AS COL1,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND D.CUATM_FULL LIKE '%'||'1111111'||';%' THEN D.COL2 ELSE NULL END)) AS COL2,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND D.CUATM_FULL LIKE '%'||'1111111'||';%' THEN D.COL2 ELSE NULL END))/
         NOZERO(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND D.CUATM_FULL LIKE '%'||'1111111'||';%' THEN D.COL1 ELSE NULL END)))*100 AS COL3,
         
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND ((D.CUATM_FULL LIKE '%'||'2222222'||';%') OR (D.CUATM_FULL LIKE '%0100000;%')) THEN D.COL1 ELSE NULL END)) AS COL4,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND ((D.CUATM_FULL LIKE '%'||'2222222'||';%') OR (D.CUATM_FULL LIKE '%0100000;%')) THEN D.COL2 ELSE NULL END)) AS COL5,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND ((D.CUATM_FULL LIKE '%'||'2222222'||';%') OR (D.CUATM_FULL LIKE '%0100000;%'))  THEN D.COL2 ELSE NULL END))/
         NOZERO(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND ((D.CUATM_FULL LIKE '%'||'2222222'||';%') OR (D.CUATM_FULL LIKE '%0100000;%')) THEN D.COL1 ELSE NULL END)))*100 AS COL6,
                  
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND ((D.CUATM_FULL LIKE '%'||'3333333'||';%') OR (D.CUATM_FULL LIKE '%'||'9600000'||';%')) THEN D.COL1 ELSE NULL END)) AS COL7,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND ((D.CUATM_FULL LIKE '%'||'3333333'||';%') OR (D.CUATM_FULL LIKE '%'||'9600000'||';%')) THEN D.COL2 ELSE NULL END)) AS COL8,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND ((D.CUATM_FULL LIKE '%'||'3333333'||';%') OR (D.CUATM_FULL LIKE '%'||'9600000'||';%')) THEN D.COL2 ELSE NULL END))/
         NOZERO(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND) AND ((D.CUATM_FULL LIKE '%'||'3333333'||';%') OR (D.CUATM_FULL LIKE '%'||'9600000'||';%')) THEN D.COL1 ELSE NULL END)))*100 AS COL9,         
                  
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' THEN D.COL1 ELSE NULL END)) AS COL10,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' THEN D.COL2 ELSE NULL END)) AS COL11,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' THEN D.COL2 ELSE NULL END))/
         NOZERO(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND) AND D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' THEN D.COL1 ELSE NULL END)))*100 AS COL12
         
  FROM
  
  CIS2.VW_DATA_ALL_GC   D
 
  CROSS JOIN ( SELECT  RIND, DENUMIRE,ORDINE 
               FROM    CIS2.MD_RIND       
               WHERE   FORM= 61 AND CAPITOL = 1112 AND RIND BETWEEN ('010') AND ('030')  ORDER BY ORDINE) RR
                 
    
WHERE
  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (61) AND D.CAPITOL IN ('1112') -- AND NR_GOSP=285600
  
  GROUP BY 
  RR.ORDINE, 
  RR.RIND,
  RR.DENUMIRE 

 
 
 UNION
 
 
 SELECT 
         RR.ORDINE AS ORDINE, 
         RR.RIND AS RIND,
         RR.DENUMIRE  DENUMIRE, 
         
         --CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND D.CUATM_FULL LIKE '%'||'1111111'||';%' THEN D.COL1 ELSE NULL END)) AS COL1,
         NULL AS COL1,
         
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND D.CUATM_FULL LIKE '%'||'1111111'||';%' THEN D.COL2 ELSE NULL END)) AS COL2,
         
         
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND D.CUATM_FULL LIKE '%'||'1111111'||';%' THEN D.COL2 ELSE NULL END))/
         NOZERO(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1111') AND D.RIND IN ('040')  AND D.CUATM_FULL LIKE '%'||'1111111'||';%' THEN D.COL1 ELSE NULL END)))*100 AS COL3,
         
         
         
         --CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND ((D.CUATM_FULL LIKE '%'||'2222222'||';%') OR (D.CUATM_FULL LIKE '%0100000;%')) THEN D.COL1 ELSE NULL END)) AS COL4,
         NULL AS COL4,
         
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND ((D.CUATM_FULL LIKE '%'||'2222222'||';%') OR (D.CUATM_FULL LIKE '%0100000;%')) THEN D.COL2 ELSE NULL END)) AS COL5,
         
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND ((D.CUATM_FULL LIKE '%'||'2222222'||';%') OR (D.CUATM_FULL LIKE '%0100000;%')) THEN D.COL2 ELSE NULL END))/
         NOZERO(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1111') AND D.RIND IN ('040')  AND ((D.CUATM_FULL LIKE '%'||'2222222'||';%') OR (D.CUATM_FULL LIKE '%0100000;%')) THEN D.COL1 ELSE NULL END)))*100 AS COL6,
         
         
                  
         --CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND ((D.CUATM_FULL LIKE '%'||'3333333'||';%') OR (D.CUATM_FULL LIKE '%'||9600000||';%')) THEN D.COL1 ELSE NULL END)) AS COL7,
         NULL AS COL4,
         
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND ((D.CUATM_FULL LIKE '%'||'3333333'||';%') OR (D.CUATM_FULL LIKE '%'||9600000||';%')) THEN D.COL2 ELSE NULL END)) AS COL8,
         
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND ((D.CUATM_FULL LIKE '%'||'3333333'||';%') OR (D.CUATM_FULL LIKE '%'||9600000||';%')) THEN D.COL2 ELSE NULL END))/
         NOZERO(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1111') AND D.RIND IN ('040') AND ((D.CUATM_FULL LIKE '%'||'3333333'||';%') OR (D.CUATM_FULL LIKE '%'||9600000||';%')) THEN D.COL1 ELSE NULL END)))*100 AS COL9,
         
                  
                  
        -- CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' THEN D.COL1 ELSE NULL END)) AS COL10,
         NULL AS COL10,
         
         
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' THEN D.COL2 ELSE NULL END)) AS COL11,
         
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1112') AND D.RIND IN (RR.RIND)  AND D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' THEN D.COL2 ELSE NULL END))/
         NOZERO(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1111') AND D.RIND IN ('040') AND D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' THEN D.COL1 ELSE NULL END)))*100 AS COL12
         
         
         
  FROM
  
  CIS2.VW_DATA_ALL_GC   D
 
  CROSS JOIN ( SELECT  RIND, DENUMIRE,ORDINE 
               FROM    CIS2.MD_RIND       
               WHERE   FORM= 61 AND CAPITOL = 1112 AND RIND IN ('040')  ORDER BY ORDINE) RR
                 
    
WHERE
  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (61) AND D.CAPITOL IN ('1112','1111') -- AND NR_GOSP=285600
  
  GROUP BY 
  RR.ORDINE, 
  RR.RIND,
  RR.DENUMIRE )
 --ORDER BY RR.ORDINE)
  
 