SELECT

  CIS2.NVAL(SUM(CASE WHEN D.FORM IN (57) AND  D.CAPITOL IN (1090) AND D.RIND IN ('410') AND D.PERIOADA IN (:PERIOADA)   THEN  NVAL(D.COL1) ELSE NULL END)) ||' <> '||
  CIS2.NVAL(SUM(CASE WHEN D.FORM IN (63) AND  D.CAPITOL IN (1120) AND D.RIND IN ('090') AND D.PERIOADA IN (:PERIOADA-1)  THEN  NVAL(D.COL2) ELSE NULL END))
  
 
  AS REZULTAT
  
  
  --Anexa1  Rd.410 col.4 RSF1 anul curent = Anexa1 Rd.090 col.5 RSFprescurtat anul precedent
  
FROM VW_DATA_ALL_FR D


WHERE
  (D.PERIOADA IN (:PERIOADA,:PERIOADA-1 ))   AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND 
  (:CUIIO_VERS=:CUIIO_VERS     OR  :CUIIO_VERS <> :CUIIO_VERS) AND
  (:FORM = :FORM                OR :FORM <>  :FORM ) AND  
  (:FORM_VERS=:FORM_VERS        OR  :FORM_VERS  <> :FORM_VERS) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <> :CAPITOL ) AND
  (:CAPITOL_VERS=:CAPITOL_VERS  OR :CAPITOL_VERS <>  :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (57,63)  
  

HAVING
 CIS2.NVAL(SUM(CASE WHEN D.FORM IN (57) AND  D.CAPITOL IN (1090) AND D.RIND IN ('410') AND D.PERIOADA IN (:PERIOADA)   THEN  NVAL(D.COL1) ELSE NULL END))  <>
  CIS2.NVAL(SUM(CASE WHEN D.FORM IN (63) AND  D.CAPITOL IN (1120) AND D.RIND IN ('090') AND D.PERIOADA IN (:PERIOADA-1)  THEN  NVAL(D.COL2) ELSE NULL END))



AND
  (
  
  
 SELECT
  DISTINCT
  D.CUIIO
FROM
  CIS2.VW_DATA_ALL_FR D
WHERE
  (D.PERIOADA IN (:PERIOADA-1)) AND
  (D.CUIIO=:CUIIO OR :CUIIO = -1) AND
   D.FORM  IN(63)
 
   
   
   
   ) IS NOT NULL

