SELECT

  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1090) AND D.PERIOADA IN (:PERIOADA)   AND D.RIND IN ('560') THEN  NVAL(D.COL1) ELSE NULL END)) ||'<>'||
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1090) AND D.PERIOADA IN (:PERIOADA-1) AND D.RIND IN ('550','560','570','580') THEN  NVAL(D.COL2) ELSE NULL END))   
  AS REZULTAT
  
FROM VW_DATA_ALL_FR D


--Anexa1 rd.60 col.4 anul curent= Anexa1 rd. 20 col.5 anul precedent

WHERE
  (D.PERIOADA IN (:PERIOADA,:PERIOADA-1 ))   AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND 
  (D.CUIIO_VERS=:CUIIO_VERS     OR  D.CUIIO_VERS <>  :CUIIO_VERS) AND
  (D.FORM = :FORM               OR :FORM = -1) AND  
  (D.FORM_VERS=:FORM_VERS       OR  D.FORM_VERS <>  :FORM_VERS) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (57)  AND
  D.CAPITOL IN (1090)   

  
HAVING
 
 
   CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1090) AND D.PERIOADA IN (:PERIOADA)   AND D.RIND IN ('560') THEN  NVAL(D.COL1) ELSE NULL END))  <>
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1090) AND D.PERIOADA IN (:PERIOADA-1) AND D.RIND IN ('550','560','570','580') THEN  NVAL(D.COL2) ELSE NULL END))  
   

AND
  (
 SELECT
  DISTINCT
  D.CUIIO
FROM
  CIS2.VW_DATA_ALL_FR D
WHERE
  (D.PERIOADA IN (:PERIOADA-1)) AND
  (D.CUIIO=:CUIIO OR :CUIIO = -1) AND
   D.FORM  IN(57)) IS NOT NULL