SELECT
'Ati introdus Anul : '||
(EXTRACT(YEAR FROM SYSDATE)) AS DATA_CURENTA,
 (MAX(CASE WHEN D.RIND IN ('2') AND CAPITOL IN (1091) THEN SUBSTR(D.COL1, -4,4) ELSE NULL END))

 AS REZULTAT,
 
 (EXTRACT(YEAR FROM SYSDATE))-1 AS DATA_CURENTA
 
    FROM
  CIS2.VW_DATA_ALL_FR D  
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (57)  AND
  D.RIND IN ('2') AND CAPITOL IN (1091)

--HAVING
-- (EXTRACT(YEAR FROM SYSDATE))-1<>
-- (MAX(CASE WHEN D.RIND IN ('2') AND CAPITOL IN (1091) THEN SUBSTR(D.COL1, -4,4) ELSE NULL END))