SELECT 
  D.CUIIO, 
  R.DENUMIRE,
  R.CUATM,
  ROUND(SUM(CASE WHEN D.PERIOADA IN (309) AND  RD.RIND = 4 THEN  D.COL1 ELSE NULL END ),1) AS COL1_2019,
  ROUND(SUM (CASE WHEN D.PERIOADA IN (310) AND  RD.RIND = 4 THEN  D.COL1 ELSE NULL END ),1) AS COL2_2020
 
FROM
  MD_RIND RD
  INNER JOIN VW_DATA_ALL D ON (D.ID_MD=RD.ID_MD)
  INNER JOIN RENIM R ON (R.CUIIO= D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
WHERE
  (D.PERIOADA IN (310,309)) AND
 
  RD.FORM IN (39) AND
  RD.FORM_VERS = :pFORM_VERS AND    
  RD.CAPITOL IN (3) 


GROUP BY 
 D.CUIIO, 
 R.DENUMIRE,
 R.CUATM