

SELECT  DISTINCT
-- :pPERIOADA,
-- :pID_MDTABLE,
-- :pCOD_CUATM,
-- '0' AS NR_SECTIE,
-- '0' AS NUME_SECTIE,
-- '0' AS NR_SECTIE1,
-- '0' AS NUME_SECTIE1,
-- '0' AS NR_SECTIE2,
-- '0' AS NUME_SECTIE2, 
  RD.RIND AS NR_ROW,
  RD.DENUMIRE AS NUME_ROW,
  RD.ORDINE AS ORDINE,
  --'1111111111111' AS DECIMAL_POS,
  
  ROUND(SUM(D.COL1),1) AS COL1,
  ROUND(SUM(D.COL2),1) AS COL2,
  ROUND(SUM(D.COL3),1) AS COL3,
  ROUND(SUM(D.COL4),1) AS COL4,
  ROUND(SUM(D.COL5),1) AS COL5,
  ROUND(SUM(D.COL6),1) AS COL6,
  ROUND(SUM(D.COL7),1) AS COL7,
  ROUND(SUM(D.COL8),1) AS COL8,
  ROUND(SUM(D.COL9),1) AS COL9,
  ROUND(SUM(D.COL10),1) AS COL10,
  ROUND(SUM(D.COL11),1) AS COL11,
  ROUND(SUM(D.COL12),1) AS COL12,
  ROUND(SUM(D.COL13),1) AS COL13,
  ROUND(SUM(D.COL14),1) AS COL14,
  ROUND(SUM(D.COL15),1) AS COL15,
  ROUND(SUM(D.COL16),1) AS COL16,
  ROUND(SUM(D.COL17),1) AS COL17,
  ROUND(SUM(D.COL18),1) AS COL18,
  ROUND(SUM(D.COL19),1) AS COL19,
  ROUND(SUM(D.COL20),1) AS COL20,
  ROUND(SUM(D.COL21),1) AS COL21,
  ROUND(SUM(D.COL22),1) AS COL22
FROM
  MD_RIND RD
  INNER JOIN VW_DATA_ALL D ON (D.ID_MD=RD.ID_MD)
  INNER JOIN RENIM R ON (R.CUIIO= D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
  
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (:pFORM=:pFORM) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  RD.FORM IN (39) AND
  RD.FORM_VERS = :pFORM_VERS AND    
  RD.CAPITOL IN (6,7) 
 -- AND D.CUIIO NOT IN (7032055,5696207,5689503) 
GROUP BY
  RD.ORDINE,
  RD.RIND,
  RD.DENUMIRE
ORDER BY
RD.RIND