SELECT 
COUNT (DISTINCT D.CUIIO) AS CNT_2016  
FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM RE ON (D.CUIIO=RE.CUIIO AND D.CUIIO_VERS=RE.CUIIO_VERS)
  
  
  WHERE
  D.PERIOADA IN (2005) AND  --2016,2017,2018,2019.
  D.FORM_VERS = 2000     AND    
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (27)                 AND 
  D.CAPITOL IN (371)          
  AND D.RIND IN ('55')
  AND NVAL(D.COL2) > 0 






