SELECT
  CI.ITEM_CODE,
  CI.NAME,
  CI.A01,
  SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA) AND  D.CAPITOL IN (407) AND D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END) AS COL1,
  (SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) AND D.CAPITOL IN (407) AND D.RIND NOT IN ('1','2','-') THEN NVAL(D.COL4) ELSE 0 END ) +
   SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) AND D.CAPITOL IN (408) AND D.RIND NOT IN ('1','-') THEN  NVAL(D.COL4) ELSE 0 END ))AS COL2
FROM
  CIS2.VW_DATA_ALL D 
  INNER JOIN  VW_CLS_CLASS_ITEM CI  ON (CI.CLASS_CODE IN ('CSPM2') AND (CASE WHEN D.PERIOADA IN (:pPERIOADA-1) THEN TRIM(D.COL1) ELSE TRIM(D.COL31) END) = 
                                                                       (CASE WHEN D.PERIOADA IN (:pPERIOADA-1) THEN TRIM(CI.A01) ELSE TRIM(CI.ITEM_CODE) END))
WHERE 
  (D.PERIOADA IN(:pPERIOADA, :pPERIOADA-1)) AND    
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (44)
  AND  D.CAPITOL IN (407,408) 
  AND D.CUIIO IN  (20282377,37474715)
GROUP BY
  CI.ITEM_CODE,
  CI.NAME,
  CI.A01
HAVING
  NVAL(SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA) AND  D.CAPITOL IN (407) AND D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END)) - 
  NVAL(SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) AND D.CAPITOL IN (407) AND D.RIND NOT IN ('1','2','-') THEN NVAL(D.COL4) ELSE 0 END ) +
       SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) AND D.CAPITOL IN (408) AND D.RIND NOT IN ('1','-') THEN  NVAL(D.COL4) ELSE 0 END )) > 500000 OR
  NVAL(SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) AND D.CAPITOL IN (407) AND D.RIND NOT IN ('1','2','-') THEN NVAL(D.COL4) ELSE 0 END ) +
       SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) AND D.CAPITOL IN (408) AND D.RIND NOT IN ('1','-') THEN  NVAL(D.COL4) ELSE 0 END )) - 
  NVAL(SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA) AND  D.CAPITOL IN (407) AND D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END)) > 500000
  AND SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA) AND  D.CAPITOL IN (407) AND D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END) > 0
--ORDER BY
--  CI.A01,
--  CI.ITEM_CODE
UNION
SELECT DISTINCT
  MAX(ITEM_CODE),
  MAX(NAME),
  A01,
  SUM(COL1),
  COL2
FROM
(SELECT
  CI.ITEM_CODE,
  CI.NAME,
  CI.A01,
  SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA) AND  D.CAPITOL IN (407) AND D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END) AS COL1,
  (SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) AND D.CAPITOL IN (407) AND D.RIND NOT IN ('1','2','-') THEN NVAL(D.COL4) ELSE 0 END ) +
   SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) AND D.CAPITOL IN (408) AND D.RIND NOT IN ('1','-') THEN  NVAL(D.COL4) ELSE 0 END ))AS COL2
FROM
  CIS2.VW_DATA_ALL D 
  INNER JOIN  VW_CLS_CLASS_ITEM CI  ON (CI.CLASS_CODE IN ('CSPM2') AND (CASE WHEN D.PERIOADA IN (:pPERIOADA-1) THEN TRIM(D.COL1) ELSE TRIM(D.COL31) END) = 
                                                                       (CASE WHEN D.PERIOADA IN (:pPERIOADA-1) THEN TRIM(CI.A01) ELSE TRIM(CI.ITEM_CODE) END))
WHERE 
  (D.PERIOADA IN(:pPERIOADA, :pPERIOADA-1)) AND    
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (44)
  AND  D.CAPITOL IN (407,408) 
  AND D.CUIIO IN  (20282377,37474715)
GROUP BY
  CI.ITEM_CODE,
  CI.NAME,
  CI.A01
HAVING
  NVAL(SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA) AND  D.CAPITOL IN (407) AND D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END)) - 
  NVAL(SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) AND D.CAPITOL IN (407) AND D.RIND NOT IN ('1','2','-') THEN NVAL(D.COL4) ELSE 0 END ) +
       SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) AND D.CAPITOL IN (408) AND D.RIND NOT IN ('1','-') THEN  NVAL(D.COL4) ELSE 0 END )) > 500000 OR
  NVAL(SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) AND D.CAPITOL IN (407) AND D.RIND NOT IN ('1','2','-') THEN NVAL(D.COL4) ELSE 0 END ) +
       SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) AND D.CAPITOL IN (408) AND D.RIND NOT IN ('1','-') THEN  NVAL(D.COL4) ELSE 0 END )) - 
  NVAL(SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA) AND  D.CAPITOL IN (407) AND D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END)) > 500000
--  AND SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA) AND  D.CAPITOL IN (407) AND D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END) > 0
ORDER BY
  CI.A01,
  CI.ITEM_CODE
)
GROUP BY
  A01,
  COL2
HAVING
  SUM(COL1) = 0