SELECT 

D.CUIIO,
--D.RIND,
D.COL1,
SUM(D.COL4) AS COL2 


FROM
  CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.VW_MD_PERIOADA P ON (D.PERIOADA=P.PERIOADA)   
WHERE
  (D.CUIIO=:CUIIO                ) AND
  (:CUIIO_VERS<>:CUIIO_VERS      OR :CUIIO_VERS=:CUIIO_VERS) AND
  (:FORM <> :FORM                OR :FORM =:FORM) AND
  (:FORM_VERS<>:FORM_VERS        OR :FORM_VERS=:FORM_VERS) AND
  (:CAPITOL <> :CAPITOL          OR :CAPITOL=:CAPITOL) AND
  (:CAPITOL_VERS<>:CAPITOL_VERS OR :CAPITOL_VERS=:CAPITOL_VERS) AND
  (:ID_MD=:ID_MD               OR :ID_MD = -1) AND
 
  P.PERIOADA_ANULA = :PERIOADA AND
  D.FORM = 13
  AND D.CAPITOL = 337

  AND D.NUM = 3
 
  GROUP BY
  D.CUIIO, 
 -- D.RIND,
  D.COL1 
HAVING 
NVAL(D.COL1) + NVAL(SUM(D.COL2)) +  NVAL(SUM(D.COL3)) +  NVAL(SUM(D.COL4))    > 0
AND D.COL1 IS NOT NULL   