SELECT
DISTINCT 
 'Rind.'||SUBSTR(L.RIND, 1, 3)||', Tara. '|| (CASE WHEN L.COL1 IS NULL THEN R.COL1  ELSE L.COL1 END) 
||':  '|| SUM(NVAL(L.COL2)) ||' < '||SUM(NVAL(R.COL2))    AS REZULTAT
FROM 
(
SELECT 
D.CUIIO,
SUBSTR(D.RIND, 1, 3) RIND,
D.COL1,
SUM(D.COL3) AS COL2 
FROM
--38262033
     CIS2.VW_DATA_ALL D 
      
WHERE

  (D.PERIOADA        =:PERIOADA          OR :PERIOADA = -1) AND
  (D.CUIIO           =:CUIIO             OR :CUIIO = -1) AND
  (D.CUIIO_VERS      = :CUIIO_VERS       OR :CUIIO_VERS = -1)  AND 
  (D.FORM            = :FORM             OR :FORM = -1)        AND 
  (D.FORM_VERS       = :FORM_VERS        OR :FORM_VERS = -1)   AND 
  (D.CAPITOL         = :CAPITOL          OR :CAPITOL = -1  )   AND 
  (D.CAPITOL_VERS    = :CAPITOL_VERS     OR :CAPITOL_VERS = -1  ) 
  AND D.FORM = 67 
  AND D.CAPITOL IN (1140)

  GROUP BY
  D.CUIIO, 
  D.RIND,
  D.COL1 
HAVING 
NVAL(D.COL1) + NVAL(SUM(D.COL2)) + NVAL(SUM(D.COL3)) > 0 
AND D.COL1 IS NOT NULL  
 
 
 
  ) L LEFT JOIN (


SELECT 

D.CUIIO,
SUBSTR(D.RIND, 1, 3) RIND,
D.COL1,
SUM(D.COL3) AS COL2 


FROM
  CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.VW_MD_PERIOADA P ON (D.PERIOADA=P.PERIOADA)   
WHERE
  (D.CUIIO=:CUIIO                OR :CUIIO = -1) AND
  (:CUIIO_VERS<>:CUIIO_VERS      OR :CUIIO_VERS=:CUIIO_VERS) AND
  (:FORM <> :FORM                OR :FORM =:FORM) AND
  (:FORM_VERS<>:FORM_VERS        OR :FORM_VERS=:FORM_VERS) AND
  (:CAPITOL <> :CAPITOL          OR :CAPITOL=:CAPITOL) AND
  (:CAPITOL_VERS<>:CAPITOL_VERS OR :CAPITOL_VERS=:CAPITOL_VERS) AND
  (:ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  P.PERIOADA_ANULA = :PERIOADA AND
  D.FORM = 13
  AND D.CAPITOL = 1020

  AND D.NUM = 3
 
  GROUP BY
  D.CUIIO, 
  D.RIND,
  D.COL1 
HAVING 
NVAL(D.COL1) + NVAL(SUM(D.COL2)) + NVAL(SUM(D.COL3)) > 0
AND D.COL1 IS NOT NULL  
  
  
  ) R ON (R.CUIIO = L.CUIIO  AND  L.RIND = R.RIND  AND L.COL1 = R.COL1)    
   
  
  WHERE 
  1=1
  --AND R.CUIIO IS NOT NULL
  
 --  AND R.RIND IS  NULL
 
-- AND R.COL1 IS    NULL
  
  GROUP BY
  L.RIND, 
  R.RIND,
  L.COL1,
  R.COL1

  
  HAVING 
  NVAL(SUM(NVAL(L.COL2)))  <  NVAL(SUM(NVAL(R.COL2)))
  
  
 
  UNION 
  
  SELECT
DISTINCT 
 'Rind.'||SUBSTR(R.RIND, 1, 3)||', Tara. '|| (CASE WHEN L.COL1 IS NULL THEN R.COL1  ELSE L.COL1 END) 
||':  '|| SUM(NVAL(L.COL2)) ||' < '||SUM(NVAL(R.COL2))    AS REZULTAT
FROM 
(
SELECT 
D.CUIIO,
SUBSTR(D.RIND, 1, 3) RIND,
D.COL1,
SUM(D.COL3) AS COL2 
FROM
--38262033
     CIS2.VW_DATA_ALL D 
      
WHERE

  (D.PERIOADA        =:PERIOADA          OR :PERIOADA = -1) AND
  (D.CUIIO           =:CUIIO             OR :CUIIO = -1) AND
  (D.CUIIO_VERS      = :CUIIO_VERS       OR :CUIIO_VERS = -1)  AND 
  (D.FORM            = :FORM             OR :FORM = -1)        AND 
  (D.FORM_VERS       = :FORM_VERS        OR :FORM_VERS = -1)   AND 
  (D.CAPITOL         = :CAPITOL          OR :CAPITOL = -1  )   AND 
  (D.CAPITOL_VERS    = :CAPITOL_VERS     OR :CAPITOL_VERS = -1  ) 
  AND D.FORM = 67 
  AND D.CAPITOL IN (1140)

  GROUP BY
  D.CUIIO, 
  D.RIND,
  D.COL1 
HAVING 
NVAL(D.COL1) + NVAL(SUM(D.COL2)) + NVAL(SUM(D.COL3)) > 0 
AND D.COL1 IS NOT NULL  
 
 
 
 
  ) L RIGHT  JOIN (


SELECT 

D.CUIIO,
SUBSTR(D.RIND, 1, 3) RIND,
D.COL1,
SUM(D.COL3) AS COL2 


FROM
  CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.VW_MD_PERIOADA P ON (D.PERIOADA=P.PERIOADA)   
WHERE
  (D.CUIIO=:CUIIO                OR :CUIIO = -1) AND
  (:CUIIO_VERS<>:CUIIO_VERS      OR :CUIIO_VERS=:CUIIO_VERS) AND
  (:FORM <> :FORM                OR :FORM =:FORM) AND
  (:FORM_VERS<>:FORM_VERS        OR :FORM_VERS=:FORM_VERS) AND
  (:CAPITOL <> :CAPITOL          OR :CAPITOL=:CAPITOL) AND
  (:CAPITOL_VERS<>:CAPITOL_VERS OR :CAPITOL_VERS=:CAPITOL_VERS) AND
  (:ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  P.PERIOADA_ANULA = :PERIOADA AND
  D.FORM = 13
  AND D.CAPITOL = 1

  AND D.NUM = 3
 
  GROUP BY
  D.CUIIO, 
  D.RIND,
  D.COL1 
HAVING 
NVAL(D.COL1) + NVAL(SUM(D.COL2)) + NVAL(SUM(D.COL3)) > 0
AND D.COL1 IS NOT NULL  
  
  
  ) R ON (R.CUIIO = L.CUIIO  AND  L.RIND = R.RIND  AND L.COL1 = R.COL1)    
   
  
  WHERE 
  1=1
  -- AND L.CUIIO IS NOT NULL
  GROUP BY
  L.RIND,
  R.RIND,
  L.COL1,
  R.COL1

  
  HAVING 
  NVAL(SUM(NVAL(L.COL2)))  <   NVAL(SUM(NVAL(R.COL2)))
  
  
 
  
  
  
  
  
  
  