CREATE TABLE USER_BANCU.CLASSIFICATOR
(
  CODUL       VARCHAR2(1024 BYTE),
  DENUMIRE    VARCHAR2(1024 BYTE)

)
TABLESPACE TBS_DTI_USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;