CREATE TABLE CL_SERVICII_NEW
(
  CODUL     VARCHAR2(255 BYTE),
  GRUPA     VARCHAR2(255 BYTE),
  DENUMIRE  VARCHAR2(255 BYTE),
  ORDINE    NUMBER
)
TABLESPACE TBS_DTI_USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;