SELECT
  ' cap.II Col 2(rind10…..rind115) '||
  
   SUM(CASE WHEN D.CAPITOL IN (1076)  THEN NVAL(D.COL2) ELSE 0 END)  
  
  
  ||' <> ' ||' cap.I(col.1(rind10…rind115) +col.7(rind10…rind115)) - '||SUM(CASE WHEN D.CAPITOL IN (1075)  THEN NVAL(D.COL1) + NVAL(D.COL7) ELSE 0 END) 
  AS REZULTAT

FROM
  VW_DATA_ALL D

WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS) AND
  (:ID_MD=:ID_MD) AND 
  D.FORM IN (54) AND 
  
  D.CAPITOL IN (1076,1075)
  

  HAVING
  
  SUM(CASE WHEN D.CAPITOL IN (1076)  THEN NVAL(D.COL2) ELSE 0 END)  <> SUM(CASE WHEN D.CAPITOL IN (1075)  THEN NVAL(D.COL1) + NVAL(D.COL7) ELSE 0 END) 
  

