SELECT
  ' Col1 AC -  '||SUM(CASE WHEN D.PERIOADA IN (:PERIOADA) THEN  NVAL(D.COL1) ELSE 0 END)||' <> ' ||' Col9 AP - '||SUM(CASE WHEN D.PERIOADA IN (:PERIOADA-1) THEN  NVAL(D.COL9) ELSE 0 END)
  AS REZULTAT

FROM
  VW_DATA_ALL D

WHERE
  (D.PERIOADA IN (:PERIOADA,:PERIOADA-1)       OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS) AND
  (:ID_MD=:ID_MD) AND 
  D.FORM IN (54) AND 
  
  D.CAPITOL IN (1076)
  

  
  HAVING 
  
  SUM(CASE WHEN D.PERIOADA IN (:PERIOADA) THEN  NVAL(D.COL1) ELSE 0 END)   <> 
  SUM(CASE WHEN D.PERIOADA IN (:PERIOADA-1) THEN  NVAL(D.COL9) ELSE 0 END)
  
