SELECT
  D.CUIIO AS KEYID,
  'F3' AS SECTOR,
  D.RIND AS NSTR,
  D.COL1 AS GR4,
  D.COL2 AS GR5,
  D.COL3 AS GR6,
  D.COL4 AS GR7,
  NULL AS XFILES,
  D.ANUL
  
FROM
  VW_DATA_ALL_FR D
WHERE
  D.PERIOADA IN (2007) AND
  D.FORM IN (57) AND
  D.CAPITOL IN (1093)
ORDER BY
  D.CUIIO,
  D.RIND