SELECT
  D.CUIIO AS KEYID,
  'F9100' AS SECTOR,
  SUBSTR(D.RIND,0,3) AS NSTR,
  D.COL1 AS TARA,
  D.COL2 AS GR1,
  D.COL3 AS GR2,
  D.COL4 AS GR3,
  D.COL5 AS GR4,
  D.COL6 AS GR5,
  D.COL6 AS GR6,
  D.COL6 AS GR7,
  D.COL6 AS GR8,
  NULL AS XFILES,
  D.ANUL
  
FROM
  VW_DATA_ALL_FR D
WHERE
  D.PERIOADA IN (2007) AND
  D.FORM IN (57) AND
  D.CAPITOL IN (1096)
--ORDER BY
--  D.CUIIO,
--  D.RIND
UNION ALL
SELECT
  D.CUIIO AS KEYID,
  'F9200' AS SECTOR,
  SUBSTR(D.RIND,0,3) AS NSTR,
  D.COL1 AS TARA,
  D.COL2 AS GR1,
  D.COL3 AS GR2,
  D.COL4 AS GR3,
  D.COL5 AS GR4,
  D.COL6 AS GR5,
  D.COL6 AS GR6,
  D.COL6 AS GR7,
  D.COL6 AS GR8,
  NULL AS XFILES,
  D.ANUL
  
FROM
  VW_DATA_ALL_FR D
WHERE
  D.PERIOADA IN (2007) AND
  D.FORM IN (57) AND
  D.CAPITOL IN (1097)
UNION ALL
SELECT
  D.CUIIO AS KEYID,
  'F9300' AS SECTOR,
  SUBSTR(D.RIND,0,3) AS NSTR,
  D.COL1 AS TARA,
  D.COL2 AS GR1,
  D.COL3 AS GR2,
  D.COL4 AS GR3,
  D.COL5 AS GR4,
  D.COL6 AS GR5,
  D.COL6 AS GR6,
  D.COL6 AS GR7,
  D.COL6 AS GR8,
  NULL AS XFILES,
  D.ANUL
  
FROM
  VW_DATA_ALL_FR D
WHERE
  D.PERIOADA IN (2007) AND
  D.FORM IN (57) AND
  D.CAPITOL IN (1098)
UNION ALL
SELECT
  D.CUIIO AS KEYID,
  'F9400' AS SECTOR,
  SUBSTR(D.RIND,0,3) AS NSTR,
  D.COL1 AS TARA,
  D.COL2 AS GR1,
  D.COL3 AS GR2,
  D.COL4 AS GR3,
  D.COL5 AS GR4,
  D.COL6 AS GR5,
  D.COL6 AS GR6,
  D.COL6 AS GR7,
  D.COL6 AS GR8,
  NULL AS XFILES,
  D.ANUL
  
FROM
  VW_DATA_ALL_FR D
WHERE
  D.PERIOADA IN (2007) AND
  D.FORM IN (57) AND
  D.CAPITOL IN (1099)
UNION ALL
SELECT
  D.CUIIO AS KEYID,
  'F9500' AS SECTOR,
  SUBSTR(D.RIND,0,3) AS NSTR,
  D.COL1 AS TARA,
  D.COL2 AS GR1,
  D.COL3 AS GR2,
  D.COL4 AS GR3,
  D.COL5 AS GR4,
  D.COL6 AS GR5,
  D.COL6 AS GR6,
  D.COL6 AS GR7,
  D.COL6 AS GR8,
  NULL AS XFILES,
  D.ANUL
  
FROM
  VW_DATA_ALL_FR D
WHERE
  D.PERIOADA IN (2007) AND
  D.FORM IN (57) AND
  D.CAPITOL IN (1100)
UNION ALL
SELECT
  D.CUIIO AS KEYID,
  'F9600' AS SECTOR,
  SUBSTR(D.RIND,0,3) AS NSTR,
  D.COL1 AS TARA,
  D.COL2 AS GR1,
  D.COL3 AS GR2,
  D.COL4 AS GR3,
  D.COL5 AS GR4,
  D.COL6 AS GR5,
  D.COL6 AS GR6,
  D.COL6 AS GR7,
  D.COL6 AS GR8,
  NULL AS XFILES,
  D.ANUL
  
FROM
  VW_DATA_ALL_FR D
WHERE
  D.PERIOADA IN (2007) AND
  D.FORM IN (57) AND
  D.CAPITOL IN (1101)
UNION ALL
SELECT
  D.CUIIO AS KEYID,
  'F9700' AS SECTOR,
  SUBSTR(D.RIND,0,3) AS NSTR,
  D.COL1 AS TARA,
  D.COL2 AS GR1,
  D.COL3 AS GR2,
  D.COL4 AS GR3,
  D.COL5 AS GR4,
  D.COL6 AS GR5,
  D.COL6 AS GR6,
  D.COL6 AS GR7,
  D.COL6 AS GR8,
  NULL AS XFILES,
  D.ANUL
  
FROM
  VW_DATA_ALL_FR D
WHERE
  D.PERIOADA IN (2007) AND
  D.FORM IN (57) AND
  D.CAPITOL IN (1102)