SELECT  
 CIS2.NVAL(SUM(CASE WHEN D.FORM IN (61) AND   D.CAPITOL IN ('1113') AND D.RIND IN ('210','220','230','240')     THEN NVAL(D.COL11) ELSE NULL END)) ||'<>'||
    CIS2.NVAL(SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN ('1117') AND D.RIND IN ('1700')  THEN NVAL(D.COL13)  ELSE NULL END))  
 AS REZULTAT

-- 1 cmpa cap.IV col.11 rind.210+220+230+240 = 3 cmpa tab.3 Col.13 r.1700 



FROM
  CIS2.VW_DATA_ALL_GC D 
         INNER JOIN CIS2.MD_PERIOADA P ON D.PERIOADA = P.PERIOADA AND P.NUM = 4
        
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.NR_GOSP=:NR_GOSP               OR :NR_GOSP = -1) AND
  (D.UNIT_CODE_VERS=:UNIT_CODE_VERS    OR :UNIT_CODE_VERS = -1) AND
  (:FORM  = :FORM               OR  :FORM  <>  :FORM ) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <> :CAPITOL) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
--  
  D.FORM IN (62,61)     
 
  
HAVING
  
 CIS2.NVAL(SUM(CASE WHEN D.FORM IN (61) AND   D.CAPITOL IN ('1113') AND D.RIND IN ('210','220','230','240')     THEN NVAL(D.COL11) ELSE NULL END)) <>
    CIS2.NVAL(SUM(CASE WHEN D.FORM IN (62) AND  D.CAPITOL IN ('1117') AND D.RIND IN ('1700')  THEN NVAL(D.COL13)  ELSE NULL END))  

 