SELECT
  'RINDUL '||D.RIND||': '||
  'COL1 = '||NVAL(CASE WHEN D.RIND IN ('01','02','03','09','11') THEN D.COL2 ELSE 0 END)||' si COL3 = '||
  NVAL(CASE WHEN D.RIND IN ('01','02','03','09','11') THEN D.COL3 ELSE 0 END) ||',  col.5/col.3 = '||
  NVAL(CASE WHEN D.RIND IN ('01','02','03','09','11') THEN NVAL(D.COL5)/NOZERO(NVAL(D.COL3)) ELSE 0 END)
  
  AS REZULTAT
  
  
FROM
  VW_DATA_ALL D      
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL=-1)  AND  
  (:FORM = :FORM) AND 
  D.FORM IN (6) AND
  D.CAPITOL IN (315)
GROUP BY
  D.RIND,
  D.COL2,
  D.COL3,
  D.COL5
 
HAVING
  NVAL(CASE WHEN D.RIND IN ('01','02','03','09','11') THEN D.COL2 ELSE 0 END) = 0
  
  AND 
 
  NVAL(CASE WHEN D.RIND IN ('01','02','03','09','11') THEN D.COL3 ELSE 0 END) > 0
  
  AND 
 NVAL(CASE WHEN D.RIND IN ('01','02','03','09','11') THEN NVAL(D.COL5)/NOZERO(NVAL(D.COL3)) ELSE 0 END) >= 1000
  
