INSERT INTO TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
 COL1,
 COL2,
 COL3,
 COL4,
 COL5
)

SELECT
  DISTINCT
  CASE WHEN A.NR_ROW=B.NR_ROW THEN B.PERIOADA ELSE B.PERIOADA END AS PERIOADA,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN B.FORM ELSE B.FORM END AS FORM,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN B.FORM_VERS ELSE B.FORM_VERS END AS FORM_VERS,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN B.ID_MDTABLE ELSE B.ID_MDTABLE END AS ID_MDTABLE,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN B.COD_CUATM ELSE B.COD_CUATM END AS COD_CUATM,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.NR_SECTIE ELSE B.NR_SECTIE END AS NR_SECTIE,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.NUME_SECTIE ELSE B.NUME_SECTIE END AS NUME_SECTIE,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.NR_SECTIE1 ELSE B.NR_SECTIE1 END AS NR_SECTIE1,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.NUME_SECTIE1 ELSE B.NUME_SECTIE1 END AS NUME_SECTIE1,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.NR_SECTIE2 ELSE B.NR_SECTIE2 END AS NR_SECTIE2,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.NUME_SECTIE2 ELSE B.NUME_SECTIE2 END AS NUME_SECTIE2,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.NR_ROW ELSE B.NR_ROW END AS NR_ROW,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN B.ORDINE ELSE B.ORDINE END AS ORDINE,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.DECIMAL_POS ELSE B.DECIMAL_POS END AS DECIMAL_POS,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN B.NUME_ROW ELSE B.NUME_ROW END AS NUME_ROW,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.COL1 ELSE B.COL1 END AS COL1,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.COL2 ELSE B.COL2 END AS COL2,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.COL3 ELSE B.COL3 END AS COL3,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.COL4 ELSE B.COL4 END AS COL4,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.COL5 ELSE B.COL5 END AS COL5
FROM
(SELECT
  DISTINCT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  CR.FULL_CODE AS NR_SECTIE,
  CR.DENUMIRE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  RD.RIND AS NR_ROW,
  RD.ID_MD AS ORDINE,
  '00001' AS DECIMAL_POS,
   RD.DENUMIRE AS NUME_ROW,  
  ROUND(SUM(D.COL1),0) AS COL1,
  ROUND(SUM(D.COL2),0) AS COL2,
  ROUND(SUM(D.COL3),0) AS COL3,
  ROUND(SUM(D.COL4),0) AS COL4,
  ROUND(SUM(D.COL5),1) AS COL5
FROM
  VW_DATA_ALL D
  INNER JOIN MD_RIND RD ON (RD.ID_MD = D.ID_MD)
  INNER JOIN RENIM R ON (R.CUIIO= D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
  INNER JOIN VW_CL_CUATM  C ON (C.CODUL = R.CUATM) 
  INNER JOIN VW_CL_CUATM CR ON(C.FULL_CODE LIKE '%'||CR.CODUL||';%')
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.FORM IN (6)                              AND 
  D.FORM_VERS = :pFORM_VERS                  AND    
  RD.CAPITOL IN (315)                        AND
  CR.FULL_CODE LIKE '%'||:pCOD_CUATM||';%'   AND
  ((:pCOD_CUATM IN ('0000000','0100000') AND LENGTH(CR.FULL_CODE)<=16) OR (:pCOD_CUATM NOT IN ('0000000','0100000') AND LENGTH(CR.FULL_CODE)<=24))
GROUP BY
  CR.FULL_CODE,
  CR.DENUMIRE,
  RD.ID_MD,
  RD.RIND,
  RD.DENUMIRE 
 ) A
 RIGHT JOIN
 (SELECT
  DISTINCT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  CR.FULL_CODE AS NR_SECTIE,
  CR.DENUMIRE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  RO.RIND AS NR_ROW,
  RO.ORDINE AS ORDINE,
  '00001' AS DECIMAL_POS,
  RO.DENUMIRE AS NUME_ROW,
  NULL AS COL1,
  NULL AS COL2,
  NULL AS COL3,
  NULL AS COL4,
  NULL AS COL5
FROM
  MD_RIND RD
  INNER JOIN VW_DATA_ALL D ON (RD.CAPITOL=D.CAPITOL AND RD.CAPITOL_VERS=D.CAPITOL_VERS)
  LEFT JOIN MD_RIND_OUT RO ON (RD.RIND=RO.RIND)
  INNER JOIN VW_CL_CUATM C ON (C.CODUL = D.CUATM) 
  INNER JOIN VW_CL_CUATM CR ON(C.FULL_CODE LIKE '%'||CR.CODUL||';%')
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  RD.CAPITOL IN (315) AND
  RD.FORM IN (6) AND
  CR.FULL_CODE LIKE '%'||:pCOD_CUATM||';%'   AND
  RD.FORM_VERS = :pFORM_VERS AND 
  RO.ID_MDTABLE IN (242)   AND
  ((:pCOD_CUATM IN ('0000000','0100000') AND LENGTH(CR.FULL_CODE)<=16) OR (:pCOD_CUATM NOT IN ('0000000','0100000') AND LENGTH(CR.FULL_CODE)<=24))
  ) B ON (A.NR_ROW=B.NR_ROW AND A.NR_SECTIE=B.NR_SECTIE)