--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
-- COL1,
-- COL2,
-- COL3,
-- COL4
--)

SELECT
  DISTINCT
  CASE WHEN A.NR_ROW=B.NR_ROW THEN B.PERIOADA ELSE B.PERIOADA END AS PERIOADA,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN B.FORM ELSE B.FORM END AS FORM,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN B.FORM_VERS ELSE B.FORM_VERS END AS FORM_VERS,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN B.ID_MDTABLE ELSE B.ID_MDTABLE END AS ID_MDTABLE,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN B.COD_CUATM ELSE B.COD_CUATM END AS COD_CUATM,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.NR_SECTIE ELSE B.NR_SECTIE END AS NR_SECTIE,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.NR_SECTIE||'-'||A.NUME_SECTIE ELSE B.NR_SECTIE||'-'||B.NUME_SECTIE END AS NUME_SECTIE,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.NR_SECTIE1 ELSE B.NR_SECTIE1 END AS NR_SECTIE1,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.NUME_SECTIE1 ELSE B.NUME_SECTIE1 END AS NUME_SECTIE1,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.NR_SECTIE2 ELSE B.NR_SECTIE2 END AS NR_SECTIE2,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.NUME_SECTIE2 ELSE B.NUME_SECTIE2 END AS NUME_SECTIE2,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.NR_ROW ELSE B.NR_ROW END||'~'||ROWNUM AS NR_ROW,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN B.ORDINE ELSE B.ORDINE END AS ORDINE,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.DECIMAL_POS ELSE B.DECIMAL_POS END AS DECIMAL_POS,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN B.NUME_ROW ELSE B.NUME_ROW END AS NUME_ROW,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.COL1 ELSE B.COL1 END AS COL1,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.COL2 ELSE B.COL2 END AS COL2,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.COL3 ELSE B.COL3 END AS COL3,
  CASE WHEN A.NR_ROW=B.NR_ROW THEN A.COL4 ELSE B.COL4 END AS COL4
FROM
(
SELECT
  DISTINCT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  R.CUIIO AS NR_SECTIE,
  R.DENUMIRE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  RD.RIND AS NR_ROW,
  RD.ID_MD AS ORDINE,
  '000000' AS DECIMAL_POS,
   RD.DENUMIRE AS NUME_ROW,  
  ROUND(SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA) THEN D.COL1 ELSE 0 END),0) AS COL1,
  ROUND(SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA) THEN D.COL3 ELSE 0 END),0) AS COL2,
  ROUND(SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) THEN D.COL1 ELSE 0 END),0) AS COL3,
  ROUND(SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) THEN D.COL3 ELSE 0 END),0) AS COL4,
  ROUND(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) THEN D.COL5 ELSE 0 END),1) AS COL5,
  ROUND(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-1) THEN D.COL5 ELSE 0 END),1) AS COL6
FROM
  CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.MD_RIND RD ON (RD.ID_MD = D.ID_MD AND RD.CAPITOL=D.CAPITOL AND RD.CAPITOL_VERS=D.CAPITOL_VERS AND RD.RIND=D.RIND AND D.RIND_VERS = RD.RIND_VERS)
  INNER JOIN CIS2.RENIM R ON (R.CUIIO= D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
WHERE
  (D.PERIOADA IN (:pPERIOADA,:pPERIOADA-1)) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.FORM IN (6)                              AND 
  D.FORM_VERS = :pFORM_VERS                  AND    
  RD.CAPITOL IN (315)                        AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  RD.STATUT = 1 AND
  D.ID_MD NOT IN (14771,100011477)  
--  AND D.CUIIO IN (15814346)
GROUP BY
  RD.RIND,
  RD.ID_MD,
  RD.DENUMIRE,
  R.CUIIO,
  R.DENUMIRE
   
 ) A
 RIGHT JOIN
 (
 
 
 SELECT
  DISTINCT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  R.CUIIO AS NR_SECTIE,
  R.DENUMIRE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  RO.RIND AS NR_ROW,
  RO.ORDINE AS ORDINE,
  '000000' AS DECIMAL_POS,
  RO.DENUMIRE AS NUME_ROW,
  NULL AS COL1,
  NULL AS COL2,
  NULL AS COL3,
  NULL AS COL4,
  NULL AS COL5,
  NULL AS COL6
  
FROM
  CIS2.MD_RIND RD
  INNER JOIN CIS2.VW_DATA_ALL D ON (RD.ID_MD = D.ID_MD AND RD.CAPITOL=D.CAPITOL AND RD.CAPITOL_VERS=D.CAPITOL_VERS AND RD.RIND = D.RIND AND RD.RIND_VERS = D.RIND_VERS)
  INNER JOIN CIS2.RENIM R ON (R.CUIIO= D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
  LEFT JOIN CIS2.MD_RIND_OUT RO ON (RD.RIND=RO.RIND)
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  RD.CAPITOL IN (315) AND
  RD.FORM IN (6) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
  RD.FORM_VERS = :pFORM_VERS AND 
  RO.ID_MDTABLE IN (242) AND
  RD.STATUT = 1 AND
  D.ID_MD NOT IN (14771,100011477)
--  AND D.CUIIO IN (15814346)



  ) B ON (A.NR_ROW=B.NR_ROW AND A.NR_SECTIE=B.NR_SECTIE)