SELECT CONTROL,
        CUIIO,
        REZULTAT,    
        DATA_REG  
FROM USER_EREPORTING.CONTROL

    WHERE 
    
    FORM = 63 
    AND PERIOADA = 2010
    AND REZULTAT <> 'OK'
    
    ORDER BY 
    DATA_REG DESC