SELECT
1 ORDINE,
'010' RIND,
SUM ( CASE WHEN D.PERIOADA = 1041 AND D.RIND IN ('010') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL1,
SUM ( CASE WHEN D.PERIOADA = 1043 AND D.RIND IN ('010') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL2,
SUM (CASE WHEN D.PERIOADA = 1045 AND D.RIND IN ('010') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL3,
SUM ( CASE WHEN D.PERIOADA = 1047 AND D.RIND IN ('010') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL4
           
     
FROM
  VW_DATA_ALL_GC  D
  
            INNER JOIN (
            SELECT
D.PERIOADA, 
D.UNIT_CODE,
D.RIND
FROM
  VW_DATA_ALL_GC  D
  
  WHERE 
    
     D.FORM IN (62)  AND
     D.CAPITOL IN (1118)
     AND D.RIND IN ('0')
            
            ) R ON R.UNIT_CODE = D.UNIT_CODE    AND R.PERIOADA = D.PERIOADA
  
WHERE
  (D.PERIOADA IN  (1041,1043,1045,1047))  AND   
 
  
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN ('010')
  
  UNION
  
  
  
  SELECT
2 ORDINE,
'011' RIND,
SUM ( CASE WHEN D.PERIOADA = 1041 AND D.RIND IN ('011') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL1,
SUM ( CASE WHEN D.PERIOADA = 1043 AND D.RIND IN ('011') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL2,
SUM (CASE WHEN D.PERIOADA = 1045 AND D.RIND IN ('011') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL3,
SUM ( CASE WHEN D.PERIOADA = 1047 AND D.RIND IN ('011') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL4
           
     
FROM
  VW_DATA_ALL_GC  D
  
            INNER JOIN (
            SELECT
D.PERIOADA, 
D.UNIT_CODE,
D.RIND
FROM
  VW_DATA_ALL_GC  D
  
  WHERE 
    
     D.FORM IN (62)  AND
     D.CAPITOL IN (1118)
     AND D.RIND IN ('0')
            
            ) R ON R.UNIT_CODE = D.UNIT_CODE    AND R.PERIOADA = D.PERIOADA
  
WHERE
  (D.PERIOADA IN  (1041,1043,1045,1047))  AND   
 
  
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
   AND D.RIND IN ('011')
   
  UNION  
   SELECT
3 ORDINE,
'020' RIND,
SUM ( CASE WHEN D.PERIOADA = 1041 AND D.RIND IN ('020') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL1,
SUM ( CASE WHEN D.PERIOADA = 1043 AND D.RIND IN ('020') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL2,
SUM (CASE WHEN D.PERIOADA = 1045 AND D.RIND IN ('020') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL3,
SUM ( CASE WHEN D.PERIOADA = 1047 AND D.RIND IN ('020') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL4
           
     
FROM
  VW_DATA_ALL_GC  D
  
            INNER JOIN (
            SELECT
D.PERIOADA, 
D.UNIT_CODE,
D.RIND
FROM
  VW_DATA_ALL_GC  D
  
  WHERE 
    
     D.FORM IN (62)  AND
     D.CAPITOL IN (1118)
     AND D.RIND IN ('0')
            
            ) R ON R.UNIT_CODE = D.UNIT_CODE    AND R.PERIOADA = D.PERIOADA
  
WHERE
  (D.PERIOADA IN  (1041,1043,1045,1047))  AND   
 
  
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
   AND D.RIND IN ('020')
   
   
   UNION  
   SELECT
4 ORDINE,
'030' RIND,
SUM ( CASE WHEN D.PERIOADA = 1041 AND D.RIND IN ('030') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL1,
SUM ( CASE WHEN D.PERIOADA = 1043 AND D.RIND IN ('030') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL2,
SUM (CASE WHEN D.PERIOADA = 1045 AND D.RIND IN ('030') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL3,
SUM ( CASE WHEN D.PERIOADA = 1047 AND D.RIND IN ('030') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL4
           
     
FROM
  VW_DATA_ALL_GC  D
  
            INNER JOIN (
            SELECT
D.PERIOADA, 
D.UNIT_CODE,
D.RIND
FROM
  VW_DATA_ALL_GC  D
  
  WHERE 
    
     D.FORM IN (62)  AND
     D.CAPITOL IN (1118)
     AND D.RIND IN ('0')
            
            ) R ON R.UNIT_CODE = D.UNIT_CODE    AND R.PERIOADA = D.PERIOADA
  
WHERE
  (D.PERIOADA IN  (1041,1043,1045,1047))  AND   
 
  
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
   AND D.RIND IN ('030')
   
   

   
   
   UNION  
   SELECT
5 ORDINE,
'040' RIND,
SUM ( CASE WHEN D.PERIOADA = 1041 AND D.RIND IN ('040') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL1,
SUM ( CASE WHEN D.PERIOADA = 1043 AND D.RIND IN ('040') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL2,
SUM (CASE WHEN D.PERIOADA = 1045 AND D.RIND IN ('040') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL3,
SUM ( CASE WHEN D.PERIOADA = 1047 AND D.RIND IN ('040') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL4
           
     
FROM
  VW_DATA_ALL_GC  D
  
            INNER JOIN (
            SELECT
D.PERIOADA, 
D.UNIT_CODE,
D.RIND
FROM
  VW_DATA_ALL_GC  D
  
  WHERE 
    
     D.FORM IN (62)  AND
     D.CAPITOL IN (1118)
     AND D.RIND IN ('0')
            
            ) R ON R.UNIT_CODE = D.UNIT_CODE    AND R.PERIOADA = D.PERIOADA
  
WHERE
  (D.PERIOADA IN  (1041,1043,1045,1047))  AND   
 
  
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
   AND D.RIND IN ('040')
   
   
   
   UNION  
   SELECT
6 ORDINE,
'050' RIND,
SUM ( CASE WHEN D.PERIOADA = 1041 AND D.RIND IN ('050') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL1,
SUM ( CASE WHEN D.PERIOADA = 1043 AND D.RIND IN ('050') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL2,
SUM (CASE WHEN D.PERIOADA = 1045 AND D.RIND IN ('050') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL3,
SUM ( CASE WHEN D.PERIOADA = 1047 AND D.RIND IN ('050') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL4
           
     
FROM
  VW_DATA_ALL_GC  D
  
            INNER JOIN (
            SELECT
D.PERIOADA, 
D.UNIT_CODE,
D.RIND
FROM
  VW_DATA_ALL_GC  D
  
  WHERE 
    
     D.FORM IN (62)  AND
     D.CAPITOL IN (1118)
     AND D.RIND IN ('0')
            
            ) R ON R.UNIT_CODE = D.UNIT_CODE    AND R.PERIOADA = D.PERIOADA
  
WHERE
  (D.PERIOADA IN  (1041,1043,1045,1047))  AND   
 
  
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
   AND D.RIND IN ('050')
   
   
   
    UNION  
   SELECT
7 ORDINE,
'060' RIND,
SUM ( CASE WHEN D.PERIOADA = 1041 AND D.RIND IN ('060') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL1,
SUM ( CASE WHEN D.PERIOADA = 1043 AND D.RIND IN ('060') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL2,
SUM (CASE WHEN D.PERIOADA = 1045 AND D.RIND IN ('060') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL3,
SUM ( CASE WHEN D.PERIOADA = 1047 AND D.RIND IN ('060') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL4
           
     
FROM
  VW_DATA_ALL_GC  D
  
            INNER JOIN (
            SELECT
D.PERIOADA, 
D.UNIT_CODE,
D.RIND
FROM
  VW_DATA_ALL_GC  D
  
  WHERE 
    
     D.FORM IN (62)  AND
     D.CAPITOL IN (1118)
     AND D.RIND IN ('0')
            
            ) R ON R.UNIT_CODE = D.UNIT_CODE    AND R.PERIOADA = D.PERIOADA
  
WHERE
  (D.PERIOADA IN  (1041,1043,1045,1047))  AND   
 
  
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
   AND D.RIND IN ('060')
   
   
   UNION  
   SELECT
8 ORDINE,
'070' RIND,
SUM ( CASE WHEN D.PERIOADA = 1041 AND D.RIND IN ('070') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL1,
SUM ( CASE WHEN D.PERIOADA = 1043 AND D.RIND IN ('070') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL2,
SUM (CASE WHEN D.PERIOADA = 1045 AND D.RIND IN ('070') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL3,
SUM ( CASE WHEN D.PERIOADA = 1047 AND D.RIND IN ('070') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL4
           
     
FROM
  VW_DATA_ALL_GC  D
  
            INNER JOIN (
            SELECT
D.PERIOADA, 
D.UNIT_CODE,
D.RIND
FROM
  VW_DATA_ALL_GC  D
  
  WHERE 
    
     D.FORM IN (62)  AND
     D.CAPITOL IN (1118)
     AND D.RIND IN ('0')
            
            ) R ON R.UNIT_CODE = D.UNIT_CODE    AND R.PERIOADA = D.PERIOADA
  
WHERE
  (D.PERIOADA IN  (1041,1043,1045,1047))  AND   
 
  
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
   AND D.RIND IN ('070')
   
   
   UNION  
   SELECT
9 ORDINE,
'080' RIND,
SUM ( CASE WHEN D.PERIOADA = 1041 AND D.RIND IN ('080') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL1,
SUM ( CASE WHEN D.PERIOADA = 1043 AND D.RIND IN ('080') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL2,
SUM (CASE WHEN D.PERIOADA = 1045 AND D.RIND IN ('080') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL3,
SUM ( CASE WHEN D.PERIOADA = 1047 AND D.RIND IN ('080') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL4
           
     
FROM
  VW_DATA_ALL_GC  D
  
            INNER JOIN (
            SELECT
D.PERIOADA, 
D.UNIT_CODE,
D.RIND
FROM
  VW_DATA_ALL_GC  D
  
  WHERE 
    
     D.FORM IN (62)  AND
     D.CAPITOL IN (1118)
     AND D.RIND IN ('0')
            
            ) R ON R.UNIT_CODE = D.UNIT_CODE    AND R.PERIOADA = D.PERIOADA
  
WHERE
  (D.PERIOADA IN  (1041,1043,1045,1047))  AND   
 
  
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
   AND D.RIND IN ('080')
   
   
   
    UNION  
   SELECT
10 ORDINE,
'090' RIND,
SUM ( CASE WHEN D.PERIOADA = 1041 AND D.RIND IN ('090') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL1,
SUM ( CASE WHEN D.PERIOADA = 1043 AND D.RIND IN ('090') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL2,
SUM (CASE WHEN D.PERIOADA = 1045 AND D.RIND IN ('090') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL3,
SUM ( CASE WHEN D.PERIOADA = 1047 AND D.RIND IN ('090') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL4
           
     
FROM
  VW_DATA_ALL_GC  D
  
            INNER JOIN (
            SELECT
D.PERIOADA, 
D.UNIT_CODE,
D.RIND
FROM
  VW_DATA_ALL_GC  D
  
  WHERE 
    
     D.FORM IN (62)  AND
     D.CAPITOL IN (1118)
     AND D.RIND IN ('0')
            
            ) R ON R.UNIT_CODE = D.UNIT_CODE    AND R.PERIOADA = D.PERIOADA
  
WHERE
  (D.PERIOADA IN  (1041,1043,1045,1047))  AND   
 
  
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
   AND D.RIND IN ('090')
   
   
   UNION  
   SELECT
11 ORDINE,
'100' RIND,
SUM ( CASE WHEN D.PERIOADA = 1041 AND D.RIND IN ('100') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL1,
SUM ( CASE WHEN D.PERIOADA = 1043 AND D.RIND IN ('100') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL2,
SUM (CASE WHEN D.PERIOADA = 1045 AND D.RIND IN ('100') AND NVAL(D.COL1) <> 0  THEN D.COL1 ELSE NULL END ) AS COL3,
SUM ( CASE WHEN D.PERIOADA = 1047 AND D.RIND IN ('100') AND NVAL(D.COL16) <> 0  THEN D.COL16 ELSE NULL END ) AS COL4
           
     
FROM
  VW_DATA_ALL_GC  D
  
            INNER JOIN (
            SELECT
D.PERIOADA, 
D.UNIT_CODE,
D.RIND
FROM
  VW_DATA_ALL_GC  D
  
  WHERE 
    
     D.FORM IN (62)  AND
     D.CAPITOL IN (1118)
     AND D.RIND IN ('0')
            
            ) R ON R.UNIT_CODE = D.UNIT_CODE    AND R.PERIOADA = D.PERIOADA
  
WHERE
  (D.PERIOADA IN  (1041,1043,1045,1047))  AND   
 
  
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
   AND D.RIND IN ('100')