SELECT
DISTINCT D.UNIT_CODE
   
     
FROM
  VW_DATA_ALL_GC  D
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN ('060')
  AND NVAL(D.COL1) <> 0