SELECT 

'COL1 CAP III -  ' ||SUM(CASE WHEN D.CAPITOL  IN  (1174) AND D.RIND IN ('01') THEN NVAL(D.COL1) ELSE NULL END) 

||' <> CAP I - '|| 

SUM(CASE WHEN D.CAPITOL  IN  (1171) AND D.RIND IN ('03','07') THEN NVAL(D.COL1) ELSE 0 END)


  ||']' AS REZULTAT
    
FROM
VW_DATA_ALL D                                  
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  ( :CAPITOL=:CAPITOL           OR :CAPITOL <>  :CAPITOL) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
 
 
  D.FORM = 69
  AND D.CAPITOL  IN  (1174,1171)
  

 

HAVING
SUM(CASE WHEN D.CAPITOL  IN  (1174) AND D.RIND IN  ('01') THEN NVAL(D.COL1) ELSE 0 END)   <>  

SUM(CASE WHEN D.CAPITOL  IN  (1171) AND D.RIND IN ('03','07') THEN NVAL(D.COL1) ELSE 0 END)
