SELECT DISTINCT

'RIND ' ||D.RIND||' [' || NVAL(SUM(D.COL1))||' < '|| NVAL(SUM(D.COL2)) ||']'
        
 AS REZULTAT
    
FROM
VW_DATA_ALL D                                  
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
 
 
  D.FORM = 69
  AND D.CAPITOL = 1173
  
GROUP BY D.RIND

HAVING

NVAL(SUM(D.COL1)) 

< 

NVAL(SUM(D.COL2))