SELECT DISTINCT

 NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL1 ELSE 0 END)) ||' < '|| 
 
 NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL1 ELSE 0 END)) 
        
 AS REZULTAT
    
FROM
VW_DATA_ALL  D                                  
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
 
 
  D.FORM = 69
  AND D.CAPITOL = 1176
  


HAVING

 NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL1 ELSE 0 END))   > 
 
 NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL1 ELSE 0 END)) 