SELECT DISTINCT

'RIND ' ||D.RIND||' [' || SUM(DECODE(D.COL2,null,0,D.COL2))||' <> '||
 SUM(
DECODE(D.COL4,NULL,0,D.COL4)+DECODE(D.COL6,NULL,0,D.COL6)  )  ||']' AS REZULTAT
    
FROM
VW_DATA_ALL_TEMP D                                  
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
 
 
  D.FORM = 69
  AND D.CAPITOL = 1171
  
GROUP BY D.RIND
 

HAVING

SUM(DECODE(D.COL2,null,0,D.COL2))<>
SUM(DECODE(D.COL4,NULL,0,D.COL4)+DECODE(D.COL6,NULL,0,D.COL6))