INSERT INTO  CIS2.TABLE_OUT
    (
      PERIOADA,
      FORM,
      FORM_VERS,
      ID_MDTABLE,
      COD_CUATM,
      NR_SECTIE,
      NUME_SECTIE,
      NR_SECTIE1,
      NUME_SECTIE1,
      NR_SECTIE2,
      NUME_SECTIE2,
      NR_ROW,
      ORDINE,
      DECIMAL_POS,
      NUME_ROW,
        COL1,
        COL2,
        COL3,
        COL4,
        COL5,
        COL6,
        COL7,
        COL8,
        COL9,
         COL10,
         COL11,
         COL12,
         COL13,
         COL14
      
    ) 

SELECT 
 :pPERIOADA AS PERIOADA,
 :pFORM AS FORM,
 :pFORM_VERS AS FORM_VERS,
 :pID_MDTABLE AS ID_MDTABLE,
 :pCOD_CUATM AS COD_CUATM,
 '0' AS NR_SECTIE,
 '0' AS NUME_SECTIE,
 '0' AS NR_SECTIE1,
 '0' AS NUME_SECTIE1,
 '0' AS NR_SECTIE2,
 '0' AS NUME_SECTIE2,
RIND AS NR_ROW, 
ROWNUM ORDINE, 
'00000000000000' AS DECIMAL_POS,  
NUME_ROW,
COL1 AS COL1,
COL2 AS COL2,
COL3 AS COL3,
COL4 AS COL4,
COL5 AS COL5,
COL6 AS COL6,
COL7 AS COL7,
COL8 AS COL8,
COL9 AS COL9,
COL10 AS COL10,
COL11 AS COL11,
COL12 AS COL12,
COL13 AS COL13,
COL14 AS COL14
FROM
(
SELECT 
RIND,
ORDINE,
DENUMIRE NUME_ROW,
SUM(COL1) AS COL1,
SUM(COL2) AS COL2,
SUM(COL3) AS COL3,
SUM(COL4) AS COL4,
SUM(COL5) AS COL5,
SUM(COL6) AS COL6,
SUM(COL7) AS COL7,
SUM(COL8) AS COL8,
SUM(COL9) AS COL9,
SUM(COL10) AS COL10,
SUM(COL11) AS COL11,
SUM(COL12) AS COL12,
SUM(COL13) AS COL13,
SUM(COL14) AS COL14

FROM
(
SELECT 

R.RIND,
R.ORDINE,
R.DENUMIRE,
NULL AS COL1,
SUM(D.COL2) AS COL2,
SUM(D.COL3) AS COL3,
SUM(D.COL4) AS COL4,
SUM(NVAL(D.COL2) + NVAL(D.COL3) +NVAL(D.COL4) ) AS COL5,
SUM(D.COL5) AS COL6,
SUM(D.COL6) AS COL7,
SUM(D.COL7) AS COL8,
SUM(D.COL8) AS COL9,
SUM(D.COL9) AS COL10,
SUM(D.COL10) AS COL11,
SUM(D.COL11) AS COL12,
SUM(D.COL12) AS COL13,
NULL  AS COL14


FROM
  VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
WHERE
  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  AND   

  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (62)  AND
  D.CAPITOL IN (1117)

 GROUP BY 
     R.RIND,
     R.ORDINE,
     R.DENUMIRE
 
     UNION 
 
SELECT 
R.RIND,
R.ORDINE,
R.DENUMIRE,
SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-3) THEN  D.COL1 ELSE NULL END) AS COL1,
NULL  AS COL2,
NULL  AS COL3,
NULL  AS COL4,
SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-3) THEN  D.COL1 ELSE NULL END) AS COL5,
NULL  AS COL6,
NULL  AS COL7,
NULL  AS COL8,
NULL  AS COL9,
NULL  AS COL10,
NULL  AS COL11,
NULL  AS COL12,
NULL  AS COL13,
SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) THEN  D.COL13 ELSE NULL END) AS COL14


FROM
  VW_DATA_ALL_GC  D
          INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
WHERE
  (D.PERIOADA IN (:pPERIOADA-3,:pPERIOADA))  AND  
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (62)  AND
  D.CAPITOL IN (1117)

 GROUP BY 

   R.RIND,
     R.ORDINE,
       R.DENUMIRE
       
       ORDER BY 
       RIND
     )
     
     GROUP BY 
     RIND,
     ORDINE,
     DENUMIRE
     ORDER BY 
     ORDINE
   )  
   
   
 