SELECT 
D.RIND,
 
 SUM(CASE WHEN D.RIND IN ('01') THEN   D.COL1 ELSE NULL END)  AS COL1,
                   SUM(CASE WHEN D.RIND IN ('02') THEN   D.COL1 ELSE NULL END)  AS COL2,
                   SUM(CASE WHEN D.RIND IN ('03') THEN   D.COL1 ELSE NULL END)  AS COL3,
                   SUM(CASE WHEN D.RIND IN ('04') THEN   D.COL1 ELSE NULL END)  AS COL4 
    
    FROM 
      CIS.VW_DATA_ALL D
      INNER JOIN (
        
        SELECT DISTINCT
          D.ANUL,
          SUM(CASE 
          WHEN D.NUM IN 1 THEN DD.COL1
          WHEN D.NUM IN 2 THEN DD.COL2
          WHEN D.NUM IN 3 THEN DD.COL3
          WHEN D.NUM IN 4 THEN DD.COL4 END) AS JIP
  
  
  
       FROM 
         CIS.MD_PERIOADA D
         INNER JOIN (
  
       SELECT DISTINCT
         ANUL,
         CASE WHEN NUM IN 3  THEN PERIOADA ELSE 0 END AS COL1,
         CASE WHEN NUM IN 6  THEN PERIOADA ELSE 0 END AS COL2,
         CASE WHEN NUM IN 9  THEN PERIOADA ELSE 0 END AS COL3,
         CASE WHEN NUM IN 12 THEN PERIOADA ELSE 0 END AS COL4
  
      FROM 
        CIS.MD_PERIOADA
  
      WHERE 
        TIP_PERIOADA = 4


  ) DD ON DD.ANUL = D.ANUL
  
WHERE
  PERIOADA = :pPERIOADA

GROUP BY
  D.ANUL
) P ON P.ANUL = D.ANUL
  
WHERE 
  D.PERIOADA = P.JIP AND
  D.CAPITOL = 37  AND
  D.RIND IN ('01','02','03','04') 
  
  GROUP BY 
  D.RIND