 SELECT 
 R.RIND AS NR_ROW,
 
             R.ORDINE AS ORDINE,
         
             R.DENUMIRE AS NUME_RO,
              (SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND R.RIND =  MR.RIND THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND R.RIND =  MR.RIND THEN D.COL2 ELSE 0 END))  AS COL1,
  
              (
              
              SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND R.RIND =  MR.RIND THEN NVAL(D.COL1) + NVAL(D.COL2)  ELSE 0 END)
 
  
  )  AS COL1_1,
  
  
    ROUND((((
    
    SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND R.RIND =  MR.RIND  THEN NVAL(D.COL1) + NVAL(D.COL2) ELSE 0 END)
  
  
  
  )/
 CIS.NOZERO(SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND R.RIND =  MR.RIND THEN NVAL(D.COL1) + NVAL(D.COL2) ELSE 0 END)
 
 
  
  
  )))*100,1) AS COL2_2,
  
  
      ROUND((((SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND R.RIND =  MR.RIND  THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND R.RIND =  MR.RIND THEN D.COL2 ELSE 0 END))/
 CIS.NOZERO(SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND R.RIND =  MR.RIND THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND R.RIND =  MR.RIND THEN D.COL2 ELSE 0 END))))*100,1) AS COL2,
  
  
  
  

FROM CIS.DATA_ALL D
                       INNER JOIN CIS.MD_RIND MR ON (MR.ID_MD=D.ID_MD)
                       INNER JOIN CIS.RENIM RR ON (RR.CUIIO = D.CUIIO AND RR.CUIIO_VERS = D.CUIIO_VERS)
                       INNER JOIN CIS.VW_CL_CUATM C ON C.CODUL = RR.CUATM
                      



CROSS JOIN (


SELECT
                             DENUMIRE,
                             RIND,
                             ORDINE
  
                           FROM  CIS.MD_RIND
  
    WHERE
    
     CAPITOL = 31 AND
     RIND_VERS >= 1040 AND
     STATUT = '1' 
       AND RIND NOT IN ('410','420','430','440','441','450','-')     

) R

WHERE 

 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
-- (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  (C.FULL_CODE LIKE '%'||:pCOD_CUATM||';%') AND   
 ((D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) OR (D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4))  AND
  D.FORM = 6 AND
  MR.CAPITOL = 31
  
           GROUP BY
           R.DENUMIRE,
           R.RIND,
           R.ORDINE
           
             
  ORDER BY 
  R.ORDINE