SELECT   
  TO_CHAR(SUM(CASE WHEN D.CAPITOL IN (411) AND  D.RIND IN ('1') THEN CIS2.NVAL(D.COL4) ELSE 0 END))  ||'<>'|| 
  TO_CHAR(SUM(CASE WHEN D.CAPITOL IN (411) AND  D.RIND IN ('2') THEN CIS2.NVAL(D.COL4) ELSE 0 END) + 
  SUM(CASE WHEN D.CAPITOL IN (403) AND  D.RIND IN ('1') THEN CIS2.NVAL(D.COL4) ELSE 0 END)) 
              
               AS REZULTAT
--Cap. Import I, Col.1 rd.1 =?(Col.1rd.2 Cap. Import  I)+(Col.1rd.1Cap.Import II)

FROM
  CIS2.VW_DATA_ALL D
 

WHERE
  (D.PERIOADA =:PERIOADA        OR :PERIOADA=  -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL           OR :CAPITOL <> :CAPITOL) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (46)  AND
  D.CAPITOL IN (411,403)
  
 
    GROUP BY 
    D.CUIIO



--
--    HAVING 
--    
--    SUM(CASE WHEN D.CAPITOL IN (411) AND  D.RIND IN ('1') THEN CIS2.NVAL(D.COL4) ELSE 0 END)  <> 
--  
--    SUM(CASE WHEN D.CAPITOL IN (411) AND  D.RIND IN ('2') THEN CIS2.NVAL(D.COL4) ELSE 0 END) + 
--        SUM(CASE WHEN D.CAPITOL IN (403) AND  D.RIND IN ('1') THEN CIS2.NVAL(D.COL4) ELSE 0 END)