


SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,        
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   CD.CODE AS NR_ROW,  
   CD.CODE AS ORDINE,
  '111111111111' AS DECIMAL_POS,
   CD.DEN_CUATM AS NUME_ROW,               

    NVAL(SUM(CASE WHEN D.RIND='01'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END)) AS COL1, 
    NVAL(SUM(CASE WHEN D.RIND='03'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END)) AS COL2,
    NVAL(SUM(CASE WHEN D.RIND='04'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END)) AS COL3,  
    NVAL(SUM(CASE WHEN D.RIND='05'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END)) AS COL4,
    NVAL(SUM(CASE WHEN D.RIND='06'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END)) AS COL5,
   (NVAL(SUM(CASE WHEN D.RIND='01'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END)) /
    NOZERO( NVAL(SUM(CASE WHEN D.RIND='01'  AND D.PERIOADA = :pPERIOADA-4 AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END))) * 100) AS COL6, 
    NVAL(SUM(CASE WHEN D.RIND='01'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL3 END)) AS COL7,
    NVAL(SUM(CASE WHEN D.RIND='03'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL3 END)) AS COL8,
    NVAL(SUM(CASE WHEN D.RIND='04'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL3 END)) AS COL9,
    NVAL(SUM(CASE WHEN D.RIND='05'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL3 END)) AS COL10,
    NVAL(SUM(CASE WHEN D.RIND='06'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL3 END)) AS COL11
   
  
  FROM
              VW_DATA_ALL D
                INNER JOIN RENIM R ON (R.CUIIO= D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
                INNER JOIN VW_CL_CUATM VC ON (VC.CODUL = R.CUATM)
                
                CROSS JOIN 

(
SELECT  V.CODUL AS CODE, V.PRGS AS PRGS, V.DENUMIRE 
AS DEN_CUATM
FROM VW_CL_CUATM V
WHERE V.FULL_CODE LIKE '%'||:pCOD_CUATM||';%' --AND  PRGS NOT IN ('2','3','4','5')
) CD

WHERE  D.PERIOADA IN (:pPERIOADA,:pPERIOADA-4) AND
       D.FORM = :pFORM AND
       D.FORM_VERS = :pFORM_VERS 
       --AND       VC.PRGS NOT IN ('2','3','4','5')
       --R.TIP_LOCAL ='1'
GROUP BY  CD.CODE , CD.DEN_CUATM

HAVING

    NVAL(SUM(CASE WHEN D.RIND='01'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END)) >0 OR
    NVAL(SUM(CASE WHEN D.RIND='03'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END)) >0 OR
    NVAL(SUM(CASE WHEN D.RIND='04'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END)) >0 OR 
    NVAL(SUM(CASE WHEN D.RIND='05'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END)) >0 OR
    NVAL(SUM(CASE WHEN D.RIND='06'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END)) >0 OR
   (NVAL(SUM(CASE WHEN D.RIND='01'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END))/
    NOZERO( NVAL(SUM(CASE WHEN D.RIND='01'  AND D.PERIOADA = :pPERIOADA-4 AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END)))  * 100) >0 OR
    NVAL(SUM(CASE WHEN D.RIND='01'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL3 END)) >0 OR
    NVAL(SUM(CASE WHEN D.RIND='03'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL3 END)) >0 OR
    NVAL(SUM(CASE WHEN D.RIND='04'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL3 END)) >0 OR
    NVAL(SUM(CASE WHEN D.RIND='05'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL3 END)) >0 OR
    NVAL(SUM(CASE WHEN D.RIND='06'  AND D.PERIOADA = :pPERIOADA AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL3 END)) >0 
   
  

ORDER BY  CD.CODE