--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,
--   
--  COL1, COL2, COL3,  COL4, COL5, COL6, COL7, COL8, COL9
--)

  SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,        
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   CD.CUATM AS NR_ROW,  
   CD.CUATM AS ORDINE,
  '111111111' AS DECIMAL_POS,
   CD.NUME_ROW AS NUME_ROW,
   NVAL(SUM(CASE WHEN D.RIND='01'  AND VC.FULL_CODE LIKE '%'||CD.CUATM||';%'  AND D.PERIOADA IN (:pPERIOADA) THEN  D.COL1 END)) AS COL1, 
   NVAL(SUM(CASE WHEN D.RIND='07'  AND VC.FULL_CODE LIKE '%'||CD.CUATM||';%'  AND D.PERIOADA IN (:pPERIOADA) THEN  D.COL1 END)) AS COL2,
   NVAL(SUM(CASE WHEN D.RIND='08'  AND VC.FULL_CODE LIKE '%'||CD.CUATM||';%'  AND D.PERIOADA IN (:pPERIOADA) THEN  D.COL1 END)) AS COL3,   
   NVAL(SUM(CASE WHEN D.RIND='09'  AND VC.FULL_CODE LIKE '%'||CD.CUATM||';%'  AND D.PERIOADA IN (:pPERIOADA) THEN  D.COL1 END)) AS COL4,
   NVAL(SUM(CASE WHEN D.RIND='01'  AND VC.FULL_CODE LIKE '%'||CD.CUATM||';%'  AND D.PERIOADA IN (:pPERIOADA) THEN  D.COL2 END)) AS COL5,
   NVAL(SUM(CASE WHEN D.RIND='07'  AND VC.FULL_CODE LIKE '%'||CD.CUATM||';%'  AND D.PERIOADA IN (:pPERIOADA) THEN  D.COL2 END)) AS COL6,
   NVAL(SUM(CASE WHEN D.RIND='08'  AND VC.FULL_CODE LIKE '%'||CD.CUATM||';%'  AND D.PERIOADA IN (:pPERIOADA) THEN  D.COL2 END)) AS COL7,
   NVAL(SUM(CASE WHEN D.RIND='09'  AND VC.FULL_CODE LIKE '%'||CD.CUATM||';%'  AND D.PERIOADA IN (:pPERIOADA) THEN  D.COL2 END)) AS COL8,
   NVAL(SUM(CASE WHEN D.RIND='01'  AND VC.FULL_CODE LIKE '%'||CD.CUATM||';%'  AND D.PERIOADA IN (:pPERIOADA) THEN  D.COL4 END)) AS COL9
  FROM
              VW_DATA_ALL D
                INNER JOIN RENIM R ON (R.CUIIO= D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
                --INNER JOIN VW_CL_CUATM VC ON (VC.CODUL = R.CUATM)
                INNER JOIN VW_CL_CUATM VC ON (VC.CODUL = R.CUATM AND VC.FULL_CODE LIKE '%'||:pCOD_CUATM||';%') 
                
                CROSS JOIN 
(   

SELECT  
    V.CODUL AS CUATM, 
    V.PRGS AS PRGS, 
    V.DENUMIRE AS NUME_ROW

FROM VW_CL_CUATM V

WHERE 
V.FULL_CODE LIKE '%'||:pCOD_CUATM||';%' 
      ) CD


WHERE  D.PERIOADA IN (:pPERIOADA) AND
       D.FORM = :pFORM AND
       D.FORM_VERS = :pFORM_VERS --AND
       
      -- VC.PRGS NOT IN ('3','4','5')
GROUP BY  
CD.NUME_ROW,
CD.CUATM
