SELECT
  D.PERIOADA,
  D.FORM,
  D.FORM_VERS,
  D.CUIIO,
  D.CUIIO_VERS,
  D.PACHET,
  MR.RIND,
  D.ID_MD,
  D.DATA_REG,
  D.ID_USER,
  D.COL1,
  D.COL2,
  D.COL3,
  D.COL4,
  D.COL5,
  D.COL6,
  D.COL7,       
  D.COL8,
  D.COL9,
  D.COL10,
  D.COL11,
  D.COL12,
  D.COL13,
  D.COL14
 

FROM CIS2.DATA_ALL_LOG D 
            INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD

WHERE 

        D.PERIOADA = 1049
AND D.FORM = 18
--AND DATA_REG >= TO_DATE('07/22/2021 10:36:08', 'MM/DD/YYYY HH24:MI:SS')

AND D.CUIIO = 39037982