--INSERT INTO  CIS2.RENIM
--
--(
--
--CUIIO,
--    CUIIO_VERS,
--    DENUMIRE,
--    EDIT_USER,
--    STATUT,
--    CUATM,
--    CFP,
--    CFOJ,
--    COCM,
--    CAEM,
--    BUGET,
--    TIP,
--    PROD,
--    FOR_CUB,
--    GENMUZEE,
--    TIPMUZEE,
--    TIP_LOCAL,
--    TIP_INST,
--    CAEM2,
--    N85_NTL,
--    N85_NTIIP,
--    N85_NDIIP,
--    N85_NPDS,
--    N85_NRIIP,
--    N85_NSIIP,
--    GENMUZEE2,
--    NFI,
--    NTII,
--    NPDS,
--    ORGANE,
--    TIP_INV,
--    RENIM_PERS,
--    ORGANE_COND,
--    GEN_INSTITUTIE
--)


SELECT 
    CUIIO,
    CUIIO_VERS,
    DENUMIRE,
    EDIT_USER,
    STATUT,
    CUATM,
    CFP,
    CFOJ,
    COCM,
    CAEM,
    BUGET,
    TIP,
    PROD,
    FOR_CUB,
    GENMUZEE,
    TIPMUZEE,
    TIP_LOCAL,
    TIP_INST,
    CAEM2,
    N85_NTL,
    N85_NTIIP,
    N85_NDIIP,
    N85_NPDS,
    N85_NRIIP,
    N85_NSIIP,
    GENMUZEE2,
    NFI,
    NTII,
    NPDS,
    ORGANE,
    TIP_INV,
    RENIM_PERS,
    ORGANE_COND,
    GEN_INSTITUTIE

FROM USER_BANCU.VW_MAX_RENIM_CIS2  
--USER_BANCU.VW_MAX_RENIM_299_CIS2
       --  USER_BANCU.VW_MAX_RENIM_TRIM_CIS2
WHERE 

CUIIO IN (

SELECT 
L.CUIIO 
FROM USER_BANCU.VW_KATALOG_EI_78_1047 L 

        LEFT   JOIN  USER_BANCU.VW_KATALOG_EI_78_2009 R ON R.CUIIO = L.CUIIO 
        
        
        WHERE 
        
        R.CUIIO IS NULL 
) 

AND CUIIO_VERS =   2009
--AND CUIIO <> 7028102