SELECT 
   
    CC.CODUL,
    CC.DENUMIRE DENUMIRE_CAEM2,
    MR.RIND,
    MR.DENUMIRE,
    SUM(D.COL1) AS COL1,
    SUM(D.COL2) AS COL2,
    SUM(NVAL(D.COL2) + NVAL(D.COL1)) AS COL3
   
   
   FROM CIS.VW_DATA_ALL D 
       
        INNER JOIN CIS.MD_RIND MR ON (MR.ID_MD = D.ID_MD)   
           
        
        INNER JOIN CIS.VW_CL_CAEM2 C ON (C.CODUL = D.CAEM2)
        INNER JOIN CIS.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
    


 WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  D.PERIOADA  IN (1035,1032,1033,1034)  AND 
  D.FORM = 6 AND
  D.CAPITOL = 31 
  
  AND CC.CODUL LIKE  '%0000'


  
  GROUP BY 
  
  CC.CODUL,
  CC.DENUMIRE,
  CC.FULL_CODE,
  MR.RIND,
  MR.DENUMIRE
  
  ORDER BY 
  CC.FULL_CODE,
  MR.RIND