SELECT 
    D.CUIIO,
    D.CUATM,
    MAX(R.DENUMIRE) DENUMIRE,
    D.CAEM2,
    C.DENUMIRE DEN_CAEM2,
    SUM(NVAL(D.COL1)) AS COL1
   
    FROM CIS.VW_DATA_ALL D 
         INNER JOIN CIS.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
         INNER JOIN CIS.VW_CL_CAEM2 C ON (C.CODUL = R.CAEM2)
                  
        
           
 WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  D.PERIOADA  IN (1035)  AND 
  D.FORM = 6 AND
  D.CAPITOL = 31 
  AND D.RIND IN ('100')
--  AND CC.CODUL LIKE '96%'
 -- AND CC.CODUL IN ('9600000')--,'9601000','9602000','9603000')
  AND D.CAEM2 LIKE 'C%'
 -- AND D.CUATM 
-- AND D.CUIIO IN (40598674)
  
  GROUP BY 
  D.CUIIO,
  --R.DENUMIRE,
  D.CUATM,
  D.CAEM2,
  C.DENUMIRE
  
   
  ORDER BY 
  D.CUIIO
  