INSERT INTO TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,
  
  COL1, COL2, COL3,  COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14, COL15, COL16, COL17, COL18, COL19
)
----------------------------------------------------------------
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  
         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  NR_ROW,
  ROWNUM AS ORDINE,
  '0000000000000000000' AS DECIMAL_POS,
  NUME_ROW,
  COL1,
  COL2,
  COL3,
  COL4,
  COL5,
  COL6,
  COL7,
  COL8,
  COL9,
  COL10,
  COL11,
  COL12,
  COL13,
  COL14,
  COL15,
  COL16,
  COL17,
  COL18,
  COL19
FROM
(
SELECT 
  D.CUIIO||'~'||MAX(D.CAEM2_CURENT)||'_'||MAX(D.CAEM2_PRECEDENT) AS NR_ROW,
  MAX(RN.DENUMIRE) AS NUME_ROW,
  MAX(D.CAEM2_CURENT) AS COL1,
  MAX(D.CAEM2_PRECEDENT) AS COL2,
  MAX(D.CUATM_CURENT) AS COL3,
  MAX(D.CFP_CURENT) AS COL4,
  MAX(D.BUGET_CURENT) AS COL5,
  D.RIND,
  SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND LIKE '%T' AND D.CAPITOL IN (301) AND COL=1 THEN VAL ELSE NULL END) COL6,
  SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-1) AND D.RIND LIKE '%T' AND D.CAPITOL IN (301) AND COL=1 THEN VAL ELSE NULL END) COL7,
  SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND LIKE '%T' AND D.CAPITOL IN (301) AND COL=2 THEN VAL ELSE NULL END) COL8,
  SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-1) AND D.RIND LIKE '%T' AND D.CAPITOL IN (301) AND COL=2 THEN VAL ELSE NULL END) COL9,
  SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND LIKE '%T' AND D.CAPITOL IN (302) AND COL=1 THEN VAL ELSE NULL END) COL10,
  SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-1) AND D.RIND LIKE '%T' AND D.CAPITOL IN (302) AND COL=1 THEN VAL ELSE NULL END) COL11,
  SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND LIKE '%T' AND D.CAPITOL IN (302) AND COL=2 THEN VAL ELSE NULL END) COL12,
  SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-1) AND D.RIND LIKE '%T' AND D.CAPITOL IN (302) AND COL=2 THEN VAL ELSE NULL END) COL13,
  SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND LIKE '%T' AND D.CAPITOL IN (302) AND COL=3 THEN VAL ELSE NULL END) COL14,
  SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-1) AND D.RIND LIKE '%T' AND D.CAPITOL IN (302) AND COL=3 THEN VAL ELSE NULL END) COL15,
  SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND LIKE '%T' AND D.CAPITOL IN (302) AND COL=4 THEN VAL ELSE NULL END) COL16,
  SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-1) AND D.RIND LIKE '%T' AND D.CAPITOL IN (302) AND COL=4 THEN VAL ELSE NULL END) COL17,
  SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND LIKE '%T' AND D.CAPITOL IN (302) AND COL=5 THEN VAL ELSE NULL END) COL18,
  SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-1) AND D.RIND LIKE '%T' AND D.CAPITOL IN (302) AND COL=5 THEN VAL ELSE NULL END) COL19
FROM
(
-------------------------------------------------------------------------------
SELECT DISTINCT
  D.PERIOADA,
  D.CUIIO,
  D.CUIIO_VERS,
  MAX(CASE WHEN D.PERIOADA IN(:pPERIOADA) THEN D.CUATM END) AS CUATM_CURENT,
  MAX(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) THEN D.CUATM END) AS CUATM_PRECEDENT,
  D.FILIAL,
  D.CAPITOL,
  D.CAPITOL_DEN,
  D.CUATM_FULL,
  MAX(CASE WHEN D.PERIOADA IN(:pPERIOADA) THEN D.CFP END) AS CFP_CURENT,
  MAX(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) THEN D.CFP END) AS CFP_PRECEDENT,
  MAX(CASE WHEN D.PERIOADA IN(:pPERIOADA) THEN D.BUGET END) AS BUGET_CURENT,
  MAX(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) THEN D.BUGET END) AS BUGET_PRECEDENT,
  C.COL-1 AS COL,
  CASE WHEN D.RIND LIKE '%T' AND S.SEX LIKE 'F' THEN SUBSTR(D.RIND,1,3)||'F' ELSE D.RIND END AS RIND, 
  MAX(CASE WHEN D.RIND LIKE '01%' AND D.PERIOADA IN (:pPERIOADA) THEN TO_NUMBER(SUBSTR(D.CAEM2,2,5))
           WHEN D.RIND LIKE '01%' AND D.PERIOADA IN (:pPERIOADA-1) THEN TO_NUMBER(SUBSTR(D.CAEM2,2,5)) 
           WHEN D.PERIOADA IN (:pPERIOADA-1) THEN D.COL1 
           WHEN D.PERIOADA IN (:pPERIOADA) THEN D.COL1 END) AS CAEM2_CURENT,
  MAX(CASE WHEN D.RIND LIKE '01%' AND D.PERIOADA IN (:pPERIOADA-1) THEN TO_NUMBER(SUBSTR(D.CAEM2,2,5)) WHEN D.PERIOADA IN (:pPERIOADA-1) THEN D.COL1 END) AS CAEM2_PRECEDENT,
  SUM(CASE WHEN D.RIND LIKE '%'||S.SEX THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2, 3,D.COL3, 4,D.COL4, 5,D.COL5, 6,D.COL6, 7,D.COL7, 8,D.COL8, 9,D.COL9, 10,D.COL10, 11,D.COL11, NULL) ELSE NULL END) AS VAL
FROM 
  VW_DATA_ALL D,
  (
    SELECT  2 AS COL FROM DUAL UNION
    SELECT  3 AS COL FROM DUAL UNION
    SELECT  4 AS COL FROM DUAL UNION
    SELECT  5 AS COL FROM DUAL UNION
    SELECT  6 AS COL FROM DUAL UNION
    SELECT  7 AS COL FROM DUAL UNION
    SELECT  8 AS COL FROM DUAL UNION
    SELECT  9 AS COL FROM DUAL UNION
    SELECT 10 AS COL FROM DUAL UNION
    SELECT 11 AS COL FROM DUAL
  ) C,
  (
    SELECT 'T' AS SEX FROM DUAL UNION
    SELECT 'F' AS SEX FROM DUAL
  ) S
WHERE
  (D.PERIOADA IN (:pPERIOADA, :pPERIOADA-1)) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  
  (:pID_MDTABLE=:pID_MDTABLE) AND
  
  D.FORM = 3 AND
  D.CAPITOL IN(301) 
--  AND
--  D.CUIIO IN (9202,20379214)
GROUP BY
  D.PERIOADA,
  D.CUIIO,
  D.CUIIO_VERS,
  D.FILIAL,
  D.CAPITOL,
  D.CUATM_FULL,
  D.CAPITOL_DEN,
  C.COL,
  CASE WHEN D.RIND LIKE '%T' AND S.SEX LIKE 'F' THEN SUBSTR(D.RIND,1,3)||'F' ELSE D.RIND END
  

UNION
    
   
SELECT DISTINCT
    D.PERIOADA,
    D.CUIIO,
    D.CUIIO_VERS,
    MAX(CASE WHEN D.PERIOADA IN(:pPERIOADA) THEN D.CUATM END) AS CUATM_CURENT,
    MAX(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) THEN D.CUATM END) AS CUATM_PRECEDENT,
    D.FILIAL,
    D.CAPITOL,
    D.CAPITOL_DEN,
    D.CUATM_FULL,
    MAX(CASE WHEN D.PERIOADA IN(:pPERIOADA) THEN D.CFP END) AS CFP_CURENT,
    MAX(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) THEN D.CFP END) AS CFP_PRECEDENT,
    MAX(CASE WHEN D.PERIOADA IN(:pPERIOADA) THEN D.BUGET END) AS BUGET_CURENT,
    MAX(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) THEN D.BUGET END) AS BUGET_PRECEDENT,
    TO_NUMBER(D.RIND) AS COL,
    '01-T' AS RIND,
    MAX(CASE WHEN D.PERIOADA IN (:pPERIOADA) THEN TO_NUMBER(SUBSTR(D.CAEM2,2,5))
             WHEN D.PERIOADA IN (:pPERIOADA-1) THEN TO_NUMBER(SUBSTR(D.CAEM2,2,5)) END) AS CAEM2_CURENT,
    MAX(CASE WHEN D.PERIOADA IN (:pPERIOADA-1) THEN TO_NUMBER(SUBSTR(D.CAEM2,2,5)) END) AS CAEM2_PRECEDENT,
    SUM(DECODE(D.RIND, 1,D.COL1, 2,D.COL1, 3,D.COL1, 4,D.COL1, 5,D.COL1, NULL)) AS VAL
FROM
    VW_DATA_ALL D
WHERE
  (D.PERIOADA IN (:pPERIOADA, :pPERIOADA-1)) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  
  D.FORM = 3 AND
  D.CAPITOL IN(302) AND
  D.RIND IN ('1','2','3','4','5')
--  AND
--  D.CUIIO IN (9202,20379214)
GROUP BY
    D.PERIOADA,
    D.CUIIO,
    D.CUIIO_VERS,
    D.FILIAL,
    D.CAPITOL,
    D.CAPITOL_DEN,
    D.CUATM_FULL,
    D.RIND
-------------------------------------------------------------------------------
) D 
--  INNER JOIN VW_CL_CAEM2 C  ON(D.CAEM2=C.NUM_CODE)
--  INNER JOIN VW_CL_CAEM2 CR ON(C.FULL_CODE LIKE '%'||CR.CODUL||';%') 
  INNER JOIN RENIM RN ON (RN.CUIIO=D.CUIIO AND RN.CUIIO_VERS = D.CUIIO_VERS)
WHERE 
  D.FILIAL = '0' AND
  (D.CAEM2_CURENT <> '0' OR
  D.CAEM2_PRECEDENT <> '0') AND
  (D.RIND LIKE '%T' --OR RIND IN ('1','2','3','4','5')
  )  AND D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' 

GROUP BY
  D.CUIIO,
  D.RIND,
  D.CAEM2_CURENT
--  D.CAEM2_PRECEDENT
--  D.FILIAL
ORDER BY
  D.CUIIO
)