DECLARE

  CURSOR C IS

SELECT 
    DF.PERIOADA,
    DF.FORM,
    DF.FORM_VERS,
    DF.ID_MDTABLE,
    DF.COD_CUATM,
    DF.NR_SECTIE,
    DF.NUME_SECTIE,
    DF.NR_SECTIE1,
    DF.NUME_SECTIE1,
    DF.NR_SECTIE2,
    DF.NUME_SECTIE2,
    DF.NR_ROW NR_ROW,
    DF.ORDINE,
    DF.DECIMAL_POS,
    DF.NUME_ROW,
    DF.COL1,
    DF.COL2,
    DF.COL3,
    DF.COL4,
    DF.COL5,
    DF.COL6,
    DF.COL7,
    DF.COL8,
    DF.COL9,
    DF.COL10,
    DF.COL11,
    DF.COL12,
    DF.COL13,
    DF.COL14,
    DF.COL15,
    DF.COL16,
    DF.COL17,
    DF.COL18,
    DF.COL19
    
    FROM 
(
----------------------------------------------------------------
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  
         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  CAEM2||'~'||CUIIO||'_'||FILIAL AS NR_ROW,
 
    
    
   ROWNUM AS ORDINE,
  '0000000011111111111' AS DECIMAL_POS,
   DENUMIRE AS NUME_ROW, 
    CUIIO AS COL1,
    CUATM AS COL2,
    CFP AS COL3,
    FILIAL AS COL4, 
    PACHET AS COL5,
    BUGET AS COL6,
    TIP_CAEM AS COL7,
    ROUND(COL1,0) AS COL8,
    ROUND(COL2,1) AS COL9,
    ROUND(COL3,1) AS COL10,
    ROUND(COL4,1) AS COL11,
    ROUND(COL5,1) AS COL12,
    ROUND(COL6,1) AS COL13,
    ROUND(COL7,1) AS COL14,
    ROUND(COL8,1) AS COL15,
    ROUND(COL9,1) AS COL16,
    ROUND(COL10,1) AS COL17,
    ROUND(COL11,1) AS COL18,
    ROUND(COL12,0) AS COL19
FROM
(
SELECT 
  CR.CODUL AS CAEM2,
  RN.DENUMIRE,
  D.CUIIO AS CUIIO,
  D.CUATM AS CUATM,
  D.CFP AS CFP, 
  D.FILIAL,
 MAX (D.PACHET) AS PACHET ,
  D.BUGET,
  MAX(CASE WHEN CR.CODUL LIKE '00000' THEN 1 ELSE TIP_CAEM END) AS TIP_CAEM,
  SUM(CASE WHEN COL=1 THEN VAL ELSE NULL END) COL1,
  SUM(NVAL(CASE WHEN COL=3 THEN VAL ELSE NULL END)+NVAL(CASE WHEN COL=5 THEN VAL ELSE NULL END)) COL2,
  SUM(CASE WHEN COL=3 THEN VAL ELSE NULL END) COL3,
  SUM(CASE WHEN COL=4 THEN VAL ELSE NULL END) COL4,
  SUM(CASE WHEN COL=5 THEN VAL ELSE NULL END) COL5,
  SUM(NVAL(CASE WHEN COL=6 THEN VAL ELSE NULL END)+NVAL(CASE WHEN COL=7 THEN VAL ELSE NULL END)) COL6,
  SUM(CASE WHEN COL=6 THEN VAL ELSE NULL END) COL7,
  SUM(CASE WHEN COL=7 THEN VAL ELSE NULL END) COL8,
  SUM(NVAL(CASE WHEN COL=8 THEN VAL ELSE NULL END)+NVAL(CASE WHEN COL=9 THEN VAL ELSE NULL END)) COL9,
  SUM(CASE WHEN COL=8 THEN VAL ELSE NULL END) COL10,
  SUM(CASE WHEN COL=9 THEN VAL ELSE NULL END) COL11,
 SUM(CASE WHEN COL=10 THEN VAL ELSE NULL END) COL12
 

  
  
FROM
(
-------------------------------------------------------------------------------
SELECT DISTINCT
  D.CUIIO,
  D.CUIIO_VERS,
  D.CUATM,
  D.FILIAL,
  D.CAPITOL,
  D.CAPITOL_DEN,
  D.CUATM_FULL,
  D.CFP,
  MAX(D.PACHET) PACHET,
  D.BUGET,
  C.COL-1 AS COL,
  CASE WHEN D.RIND LIKE '%T' AND S.SEX LIKE 'F' THEN SUBSTR(D.RIND,1,3)||'F' ELSE D.RIND END AS RIND, 
  MAX(CASE WHEN D.RIND LIKE '00%' THEN 0 WHEN D.RIND LIKE '01%' THEN TO_NUMBER(SUBSTR(D.CAEM2,2,5)) ELSE D.COL1 END) AS CAEM2,
  MAX(CASE WHEN D.RIND LIKE '00%' THEN 1 WHEN D.RIND LIKE '01%' THEN 2 ELSE 3 END) AS TIP_CAEM,
  SUM(CASE WHEN D.RIND LIKE '%'||S.SEX THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2, 3,D.COL3, 4,D.COL4, 5,D.COL5, 6,D.COL6, 7,D.COL7, 8,D.COL8, 9,D.COL9, 10,D.COL10, 11,D.COL11, NULL) ELSE NULL END) AS VAL
FROM 
  VW_DATA_ALL D,
  (
    SELECT  2 AS COL FROM DUAL UNION
    SELECT  3 AS COL FROM DUAL UNION
    SELECT  4 AS COL FROM DUAL UNION
    SELECT  5 AS COL FROM DUAL UNION
    SELECT  6 AS COL FROM DUAL UNION
    SELECT  7 AS COL FROM DUAL UNION
    SELECT  8 AS COL FROM DUAL UNION
    SELECT  9 AS COL FROM DUAL UNION
    SELECT 10 AS COL FROM DUAL UNION
    SELECT 11 AS COL FROM DUAL
  ) C,
  (
    SELECT 'T' AS SEX FROM DUAL UNION
    SELECT 'F' AS SEX FROM DUAL
  ) S
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  
  (:pID_MDTABLE=:pID_MDTABLE) AND
  
  D.FORM = 3 AND
  D.CAPITOL IN(301) 
--  AND
--  D.CUIIO IN (1587378)
GROUP BY
  D.CUIIO,
  D.CUIIO_VERS,
  D.CUATM,
  D.FILIAL,
  D.CAPITOL,
  D.CUATM_FULL,
  D.CAPITOL_DEN,
  D.CFP,
--  D.PACHET,
  D.BUGET,
  C.COL,
  CASE WHEN D.RIND LIKE '%T' AND S.SEX LIKE 'F' THEN SUBSTR(D.RIND,1,3)||'F' ELSE D.RIND END
UNION
SELECT DISTINCT
    D.CUIIO,
    D.CUIIO_VERS,
    D.CUATM,
    D.FILIAL,
    D.CAPITOL,
    D.CAPITOL_DEN,
    D.CUATM_FULL,
    D.CFP,
    MAX(D.PACHET) PACHET,
    D.BUGET,
    NULL AS COL,
    D.RIND AS RIND,
    TO_NUMBER(SUBSTR(D.CAEM2,2,5)) AS CAEM2,
    2 AS TIP_CAEM,
    SUM(DECODE(D.RIND, 1,D.COL1, 2,D.COL1, 3,D.COL1, 4,D.COL1, 5,D.COL1, NULL)) AS VAL
FROM
    VW_DATA_ALL D
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  
  (:pID_MDTABLE=:pID_MDTABLE) AND
  
  D.FORM = 3 AND
  D.CAPITOL IN(302,100) AND
  D.RIND IN ('1','2','3','4','5') 
--  AND
--  D.CUIIO IN (1587378)
GROUP BY
  D.CUIIO,
  D.CUIIO_VERS,
  D.CUATM,
  D.FILIAL,
  D.CAEM2,
  D.CUATM_FULL,
  D.CAPITOL,
  D.CAPITOL_DEN,
  D.CFP,
 -- D.PACHET,
  D.BUGET,
  D.RIND
-------------------------------------------------------------------------------
) D 
  INNER JOIN VW_CL_CAEM2 C  ON(D.CAEM2=C.NUM_CODE)
  INNER JOIN VW_CL_CAEM2 CR ON(C.FULL_CODE LIKE '%'||CR.CODUL||';%') 
  INNER JOIN RENIM RN ON (RN.CUIIO=D.CUIIO AND RN.CUIIO_VERS = D.CUIIO_VERS)
WHERE 
  D.CAEM2 <> '0' AND 
--  FILIAL = '0' AND
  (RIND LIKE '%T' OR RIND IN ('1','2','3','4','5'))  AND D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  (CR.CODUL LIKE '00000' OR (C.CODUL=CR.CODUL))
GROUP BY
  RN.DENUMIRE,
  CR.CODUL,
  D.CUIIO,
  D.CUATM,
  D.CFP,
  D.FILIAL,
 -- D.PACHET,
  D.BUGET
ORDER BY
  CUIIO,
  CUATM,
  CAEM2
)


 ) DF
  
  ;
  
  BEGIN

  FOR CR IN C
  
  LOOP
    INSERT INTO  -- USER_BANCU.TABLE_OUT_TEST 
    
     CIS2.TABLE_OUT
    (
      PERIOADA,
      FORM,
      FORM_VERS,

      ID_MDTABLE,
      COD_CUATM,
      NR_SECTIE,
      NUME_SECTIE,
      NR_SECTIE1,
      NUME_SECTIE1,
      NR_SECTIE2,
      NUME_SECTIE2,
      NR_ROW,
      ORDINE,
      DECIMAL_POS,
      NUME_ROW,
       
     COL1, COL2, COL3,  COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14, COL15, COL16, COL17, COL18, COL19
    )
    VALUES
    (
      CR.PERIOADA,
      CR.FORM,
      CR.FORM_VERS,
      CR.ID_MDTABLE,
      CR.COD_CUATM,
      CR.NR_SECTIE,
      CR.NUME_SECTIE,
      CR.NR_SECTIE1,
      CR.NUME_SECTIE1,
      CR.NR_SECTIE2,
      CR.NUME_SECTIE2,
      CR.NR_ROW,
      CR.ORDINE,
      CR.DECIMAL_POS,
      CR.NUME_ROW,
       
      CR.COL1, CR.COL2, CR.COL3, CR.COL4, CR.COL5,  CR.COL6,  CR.COL7,  CR.COL8 ,  CR.COL9, CR.COL10, CR.COL11, CR.COL12, CR.COL13, CR.COL14, CR.COL15, CR.COL16, CR.COL17, CR.COL18, CR.COL19
    );
  END LOOP;
END;