INSERT INTO TABLE_OUT
  (PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,   
  COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13)
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  CODUL AS NR_ROW,
  '0' AS ORDINE,
  '0000000000000' AS DECIMAL_POS,
  DENUMIRE AS NUME_ROW,
  ROUND(SUM(COL1),0) AS COL1,
  ROUND(SUM(COL2),0) AS COL2,
  ROUND(SUM(COL3),0) AS COL3,
  ROUND(SUM(COL4),0) AS COL4,
  ROUND(SUM(COL5),0) AS COL5,
  ROUND(SUM(COL6),0) AS COL6,
  ROUND(SUM(COL7),0) AS COL7,
  ROUND(SUM(COL8),0) AS COL8,
  ROUND(SUM(COL9),0) AS COL9,
  ROUND(SUM(COL10),0) AS COL10,
  ROUND(SUM(COL11),0) AS COL11,
  ROUND(SUM(COL12),0) AS COL12,
  ROUND(SUM(COL13),0) AS COL13
FROM
(
SELECT
  CG.CODUL,
  CG.DENUMIRE,
      
  SUM(CASE WHEN RIND IN ('10') THEN D.COL1 ELSE NULL END) AS COL1,
  SUM(CASE WHEN RIND IN ('20') THEN D.COL1 ELSE NULL END) AS COL2,
  SUM(CASE WHEN RIND IN ('21') THEN D.COL1 ELSE NULL END) AS COL3,
  SUM(CASE WHEN RIND IN ('22') THEN D.COL1 ELSE NULL END) AS COL4,
  SUM(CASE WHEN RIND IN ('30') THEN D.COL1 ELSE NULL END) AS COL5,
  SUM(CASE WHEN RIND IN ('40') THEN D.COL1 ELSE NULL END) AS COL6,
  SUM(CASE WHEN RIND IN ('41') THEN D.COL1 ELSE NULL END) AS COL7,
  SUM(CASE WHEN RIND IN ('42') THEN D.COL1 ELSE NULL END) AS COL8,
  SUM(CASE WHEN RIND IN ('43') THEN D.COL1 ELSE NULL END) AS COL9,
  SUM(CASE WHEN RIND IN ('50') THEN D.COL1 ELSE NULL END) AS COL10,
  SUM(CASE WHEN RIND IN ('60') THEN D.COL1 ELSE NULL END) AS COL11,
  SUM(CASE WHEN RIND IN ('61') THEN D.COL1 ELSE NULL END) AS COL12,
  COUNT(DISTINCT D.CUIIO) AS COL13

FROM CIS.VW_DATA_ALL_COEF D
  INNER JOIN CIS.VW_CL_CAEM2 C ON (D.CAEM2=C.CODUL)
  INNER JOIN CIS.VW_CL_CAEM2 CG ON (C.FULL_CODE LIKE '%'||CG.CODUL||';%')-- AND LENGTH(CG.FULL_CODE) <= (6+6+6))

WHERE 
  PERIOADA = :pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND 
  FORM = 11 AND
  CAPITOL IN (95) AND
  CG.CODUL LIKE '%00' AND
  D.CAEM2 NOT LIKE 'O84%' AND D.CD > 0 
  AND D.CUIIO IN (SELECT DISTINCT
                  D.CUIIO
                FROM
                  VW_DATA_ALL_COEF D
                  INNER JOIN MD_PERIOADA P ON P.ANUL = D.ANUL AND P.PERIOADA IN (:pPERIOADA)
                WHERE
                  D.NUM IN 12 AND
                  D.FORM IN (5) AND
                  D.CAPITOL IN (0) AND
                  D.RIND IN ('CM'))
GROUP BY
  CG.CODUL,
  CG.DENUMIRE
--ORDER BY
--  CG.CODUL
  
UNION

SELECT
  CG.CODUL,
  CG.DENUMIRE,
      
  SUM(CASE WHEN RIND IN ('10') THEN D.COL2 ELSE NULL END) AS COL1,
  SUM(CASE WHEN RIND IN ('20') THEN D.COL2 ELSE NULL END) AS COL2,
  SUM(CASE WHEN RIND IN ('21') THEN D.COL2 ELSE NULL END) AS COL3,
  SUM(CASE WHEN RIND IN ('22') THEN D.COL2 ELSE NULL END) AS COL4,
  SUM(CASE WHEN RIND IN ('30') THEN D.COL2 ELSE NULL END) AS COL5,
  SUM(CASE WHEN RIND IN ('40') THEN D.COL2 ELSE NULL END) AS COL6,
  SUM(CASE WHEN RIND IN ('41') THEN D.COL2 ELSE NULL END) AS COL7,
  SUM(CASE WHEN RIND IN ('42') THEN D.COL2 ELSE NULL END) AS COL8,
  SUM(CASE WHEN RIND IN ('43') THEN D.COL2 ELSE NULL END) AS COL9,
  SUM(CASE WHEN RIND IN ('50') THEN D.COL2 ELSE NULL END) AS COL10,
  SUM(CASE WHEN RIND IN ('60') THEN D.COL2 ELSE NULL END) AS COL11,
  SUM(CASE WHEN RIND IN ('61') THEN D.COL2 ELSE NULL END) AS COL12,
  COUNT(DISTINCT D.CUIIO) AS COL13

FROM CIS.VW_DATA_ALL_COEF D
  INNER JOIN CIS.VW_CL_CAEM2 C ON (D.CAEM2=C.CODUL)
  INNER JOIN CIS.VW_CL_CAEM2 CG ON (C.FULL_CODE LIKE '%'||CG.CODUL||';%')-- AND LENGTH(CG.FULL_CODE) <= (6+6+6))

WHERE 
  PERIOADA = :pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND 
  FORM = 11 AND
  CAPITOL IN (95) AND
  CG.CODUL LIKE '%00' AND
  D.CAEM2 LIKE 'O84%' AND D.CD > 0
  AND D.CUIIO IN (SELECT DISTINCT
                  D.CUIIO
                FROM
                  VW_DATA_ALL_COEF D
                  INNER JOIN MD_PERIOADA P ON P.ANUL = D.ANUL AND P.PERIOADA IN (:pPERIOADA)
                WHERE
                  D.NUM IN 12 AND
                  D.FORM IN (5) AND
                  D.CAPITOL IN (0) AND
                  D.RIND IN ('CM'))
GROUP BY
  CG.CODUL,
  CG.DENUMIRE
--ORDER BY
--  CG.CODUL

UNION

SELECT
  CG.CODUL,
  CG.DENUMIRE,
  SUM(COL1) AS COL1,
  SUM(COL2) AS COL2,
  SUM(COL3) AS COL3,
  SUM(COL4) AS COL4,
  SUM(COL5) AS COL5,
  SUM(COL6) AS COL6,
  SUM(COL7) AS COL7,
  SUM(COL8) AS COL8,
  SUM(COL9) AS COL9,
  SUM(COL10) AS COL10,
  SUM(COL11) AS COL11,
  SUM(COL12) AS COL12,
  SUM(COL13) AS COL13  
FROM
(
SELECT
  'P8500' AS CAEM2,
  --CG.DENUMIRE,
  SUM(CASE WHEN RIND IN ('10') THEN D.COL3 ELSE NULL END) AS COL1,
  SUM(CASE WHEN RIND IN ('20') THEN D.COL3 ELSE NULL END) AS COL2,
  SUM(CASE WHEN RIND IN ('21') THEN D.COL3 ELSE NULL END) AS COL3,
  SUM(CASE WHEN RIND IN ('22') THEN D.COL3 ELSE NULL END) AS COL4,
  SUM(CASE WHEN RIND IN ('30') THEN D.COL3 ELSE NULL END) AS COL5,
  SUM(CASE WHEN RIND IN ('40') THEN D.COL3 ELSE NULL END) AS COL6,
  SUM(CASE WHEN RIND IN ('41') THEN D.COL3 ELSE NULL END) AS COL7,
  SUM(CASE WHEN RIND IN ('42') THEN D.COL3 ELSE NULL END) AS COL8,
  SUM(CASE WHEN RIND IN ('43') THEN D.COL3 ELSE NULL END) AS COL9,
  SUM(CASE WHEN RIND IN ('50') THEN D.COL3 ELSE NULL END) AS COL10,
  SUM(CASE WHEN RIND IN ('60') THEN D.COL3 ELSE NULL END) AS COL11,
  SUM(CASE WHEN RIND IN ('61') THEN D.COL3 ELSE NULL END) AS COL12,
  0 AS COL13

FROM CIS.VW_DATA_ALL_COEF D
  
WHERE 
  PERIOADA = :pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND 
  FORM = 11 AND
  CAPITOL IN (95) AND
  D.CAEM2 LIKE 'O84%' AND D.CD > 0
  AND D.CUIIO IN (SELECT DISTINCT
                  D.CUIIO
                FROM
                  VW_DATA_ALL_COEF D
                  INNER JOIN MD_PERIOADA P ON P.ANUL = D.ANUL AND P.PERIOADA IN (:pPERIOADA)
                WHERE
                  D.NUM IN 12 AND
                  D.FORM IN (5) AND
                  D.CAPITOL IN (0) AND
                  D.RIND IN ('CM'))
GROUP BY
  D.CAEM2
) D
  INNER JOIN CIS.VW_CL_CAEM2 C ON (D.CAEM2=C.CODUL)
  INNER JOIN CIS.VW_CL_CAEM2 CG ON (C.FULL_CODE LIKE '%'||CG.CODUL||';%')
GROUP BY
  CG.CODUL,
  CG.DENUMIRE
--ORDER BY
--  CG.CODUL

UNION

SELECT
  CG.CODUL,
  CG.DENUMIRE,
  SUM(COL1) AS COL1,
  SUM(COL2) AS COL2,
  SUM(COL3) AS COL3,
  SUM(COL4) AS COL4,
  SUM(COL5) AS COL5,
  SUM(COL6) AS COL6,
  SUM(COL7) AS COL7,
  SUM(COL8) AS COL8,
  SUM(COL9) AS COL9,
  SUM(COL10) AS COL10,
  SUM(COL11) AS COL11,
  SUM(COL12) AS COL12,
  SUM(COL13) AS COL13  
FROM
(
SELECT
  'R9000' AS CAEM2,
  --CG.DENUMIRE,
  SUM(CASE WHEN RIND IN ('10') THEN D.COL4 ELSE NULL END) AS COL1,
  SUM(CASE WHEN RIND IN ('20') THEN D.COL4 ELSE NULL END) AS COL2,
  SUM(CASE WHEN RIND IN ('21') THEN D.COL4 ELSE NULL END) AS COL3,
  SUM(CASE WHEN RIND IN ('22') THEN D.COL4 ELSE NULL END) AS COL4,
  SUM(CASE WHEN RIND IN ('30') THEN D.COL4 ELSE NULL END) AS COL5,
  SUM(CASE WHEN RIND IN ('40') THEN D.COL4 ELSE NULL END) AS COL6,
  SUM(CASE WHEN RIND IN ('41') THEN D.COL4 ELSE NULL END) AS COL7,
  SUM(CASE WHEN RIND IN ('42') THEN D.COL4 ELSE NULL END) AS COL8,
  SUM(CASE WHEN RIND IN ('43') THEN D.COL4 ELSE NULL END) AS COL9,
  SUM(CASE WHEN RIND IN ('50') THEN D.COL4 ELSE NULL END) AS COL10,
  SUM(CASE WHEN RIND IN ('60') THEN D.COL4 ELSE NULL END) AS COL11,
  SUM(CASE WHEN RIND IN ('61') THEN D.COL4 ELSE NULL END) AS COL12,
  0 AS COL13

FROM CIS.VW_DATA_ALL_COEF D
  
WHERE 
  PERIOADA = :pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND 
  FORM = 11 AND
  CAPITOL IN (95) AND
  D.CAEM2 LIKE 'O84%' AND D.CD > 0
  AND D.CUIIO IN (SELECT DISTINCT
                  D.CUIIO
                FROM
                  VW_DATA_ALL_COEF D
                  INNER JOIN MD_PERIOADA P ON P.ANUL = D.ANUL AND P.PERIOADA IN (:pPERIOADA)
                WHERE
                  D.NUM IN 12 AND
                  D.FORM IN (5) AND
                  D.CAPITOL IN (0) AND
                  D.RIND IN ('CM'))
GROUP BY
  D.CAEM2
) D
  INNER JOIN CIS.VW_CL_CAEM2 C ON (D.CAEM2=C.CODUL)
  INNER JOIN CIS.VW_CL_CAEM2 CG ON (C.FULL_CODE LIKE '%'||CG.CODUL||';%')
GROUP BY
  CG.CODUL,
  CG.DENUMIRE
--ORDER BY
--  CG.CODUL
UNION

SELECT
  CG.CODUL,
  CG.DENUMIRE,
  SUM(COL1) AS COL1,
  SUM(COL2) AS COL2,
  SUM(COL3) AS COL3,
  SUM(COL4) AS COL4,
  SUM(COL5) AS COL5,
  SUM(COL6) AS COL6,
  SUM(COL7) AS COL7,
  SUM(COL8) AS COL8,
  SUM(COL9) AS COL9,
  SUM(COL10) AS COL10,
  SUM(COL11) AS COL11,
  SUM(COL12) AS COL12,
  SUM(COL13) AS COL13  
FROM
(
SELECT
  'Q8800' AS CAEM2,
  --CG.DENUMIRE,
  SUM(CASE WHEN RIND IN ('10') THEN D.COL5 ELSE NULL END) AS COL1,
  SUM(CASE WHEN RIND IN ('20') THEN D.COL5 ELSE NULL END) AS COL2,
  SUM(CASE WHEN RIND IN ('21') THEN D.COL5 ELSE NULL END) AS COL3,
  SUM(CASE WHEN RIND IN ('22') THEN D.COL5 ELSE NULL END) AS COL4,
  SUM(CASE WHEN RIND IN ('30') THEN D.COL5 ELSE NULL END) AS COL5,
  SUM(CASE WHEN RIND IN ('40') THEN D.COL5 ELSE NULL END) AS COL6,
  SUM(CASE WHEN RIND IN ('41') THEN D.COL5 ELSE NULL END) AS COL7,
  SUM(CASE WHEN RIND IN ('42') THEN D.COL5 ELSE NULL END) AS COL8,
  SUM(CASE WHEN RIND IN ('43') THEN D.COL5 ELSE NULL END) AS COL9,
  SUM(CASE WHEN RIND IN ('50') THEN D.COL5 ELSE NULL END) AS COL10,
  SUM(CASE WHEN RIND IN ('60') THEN D.COL5 ELSE NULL END) AS COL11,
  SUM(CASE WHEN RIND IN ('61') THEN D.COL5 ELSE NULL END) AS COL12,
  0 AS COL13

FROM CIS.VW_DATA_ALL_COEF D
  
WHERE 
  PERIOADA = :pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND 
  FORM = 11 AND
  CAPITOL IN (95) AND
  D.CAEM2 LIKE 'O84%' AND D.CD > 0
  AND D.CUIIO IN (SELECT DISTINCT
                  D.CUIIO
                FROM
                  VW_DATA_ALL_COEF D
                  INNER JOIN MD_PERIOADA P ON P.ANUL = D.ANUL AND P.PERIOADA IN (:pPERIOADA)
                WHERE
                  D.NUM IN 12 AND
                  D.FORM IN (5) AND
                  D.CAPITOL IN (0) AND
                  D.RIND IN ('CM'))
GROUP BY
  D.CAEM2
) D
  INNER JOIN CIS.VW_CL_CAEM2 C ON (D.CAEM2=C.CODUL)
  INNER JOIN CIS.VW_CL_CAEM2 CG ON (C.FULL_CODE LIKE '%'||CG.CODUL||';%')
GROUP BY
  CG.CODUL,
  CG.DENUMIRE
--ORDER BY
--  CG.CODUL
)
GROUP BY
  CODUL,
  DENUMIRE
ORDER BY
  CODUL