SELECT DISTINCT
'Rind.010 nu este completat'  AS REZULTAT

 

FROM 
CIS2.VW_DATA_ALL D 

WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (13) AND D.RIND IN ('010')
  
GROUP BY 
D.COL2,
D.COL3,
D.COL4,
D.COL3,
D.COL6,
D.COL7

 HAVING  
 
 NVAL(D.COL2) + NVAL(D.COL3) + NVAL(D.COL4) + NVAL(D.COL6) + NVAL(D.COL7) = 0 
  

  
  
  
