SELECT 


'Rind.'||SUBSTR(D.RIND, 1, 3)||', Tara. '||D.COL1||':  '||
  SUM(CASE WHEN D.CAPITOL IN (1020)  AND D.PERIOADA IN (:PERIOADA)  AND D.NUM IN (2,3,4) THEN CIS2.NVAL(D.COL2) ELSE 0 END) ||'<> '||
  SUM(CASE WHEN D.CAPITOL IN (1020)  AND D.PERIOADA IN (:PERIOADA-1)AND D.NUM IN (1,2,3) THEN CIS2.NVAL(D.COL2) ELSE 0 END)
  AS REZULTAT

FROM
  CIS2.VW_DATA_ALL D                                    
WHERE
  (D.PERIOADA IN (:PERIOADA,:PERIOADA-1)) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
 (:CUIIO_VERS=:CUIIO_VERS     OR  :CUIIO_VERS <>:CUIIO_VERS) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS <> :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL=-1) AND
  (:FORM = :FORM) AND
  
  D.FORM  IN(13) AND     
  D.CAPITOL IN(1020) 
  
GROUP BY SUBSTR(D.RIND, 1, 3),D.COL1

HAVING

 SUM(CASE WHEN D.CAPITOL IN (1020) AND D.PERIOADA IN (:PERIOADA) AND D.NUM IN (2,3,4) THEN CIS2.NVAL(D.COL2) ELSE 0 END) <> 
 SUM(CASE WHEN D.CAPITOL IN (1020) AND D.PERIOADA IN (:PERIOADA-1)AND D.NUM IN (1,2,3) THEN CIS2.NVAL(D.COL2) ELSE 0 END)  
 


AND 

(

  SELECT
  DISTINCT
  D.CUIIO
FROM
  CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA IN (:PERIOADA-1)) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  D.FORM  IN(13)    
  
  
  ) IS NOT NULL
