SELECT 
---40788535

--CIS2 1324839
'Rind.'||SUBSTR(D.RIND, 1, 3)||', Tara. '||D.COL1||': '||
  MAX(CASE WHEN D.CAPITOL IN (1020) AND   D.PERIOADA IN (:PERIOADA)   AND D.NUM IN (2,3,4)  THEN D.COL4 ELSE 0 END) ||'<= '||
  MAX(CASE WHEN D.CAPITOL IN (1020) AND   D.PERIOADA IN (:PERIOADA-1) AND D.NUM IN (1,2,3)  THEN D.COL4 ELSE 0 END)
  AS REZULTAT

FROM
  VW_DATA_ALL D                                    
WHERE
  (D.PERIOADA IN (:PERIOADA,:PERIOADA-1)) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR  D.CUIIO_VERS <>:CUIIO_VERS) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL=-1) AND
  (:FORM = :FORM) AND
  
  D.FORM  IN(13) AND     
  D.CAPITOL IN(1020)
 
  
GROUP BY SUBSTR(D.RIND, 1, 3),D.COL1

HAVING

  MAX(CASE WHEN D.CAPITOL IN (1020) AND   D.PERIOADA IN (:PERIOADA)   AND D.NUM IN (2,3,4)  THEN D.COL4 ELSE 0 END) < 
  MAX(CASE WHEN D.CAPITOL IN (1020) AND   D.PERIOADA IN (:PERIOADA-1) AND D.NUM IN (1,2,3)  THEN D.COL4 ELSE 0 END) AND
 (SELECT
  DISTINCT
  D.CUIIO
FROM
  VW_DATA_ALL D
WHERE
  (D.PERIOADA IN (:PERIOADA-1)) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  D.FORM  IN(13) 
  
  
  
  ) IS NOT NULL