SELECT
  'Completati Va Rog rind.012 col.3'  AS REZULTAT

FROM 
 VW_DATA_ALL_GC D
 
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.NR_GOSP=:NR_GOSP               OR :NR_GOSP = -1) AND
  (D.UNIT_CODE_VERS=:UNIT_CODE_VERS     OR :UNIT_CODE_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (58)  AND
  D.CAPITOL IN (416) 
  AND D.RIND  IN ('011','012')
  

  
HAVING
  SUM(CASE WHEN D.CAPITOL IN 416 AND D.RIND  IN ('011') THEN NVAL(D.COL3) ELSE 0 END) > 0 
  
  AND 
 

SUM(CASE WHEN D.CAPITOL IN 416 AND D.RIND  IN ('012') THEN NVAL(D.COL3) ELSE 0 END) = 0 
  