SELECT DISTINCT 
'Ancheta: '||D.FILIAL||'; Rind  '||D.RIND||'=0,  (p/u info: Salariu mediu='||--Cap.II Col. 1 rândului curent*1000/Cap.I Col.2 rândului curent[fara zecimale])' 

ROUND(
SUM(CASE WHEN D.CAPITOL IN('303') THEN  NVAL(D.COL2) ELSE 0 END)*1000/
NOZERO(SUM(CASE WHEN D.CAPITOL IN('301') THEN  NVAL(D.COL3) ELSE 0 END))/12 )||')' 



  AS REZULTAT
  
  

FROM
  CIS2.VW_DATA_ALL D      
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL_VERS=:CAPITOL_VERS  OR :CAPITOL_VERS <>  :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL<> :CAPITOL)  AND
  
  -- D.CAPITOL=303 and
  (:FORM = :FORM) AND D.FORM IN (3) 
  
 GROUP BY D.RIND,D.FILIAL
 
--HAVING
--
--CASE WHEN nval(SUM(CASE WHEN D.CAPITOL IN('303') THEN  D.COL2 ELSE 0 END) ) <> 0 THEN
--ROUND(
--   NVAL((SUM(CASE WHEN D.CAPITOL IN('303') THEN  D.COL7 ELSE 0 END)))*100/
--   NOZERO( nval(SUM(CASE WHEN D.CAPITOL IN('303') THEN  D.COL2 ELSE 0 END) )),2)
--   ELSE 0 END <=0 
--   AND nval(SUM(CASE WHEN D.CAPITOL IN('303') THEN  D.COL2 ELSE 0 END) ) >  0