SELECT   
'Ancheta: '||D.FILIAL||'; Rind '||D.RIND||':  '||  CIS2.NVAL(SUM(D.COL12)) ||' > '||  CIS2.NVAL(SUM(D.COL3))
   
  AS REZULTAT

FROM
  CIS2.VW_DATA_ALL D
 

WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (3)  AND
  D.CAPITOL in (301) AND
  D.RIND IN  ('00-T')
 
GROUP BY D.RIND,D.FILIAL

HAVING
 CIS2.NVAL(SUM(D.COL12))> 
 CIS2.NVAL(SUM(D.COL3))