SELECT 
  'Filiala:'||D.FILIAL||' Rind.'||D.RIND||' COL1='||
  CASE 
  WHEN (CIS2.NVAL((D.COL2)) <=  CIS2.NVAL((D.COL7))) THEN  CIS2.NVAL((D.COL2))||', dar COL6='||  CIS2.NVAL((D.COL7)) 
  END AS REZULTAT

FROM
  CIS2.VW_DATA_ALL D                                    
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL=-1) AND
  (:FORM = :FORM) AND
  D.CAPITOL IN (303) AND
  D.FORM  IN(3)
GROUP BY
  D.FILIAL,
  D.RIND,
  D.COL2,
  D.COL7
HAVING
  CIS2.NVAL((D.COL2)) <> 0 AND  (CIS2.NVAL((D.COL2)) <=  CIS2.NVAL((D.COL7)))
  
UNION

SELECT 
  'Filiala:'||D.FILIAL||' Rind.'||D.RIND||' COL1='||
  CASE 
  WHEN (CIS2.NVAL((D.COL2)) <=  CIS2.NVAL((D.COL8))) THEN  CIS2.NVAL((D.COL2))||', dar COL7='||  CIS2.NVAL((D.COL8))   
  END AS REZULTAT

FROM
  CIS2.VW_DATA_ALL D                                    
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL=-1) AND
  (:FORM = :FORM) AND
  D.CAPITOL IN (303) AND
  D.FORM  IN(3)
GROUP BY
  D.FILIAL,
  D.RIND,
  D.COL2,
  D.COL8
HAVING
  CIS2.NVAL((D.COL2)) <> 0 AND  (CIS2.NVAL((D.COL2)) <=  CIS2.NVAL((D.COL8)))