
SELECT 
  CC.CODUL,
  CC.DENUMIRE,
  CC.FULL_CODE,
  NVAL(SUM(CASE WHEN D.RIND IN ('1')  THEN D.COL1 END)) AS COL1,
  NVAL(SUM(CASE WHEN D.RIND IN ('2')  THEN D.COL1 END)) AS COL2,
  NVAL(SUM(CASE WHEN D.RIND IN ('7')  THEN D.COL1 END)) AS COL3,
  NVAL(SUM(CASE WHEN D.RIND IN ('8')  THEN D.COL1 END)) AS COL4,
  NVAL(SUM(CASE WHEN D.RIND IN ('10','13') THEN D.COL1 END)) AS COL5,
  NVAL(SUM(CASE WHEN D.RIND IN ('11','14')  THEN D.COL1 END)) AS COL6,
  NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN  D.COL1 END)) AS COL7,
  NVAL(SUM(CASE WHEN D.RIND IN ('11')  THEN D.COL1 END)) AS COL8,
  NVAL(SUM(CASE WHEN D.RIND IN ('13')  THEN D.COL1 END)) AS COL9,
  NVAL(SUM(CASE WHEN D.RIND IN ('14')  THEN D.COL1 END)) AS COL10,
  NVAL(SUM(CASE WHEN D.RIND IN ('15')  THEN D.COL1 END)) AS COL11,
  NVAL(SUM(CASE WHEN D.RIND IN ('20')  THEN D.COL1 END)) AS COL12
FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM RE ON (D.CUIIO=RE.CUIIO AND D.CUIIO_VERS=RE.CUIIO_VERS)
  INNER JOIN VW_CL_CUATM C ON(D.CUATM = C.CODUL)
  INNER JOIN VW_CL_CUATM CC ON C.FULL_CODE LIKE '%'||CC.CODUL||';%'
  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (29)                 AND 
  D.CAPITOL IN (375)           
  AND CC.FULL_CODE LIKE '%'||'0000000;9600000;'||'%'
GROUP BY 
  CC.CODUL,
  CC.DENUMIRE,
  CC.FULL_CODE
  
  ORDER BY 
  CC.FULL_CODE