SELECT
--  :pPERIOADA AS PERIOADA,
--  :pFORM AS FORM,
--  :pFORM_VERS AS FORM_VERS,
--  :pID_MDTABLE AS ID_MDTABLE,
--  :pCOD_CUATM AS COD_CUATM,
--         
--  '0' AS NR_SECTIE,
--  '0' AS NUME_SECTIE,
--  '0' AS NR_SECTIE1,
--  '0' AS NUME_SECTIE1,
--  '0' AS NR_SECTIE2,
--  '0' AS NUME_SECTIE2,
  NUME_ROW,
  ROUND(COL1,0)||'~'||NR_ROW AS COL1,
  ROUND(COL2,0) AS COL2,
  ROUND(NVAL(COL2)/NOZERO(COL1)*100,1) AS COL3,
  ROUND(COL4,0) AS COL4,
  ROUND(COL5,0) AS COL5,
  ROUND(NVAL(COL5)/NOZERO(COL4)*100,0) AS COL6,
  ROUND(COL7,0) AS COL7,
  ROUND(COL8,0) AS COL8,
  ROUND(NVAL(COL8)/NOZERO(COL7)*100,0) AS COL9,
  ROUND(COL10,0) AS COL10,
  ROUND(COL11,0) AS COL11,
  ROUND(COL12,0) AS COL12,
  ROUND(NVAL(COL12)/NOZERO(COL11)*100,1) AS COL13,
  ROUND(COL14,0) AS COL14,
  ROUND(COL15,0) AS COL15,
  ROUND(NVAL(COL15)/NOZERO(COL14)*100,1) AS COL16,
  ROUND(COL17,0) AS COL17,
  ROUND(COL18,0) AS COL18,
  ROUND(COL19,0) AS COL19,
  ROUND(NVAL(COL19)/NOZERO(COL18)*100,1) AS COL20,
  ROUND(COL21,0) AS COL21,
  ROUND(COL22,0) AS COL22,
  ROUND(COL23,0) AS COL23,
  ROUND(NVAL(COL23)/NOZERO(COL22)*100,1) AS COL24
FROM
(
SELECT 
  CC.CODUL     NR_ROW,
  CC.DENUMIRE  NUME_ROW,
  CC.FULL_CODE AS ORDINE,

  NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('1')  THEN D.COL1 END)) AS COL1,
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('1') THEN D.COL1 END)) AS COL2,
  
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('2')  THEN D.COL1 END)) AS COL4,
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('2')  THEN D.COL1 END)) AS COL5,
  
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('7') THEN D.COL1 END)) AS COL7,
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('7')  THEN D.COL1 END)) AS COL8,
  
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('8') THEN D.COL1 END)) AS COL10,
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('10','13')  THEN D.COL1 END)) AS COL11,
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('10','13')  THEN D.COL1 END)) AS COL12,
  
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('10')  THEN D.COL1 END)) AS COL14,
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('10')  THEN D.COL1 END)) AS COL15,
  
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('11') THEN D.COL1 END)) AS COL17,
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('13') THEN D.COL1 END)) AS COL18,
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('13')  THEN D.COL1 END)) AS COL19,
  
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('14') THEN D.COL1 END)) AS COL21,
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('15')  THEN D.COL1 END)) AS COL22,
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('15') THEN D.COL1 END)) AS COL23
FROM 
  VW_DATA_ALL D
  
  INNER JOIN RENIM RE ON (D.CUIIO=RE.CUIIO AND D.CUIIO_VERS=RE.CUIIO_VERS)

 INNER JOIN VW_CL_CUATM C ON(D.CUATM = C.CODUL)
  INNER JOIN VW_CL_CUATM CC ON C.FULL_CODE LIKE '%'||CC.CODUL||';%'
  
WHERE
  D.PERIOADA IN (:pPERIOADA,:pPERIOADA-4) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (29)                 AND 
  D.CAPITOL IN (375)           
   AND CC.FULL_CODE LIKE '%'||'0000000;9600000;'||'%'
GROUP BY 
  CC.CODUL,
  CC.DENUMIRE,
  CC.FULL_CODE
  
  ORDER BY 
  CC.FULL_CODE
)