SELECT
  '% -'||ROUND(((SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('7.40.160') AND D.PERIOADA IN (:PERIOADA) THEN D.COL1 ELSE 0 END)*100)/
   
                 SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('7.40.10') AND D.PERIOADA IN (:PERIOADA)  THEN D.COL1 ELSE 0 END))/
   
     CIS.NOZERO((SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('7.40.160') AND D.PERIOADA IN (:PERIOADA-12) THEN D.COL1 ELSE 0 END))/
   
                 SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('7.40.10') AND D.PERIOADA IN (:PERIOADA-12)  THEN D.COL1 ELSE 0 END)),1)
   
    ||' (p/u info: Anul='||--5263, Anul1=5499)
   
  ROUND((SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('7.40.160') AND D.PERIOADA IN (:PERIOADA) THEN D.COL1 ELSE 0 END)*1000)/  
          SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('7.40.10') AND D.PERIOADA IN (:PERIOADA)  THEN D.COL1 ELSE 0 END))
  
    ||',  Anul-1='||
    
   ROUND ((SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('7.40.160') AND D.PERIOADA IN (:PERIOADA-12) THEN D.COL1 ELSE 0 END)*1000)/  
    CIS.NOZERO( SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('7.40.10') AND D.PERIOADA IN (:PERIOADA-12)  THEN D.COL1 ELSE 0 END)))
  
  AS REZULTAT

FROM
  CIS.VW_DATA_ALL D
  
WHERE
  (D.PERIOADA IN (:PERIOADA,:PERIOADA -12)         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  ( :CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  ( :FORM = :FORM               OR :FORM = -1) AND
  ( :FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  ( :CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  ( :CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  ( :ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
   FORM IN (7) AND
   CAPITOL IN (40)
  
  
HAVING

   ROUND(((SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('7.40.160') AND D.PERIOADA IN (:PERIOADA) THEN D.COL1 ELSE 0 END)*100)/
   
                 SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('7.40.10') AND D.PERIOADA IN (:PERIOADA)  THEN D.COL1 ELSE 0 END))/
   
     CIS.NOZERO((SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('7.40.160') AND D.PERIOADA IN (:PERIOADA-12) THEN D.COL1 ELSE 0 END))/
   
                 SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('7.40.10') AND D.PERIOADA IN (:PERIOADA-12)  THEN D.COL1 ELSE 0 END)),1)  <100
   
   OR
   
   ROUND(((SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('7.40.160') AND D.PERIOADA IN (:PERIOADA) THEN D.COL1 ELSE 0 END)*100)/
   
                 SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('7.40.10') AND D.PERIOADA IN (:PERIOADA)  THEN D.COL1 ELSE 0 END))/
   
     CIS.NOZERO((SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('7.40.160') AND D.PERIOADA IN (:PERIOADA-12) THEN D.COL1 ELSE 0 END))/
   
                 SUM(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('7.40.10') AND D.PERIOADA IN (:PERIOADA-12)  THEN D.COL1 ELSE 0 END)),1)>160
   
   