SELECT DISTINCT
  'Forma: '||MAX(DECODE(D.FORM,7,NULL,D.FORM_DEN))||', Col.'||C.COL||' ('||
  NVAL(MAX(CASE WHEN DD.FORM||'.'||DD.CAPITOL||'.'||DD.RIND     IN('7.40.CAEM')  THEN DECODE(C.COL, 1,DD.COL1, 2,DD.COL2, 3,DD.COL3, 4,DD.COL4, 5,DD.COL5, 6,DD.COL6, 7,DD.COL7, 8,DD.COL8, 9,DD.COL9, 10,DD.COL10, 11,DD.COL11, 12,DD.COL12) ELSE 0 END)) ||' <> '||
  NVAL(MAX(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN('5.27.CAEM')  THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2, 3,D.COL3, 4,D.COL4, 5,D.COL5, 6,D.COL6, 7,D.COL7, 8,D.COL8, 9,D.COL9, 10,D.COL10, 11,D.COL11, 12,D.COL12) ELSE 0 END))
  ||')'
  AS REZULTAT
FROM
  CIS.VW_DATA_ALL D
  RIGHT JOIN USER_EREPORTING.VW_DATA_ALL_FOR_VALIDATE DD ON (D.CUIIO=DD.CUIIO AND D.PERIOADA=DD.PERIOADA AND DD.ID_SCHEMA IN (1)),
  (
    SELECT 3  AS COL FROM DUAL UNION
    SELECT 4  AS COL FROM DUAL UNION
    SELECT 5  AS COL FROM DUAL UNION
    SELECT 6  AS COL FROM DUAL UNION
    SELECT 7  AS COL FROM DUAL UNION
    SELECT 8  AS COL FROM DUAL UNION
    SELECT 9  AS COL FROM DUAL UNION
    SELECT 10 AS COL FROM DUAL UNION
    SELECT 11 AS COL FROM DUAL UNION
    SELECT 12 AS COL FROM DUAL
  ) C                                        
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (DD.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (DD.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  ( :CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  ( :FORM = :FORM               OR :FORM = -1) AND
  ( :FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  ( :CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  ( :CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  ( :ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('5.27.CAEM') AND
    DD.FORM||'.'||DD.CAPITOL||'.'||DD.RIND IN ( 
    '7.40.CAEM')
GROUP BY
  C.COL 
HAVING
  NVAL(MAX(CASE WHEN DD.FORM||'.'||DD.CAPITOL||'.'||DD.RIND     IN('7.40.CAEM')  THEN DECODE(C.COL, 1,DD.COL1, 2,DD.COL2, 3,DD.COL3, 4,DD.COL4, 5,DD.COL5, 6,DD.COL6, 7,DD.COL7, 8,DD.COL8, 9,DD.COL9, 10,DD.COL10, 11,DD.COL11, 12,DD.COL12) ELSE 0 END))<>
  NVAL(MAX(CASE WHEN D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN('5.27.CAEM')  THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2, 3,D.COL3, 4,D.COL4, 5,D.COL5, 6,D.COL6, 7,D.COL7, 8,D.COL8, 9,D.COL9, 10,D.COL10, 11,D.COL11, 12,D.COL12) ELSE 0 END))
