    INSERT INTO    CIS2.TABLE_OUT
    (
      
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
  COL1,COL2, COL3, COL4, COL5, COL6
  
    )


SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   VB.CODUL||'~'||ROWNUM AS NR_ROW,
   ROWNUM  AS ORDINE,
  '00000000000' AS DECIMAL_POS, 
   VB.DENUMIRE AS NUME_ROW,
   COL1  AS COL1,
   COL2  AS COL2,
   COL3  AS COL3,
   COL4  AS COL4,
   COL5  AS COL5,
   COL6  AS COL6
 

   
  

FROM
(
SELECT 
     1 ORDINE,
    '1' CODUL,
    'Teatre profesionale' DENUMIRE,
    SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 ELSE NULL END )  AS COL1,
    SUM(CASE WHEN D.RIND IN ('20') THEN D.COL2 ELSE NULL END )  AS COL2,
    SUM(CASE WHEN D.RIND IN ('30') THEN D.COL2 ELSE NULL END )  AS COL3,
    SUM(CASE WHEN D.RIND IN ('40') THEN D.COL2 ELSE NULL END )  AS COL4,
    SUM(CASE WHEN D.RIND IN ('50') THEN D.COL2 ELSE NULL END )  AS COL5,
    SUM(CASE WHEN D.RIND IN ('60') THEN D.COL2 ELSE NULL END )  AS COL6
    
   
   
   FROM   CIS2.VW_DATA_ALL D 

               INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS AND R.GEN_INSTITUTIE IN ('2','3','5','6'))
                
               
                 WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1078)
  
  UNION ALL 
  
  SELECT 
     2 ORDINE,
    '2' CODUL,
    'de opera si balet' DENUMIRE,
    SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 ELSE NULL END )  AS COL1,
    SUM(CASE WHEN D.RIND IN ('20') THEN D.COL2 ELSE NULL END )  AS COL2,
    SUM(CASE WHEN D.RIND IN ('30') THEN D.COL2 ELSE NULL END )  AS COL3,
    SUM(CASE WHEN D.RIND IN ('40') THEN D.COL2 ELSE NULL END )  AS COL4,
    SUM(CASE WHEN D.RIND IN ('50') THEN D.COL2 ELSE NULL END )  AS COL5,
    SUM(CASE WHEN D.RIND IN ('60') THEN D.COL2 ELSE NULL END )  AS COL6
    
   
   FROM   CIS2.VW_DATA_ALL D 

                 INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS AND R.GEN_INSTITUTIE IN ('2'))
                
               
                 WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1078)
  
  
  UNION ALL 
  
  SELECT 
     3 ORDINE,
    '3' CODUL,
    'dramatice, de comedie si muzicale' DENUMIRE,
    SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 ELSE NULL END )  AS COL1,
    SUM(CASE WHEN D.RIND IN ('20') THEN D.COL2 ELSE NULL END )  AS COL2,
    SUM(CASE WHEN D.RIND IN ('30') THEN D.COL2 ELSE NULL END )  AS COL3,
    SUM(CASE WHEN D.RIND IN ('40') THEN D.COL2 ELSE NULL END )  AS COL4,
    SUM(CASE WHEN D.RIND IN ('50') THEN D.COL2 ELSE NULL END )  AS COL5,
    SUM(CASE WHEN D.RIND IN ('60') THEN D.COL2 ELSE NULL END )  AS COL6
    
   
   
   FROM   CIS2.VW_DATA_ALL D 

                INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS AND R.GEN_INSTITUTIE IN ('3'))
                
               
                 WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1078)
  
  
  UNION  ALL 
  
  SELECT 
     4 ORDINE,
    '4' CODUL,
    'pentru copii si tineret' DENUMIRE,
    SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 ELSE NULL END )  AS COL1,
    SUM(CASE WHEN D.RIND IN ('20') THEN D.COL2 ELSE NULL END )  AS COL2,
    SUM(CASE WHEN D.RIND IN ('30') THEN D.COL2 ELSE NULL END )  AS COL3,
    SUM(CASE WHEN D.RIND IN ('40') THEN D.COL2 ELSE NULL END )  AS COL4,
    SUM(CASE WHEN D.RIND IN ('50') THEN D.COL2 ELSE NULL END )  AS COL5,
    SUM(CASE WHEN D.RIND IN ('60') THEN D.COL2 ELSE NULL END )  AS COL6
    
   
   
   FROM   CIS2.VW_DATA_ALL D 

                INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS AND R.GEN_INSTITUTIE IN ('5','4'))
                
               
                 WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1078)
  
  
  UNION  ALL 
  
  SELECT 
     5 ORDINE,
    '5' CODUL,
    'de papusi' DENUMIRE,
    SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 ELSE NULL END )  AS COL1,
    SUM(CASE WHEN D.RIND IN ('20') THEN D.COL2 ELSE NULL END )  AS COL2,
    SUM(CASE WHEN D.RIND IN ('30') THEN D.COL2 ELSE NULL END )  AS COL3,
    SUM(CASE WHEN D.RIND IN ('40') THEN D.COL2 ELSE NULL END )  AS COL4,
    SUM(CASE WHEN D.RIND IN ('50') THEN D.COL2 ELSE NULL END )  AS COL5,
    SUM(CASE WHEN D.RIND IN ('60') THEN D.COL2 ELSE NULL END )  AS COL6
    
   
   
   FROM   CIS2.VW_DATA_ALL D 

                 INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS AND R.GEN_INSTITUTIE IN ('5'))
                
               
                 WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1078)
  
  
  UNION  ALL 
  
  SELECT 
     6 ORDINE,
    '6' CODUL,
    'Studiou teatral' DENUMIRE,
   SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 ELSE NULL END )  AS COL1,
    SUM(CASE WHEN D.RIND IN ('20') THEN D.COL2 ELSE NULL END )  AS COL2,
    SUM(CASE WHEN D.RIND IN ('30') THEN D.COL2 ELSE NULL END )  AS COL3,
    SUM(CASE WHEN D.RIND IN ('40') THEN D.COL2 ELSE NULL END )  AS COL4,
    SUM(CASE WHEN D.RIND IN ('50') THEN D.COL2 ELSE NULL END )  AS COL5,
    SUM(CASE WHEN D.RIND IN ('60') THEN D.COL2 ELSE NULL END )  AS COL6
    
   
   
   FROM   CIS2.VW_DATA_ALL D 

                INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS AND R.GEN_INSTITUTIE IN ('6'))
                
               
                 WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1078)
  
  
  UNION  ALL 
  
  SELECT 
     7 ORDINE,
    '7' CODUL,
    'Organizatii concertistice de impresariat' DENUMIRE,
    SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 ELSE NULL END )  AS COL1,
    SUM(CASE WHEN D.RIND IN ('20') THEN D.COL2 ELSE NULL END )  AS COL2,
    SUM(CASE WHEN D.RIND IN ('30') THEN D.COL2 ELSE NULL END )  AS COL3,
    SUM(CASE WHEN D.RIND IN ('40') THEN D.COL2 ELSE NULL END )  AS COL4,
    SUM(CASE WHEN D.RIND IN ('50') THEN D.COL2 ELSE NULL END )  AS COL5,
    SUM(CASE WHEN D.RIND IN ('60') THEN D.COL2 ELSE NULL END )  AS COL6
    
   
   
   FROM   CIS2.VW_DATA_ALL D 

                INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS AND R.GEN_INSTITUTIE IN ('7'))
                
               
                 WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1078)
  
  
  UNION  ALL 
  
  SELECT 
     8 ORDINE,
    '8' CODUL,
    'Organizatii concertistice' DENUMIRE,
    SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 ELSE NULL END )  AS COL1,
    SUM(CASE WHEN D.RIND IN ('20') THEN D.COL2 ELSE NULL END )  AS COL2,
    SUM(CASE WHEN D.RIND IN ('30') THEN D.COL2 ELSE NULL END )  AS COL3,
    SUM(CASE WHEN D.RIND IN ('40') THEN D.COL2 ELSE NULL END )  AS COL4,
    SUM(CASE WHEN D.RIND IN ('50') THEN D.COL2 ELSE NULL END )  AS COL5,
    SUM(CASE WHEN D.RIND IN ('60') THEN D.COL2 ELSE NULL END )  AS COL6
    
   
   
   FROM   CIS2.VW_DATA_ALL D 

                INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS AND R.GEN_INSTITUTIE IN ('8'))
                
               
                 WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1078)
  
  
  UNION  ALL 
  
  SELECT 
     9 ORDINE,
    '9' CODUL,
    'Circ' DENUMIRE,
   SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 ELSE NULL END )  AS COL1,
    SUM(CASE WHEN D.RIND IN ('20') THEN D.COL2 ELSE NULL END )  AS COL2,
    SUM(CASE WHEN D.RIND IN ('30') THEN D.COL2 ELSE NULL END )  AS COL3,
    SUM(CASE WHEN D.RIND IN ('40') THEN D.COL2 ELSE NULL END )  AS COL4,
    SUM(CASE WHEN D.RIND IN ('50') THEN D.COL2 ELSE NULL END )  AS COL5,
    SUM(CASE WHEN D.RIND IN ('60') THEN D.COL2 ELSE NULL END )  AS COL6
    
   
   
   FROM   CIS2.VW_DATA_ALL D 

               INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS AND R.GEN_INSTITUTIE IN ('9'))
                
               
                 WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1078)
  
 ) VB 
  
 
  
