SELECT
CC.CODUL,
CC.DENUMIRE, 
CC.FULL_CODE,
COUNT (DISTINCT D.RIND) AS COL1
  
FROM
  CIS2.VW_DATA_ALL D
 INNER JOIN CIS2.VW_CL_CUATM C ON (D.RIND=C.CODUL )
 INNER JOIN CIS2.VW_CL_CUATM CC ON ((C.CODUL=CC.CODUL AND CC.PRGS IN (8,3,5)) OR (CC.PRGS NOT IN (8,3,5) AND C.FULL_CODE LIKE '%'||CC.CODUL||'%'))
  
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (D.FORM=:pFORM) AND
  (D.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
   D.FORM = 47 AND
   D.CAPITOL IN (1034,1035)
 
   AND D.RIND NOT IN '0000000' 
   AND C.FULL_CODE LIKE '%'||:pCOD_CUATM||'%'

   AND CC.PRGS NOT IN ('4')  
   AND CC.PRGS IN ('2')       
   
GROUP BY 
CC.CODUL,
CC.DENUMIRE, 
CC.FULL_CODE

 HAVING 
  CIS2.NVAL(SUM(CASE WHEN CAPITOL IN (1034) AND D.RIND NOT IN '0000000' THEN NVAL(D.COL9) ELSE 0 END))  > 0
  AND 
   CIS2.NVAL(SUM(CASE WHEN CAPITOL IN (1035) AND D.RIND NOT IN '0000000' THEN NVAL(D.COL9) ELSE 0 END))  > 0
   
   union 
   
   SELECT
CC.CODUL,
CC.DENUMIRE, 
CC.FULL_CODE,
COUNT (DISTINCT D.RIND) AS COL1
  
FROM
  CIS2.VW_DATA_ALL D
 INNER JOIN CIS2.VW_CL_CUATM C ON (D.RIND=C.CODUL )
 INNER JOIN CIS2.VW_CL_CUATM CC ON ((C.CODUL=CC.CODUL AND CC.PRGS IN (8,3,5)) OR (CC.PRGS NOT IN (8,3,5) AND C.FULL_CODE LIKE '%'||CC.CODUL||'%'))
 
 
  
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (D.FORM=:pFORM) AND
  (D.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
   D.FORM = 47 AND
   D.CAPITOL IN (1034,1035)
 
   AND D.RIND NOT IN '0000000' 
   AND C.FULL_CODE LIKE '%'||:pCOD_CUATM||'%'

   AND CC.PRGS NOT IN ('4')  
   --AND CC.PRGS IN ('2')
   AND cc.CODUL in ('9601000','9603000','9602000')     
     
   
GROUP BY 
CC.CODUL,
CC.DENUMIRE, 
CC.FULL_CODE

 HAVING 
  CIS2.NVAL(SUM(CASE WHEN CAPITOL IN (1034) AND D.RIND NOT IN '0000000' THEN NVAL(D.COL9) ELSE 0 END))  > 0
  AND 
   CIS2.NVAL(SUM(CASE WHEN CAPITOL IN (1035) AND D.RIND NOT IN '0000000' THEN NVAL(D.COL9) ELSE 0 END))  > 0
   

   
   ORDER BY 
   FULL_CODE