SELECT
  CC.DENUMIRE,CC.CODUL, CC.FULL_CODE, 0 AS ORDINE, CC.PRGS,
  CIS2.NVAL(SUM(CASE WHEN CAPITOL IN (1034) AND D.RIND NOT IN '0000000' THEN COL1 ELSE 0 END)) AS COL1,
  CIS2.NVAL(SUM(CASE WHEN CAPITOL IN (1034) AND D.RIND NOT IN '0000000' THEN COL2 ELSE 0 END)) AS COL2,
  CIS2.NVAL(SUM(CASE WHEN CAPITOL IN (1034) AND D.RIND NOT IN '0000000' THEN COL3 ELSE 0 END)) AS COL3,
  CIS2.NVAL(SUM(CASE WHEN CAPITOL IN (1034) AND D.RIND NOT IN '0000000' THEN COL4 ELSE 0 END)) AS COL4,
  CIS2.NVAL(SUM(CASE WHEN CAPITOL IN (1034) AND D.RIND NOT IN '0000000' THEN COL5 ELSE 0 END)) AS COL5,
  CIS2.NVAL(SUM(CASE WHEN CAPITOL IN (1034) AND D.RIND NOT IN '0000000' THEN COL6 ELSE 0 END)) AS COL6,
  CIS2.NVAL(SUM(CASE WHEN CAPITOL IN (1034) AND D.RIND NOT IN '0000000' THEN COL7 ELSE 0 END)) AS COL7,
  CIS2.NVAL(SUM(CASE WHEN CAPITOL IN (1034) AND D.RIND NOT IN '0000000' THEN COL8 ELSE 0 END)) AS COL8
  
FROM
  CIS2.VW_DATA_ALL D
 INNER JOIN CIS2.VW_CL_CUATM C ON (D.RIND=C.CODUL )
--  INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||'%')
INNER JOIN CIS2.VW_CL_CUATM CC ON ((C.CODUL=CC.CODUL AND CC.PRGS IN (8,3,5)) OR (CC.PRGS NOT IN (8,3,5) AND C.FULL_CODE LIKE '%'||CC.CODUL||'%'))
  
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (D.FORM=:pFORM) AND
  (D.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
   D.FORM = 47 AND
  -- D.CUIIO=3399698 AND
   D.CAPITOL IN (1034) AND CC.PRGS NOT IN 4  AND
   C.FULL_CODE LIKE '%'||:pCOD_CUATM||'%'
   
GROUP BY CC.DENUMIRE,
  CC.CODUL, CC.FULL_CODE,CC.PRGS