SELECT
  MAX(DISTINCT CASE WHEN  (D.PERIOADA =:pPERIOADA) AND D.FORM IN (4) AND D.CAPITOL IN (0)   THEN  D.CUIIO   END) CUIIO,
  MAX(DISTINCT CASE WHEN  (D.PERIOADA =:pPERIOADA) AND D.FORM IN (4) AND D.CAPITOL IN (0)   THEN  R.DENUMIRE   END) DENUMIRE,
  MAX(DISTINCT CASE WHEN  (D.PERIOADA =:pPERIOADA) AND D.FORM IN (4) AND D.CAPITOL IN (0)   THEN  R.CAEM2   END) CAEM2,
  
  MAX(DISTINCT CASE WHEN  (D.PERIOADA =:pPERIOADA) AND D.FORM IN (4) AND D.CAPITOL IN (0)   THEN  R.CUATM   END) CUATM,
  MAX(DISTINCT CASE WHEN  (D.PERIOADA =:pPERIOADA) AND D.FORM IN (4) AND D.CAPITOL IN (0)   THEN  D.PACHET   END) PACHET,
  SUM(CASE WHEN  (D.PERIOADA =:pPERIOADA-2) AND  D.FORM IN (4) AND D.CAPITOL IN (4) AND D.RIND IN ('10') THEN D.COL1  ELSE  NULL END) COL1,
  SUM(CASE WHEN  (D.PERIOADA =:pPERIOADA-1) AND  D.FORM IN (4) AND D.CAPITOL IN (4) AND D.RIND IN ('10') THEN D.COL1  ELSE  NULL END) COL2,
  SUM(CASE WHEN  (D.PERIOADA =:pPERIOADA) AND  D.FORM IN (4) AND D.CAPITOL IN (4) AND D.RIND IN ('10') THEN D.COL1  ELSE  NULL END) COL3,
    
  CIS.NVAL(SUM(CASE WHEN  (D.PERIOADA =:pPERIOADA-2) AND  D.FORM IN (4) AND D.CAPITOL IN (4) AND D.RIND IN ('10') THEN D.COL1  ELSE  NULL END)) +
  CIS.NVAL(SUM(CASE WHEN  (D.PERIOADA =:pPERIOADA-1) AND  D.FORM IN (4) AND D.CAPITOL IN (4) AND D.RIND IN ('10') THEN D.COL1  ELSE  NULL END)) + 
  CIS.NVAL(SUM(CASE WHEN  (D.PERIOADA =:pPERIOADA) AND  D.FORM IN (4) AND D.CAPITOL IN (4) AND D.RIND IN ('10') THEN D.COL1  ELSE  NULL END))     AS COL4   
FROM
  CIS.VW_DATA_ALL D 
  
  
       INNER JOIN CIS.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
       INNER  JOIN CIS.VW_CL_CUATM CT ON R.CUATM = CT.CODUL
        
        
  WHERE 
  
  ((D.PERIOADA IN (:pPERIOADA, :pPERIOADA - 1, :pPERIOADA - 2)) ) 
  
  
  
  AND 
  (D.FORM=:pFORM) AND
  (D.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  
  (D.FORM IN (4) AND D.CAPITOL IN (0,4))

  GROUP BY 
  D.CUIIO

  
  
  ORDER BY
  D.CUIIO