
SELECT 
D.CUIIO,
D.CUATM,
MAX(DATA_REG)  DATA_REG


FROM
  USER_EREPORTING.VW_DATA_ALL_PRIMIT D
  
                INNER JOIN  CIS.VW_CL_CUATM C   ON C.CODUL = D.CUATM 
  WHERE
   (C.FULL_CODE LIKE '%'||:pCOD_CUATM||';%') AND
--  (D.FORM=:pFORM) AND
--  (D.FORM_VERS=:pFORM_VERS) AND
--  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.PERIOADA IN (:pPERIOADA)) AND 
   D.FORM IN (4) 
   
   
   GROUP BY
   D.CUIIO,
   D.CUATM
   
   ORDER BY 
   D.CUATM