
SELECT 
D.CUIIO,
D.CUATM,
MAX(DATA_REG)  DATA_REG


FROM
  CIS.VW_DATA_ALL D 
  
  WHERE
   (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  (D.FORM=:pFORM) AND
  (D.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.PERIOADA IN (:pPERIOADA)) AND 
   D.FORM IN (4) 
   
   
   GROUP BY
   D.CUIIO,
   D.CUATM
   
   ORDER BY 
   D.CUATM