SELECT
  'Rind - '||D.RIND||
  ' Col1: '||'['||SUM(NVAL(COL1))||'] < [' ||SUM(NVAL(COL2))||'] : Col2 '
  AS REZULTAT

FROM
  VW_DATA_ALL D

WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND 
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS) AND
  (:ID_MD=:ID_MD) AND 
  D.FORM IN (55) AND 
  
  D.CAPITOL IN (1080)
  
  GROUP BY 
  D.RIND

  
HAVING
SUM(NVAL(COL1)) < SUM(NVAL(COL2))