SELECT
  
' Col1: '||SUM(NVAL(D.COL1))||' <> ' ||' (Col2+Col3+Col4+Col5+Col6+Col7+Col8+Col9+Col10+Col11) - '|| SUM(NVAL(D.COL2)+NVAL(D.COL3)+NVAL(D.COL4)+NVAL(D.COL5)+NVAL(D.COL6)+NVAL(D.COL7)+NVAL(D.COL8)+NVAL(D.COL9)+NVAL(D.COL10)+NVAL(COL11))
  AS REZULTAT

FROMs
  VW_DATA_ALL D

WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS) AND
  (:ID_MD=:ID_MD) AND 
  D.FORM IN (55) AND 
  
  D.CAPITOL IN (1080)
  

  
HAVING
SUM(NVAL(COL1)) <> SUM(NVAL(D.COL2)+NVAL(D.COL3)+NVAL(D.COL4)+NVAL(D.COL5)+NVAL(D.COL6)+NVAL(D.COL7)+NVAL(D.COL8)+NVAL(D.COL9)+NVAL(D.COL10)+NVAL(COL11))