SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   VB.CODUL||'~'||ROWNUM AS NR_ROW,
   ROWNUM  AS ORDINE,
  '00000000000' AS DECIMAL_POS, 
   VB.DENUMIRE AS NUME_ROW,
   COL1  AS COL1,
   COL2  AS COL2,
   COL3  AS COL3,
   COL4  AS COL4,
   COL5  AS COL5,
   COL6  AS COL6,
   COL7  AS COL7,
   COL8  AS COL8,
   COL9  AS COL9,
   COL10  AS COL10,
   COL11  AS COL11
   
  

FROM
(
SELECT 
     1 ORDINE,
    '1' CODUL,
    'Teatre profesionale' DENUMIRE,
    COUNT (DISTINCT D.CUIIO) AS COL1,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL4 ELSE NULL END ) AS COL2,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL5 ELSE NULL END ) AS COL3,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL4,   
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL5,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 3 THEN D.CUIIO ELSE 0 END  ) AS COL6,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL2) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL7,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL2) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL8,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL3) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL9,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL3) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL10,
    ROUND(SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN  D.COL6 ELSE NULL END ),1) AS COL11
   
   
   FROM   CIS2.VW_DATA_ALL D 

                INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
                INNER JOIN CIS2.CLS_CLASS_ITEM CI ON (CLASS_CODE IN ('GEN_INSTITUTIE') AND R.GEN_INSTITUTIE=CI.ITEM_CODE AND CI.ITEM_CODE NOT IN ('9','8','10'))
                
               
                 WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1079)
  
  UNION ALL 
  
  SELECT 
     2 ORDINE,
    '2' CODUL,
    'de opera si balet' DENUMIRE,
    COUNT (DISTINCT D.CUIIO) AS COL1,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL4 ELSE NULL END ) AS COL2,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL5 ELSE NULL END ) AS COL3,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL4,   
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL5,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 3 THEN D.CUIIO ELSE 0 END  ) AS COL6,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL2) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL7,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL2) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL8,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL3) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL9,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL3) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL10,
    ROUND(SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN  D.COL6 ELSE NULL END ),1) AS COL11
   
   
   FROM   CIS2.VW_DATA_ALL D 

                INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
                INNER JOIN CIS2.CLS_CLASS_ITEM CI ON (CLASS_CODE IN ('GEN_INSTITUTIE') AND R.GEN_INSTITUTIE=CI.ITEM_CODE AND CI.ITEM_CODE  IN ('2'))
                
               
                 WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1079)
  
  
  UNION ALL 
  
  SELECT 
     3 ORDINE,
    '3' CODUL,
    'dramatice, de comedie si muzicale' DENUMIRE,
    COUNT (DISTINCT D.CUIIO) AS COL1,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL4 ELSE NULL END ) AS COL2,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL5 ELSE NULL END ) AS COL3,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL4,   
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL5,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 3 THEN D.CUIIO ELSE 0 END  ) AS COL6,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL2) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL7,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL2) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL8,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL3) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL9,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL3) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL10,
    ROUND(SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN  D.COL6 ELSE NULL END ),1) AS COL11
   
   
   FROM   CIS2.VW_DATA_ALL D 

                INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
                INNER JOIN CIS2.CLS_CLASS_ITEM CI ON (CLASS_CODE IN ('GEN_INSTITUTIE') AND R.GEN_INSTITUTIE=CI.ITEM_CODE AND CI.ITEM_CODE  IN ('3'))
                
               
                 WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1079)
  
  
  UNION  ALL 
  
  SELECT 
     4 ORDINE,
    '4' CODUL,
    'pentru copii si tineret' DENUMIRE,
    COUNT (DISTINCT D.CUIIO) AS COL1,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL4 ELSE NULL END ) AS COL2,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL5 ELSE NULL END ) AS COL3,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL4,   
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL5,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 3 THEN D.CUIIO ELSE 0 END  ) AS COL6,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL2) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL7,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL2) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL8,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL3) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL9,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL3) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL10,
    ROUND(SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN  D.COL6 ELSE NULL END ),1) AS COL11
   
   
   FROM   CIS2.VW_DATA_ALL D 

                INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
                INNER JOIN CIS2.CLS_CLASS_ITEM CI ON (CLASS_CODE IN ('GEN_INSTITUTIE') AND R.GEN_INSTITUTIE=CI.ITEM_CODE AND CI.ITEM_CODE  IN ('5','6'))
                
               
                 WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1079)
  
  
  UNION  ALL 
  
  SELECT 
     5 ORDINE,
    '5' CODUL,
    'de papusi' DENUMIRE,
    COUNT (DISTINCT D.CUIIO) AS COL1,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL4 ELSE NULL END ) AS COL2,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL5 ELSE NULL END ) AS COL3,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL4,   
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL5,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 3 THEN D.CUIIO ELSE 0 END  ) AS COL6,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL2) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL7,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL2) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL8,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL3) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL9,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL3) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL10,
    ROUND(SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN  D.COL6 ELSE NULL END ),1) AS COL11
   
   
   FROM   CIS2.VW_DATA_ALL D 

                INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
                INNER JOIN CIS2.CLS_CLASS_ITEM CI ON (CLASS_CODE IN ('GEN_INSTITUTIE') AND R.GEN_INSTITUTIE=CI.ITEM_CODE AND CI.ITEM_CODE  IN ('5'))
                
               
                 WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1079)
  
  
  UNION  ALL 
  
  SELECT 
     6 ORDINE,
    '6' CODUL,
    'de papusi' DENUMIRE,
    COUNT (DISTINCT D.CUIIO) AS COL1,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL4 ELSE NULL END ) AS COL2,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL5 ELSE NULL END ) AS COL3,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL4,   
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL5,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 3 THEN D.CUIIO ELSE 0 END  ) AS COL6,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL2) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL7,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL2) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL8,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL3) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL9,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL3) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL10,
    ROUND(SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN  D.COL6 ELSE NULL END ),1) AS COL11
   
   
   FROM   CIS2.VW_DATA_ALL D 

                INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
                INNER JOIN CIS2.CLS_CLASS_ITEM CI ON (CLASS_CODE IN ('GEN_INSTITUTIE') AND R.GEN_INSTITUTIE=CI.ITEM_CODE AND CI.ITEM_CODE  IN ('6'))
                
               
                 WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1079)
  
  
  UNION  ALL 
  
  SELECT 
     7 ORDINE,
    '7' CODUL,
    'Organizatii concertistice de impresariat' DENUMIRE,
    COUNT (DISTINCT D.CUIIO) AS COL1,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL4 ELSE NULL END ) AS COL2,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL5 ELSE NULL END ) AS COL3,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL4,   
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL5,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 3 THEN D.CUIIO ELSE 0 END  ) AS COL6,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL2) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL7,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL2) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL8,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL3) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL9,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL3) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL10,
    ROUND(SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN  D.COL6 ELSE NULL END ),1) AS COL11
   
   
   FROM   CIS2.VW_DATA_ALL D 

                INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
                INNER JOIN CIS2.CLS_CLASS_ITEM CI ON (CLASS_CODE IN ('GEN_INSTITUTIE') AND R.GEN_INSTITUTIE=CI.ITEM_CODE AND CI.ITEM_CODE  IN ('7'))
                
               
                 WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1079)
  
  
  UNION  ALL 
  
  SELECT 
     8 ORDINE,
    '8' CODUL,
    'Organizatii concertistice' DENUMIRE,
    COUNT (DISTINCT D.CUIIO) AS COL1,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL4 ELSE NULL END ) AS COL2,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL5 ELSE NULL END ) AS COL3,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL4,   
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL5,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 3 THEN D.CUIIO ELSE 0 END  ) AS COL6,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL2) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL7,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL2) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL8,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL3) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL9,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL3) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL10,
    ROUND(SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN  D.COL6 ELSE NULL END ),1) AS COL11
   
   
   FROM   CIS2.VW_DATA_ALL D 

                INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
                INNER JOIN CIS2.CLS_CLASS_ITEM CI ON (CLASS_CODE IN ('GEN_INSTITUTIE') AND R.GEN_INSTITUTIE=CI.ITEM_CODE AND CI.ITEM_CODE  IN ('8'))
                
               
                 WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1079)
  
  
  UNION  ALL 
  
  SELECT 
     9 ORDINE,
    '9' CODUL,
    'Circ' DENUMIRE,
    COUNT (DISTINCT D.CUIIO) AS COL1,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL4 ELSE NULL END ) AS COL2,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL5 ELSE NULL END ) AS COL3,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL4,   
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL5,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 3 THEN D.CUIIO ELSE 0 END  ) AS COL6,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL2) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL7,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL2) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL8,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL3) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL9,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL3) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL10,
    ROUND(SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN  D.COL6 ELSE NULL END ),1) AS COL11
   
   
   FROM   CIS2.VW_DATA_ALL D 

                INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
                INNER JOIN CIS2.CLS_CLASS_ITEM CI ON (CLASS_CODE IN ('GEN_INSTITUTIE') AND R.GEN_INSTITUTIE=CI.ITEM_CODE AND CI.ITEM_CODE  IN (''))
                
               
                 WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1079)
  
 ) VB 
  
 
  
