    INSERT INTO    CIS2.TABLE_OUT
    (
      
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
  COL1,COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9
  
    )


    SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   VB.CODUL||'~'||ROWNUM AS NR_ROW,
   ROWNUM  AS ORDINE,
  '00000000000' AS DECIMAL_POS, 
   VB.DENUMIRE AS NUME_ROW,
   VB.COL1  AS COL1,
   VB.COL2  AS COL2,
   VB.COL3  AS COL3,
   VB.COL4  AS COL4,
   VB.COL5  AS COL5,
   VB.COL6  AS COL6,
   VB.COL7  AS COL7,
   VB.COL8  AS COL8,
   VB.COL9  AS COL9
 
   
  

FROM
(
    
    SELECT
    CC.CODUL,
    CC.DENUMIRE,
    SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 ELSE NULL END )  AS COL1,
    SUM(CASE WHEN D.RIND IN ('20') THEN D.COL1 ELSE NULL END )  AS COL2,
    SUM(CASE WHEN D.RIND IN ('30') THEN D.COL1 ELSE NULL END )  AS COL3,
    SUM(CASE WHEN D.RIND IN ('40') THEN D.COL1 ELSE NULL END )  AS COL4,
    SUM(CASE WHEN D.RIND IN ('50') THEN D.COL1 ELSE NULL END )  AS COL5,
    SUM(CASE WHEN D.RIND IN ('60') THEN D.COL1 ELSE NULL END )  AS COL6,
    SUM(CASE WHEN D.RIND IN ('70') THEN D.COL1 ELSE NULL END )  AS COL7,
    SUM(CASE WHEN D.RIND IN ('80') THEN D.COL1 ELSE NULL END )  AS COL8,
    SUM(CASE WHEN D.RIND IN ('90') THEN D.COL1 ELSE NULL END )  AS COL9
   
   
   FROM   CIS2.VW_DATA_ALL D 

                INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
                INNER JOIN CIS2.VW_CL_CFP C  ON (C.CODUL = D.CFP)
                INNER JOIN CIS2.VW_CL_CFP CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
                
                
  WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1078)
  
  AND CC.CODUL IN ('11','15','00')
  
  GROUP BY 
  CC.CODUL,
  CC.DENUMIRE
  ) VB
 
  
