    SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   VB.CODUL||'~'||ROWNUM AS NR_ROW,
   ROWNUM  AS ORDINE,
  '00000000000' AS DECIMAL_POS, 
   VB.DENUMIRE AS NUME_ROW,
   VB.COL1  AS COL1,
   VB.COL2  AS COL2,
   VB.COL3  AS COL3,
   VB.COL4  AS COL4,
   VB.COL5  AS COL5,
   VB.COL6  AS COL6,
   VB.COL7  AS COL7,
   VB.COL8  AS COL8,
   VB.COL9  AS COL9,
   VB.COL10  AS COL10,
   VB.COL11  AS COL11
   
  

FROM
(
    
    SELECT
    CC.CODUL,
    CC.DENUMIRE,
    COUNT (DISTINCT D.CUIIO) AS COL1,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL4 ELSE NULL END ) AS COL2,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL5 ELSE NULL END ) AS COL3,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL4,   
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL5,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL1) = 3 THEN D.CUIIO ELSE 0 END  ) AS COL6,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL2) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL7,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL2) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL8,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL3) = 1 THEN D.CUIIO ELSE 0 END  ) AS COL9,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  CIS2.NVAL(D.COL3) = 2 THEN D.CUIIO ELSE 0 END  ) AS COL10,
    ROUND(SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN  D.COL6 ELSE NULL END ),1) AS COL11
   
   
   FROM   CIS2.VW_DATA_ALL D 

                INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
                INNER JOIN CIS2.VW_CL_CFP C  ON (C.CODUL = D.CFP)
                INNER JOIN CIS2.VW_CL_CFP CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
                
                
  WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1079)
  
  AND CC.CODUL IN ('11','15','00')
  
  GROUP BY 
  CC.CODUL,
  CC.DENUMIRE
  ) VB