SELECT 


  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  
   VB.CODUL||'~'||ROWNUM  AS NR_ROW,
   ROWNUM AS ORDINE,
  '00000000000' AS DECIMAL_POS, 
   VB.DENUMIRE AS NUME_ROW,
   VB.COL1,
   VB.COL2,
   VB.COL3,
   VB.COL4,
   VB.COL5,
   VB.COL6,
   VB.COL7,
   VB.COL8,
   VB.COL9,
   VB.COL10,
   VB.COL11
   FROM

(
SELECT
   1 ORDINE,
  '1' CODUL,
    'Teatre profesionale' DENUMIRE,
   NULL  AS COL1,
   NULL  AS COL2,
   NULL  AS COL3,
   NULL  AS COL4,
   NULL  AS COL5,
   NULL  AS COL6,
   NULL  AS COL7,
   NULL  AS COL8,
   NULL  AS COL9,
   NULL  AS COL10,
   NULL  AS COL11
FROM   DUAL

UNION ALL  

  SELECT *

FROM(
 SELECT
  2 ORDINE,
   MR.RIND AS NR_ROW,
   MR.DENUMIRE NUME_ROW,
   SUM(CIS2.NVAL(D.COL1)) AS COL1,
   SUM(CIS2.NVAL(D.COL2)) AS COL2,
   SUM(CIS2.NVAL(D.COL3)) AS COL3,
   SUM(CIS2.NVAL(D.COL4)) AS COL4,
   SUM(CIS2.NVAL(D.COL5)) AS COL5,
   SUM(CIS2.NVAL(D.COL6)) AS COL6,
   SUM(CIS2.NVAL(D.COL7)) AS COL7,
   SUM(CIS2.NVAL(D.COL8)) AS COL8,
   SUM(CIS2.NVAL(D.COL9)) AS COL9,
   SUM(CIS2.NVAL(D.COL10)) AS COL10,
   SUM(CIS2.NVAL(D.COL11)) AS COL11
     
   
FROM 
  VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
 INNER JOIN CIS2.CLS_CLASS_ITEM CI ON (CLASS_CODE IN ('GEN_INSTITUTIE') AND R.GEN_INSTITUTIE=CI.ITEM_CODE AND CI.ITEM_CODE NOT IN ('9','8','10'))
  RIGHT JOIN MD_RIND MR ON (D.FORM=MR.FORM AND D.ID_MD=MR.ID_MD AND D.CAPITOL=MR.CAPITOL AND 
  
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')

  
WHERE
  MR.FORM IN (55)                 AND 
  MR.CAPITOL IN (1080) 
GROUP BY
  MR.RIND,
  MR.DENUMIRE,
  MR.ORDINE
  
  ORDER BY
  ORDINE,
  MR.ORDINE
  )
  
---------------------------------------------------------------------------------------

  
  
  UNION ALL 
  
  
  SELECT
   3 ORDINE,
  '2' CODUL,
  'de opera si balet' DENUMIRE,
   NULL  AS COL1,
   NULL  AS COL2,
   NULL  AS COL3,
   NULL  AS COL4,
   NULL  AS COL5,
   NULL  AS COL6,
   NULL  AS COL7,
   NULL  AS COL8,
   NULL  AS COL9,
   NULL  AS COL10,
   NULL  AS COL11
FROM   DUAL

UNION ALL  

  SELECT *

FROM(
 SELECT
  4 ORDINE,
   MR.RIND AS NR_ROW,
   MR.DENUMIRE NUME_ROW,
   SUM(CIS2.NVAL(D.COL1)) AS COL1,
   SUM(CIS2.NVAL(D.COL2)) AS COL2,
   SUM(CIS2.NVAL(D.COL3)) AS COL3,
   SUM(CIS2.NVAL(D.COL4)) AS COL4,
   SUM(CIS2.NVAL(D.COL5)) AS COL5,
   SUM(CIS2.NVAL(D.COL6)) AS COL6,
   SUM(CIS2.NVAL(D.COL7)) AS COL7,
   SUM(CIS2.NVAL(D.COL8)) AS COL8,
   SUM(CIS2.NVAL(D.COL9)) AS COL9,
   SUM(CIS2.NVAL(D.COL10)) AS COL10,
   SUM(CIS2.NVAL(D.COL11)) AS COL11
     
   
FROM 
  VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
 INNER JOIN CIS2.CLS_CLASS_ITEM CI ON (CLASS_CODE IN ('GEN_INSTITUTIE') AND R.GEN_INSTITUTIE=CI.ITEM_CODE AND CI.ITEM_CODE IN ('2'))
  RIGHT JOIN MD_RIND MR ON (D.FORM=MR.FORM AND D.ID_MD=MR.ID_MD AND D.CAPITOL=MR.CAPITOL AND 
  
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')

  
WHERE
  MR.FORM IN (55)                 AND 
  MR.CAPITOL IN (1080) 
GROUP BY
  MR.RIND,
  MR.DENUMIRE,
  MR.ORDINE
  
  ORDER BY
  ORDINE,
  MR.ORDINE
  )
  
  
-----------------------------------------------------------------------------------------  
 
UNION ALL 
  
  
  SELECT
   5 ORDINE,
  '3' CODUL,
  'dramatice, de comedie si muzicale' DENUMIRE,
   NULL  AS COL1,
   NULL  AS COL2,
   NULL  AS COL3,
   NULL  AS COL4,
   NULL  AS COL5,
   NULL  AS COL6,
   NULL  AS COL7,
   NULL  AS COL8,
   NULL  AS COL9,
   NULL  AS COL10,
   NULL  AS COL11
FROM   DUAL

UNION ALL  

  SELECT *

FROM(
 SELECT
  6 ORDINE,
   MR.RIND AS NR_ROW,
   MR.DENUMIRE NUME_ROW,
   SUM(CIS2.NVAL(D.COL1)) AS COL1,
   SUM(CIS2.NVAL(D.COL2)) AS COL2,
   SUM(CIS2.NVAL(D.COL3)) AS COL3,
   SUM(CIS2.NVAL(D.COL4)) AS COL4,
   SUM(CIS2.NVAL(D.COL5)) AS COL5,
   SUM(CIS2.NVAL(D.COL6)) AS COL6,
   SUM(CIS2.NVAL(D.COL7)) AS COL7,
   SUM(CIS2.NVAL(D.COL8)) AS COL8,
   SUM(CIS2.NVAL(D.COL9)) AS COL9,
   SUM(CIS2.NVAL(D.COL10)) AS COL10,
   SUM(CIS2.NVAL(D.COL11)) AS COL11
     
   
FROM 
  VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
 INNER JOIN CIS2.CLS_CLASS_ITEM CI ON (CLASS_CODE IN ('GEN_INSTITUTIE') AND R.GEN_INSTITUTIE=CI.ITEM_CODE AND CI.ITEM_CODE IN ('3'))
  RIGHT JOIN MD_RIND MR ON (D.FORM=MR.FORM AND D.ID_MD=MR.ID_MD AND D.CAPITOL=MR.CAPITOL AND 
  
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')

  
WHERE
  MR.FORM IN (55)                 AND 
  MR.CAPITOL IN (1080) 
GROUP BY
  MR.RIND,
  MR.DENUMIRE,
  MR.ORDINE
  
  ORDER BY
  ORDINE,
  MR.ORDINE
  )
 

-------------------------------------------------------------------------------------


UNION ALL 
  
  
  SELECT
   7 ORDINE,
  '4' CODUL,
  'pentru copii si tineret' DENUMIRE,
   NULL  AS COL1,
   NULL  AS COL2,
   NULL  AS COL3,
   NULL  AS COL4,
   NULL  AS COL5,
   NULL  AS COL6,
   NULL  AS COL7,
   NULL  AS COL8,
   NULL  AS COL9,
   NULL  AS COL10,
   NULL  AS COL11
FROM   DUAL

UNION ALL  

  SELECT *

FROM(
 SELECT
  8 ORDINE,
   MR.RIND AS NR_ROW,
   MR.DENUMIRE NUME_ROW,
   SUM(CIS2.NVAL(D.COL1)) AS COL1,
   SUM(CIS2.NVAL(D.COL2)) AS COL2,
   SUM(CIS2.NVAL(D.COL3)) AS COL3,
   SUM(CIS2.NVAL(D.COL4)) AS COL4,
   SUM(CIS2.NVAL(D.COL5)) AS COL5,
   SUM(CIS2.NVAL(D.COL6)) AS COL6,
   SUM(CIS2.NVAL(D.COL7)) AS COL7,
   SUM(CIS2.NVAL(D.COL8)) AS COL8,
   SUM(CIS2.NVAL(D.COL9)) AS COL9,
   SUM(CIS2.NVAL(D.COL10)) AS COL10,
   SUM(CIS2.NVAL(D.COL11)) AS COL11
     
   
FROM 
  VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
 INNER JOIN CIS2.CLS_CLASS_ITEM CI ON (CLASS_CODE IN ('GEN_INSTITUTIE') AND R.GEN_INSTITUTIE=CI.ITEM_CODE AND CI.ITEM_CODE IN ('5','6'))
  RIGHT JOIN MD_RIND MR ON (D.FORM=MR.FORM AND D.ID_MD=MR.ID_MD AND D.CAPITOL=MR.CAPITOL AND 
  
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')

  
WHERE
  MR.FORM IN (55)                 AND 
  MR.CAPITOL IN (1080) 
GROUP BY
  MR.RIND,
  MR.DENUMIRE,
  MR.ORDINE
  
  ORDER BY
  ORDINE,
  MR.ORDINE
  )
   
  
  
----------------------------------------------------------------------------------------

UNION ALL 
  
  
  SELECT
   9 ORDINE,
  '5' CODUL,
  'de papusi' DENUMIRE,
   NULL  AS COL1,
   NULL  AS COL2,
   NULL  AS COL3,
   NULL  AS COL4,
   NULL  AS COL5,
   NULL  AS COL6,
   NULL  AS COL7,
   NULL  AS COL8,
   NULL  AS COL9,
   NULL  AS COL10,
   NULL  AS COL11
FROM   DUAL

UNION ALL  

  SELECT *

FROM(
 SELECT
  10 ORDINE,
   MR.RIND AS NR_ROW,
   MR.DENUMIRE NUME_ROW,
   SUM(CIS2.NVAL(D.COL1)) AS COL1,
   SUM(CIS2.NVAL(D.COL2)) AS COL2,
   SUM(CIS2.NVAL(D.COL3)) AS COL3,
   SUM(CIS2.NVAL(D.COL4)) AS COL4,
   SUM(CIS2.NVAL(D.COL5)) AS COL5,
   SUM(CIS2.NVAL(D.COL6)) AS COL6,
   SUM(CIS2.NVAL(D.COL7)) AS COL7,
   SUM(CIS2.NVAL(D.COL8)) AS COL8,
   SUM(CIS2.NVAL(D.COL9)) AS COL9,
   SUM(CIS2.NVAL(D.COL10)) AS COL10,
   SUM(CIS2.NVAL(D.COL11)) AS COL11
     
   
FROM 
  VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
 INNER JOIN CIS2.CLS_CLASS_ITEM CI ON (CLASS_CODE IN ('GEN_INSTITUTIE') AND R.GEN_INSTITUTIE=CI.ITEM_CODE AND CI.ITEM_CODE IN ('5'))
  RIGHT JOIN MD_RIND MR ON (D.FORM=MR.FORM AND D.ID_MD=MR.ID_MD AND D.CAPITOL=MR.CAPITOL AND 
  
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')

  
WHERE
  MR.FORM IN (55)                 AND 
  MR.CAPITOL IN (1080) 
GROUP BY
  MR.RIND,
  MR.DENUMIRE,
  MR.ORDINE
  
  ORDER BY
  ORDINE,
  MR.ORDINE
  )
  
 --------------------------------------------------------------------------------------------------------------
 
 UNION ALL 
  
  
  SELECT
   11 ORDINE,
  '6' CODUL,
  'Studiou teatral' DENUMIRE,
   NULL  AS COL1,
   NULL  AS COL2,
   NULL  AS COL3,
   NULL  AS COL4,
   NULL  AS COL5,
   NULL  AS COL6,
   NULL  AS COL7,
   NULL  AS COL8,
   NULL  AS COL9,
   NULL  AS COL10,
   NULL  AS COL11
FROM   DUAL

UNION ALL  

  SELECT *

FROM(
 SELECT
  12 ORDINE,
   MR.RIND AS NR_ROW,
   MR.DENUMIRE NUME_ROW,
   SUM(CIS2.NVAL(D.COL1)) AS COL1,
   SUM(CIS2.NVAL(D.COL2)) AS COL2,
   SUM(CIS2.NVAL(D.COL3)) AS COL3,
   SUM(CIS2.NVAL(D.COL4)) AS COL4,
   SUM(CIS2.NVAL(D.COL5)) AS COL5,
   SUM(CIS2.NVAL(D.COL6)) AS COL6,
   SUM(CIS2.NVAL(D.COL7)) AS COL7,
   SUM(CIS2.NVAL(D.COL8)) AS COL8,
   SUM(CIS2.NVAL(D.COL9)) AS COL9,
   SUM(CIS2.NVAL(D.COL10)) AS COL10,
   SUM(CIS2.NVAL(D.COL11)) AS COL11
     
   
FROM 
  VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
 INNER JOIN CIS2.CLS_CLASS_ITEM CI ON (CLASS_CODE IN ('GEN_INSTITUTIE') AND R.GEN_INSTITUTIE=CI.ITEM_CODE AND CI.ITEM_CODE IN ('6'))
  RIGHT JOIN MD_RIND MR ON (D.FORM=MR.FORM AND D.ID_MD=MR.ID_MD AND D.CAPITOL=MR.CAPITOL AND 
  
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')

  
WHERE
  MR.FORM IN (55)                 AND 
  MR.CAPITOL IN (1080) 
GROUP BY
  MR.RIND,
  MR.DENUMIRE,
  MR.ORDINE
  
  ORDER BY
  ORDINE,
  MR.ORDINE
  )
 
 
 
 ---------------------------------------------------------------------------------------------
 UNION ALL 
  
  
  SELECT
   13 ORDINE,
  '7' CODUL,
  'Organizatii concertistice de impresariat' DENUMIRE,
   NULL  AS COL1,
   NULL  AS COL2,
   NULL  AS COL3,
   NULL  AS COL4,
   NULL  AS COL5,
   NULL  AS COL6,
   NULL  AS COL7,
   NULL  AS COL8,
   NULL  AS COL9,
   NULL  AS COL10,
   NULL  AS COL11
FROM   DUAL

UNION ALL  

  SELECT *

FROM(
 SELECT
  14 ORDINE,
   MR.RIND AS NR_ROW,
   MR.DENUMIRE NUME_ROW,
   SUM(CIS2.NVAL(D.COL1)) AS COL1,
   SUM(CIS2.NVAL(D.COL2)) AS COL2,
   SUM(CIS2.NVAL(D.COL3)) AS COL3,
   SUM(CIS2.NVAL(D.COL4)) AS COL4,
   SUM(CIS2.NVAL(D.COL5)) AS COL5,
   SUM(CIS2.NVAL(D.COL6)) AS COL6,
   SUM(CIS2.NVAL(D.COL7)) AS COL7,
   SUM(CIS2.NVAL(D.COL8)) AS COL8,
   SUM(CIS2.NVAL(D.COL9)) AS COL9,
   SUM(CIS2.NVAL(D.COL10)) AS COL10,
   SUM(CIS2.NVAL(D.COL11)) AS COL11
     
   
FROM 
  VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
 INNER JOIN CIS2.CLS_CLASS_ITEM CI ON (CLASS_CODE IN ('GEN_INSTITUTIE') AND R.GEN_INSTITUTIE=CI.ITEM_CODE AND CI.ITEM_CODE IN ('7'))
  RIGHT JOIN MD_RIND MR ON (D.FORM=MR.FORM AND D.ID_MD=MR.ID_MD AND D.CAPITOL=MR.CAPITOL AND 
  
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')

  
WHERE
  MR.FORM IN (55)                 AND 
  MR.CAPITOL IN (1080) 
GROUP BY
  MR.RIND,
  MR.DENUMIRE,
  MR.ORDINE
  
  ORDER BY
  ORDINE,
  MR.ORDINE
  )
 
 
 ----------------------------------------------------------------------------------------------
 
 UNION ALL 
  
  
  SELECT
   15 ORDINE,
  '8' CODUL,
  'Organizatii concertistice' DENUMIRE,
   NULL  AS COL1,
   NULL  AS COL2,
   NULL  AS COL3,
   NULL  AS COL4,
   NULL  AS COL5,
   NULL  AS COL6,
   NULL  AS COL7,
   NULL  AS COL8,
   NULL  AS COL9,
   NULL  AS COL10,
   NULL  AS COL11
FROM   DUAL

UNION ALL  

  SELECT *

FROM(
 SELECT
  16 ORDINE,
   MR.RIND AS NR_ROW,
   MR.DENUMIRE NUME_ROW,
   SUM(CIS2.NVAL(D.COL1)) AS COL1,
   SUM(CIS2.NVAL(D.COL2)) AS COL2,
   SUM(CIS2.NVAL(D.COL3)) AS COL3,
   SUM(CIS2.NVAL(D.COL4)) AS COL4,
   SUM(CIS2.NVAL(D.COL5)) AS COL5,
   SUM(CIS2.NVAL(D.COL6)) AS COL6,
   SUM(CIS2.NVAL(D.COL7)) AS COL7,
   SUM(CIS2.NVAL(D.COL8)) AS COL8,
   SUM(CIS2.NVAL(D.COL9)) AS COL9,
   SUM(CIS2.NVAL(D.COL10)) AS COL10,
   SUM(CIS2.NVAL(D.COL11)) AS COL11
     
   
FROM 
  VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
 INNER JOIN CIS2.CLS_CLASS_ITEM CI ON (CLASS_CODE IN ('GEN_INSTITUTIE') AND R.GEN_INSTITUTIE=CI.ITEM_CODE AND CI.ITEM_CODE IN ('8'))
  RIGHT JOIN MD_RIND MR ON (D.FORM=MR.FORM AND D.ID_MD=MR.ID_MD AND D.CAPITOL=MR.CAPITOL AND 
  
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')

  
WHERE
  MR.FORM IN (55)                 AND 
  MR.CAPITOL IN (1080) 
GROUP BY
  MR.RIND,
  MR.DENUMIRE,
  MR.ORDINE
  
  ORDER BY
  ORDINE,
  MR.ORDINE
  )
 -----------------------------------------------------------------------------------------------
 
 UNION ALL 
  
  
  SELECT
   17 ORDINE,
  '9' CODUL,
  'Circ' DENUMIRE,
   NULL  AS COL1,
   NULL  AS COL2,
   NULL  AS COL3,
   NULL  AS COL4,
   NULL  AS COL5,
   NULL  AS COL6,
   NULL  AS COL7,
   NULL  AS COL8,
   NULL  AS COL9,
   NULL  AS COL10,
   NULL  AS COL11
FROM   DUAL

UNION ALL  

  SELECT *

FROM(
 SELECT
  18 ORDINE,
   MR.RIND AS NR_ROW,
   MR.DENUMIRE NUME_ROW,
   SUM(CIS2.NVAL(D.COL1)) AS COL1,
   SUM(CIS2.NVAL(D.COL2)) AS COL2,
   SUM(CIS2.NVAL(D.COL3)) AS COL3,
   SUM(CIS2.NVAL(D.COL4)) AS COL4,
   SUM(CIS2.NVAL(D.COL5)) AS COL5,
   SUM(CIS2.NVAL(D.COL6)) AS COL6,
   SUM(CIS2.NVAL(D.COL7)) AS COL7,
   SUM(CIS2.NVAL(D.COL8)) AS COL8,
   SUM(CIS2.NVAL(D.COL9)) AS COL9,
   SUM(CIS2.NVAL(D.COL10)) AS COL10,
   SUM(CIS2.NVAL(D.COL11)) AS COL11
     
   
FROM 
  VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
 INNER JOIN CIS2.CLS_CLASS_ITEM CI ON (CLASS_CODE IN ('GEN_INSTITUTIE') AND R.GEN_INSTITUTIE=CI.ITEM_CODE AND CI.ITEM_CODE IN ('9'))
  RIGHT JOIN MD_RIND MR ON (D.FORM=MR.FORM AND D.ID_MD=MR.ID_MD AND D.CAPITOL=MR.CAPITOL AND 
  
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')

  
WHERE
  MR.FORM IN (55)                 AND 
  MR.CAPITOL IN (1080) 
GROUP BY
  MR.RIND,
  MR.DENUMIRE,
  MR.ORDINE
  
  ORDER BY
  ORDINE,
  MR.ORDINE
  )
  -----------------------------------------------------------------------------------------------
  ORDER BY   
  ORDINE,
  CODUL
  
  ) VB 