-- INSERT INTO    --USER_BANCU.TABLE_OUT_TEST
-- 
--  CIS2.TABLE_OUT
--    (
--      
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
--  COL1,COL2, COL3, COL4, COL5, COL6
--  
--    )




   SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  
   VB.DEN_CUATM||'~'||ROWNUM  AS NR_ROW,
   ROWNUM AS ORDINE,
  '00000000000' AS DECIMAL_POS, 
   VB.DENUMIRE AS NUME_ROW,
   VB.COL1,
   VB.COL2,
   VB.COL3,
   VB.COL4,
   VB.COL5,
   VB.COL6  
   FROM

(
 SELECT
   R.CUIIO,
   R.GEN_INSTITUTIE, 
   CASE WHEN  C.DENUMIRE LIKE 'SEC%'  THEN  'MUN.CHISINAU'      
        WHEN  C.DENUMIRE LIKE 'OR.BALTI%'  THEN  'MUN.BALTI'     
   ELSE C.DENUMIRE  END           DEN_CUATM,
   MAX(R.DENUMIRE)  DENUMIRE,
   SUM(CASE WHEN  D.CAPITOL IN (1079) AND D.RIND IN ('100') THEN D.COL4 ELSE NULL END) AS COL1,
   SUM(CASE WHEN  D.CAPITOL IN (1078) AND D.RIND IN ('10') THEN D.COL1 ELSE NULL END) AS COL2,
   SUM(CASE WHEN  D.CAPITOL IN (1078) AND D.RIND IN ('50') THEN D.COL1 ELSE NULL END) AS COL3,
   SUM(CASE WHEN  D.CAPITOL IN (1078) AND D.RIND IN ('10') THEN D.COL2 ELSE NULL END) AS COL4,
   SUM(CASE WHEN  D.CAPITOL IN (1078) AND D.RIND IN ('70') THEN D.COL1 ELSE NULL END) AS COL5,
   SUM(CASE WHEN  D.CAPITOL IN (1080) AND D.RIND IN ('110') THEN D.COL1 ELSE NULL END) AS COL6
     
   
FROM 
  CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
  INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM = C.CODUL)
  
 
  WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND 

  D.FORM IN (55) AND                
  D.CAPITOL IN (1078,1079,1080) 

GROUP BY
 R.CUIIO,
 R.GEN_INSTITUTIE,
 C.DENUMIRE,
 C.FULL_CODE
 
 
 ORDER BY
 R.GEN_INSTITUTIE,
 C.FULL_CODE
 
 ) VB
 
  
 