SELECT   
    'Rind '||D.RIND||':  '||  
    NVAL(SUM(CASE WHEN D.PERIOADA=:PERIOADA THEN D.COL1 ELSE 0 END)) ||'<>'||  
    NVAL(SUM(CASE WHEN D.PERIOADA=:PERIOADA THEN D.COL3 ELSE 0 END))
   
  AS REZULTAT

FROM
  USER_EREPORTING.VW_DATA_ALL_FOR_VALIDATE  D
 

WHERE
  (D.PERIOADA =:PERIOADA        OR :PERIOADA=  -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (7)  AND
  D.CAPITOL IN (313) AND
  D.NUM IN (1)
  AND  D.ID_SCHEMA IN (2)
 
GROUP BY D.RIND

    HAVING

   NVAL(SUM(CASE WHEN D.PERIOADA=:PERIOADA THEN D.COL1 ELSE 0 END))<>
  NVAL(SUM(CASE WHEN D.PERIOADA=:PERIOADA THEN D.COL3 ELSE 0 END))