SELECT 
  'Ati selectat '||SUM(R.CNUM)||' cauza(e)' AS REZULTAT 
FROM
(

SELECT COUNT(D.COL1) AS CNUM
FROM VW_DATA_ALL_GC D
WHERE
   
   (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.NR_GOSP=:NR_GOSP               OR :NR_GOSP = -1) AND
  (D.UNIT_CODE_VERS=:UNIT_CODE_VERS     OR :UNIT_CODE_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  

  D.FORM IN (62)  AND
  D.CAPITOL IN (1118)
  AND D.RIND NOT IN ('CA','-','TIP2','TIP3','0')

UNION
SELECT 0 AS CNUM
FROM DUAL

) R
WHERE
 1=1
HAVING
  SUM(R.CNUM)=0