SELECT * 

FROM

(
 
    SELECT 'Bovine - total' AS DENUMIRE, 1 AS ORDINE,  '010' AS RIND FROM DUAL UNION  
    SELECT '  vaci' AS DENUMIRE, 2 AS ORDINE,  '011' AS RIND FROM DUAL UNION   
    SELECT '  tineret 0-6 luni' AS DENUMIRE,3 AS ORDINE,  '012' AS RIND FROM DUAL UNION 
    SELECT '  tineret 6 luni pina la 1 an' AS DENUMIRE, 4 AS ORDINE,  '013' AS RIND FROM DUAL UNION 
    SELECT '  tineret peste 1 an' AS DENUMIRE, 4 AS ORDINE,  '014' AS RIND FROM DUAL UNION   
    SELECT '    din care junci peste 18 luni' AS DENUMIRE, 5 AS ORDINE,  '015' AS RIND FROM DUAL  UNION
    SELECT 'Porcine - total' AS DENUMIRE, 6 AS ORDINE,  '020' AS RIND FROM DUAL   UNION   
    SELECT '  scroafe de baza' AS DENUMIRE,7 AS ORDINE,  '021' AS RIND FROM DUAL  UNION 
    SELECT '  porcine 0-4 luni' AS DENUMIRE,8 AS ORDINE,  '022' AS RIND FROM DUAL  UNION
    SELECT '  porcine peste 4 luni' AS DENUMIRE,9 AS ORDINE,  '023' AS RIND FROM DUAL  UNION
    SELECT '    din care purcele de repr.de  la 9 lun' AS DENUMIRE,10 AS ORDINE,  '024' AS RIND FROM DUAL UNION  
    SELECT 'Ovine - total' AS DENUMIRE,11 AS ORDINE,  '030' AS RIND FROM DUAL  UNION
    SELECT '  oi fatatoare' AS DENUMIRE,12 AS ORDINE,  '031' AS RIND FROM DUAL UNION
    SELECT '  mioare de 1 an si peste' AS DENUMIRE,13 AS ORDINE,  '032' AS RIND FROM DUAL UNION 
    SELECT '  tineret pina la 1 an' AS DENUMIRE,14 AS ORDINE,  '033' AS RIND FROM DUAL    UNION
    SELECT 'Caprine - total' AS DENUMIRE,15 AS ORDINE,  '040' AS RIND FROM DUAL   UNION
    SELECT '  capre fatatoare de 1an si peste' AS DENUMIRE,16 AS ORDINE,  '041' AS RIND FROM DUAL UNION  
    SELECT '  tineret pina la 1 an' AS DENUMIRE,17 AS ORDINE,  '042' AS RIND FROM DUAL UNION 
    SELECT 'Cabaline' AS DENUMIRE,18 AS ORDINE,  '050' AS RIND FROM DUAL UNION
    SELECT '   adulte' AS DENUMIRE,20 AS ORDINE,  '051' AS RIND FROM DUAL UNION
    SELECT 'Gaini si cucosi total' AS DENUMIRE,21 AS ORDINE,  '060' AS RIND FROM DUAL UNION
    SELECT '  gaini ouatoare' AS DENUMIRE,22 AS ORDINE,  '061' AS RIND FROM DUAL  UNION 
    SELECT 'Giste total' AS DENUMIRE,23 AS ORDINE,  '070' AS RIND FROM DUAL  UNION 
    SELECT '  giste adulte' AS DENUMIRE,24 AS ORDINE,  '071' AS RIND FROM DUAL  UNION 
    SELECT 'Rate total' AS DENUMIRE,25 AS ORDINE,  '080' AS RIND FROM DUAL UNION    
    SELECT '  rate adulte' AS DENUMIRE,26 AS ORDINE,  '081' AS RIND FROM DUAL UNION
    SELECT 'Curcani total' AS DENUMIRE,27 AS ORDINE,  '090' AS RIND FROM DUAL UNION
    SELECT '  curcani adulti' AS DENUMIRE,28 AS ORDINE,  '091' AS RIND FROM DUAL UNION
    SELECT 'Iepuri total' AS DENUMIRE,29 AS ORDINE,  '100' AS RIND FROM DUAL UNION 
    SELECT '  iepuri adulti' AS DENUMIRE,30 AS ORDINE,  '101' AS RIND FROM DUAL UNION
    SELECT 'familii de albine' AS DENUMIRE,31 AS ORDINE,  '201' AS RIND FROM DUAL  
    
    
         
    
    ORDER BY 
    
    ORDINE   

) D