


SELECT 
D.UNIT_CODE,
D.CUATM,
D.RIND,
D.COL3

FROM
  VW_DATA_ALL_GC  D

WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN ('071') 
  AND D.COL3 IS NOT NULL 