


SELECT 
D.UNIT_CODE,
D.CUATM,
D.RIND,
D.COL4,
D.COL5,
D.COL18

FROM
  VW_DATA_ALL_GC  D

WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN ('021') 
  AND 
  
  (D.COL4 IS NOT NULL 
  OR   D.COL5 IS NOT NULL
  OR   D.COL8 IS NOT NULL
  )  