


SELECT 
D.UNIT_CODE,
D.CUATM,
D.RIND,
D.COL2

FROM
  VW_DATA_ALL_GC  D

WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (417)
  AND D.RIND IN ('061') 
  AND D.COL2 IS NOT NULL 
  AND 
  
  (D.CUATM LIKE '34%' OR D.CUATM LIKE '62%' OR D.CUATM LIKE '17%'
  
  )  