SELECT
        
      DISTINCT   D.UNIT_CODE,
      D.RIND,
      C.CODUL CUATM,
      SUM (D.COL2) AS COL2  
       
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (61)  AND
  D.CAPITOL IN (1112)
  AND D.RIND IN ('042','046','047','051','053')  
  
  GROUP BY 
  D.UNIT_CODE,
  D.RIND,
  C.CODUL 
  
 HAVING  
 SUM (D.COL2) > 0