SELECT
      DISTINCT   D.UNIT_CODE,
      D.RIND,
      C.CODUL,
      SUM (D.COL4) AS COL4  
       
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||'7100000'||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (417)
  AND D.RIND IN ('061')  
  
  GROUP BY 
  D.UNIT_CODE,
  D.RIND,
  C.CODUL 
  
 HAVING  
 SUM (D.COL4) > 0
 
 UNION 
 
 SELECT
      DISTINCT   D.UNIT_CODE,
      D.RIND,
      C.CODUL,
      SUM (D.COL4) AS COL4  
       
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||'5500000'||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (417)
  AND D.RIND IN ('061')  
  
  GROUP BY 
  D.UNIT_CODE,
  D.RIND,
  C.CODUL 
  
 HAVING  
 SUM (D.COL4) > 0
 
 
 UNION 
 
 SELECT
      DISTINCT   D.UNIT_CODE,
      D.RIND,
      C.CODUL,
      SUM (D.COL4) AS COL4  
       
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||'1200000'||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (417)
  AND D.RIND IN ('061')  
  
  GROUP BY 
  D.UNIT_CODE,
  D.RIND,
  C.CODUL 
  
 HAVING  
 SUM (D.COL4) > 0