SELECT
         2 ORDINE,    
         '01' rind, 
         'numai cu bovine' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')   AND D.RIND IN('010')  THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')   AND D.RIND IN('010')  THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')   AND D.RIND IN('010') THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    AND D.RIND IN('010') THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    AND D.RIND IN('010') THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')    AND D.RIND IN('010') THEN  D.UNIT_CODE ELSE NULL END) AS COL6,
          
 SUM (CASE WHEN D.RIND NOT IN('010','011','012', '013','014','015')  THEN  NVAL(D.COL1) +  NVAL(D.COL2) +  NVAL(D.COL3) +  NVAL(D.COL4) +  NVAL(D.COL5) +  NVAL(D.COL6)
+  NVAL(D.COL7) +  NVAL(D.COL8) +  NVAL(D.COL9) +  NVAL(D.COL10) +  NVAL(D.COL11) +  NVAL(D.COL2) +  NVAL(D.COL13) +  NVAL(D.COL14)
+  NVAL(D.COL15) +  NVAL(D.COL16) +  NVAL(D.COL17) +  NVAL(D.COL18) + NVAL(D.COL19) ELSE  0 END  ) AS COL7
          
          
          
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
--  AND D.RIND IN('010')
  --AND D.UNIT_CODE = 822257


HAVING 
 SUM (CASE WHEN D.RIND NOT IN('010','011','012', '013','014','015')  THEN  NVAL(D.COL1) +  NVAL(D.COL2) +  NVAL(D.COL3) +  NVAL(D.COL4) +  NVAL(D.COL5) +  NVAL(D.COL6)
+  NVAL(D.COL7) +  NVAL(D.COL8) +  NVAL(D.COL9) +  NVAL(D.COL10) +  NVAL(D.COL11) +  NVAL(D.COL2) +  NVAL(D.COL13) +  NVAL(D.COL14)
+  NVAL(D.COL15) +  NVAL(D.COL16) +  NVAL(D.COL17) +  NVAL(D.COL18) + NVAL(D.COL19) ELSE  0 END  ) = 0 


