SELECT 


      :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
    '0' AS NR_SECTIE,
    '0' AS NUME_SECTIE,
    '0' AS NR_SECTIE1,
    '0' AS NUME_SECTIE1,
    '0' AS NR_SECTIE2,
    '0' AS NUME_SECTIE2,  
      NULL||'~'||ROWNUM AS NR_ROW,  
      ROWNUM AS ORDINE,
      '002002002002' AS DECIMAL_POS,
     REPLACE(REPLACE(DENUMIRE, '<br>'),'</br>') AS NUME_ROW,
COL1, COL2, COL3,  COL4, COL5, COL6, COL7, COL8, COL9, COL10,  COL11, COL12
FROM
(
SELECT
     R.ORDINE,
     R.RIND,
     R.DENUMIRE,            
     SUM(D.COL18) AS COL1,
     SUM(D.COL4)  AS COL2,
     ROUND(SUM(D.COL18) / NOZERO(SUM(D.COL4)),2) AS COL3,
     SUM(D.COL18) AS COL4,
     SUM(D.COL5)  AS COL5,
     ROUND(SUM(D.COL18) / NOZERO(SUM(D.COL5)),2) AS COL6,
     SUM(D.COL19) AS COL7,
     SUM(D.COL9)  AS COL8,
     ROUND(SUM(D.COL19) / NOZERO(SUM(D.COL9)),2) AS COL9,
     SUM(D.COL19) AS COL10,
     SUM(D.COL10)  AS COL11,
     ROUND(SUM(D.COL19) / NOZERO(SUM(D.COL10)),2) AS COL12
     
     
      
    
   
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  
GROUP BY
  R.RIND,
  R.DENUMIRE,
  R.ORDINE
  
  
  UNION 
  
  SELECT
     17.2 ORDINE,
     '043' RIND,
     'Ovine si Caprine - total' DENUMIRE,            
     SUM(D.COL18) AS COL1,
     SUM(D.COL4)  AS COL2,
     ROUND(SUM(D.COL18) / NOZERO(SUM(D.COL4)),2) AS COL3,
     SUM(D.COL18) AS COL4,
     SUM(D.COL5)  AS COL5,
     ROUND(SUM(D.COL18) / NOZERO(SUM(D.COL5)),2) AS COL6,
     SUM(D.COL19) AS COL7,
     SUM(D.COL9)  AS COL8,
     ROUND(SUM(D.COL19) / NOZERO(SUM(D.COL9)),2) AS COL9,
     SUM(D.COL19) AS COL10,
     SUM(D.COL10)  AS COL11,
     ROUND(SUM(D.COL19) / NOZERO(SUM(D.COL10)),2) AS COL12
     
     
      
    
   
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND R.RIND IN ('030','040')
  
  
  
  UNION 
  
  
  SELECT
     27.2 ORDINE,
     '092' RIND,
     'Pasari - total' DENUMIRE,            
     SUM(D.COL18) AS COL1,
     SUM(D.COL4)  AS COL2,
     ROUND(SUM(D.COL18) / NOZERO(SUM(D.COL4)),2) AS COL3,
     SUM(D.COL18) AS COL4,
     SUM(D.COL5)  AS COL5,
     ROUND(SUM(D.COL18) / NOZERO(SUM(D.COL5)),2) AS COL6,
     SUM(D.COL19) AS COL7,
     SUM(D.COL9)  AS COL8,
     ROUND(SUM(D.COL19) / NOZERO(SUM(D.COL9)),2) AS COL9,
     SUM(D.COL19) AS COL10,
     SUM(D.COL10)  AS COL11,
     ROUND(SUM(D.COL19) / NOZERO(SUM(D.COL10)),2) AS COL12
     
     
      
    
   
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND R.RIND IN ('061','071','081','091')
  
  ORDER BY 
  
  ORDINE
  )