
SELECT 
  D.UNIT_CODE,
  
    
  COUNT (D.UNIT_CODE) AS CNT 
    
    FROM

(
SELECT
         7.1 ORDINE,
         D.UNIT_CODE,
         D.RIND,    
         '06.1'  rind_tab, 
         'numai  gaini' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('060')
  
    GROUP BY 
  D.UNIT_CODE,
  D.RIND
  
  UNION 
  
  
  SELECT
         7.2 ORDINE,
         D.UNIT_CODE,
         D.RIND,    
         '06.2'  rind_tab, 
         'numai  ga?te' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('070')
  
    GROUP BY 
  D.UNIT_CODE,
  D.RIND
  
  UNION 
  
  
  SELECT
         7.3 ORDINE,
         D.UNIT_CODE,
         D.RIND,    
         '06.3'  rind_tab, 
         'numai  ra?e' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('080')
  
    GROUP BY 
  D.UNIT_CODE,
  D.RIND
  
  UNION 
  
  ------------------
  SELECT
         7.4 ORDINE,
         D.UNIT_CODE,
         D.RIND,    
         '06.4'  rind_tab, 
         'numai curci' DENUMIRE,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0000000'||';%')    THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'0100000'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'1111111'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL3,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'2222222'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL4,
         COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'3333333'||';%')    THEN   D.UNIT_CODE ELSE NULL END) AS COL5,
          COUNT(DISTINCT CASE WHEN (D.CUATM_FULL LIKE '%'||'9600000'||';%')   THEN  D.UNIT_CODE ELSE NULL END) AS COL6
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
  INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND D.RIND IN('090')
  
   GROUP BY 
  D.UNIT_CODE,
  D.RIND
  )
  
  D
  
  
  
  GROUP BY 
  D.UNIT_CODE
  
  
  
  
 HAVING 
 
 COUNT (D.UNIT_CODE) = 4 
 