SELECT 
        D.UNIT_CODE,   
        SUM(D.COL16) AS COL16
         
               
FROM
  VW_DATA_ALL_GC  D
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  
  

  
  
  GROUP BY
  D.UNIT_CODE
--  R.RIND,
--  R.ORDINE,
--  R.DENUMIRE
--  
--  ORDER BY 
--  R.ORDINE