SELECT
     
      D.UNIT_CODE, 
      SUM(CASE WHEN D.RIND IN ('TIP2') THEN   D.COL1 ELSE NULL END )  AS COL1,
      SUM(CASE WHEN D.RIND IN ('TIP3') THEN   D.COL1 ELSE NULL END )  AS COL2
      
       
FROM
  VW_DATA_ALL_GC  D
 
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (419)
  AND D.RIND IN ('TIP2','TIP3')
  
  GROUP BY 
  D.UNIT_CODE
  
  
  HAVING 
  
   SUM(CASE WHEN D.RIND IN ('TIP2') THEN   D.COL1 ELSE NULL END )  IS NULL
   
   AND  
   
   SUM(CASE WHEN D.RIND IN ('TIP3') THEN   D.COL1 ELSE NULL END ) IS NULL