SELECT 
 D.CUIIO,
 D.RIND,
 
  SUM(D.COL2) AS COL1,
  SUM(D.COL3) AS COL2,
  SUM(D.COL4) AS COL3,
  SUM(D.COL5) AS COL4,
  SUM(D.COL6) AS COL5,
  SUM(D.COL7) AS COL6,
  SUM(D.COL8) AS COL7,
  SUM(D.COL9) AS COL8,
  SUM(D.COL10) AS COL9
 FROM VW_DATA_ALL D  

WHERE 
  (D.PERIOADA=:pPERIOADA) AND
  (D.FORM=:pFORM) AND
  (D.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  
  D.FORM = 14 AND
 -- FF.CODUL IN (00,11,14) AND
  D.CAPITOL IN (349)
  AND D.RIND IN ('700')
  
  
  GROUP BY
   D.CUIIO, 
   D.RIND