SELECT
  'Institutii de cercetari stiintifice' AS DENUMIRE,
  '2' AS RIND,
  RC.NR_ROW AS COD_CFP,
  RC.NUME_ROW AS DEN_CFP,
  COUNT( DISTINCT CASE WHEN D.RIND IN ('700') AND RC.CFP LIKE '%'||D.CFP||'%' THEN D.CUIIO END) AS COL1,
  SUM(CASE WHEN D.RIND IN ('700') AND RC.CFP LIKE '%'||D.CFP||'%' THEN CIS2.NVAL(D.COL9) END) AS COL2,
  SUM(CASE WHEN D.RIND IN ('700') AND RC.CFP LIKE '%'||D.CFP||'%' THEN CIS2.NVAL(D.COL10) END) AS COL3,
  SUM(CASE WHEN D.RIND IN ('700') AND RC.CFP LIKE '%'||D.CFP||'%' THEN CIS2.NVAL(D.COL4) END) AS COL4,
  SUM(CASE WHEN D.RIND IN ('700') AND RC.CFP LIKE '%'||D.CFP||'%' THEN CIS2.NVAL(D.COL6) END) AS COL5
  
FROM
  CIS2.VW_DATA_ALL D 
      INNER JOIN CIS2.VW_CL_CFP CP ON (D.CFP = CP.CODUL) 
  CROSS JOIN
  (     
    SELECT 'Total pe Republica' AS NUME_ROW,            '01' AS NR_ROW, '11-12-13-14-15-16-17-18-19-20-22-23-24-25-26-27-28-29' AS CFP FROM DUAL UNION
    SELECT 'Proprietate Statala' AS NUME_ROW,           '02' AS NR_ROW, '11-12-13'          AS CFP FROM DUAL UNION 
    SELECT 'Proprietate Ne Statala' AS NUME_ROW,        '03' AS NR_ROW, '14-15-16-17-18-19-20-22-23-24-25-26-27-28-29' AS CFP FROM DUAL
  ) RC 
WHERE 
  (D.PERIOADA=:pPERIOADA) AND
  (D.FORM=:pFORM) AND
  (D.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  
  D.FORM = 14 AND
  D.CAPITOL IN (349) AND
  D.TIP_INST IN (1)
   GROUP BY RC.NR_ROW, RC.NUME_ROW