--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
--  COL1, COL2, COL3,COL4,COL5,COL6,COL7,COL8,COL9
--)
SELECT
--  :pPERIOADA AS PERIOADA,
--  :pFORM AS FORM,
--  :pFORM_VERS AS FORM_VERS,
--  :pID_MDTABLE AS ID_MDTABLE,
--  :pCOD_CUATM AS COD_CUATM,
  
         
  COD_CFP AS NR_SECTIE,
  DEN_CFP AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  RIND||'~'||FULL_CODE||'_'||COD_CFP AS NR_ROW,
--  CASE WHEN RIND IN ('100') THEN 0 
--       WHEN RIND IN ('101') THEN 0.1 ELSE ROWNUM END ORDINE,
  ROWNUM AS ORDINE,
  '000000000000000' AS DECIMAL_POS,
  DENUMIRE AS NUME_ROW,
  COL2 AS COL1,
  COL3 AS COL2,
  COL4 AS COL3,
  COL5 AS COL4,
  COL6 AS COL5,
  COL7 AS COL6,
  COL8 AS COL7,
  COL9 AS COL8,
  COL10 AS COL9
FROM
(
SELECT
  MAX(CASE WHEN D.RIND IN ('700','701') THEN D.RIND ELSE SS.COD_SPEC END) AS RIND,
  MAX(CASE WHEN D.RIND IN ('700') THEN 0 
           WHEN D.RIND IN ('701') THEN 0.1 ELSE TO_NUMBER(D.RIND) END) AS ORDINE,
  MAX(CASE WHEN D.RIND IN ('700','701') THEN R.DENUMIRE ELSE SS.DENUMIRE END) AS DENUMIRE,
  MAX(CASE WHEN D.RIND IN ('700') THEN '00000;'
           WHEN D.RIND IN ('701') THEN '00000;00000;' ELSE SS.FULL_CODE END) AS FULL_CODE,
  SS.COD_SPEC,
  SS.DENUMIRE AS DENUMIRE_SPEC,
  SS.FULL_CODE AS FULL_CODE_SPEC,
  C.CAPITOL,
  C.DEN_SHORT AS CAPITOL_DEN,
  C.DENUMIRE AS DEN_CAPITOL,
  FF.CODUL AS COD_CFP,
  FF.DENUMIRE AS DEN_CFP,
  SUM(D.COL2) AS COL2,
  SUM(D.COL3) AS COL3,
  SUM(D.COL4) AS COL4,
  SUM(D.COL5) AS COL5,
  SUM(D.COL6) AS COL6,
  SUM(D.COL7) AS COL7,
  SUM(D.COL8) AS COL8,
  SUM(D.COL9) AS COL9,
  SUM(D.COL10) AS COL10
  
FROM
  VW_DATA_ALL D 
  INNER JOIN MD_RIND R    ON (D.ID_MD = R.ID_MD) 
  INNER JOIN MD_CAPITOL C ON (D.CAPITOL=C.CAPITOL AND D.CAPITOL_VERS = C.CAPITOL_VERS)
  LEFT JOIN VW_CL_CFP F  ON (D.CFP=F.CODUL)
  LEFT JOIN VW_CL_CFP FF ON (F.FULL_CODE LIKE '%'||FF.CODUL||';%' )
  LEFT JOIN VW_CL_SPEC2 S  ON (D.COL1=S.COD_SPEC)
  LEFT JOIN VW_CL_SPEC2 SS ON (S.FULL_CODE LIKE '%'||SS.COD_SPEC||';%' )
WHERE 
  (D.PERIOADA=:pPERIOADA) AND
  (D.FORM=:pFORM) AND
  (D.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  
  D.FORM = 14 AND
 -- FF.CODUL IN (00,11,14) AND
  D.CAPITOL IN (349)
--  AND CUIIO IN (2166868)
GROUP BY
--  D.RIND,
  R.DENUMIRE,
  SS.DENUMIRE,
  SS.COD_SPEC,
  SS.FULL_CODE,
  FF.CODUL,
  FF.DENUMIRE,
  C.CAPITOL,
  C.DEN_SHORT,
  C.DENUMIRE
ORDER BY 
  FF.CODUL,
  MAX(CASE WHEN D.RIND IN ('700') THEN '00000;'
           WHEN D.RIND IN ('701') THEN '00000;00000;' ELSE SS.FULL_CODE END)
--  FF.CODUL,
--  MAX(CASE WHEN D.RIND IN ('100') THEN 0 
--       WHEN D.RIND IN ('101') THEN 0.1 ELSE TO_NUMBER(D.RIND) END)
) 
--GROUP BY
--  COD_CFP,
--  DEN_CFP,
--  RIND,
--  FULL_CODE,
--  ROWNUM,
--  DENUMIRE