INSERT INTO TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,

  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
  COL1, COL2, COL3,COL4,COL5,COL6,COL7,COL8,COL9,COL10,COL11,COL12,COL13,COL14,COL15
)
----------------------------------------------------------------

SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  
         
  COD_CFP AS NR_SECTIE,
  DEN_CFP AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  RIND||'~'||FULL_CODE AS NR_ROW,
  ORDINE ORDINE,
  '000000000000000' AS DECIMAL_POS,
  DENUMIRE AS NUME_ROW,
  SUM(COL2) AS COL1,
  SUM(COL3) AS COL2,
  SUM(COL4) AS COL3,
  SUM(COL5) AS COL4,
  SUM(COL6) AS COL5,
  SUM(COL7) AS COL6,
  SUM(COL8) AS COL7,
  SUM(COL9) AS COL8,
  SUM(COL10) AS COL9,
  SUM(COL11) AS COL10,
  SUM(COL12) AS COL11,
  SUM(COL13) AS COL12,
  SUM(COL14) AS COL13,
  SUM(COL15) AS COL14,
  SUM(COL16) AS COL15
FROM
(
SELECT
  D.RIND AS RINDURI,
  CASE WHEN LENGTH(D.RIND)=3 THEN D.RIND ELSE T.CODUL END AS RIND,
    R.ORDINE,
  CASE WHEN LENGTH(D.RIND)=3 THEN R.DENUMIRE ELSE T.DENUMIRE END AS DENUMIRE,
  SS.COD_SPEC,
  SS.FULL_CODE,
  C.CAPITOL,
  C.DEN_SHORT AS CAPITOL_DEN,
  C.DENUMIRE AS DEN_CAPITOL,
  FF.CODUL AS COD_CFP,
  FF.DENUMIRE AS DEN_CFP,
  SUM(D.COL2) AS COL2,
  SUM(D.COL3) AS COL3,
  SUM(D.COL4) AS COL4,
  SUM(D.COL5) AS COL5,
  SUM(D.COL6) AS COL6,
  SUM(D.COL7) AS COL7,
  SUM(D.COL8) AS COL8,
  SUM(D.COL9) AS COL9,
  SUM(D.COL10) AS COL10,
  SUM(D.COL11) AS COL11,
  SUM(D.COL12) AS COL12,
  SUM(D.COL13) AS COL13,
  SUM(D.COL14) AS COL14,
  SUM(D.COL15) AS COL15,
  SUM(D.COL16) AS COL16
  
FROM
  VW_DATA_ALL D 
  INNER JOIN MD_RIND R    ON (D.ID_MD = R.ID_MD) 
  INNER JOIN MD_CAPITOL C ON (D.CAPITOL=C.CAPITOL AND D.CAPITOL_VERS = C.CAPITOL_VERS)
  LEFT JOIN CL_TARI_CS T  ON (D.COL1=T.CODUL )
  --INNER JOIN CL_TIP_INST I ON (D.TIP_INST=I.CODUL)
  --INNER JOIN VW_CL_CFP C ON (D.CFP=C.CODUL)
  LEFT JOIN VW_CL_CFP F  ON (D.CFP=F.CODUL)
  LEFT JOIN VW_CL_CFP FF ON (F.FULL_CODE LIKE '%'||FF.CODUL||';%' )
  LEFT JOIN VW_CL_SPEC S  ON (D.RIND=S.COD_SPEC)
  LEFT JOIN VW_CL_SPEC SS ON (S.FULL_CODE LIKE '%'||SS.COD_SPEC||';%' )
WHERE 
  (D.PERIOADA=:pPERIOADA) AND
  (D.FORM=:pFORM) AND
  (D.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  
  D.FORM = 14 AND
 -- FF.CODUL IN (00,11,14) AND
  D.CAPITOL IN (347)
--  AND
--  (SS.COD_SPEC LIKE '%00' OR LENGTH(D.RIND)=3)
GROUP BY
  D.RIND,
  R.DENUMIRE,
    R.ORDINE,
  --SS.DENUMIRE,
  T.CODUL,
  T.DENUMIRE,
  SS.COD_SPEC,
  SS.FULL_CODE,
  FF.CODUL,
  FF.DENUMIRE,
  C.CAPITOL,
  C.DEN_SHORT,
  C.DENUMIRE
  
    ORDER BY 
  R.ORDINE
)
GROUP BY
  RIND, 
  ORDINE,
  DENUMIRE,
  FULL_CODE,
  CAPITOL,
  CAPITOL_DEN,
  DEN_CAPITOL,
  COD_CFP,
  DEN_CFP
ORDER BY
ORDINE,
  LENGTH(RIND),
  FULL_CODE,
  NR_SECTIE,
  NR_ROW