
SELECT 
  A.CUIIO,
  A.CUIIO_VERS,
  A.DENUMIRE,
   A.CUATM,
  A.CFOJ,
  A.CFP,
  A.CAEM2   

FROM USER_BANCU.KAT_2_NVEST_TRIM A;



SELECT 
CUIIO,
CUATM   CUATM_ORIGINAL,
CASE WHEN  (LENGTH(CUATM) = 6 AND SUBSTR(CUATM,1,1) = 1)  OR  (LENGTH(CUATM) = 6 AND SUBSTR(CUATM,1,1) = 3)  THEN '0'||CUATM ELSE  CUATM END CUATM ,
LENGTH(CUATM)  LENGTH_CUATM,
SUBSTR(CUATM,1,1) AS VAL
FROM USER_BANCU.KAT_2_NVEST_TRIM;

UPDATE USER_BANCU.KAT_2_NVEST_TRIM

SET CUATM = (CASE WHEN   (LENGTH(CUATM) = 6 AND SUBSTR(CUATM,1,1) = 1)  OR  (LENGTH(CUATM) = 6 AND SUBSTR(CUATM,1,1) = 3)  THEN '0'||CUATM ELSE  CUATM end );