SELECT DISTINCT
D.CUIIO, 
  SUM(CASE WHEN D.RIND IN('413') THEN D.COL1 ELSE 0 END) ||'<>'||
  (NVAL(SUM(CASE WHEN D.RIND IN('862') AND P.NUM IN (4) THEN D.COL1  END)) +
 NVAL(SUM(CASE WHEN D.RIND IN('863') AND P.NUM IN (4) THEN D.COL1 END)))  AS REZULTAT
FROM
  CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.VW_MD_PERIOADA P ON (D.PERIOADA=P.PERIOADA)   
WHERE
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (:CUIIO_VERS<>:CUIIO_VERS     OR :CUIIO_VERS=:CUIIO_VERS) AND
  (:FORM <> :FORM               OR :FORM =:FORM) AND
  (:FORM_VERS<>:FORM_VERS       OR :FORM_VERS=:FORM_VERS) AND
  (:CAPITOL<>:CAPITOL           OR :CAPITOL=:CAPITOL) AND
  (:CAPITOL_VERS<>:CAPITOL_VERS OR :CAPITOL_VERS=:CAPITOL_VERS) AND
  (:ID_MD=:ID_MD               OR :ID_MD = -1) AND
  P.PERIOADA_ANULA = :PERIOADA AND
 
 D.CUIIO IN (SELECT CUIIO FROM CIS2.FORM_CUIIO WHERE FORM = 5 AND STATUT = '1') AND
  D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('5.309.862','5.309.863','4.320.413')
  
  GROUP BY 
  D.CUIIO 
  
HAVING
 NVAL(SUM(CASE WHEN D.RIND IN('413') THEN D.COL1 ELSE 0 END)) 
 <>
 
 (NVAL(SUM(CASE WHEN D.RIND IN('862') AND P.NUM IN (4) THEN NVAL(D.COL1)  END)) +
 NVAL(SUM(CASE WHEN D.RIND IN('863') AND P.NUM IN (4) THEN NVAL(D.COL1) END)))