SELECT
  'Rind. '||MR.RIND||': '||
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1117) THEN CIS2.NVAL(D.COL10) ELSE 0 END))||' <> '||
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1117) THEN CIS2.NVAL(D.COL1)+CIS2.NVAL(D.COL2)+CIS2.NVAL(D.COL3)+CIS2.NVAL(D.COL4)-
  CIS2.NVAL(D.COL5)-CIS2.NVAL(D.COL6)-CIS2.NVAL(D.COL7)-CIS2.NVAL(D.COL8)-CIS2.NVAL(D.COL9)-CIS2.NVAL(D.COL11)-CIS2.NVAL(D.COL12)-CIS2.NVAL(D.COL13)
                                        
  ELSE 0 END)) AS REZULTAT


FROM CIS2.VW_DATA_ALL_GC D

                                INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD

WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.NR_GOSP=:NR_GOSP               OR :NR_GOSP = -1) AND
  (D.UNIT_CODE_VERS=:UNIT_CODE_VERS     OR :UNIT_CODE_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <> :CAPITOL) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (62)  AND
  D.CAPITOL IN (1117)  
  AND MR.RIND NOT IN ('0110')
  
GROUP BY 
MR.RIND
  
HAVING 
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1117) THEN CIS2.NVAL(D.COL10) ELSE 0 END))  <>  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1117) THEN CIS2.NVAL(D.COL1)+CIS2.NVAL(D.COL2)+CIS2.NVAL(D.COL3)+CIS2.NVAL(D.COL4)-
  CIS2.NVAL(D.COL5)-CIS2.NVAL(D.COL6)-CIS2.NVAL(D.COL7)-CIS2.NVAL(D.COL8)-CIS2.NVAL(D.COL9)-CIS2.NVAL(D.COL11)-CIS2.NVAL(D.COL12)-CIS2.NVAL(D.COL13)
                                        
  ELSE 0 END))
  

ORDER BY MR.RIND