SELECT DISTINCT
  'Codul CUIIO='||D.CUIIO||' exista deja in sistemul BNS'
  AS REZULTAT

FROM
  CIS.VW_DATA_ALL D

WHERE
  (D.PERIOADA=:PERIOADA        OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO              OR :CUIIO = -1) AND
  (:CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM              OR :FORM = -1) AND
  (:FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS) AND
  (:ID_MD=:ID_MD)
  AND D.FORM NOT IN (2,3,6) 
  
  AND
  ((CASE WHEN D.FORM IN (10) AND D.CAPITOL IN (97) AND COL4  IS NOT NULL THEN 1 ELSE 0 END) NOT IN (1) AND
   (CASE WHEN D.FORM IN (10) AND D.CAPITOL IN (97) AND COL5  IS NOT NULL THEN 1 ELSE 0 END) NOT IN (1) AND
   (CASE WHEN D.FORM IN (10) AND D.CAPITOL IN (97) AND COL6  IS NOT NULL THEN 1 ELSE 0 END) NOT IN (1) AND
   (CASE WHEN D.FORM IN (10) AND D.CAPITOL IN (93) AND COL3  IS NOT NULL THEN 1 ELSE 0 END) NOT IN (1) AND
   (CASE WHEN D.FORM IN (10) AND D.CAPITOL IN (93) AND COL1  IS NOT NULL THEN 1 ELSE 0 END) NOT IN (1))