INSERT INTO TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
 COL1,COL2, COL3
)
SELECT                                                                       
  :pPERIOADA AS PERIOADA,                                                    
  :pFORM AS FORM,                                                            
  :pFORM_VERS AS FORM_VERS,                                                  
  :pID_MDTABLE AS ID_MDTABLE,                                                
  :pCOD_CUATM AS COD_CUATM,                                                  
  '0' AS NR_SECTIE,                                                         
  '0' AS NUME_SECTIE,                                                        
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   TO_NUMBER(R.RIND) AS NR_ROW,  
   R.ORDINE AS ORDINE,
  '111' AS DECIMAL_POS,
   R.DENUMIRE AS NUME_ROW,



   R.COL1 AS COL1, ROUND(R.COL2,1) AS COL2, ROUND(R.COL3 ,1) AS COL3  FROM



(

SELECT
  R.ORDINE,
  D.RIND,
  R.DENUMIRE,
  SUM(CASE WHEN D.PERIOADA IN  (:pPERIOADA) AND  R.RIND_VERS >= :pPERIOADA  THEN D.COL1 ELSE NULL END) AS COL1,
  (SUM(CASE WHEN D.PERIOADA IN  (:pPERIOADA) AND R.RIND_VERS >= :pPERIOADA  THEN D.COL1 ELSE NULL END) /
   SUM(CASE WHEN D.PERIOADA IN  (:pPERIOADA-1) AND  R.RIND_VERS < :pPERIOADA  THEN D.COL1 ELSE NULL END)) * 100  AS COL2,
   (SUM(CASE WHEN D.CAPITOL IN 1021 AND  R.RIND_VERS >= :pPERIOADA THEN D.COL1 ELSE 0 END)/J.COL1)*100 AS COL3
  
 
  
FROM CIS2.VW_DATA_ALL D

  
INNER JOIN CIS2.MD_RIND R ON (R.ID_MD = D.ID_MD)

CROSS JOIN (
SELECT 
  FORM, 
  PERIOADA, 
  SUM(COL1) AS COL1 

FROM CIS2.VW_DATA_ALL D
   WHERE FORM = 28 AND 
   RIND = '210' AND
   PERIOADA = :pPERIOADA AND 
   D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'


GROUP BY FORM, PERIOADA


) J

WHERE 
  D.FORM = 28
  AND D.CAPITOL = 1021 AND
  D.PERIOADA IN  (:pPERIOADA,:pPERIOADA-1)  AND  
  D.RIND NOT IN '210' AND 
  --R.RIND_VERS >= :pPERIOADA AND 
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' 
  
-- AND D.CUIIO = 1588702 
GROUP BY R.ORDINE, D.RIND,R.DENUMIRE, J.COL1

UNION

SELECT
  21 AS ORDINE,
  '210' AS RIND,
  R.DENUMIRE,
 SUM(CASE WHEN D.PERIOADA IN  (:pPERIOADA) AND  R.RIND_VERS >= :pPERIOADA  THEN D.COL1 ELSE NULL END) AS COL1,
  (SUM(CASE WHEN D.PERIOADA IN  (:pPERIOADA) AND R.RIND_VERS >= :pPERIOADA  THEN D.COL1 ELSE NULL END) /
   SUM(CASE WHEN D.PERIOADA IN  (:pPERIOADA-1) AND  R.RIND_VERS < :pPERIOADA  THEN D.COL1 ELSE NULL END)) * 100  AS COL2,
--  100 AS COL3
  
      (SUM(CASE WHEN D.PERIOADA IN  (:pPERIOADA) THEN D.COL1 ELSE NULL END) / J.COL1) * 100 AS COL3
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.MD_RIND R ON (R.ID_MD = D.ID_MD)
  CROSS JOIN (
SELECT 
  FORM, 
  PERIOADA, 
  SUM(COL1) AS COL1 

FROM CIS2.VW_DATA_ALL D
   WHERE FORM = 28 AND 
   RIND = '210' AND
   PERIOADA = :pPERIOADA AND 
   D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'


GROUP BY FORM, PERIOADA


) J
  
WHERE D.FORM = 28 AND
      D.CAPITOL = 1021 AND
  D.PERIOADA IN  (:pPERIOADA,:pPERIOADA-1)  AND  
      D.RIND IN '210' 
 --     AND D.CUIIO = 1588702 
      AND D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' 
GROUP BY R.DENUMIRE,
J.COL1
  
) R

ORDER BY R.ORDINE