SELECT   
'FILIALA:'||D.FILIAL||' '|| 
 'RIND - '||D.RIND||

 SUM(CASE WHEN D.RIND IN ('1','2','3','4','5','6','7')  THEN CIS2.NVAL(D.COL1) + CIS2.NVAL(D.COL2)+CIS2.NVAL(D.COL3)+CIS2.NVAL(D.COL4)+CIS2.NVAL(D.COL5)+CIS2.NVAL(D.COL6)+CIS2.NVAL(D.COL7)+CIS2.NVAL(D.COL4) ELSE 0 END) 
    
    AS REZULTAT,
    
    SUM(CASE WHEN D.RIND IN ('8')  THEN CIS2.NVAL(D.COL1) + CIS2.NVAL(D.COL2) +CIS2.NVAL(D.COL3)+CIS2.NVAL(D.COL4)+CIS2.NVAL(D.COL5)+CIS2.NVAL(D.COL6)+CIS2.NVAL(D.COL7)+CIS2.NVAL(D.COL4) ELSE 0 END) COL1
 
  

FROM
  CIS2.VW_DATA_ALL D
 
WHERE
  (D.PERIOADA =:PERIOADA        OR :PERIOADA=  -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (16)  AND
  D.CAPITOL IN  (353) 
  
 
GROUP BY 

D.FILIAL,
D.RIND

HAVING 
SUM(CASE WHEN D.RIND IN ('1','2','3','4','5','6','7')  THEN CIS2.NVAL(D.COL1) + CIS2.NVAL(D.COL2)+CIS2.NVAL(D.COL3)+CIS2.NVAL(D.COL4)+CIS2.NVAL(D.COL5)+CIS2.NVAL(D.COL6)+CIS2.NVAL(D.COL7)+CIS2.NVAL(D.COL4) ELSE 0 END)  > 0 

AND 

 SUM(CASE WHEN D.RIND IN ('8')  THEN CIS2.NVAL(D.COL1) + CIS2.NVAL(D.COL2) +CIS2.NVAL(D.COL3)+CIS2.NVAL(D.COL4)+CIS2.NVAL(D.COL5)+CIS2.NVAL(D.COL6)+CIS2.NVAL(D.COL7)+CIS2.NVAL(D.COL4) ELSE 0 END) = 0 
