SELECT 
CUIIO,
COUNT (CUIIO) AS CNT

    FROM USER_BANCU.KATALOG_2RSF_2009_v1
    
    GROUP BY 
    CUIIO 
    
    HAVING 
    COUNT (CUIIO) > 1  ; --1127
    
    
    SELECT 
        COUNT (CUIIO) AS CNT,
        COUNT (DISTINCT CUIIO) AS CNT_DISTINCT 


    FROM USER_BANCU.KATALOG_2RSF_2009_v1
    
--    GROUP BY 
--    CUIIO 
--    
--    HAVING 
--    COUNT (CUIIO) > 1  ; --1127