SELECT
    
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
    '0' AS NR_SECTIE,
    '0' AS NUME_SECTIE,
    '0' AS NR_SECTIE1,
    '0' AS NUME_SECTIE1,
    '0' AS NR_SECTIE2,
    '0' AS NUME_SECTIE2,
                
     ROUND(SUM(D.COL1),2) ||'~'||CC.CODUL AS NR_ROW, 
     CC.CODUL AS ORDINE,
    '001' AS DECIMAL_POS,

     CC.DENUMIRE AS NUME_ROW,
     ROUND(SUM(D.COL2),2) AS COL1, 
     ROUND((SUM(D.COL2) / NOZERO(SUM(D.COL1))),2) AS COL2     
    
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
  
   INNER  JOIN VW_CL_CUATM C ON D.CUATM = C.CODUL 
  INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
WHERE
  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  AND  
  -- D.PERIOADA IN (:pPERIOADA ) AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (417)
  AND R.RIND IN ('041')
  
  AND CC.PRGS IN ('2')
  
  
GROUP BY
 
  CC.CODUL,
  CC.DENUMIRE,
  CC.FULL_CODE
  
  ORDER BY 
  CC.FULL_CODE
