SELECT
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
    '0' AS NR_SECTIE,
    '0' AS NUME_SECTIE,
    '0' AS NR_SECTIE1,
    '0' AS NUME_SECTIE1,
    '0' AS NR_SECTIE2,
    '0' AS NUME_SECTIE2,
                
     ROUND(SUM(D.COL1),2) ||'~'||D.RIND AS NR_ROW, 
     D.RIND AS ORDINE,
    '001' AS DECIMAL_POS,

     REPLACE(REPLACE(R.DENUMIRE, '<br>'),'</br>') AS NUME_ROW,
     ROUND(SUM(D.COL13),2) AS COL1, 
     ROUND((SUM(D.COL13) / NOZERO(SUM(D.COL1)) * 100),2) AS COL2     
    
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND R ON D.ID_MD = R.ID_MD
WHERE
  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
GROUP BY
  D.RIND,
  R.DENUMIRE