SELECT   
--   C.FULL_CODE,
--   C.DENUMIRE,
--D.CUIIO,
B.NR_ROW,
   B.ORDINE,
   B.NUME_ROW,  
   
   
  SUM(CASE WHEN B.NR_ROW LIKE '%'||TRIM(D.RIND)||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL14) ELSE 0 END) AS COL1,
  
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL1) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL3) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL4) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL5) ELSE 0 END)) AS COL2,
  
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL6) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL7) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL8) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL9) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL10) ELSE 0 END)) AS COL3,
  
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL11) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL12) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL13) ELSE 0 END)) AS COL4,
  
  
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL14) ELSE 0 END) AS COL5,
 
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL1) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL3) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL4) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL5) ELSE 0 END))AS COL6,
 
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL6) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL7) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL8) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL9) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL10) ELSE 0 END)) AS COL7,
  
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL11) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL12) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL13) ELSE 0 END)) AS COL8,
  
  (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL14) ELSE 0 END)-
   SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL14) ELSE 0 END)) AS COL9,
  
((SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL1) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL3) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL4) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL5) ELSE 0 END))- 
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL1) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL3) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL4) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL5) ELSE 0 END))) AS COL10,
 
((SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL6) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL7) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL8) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL9) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL10) ELSE 0 END))-
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL6) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL7) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL8) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL9) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN D.COL10 ELSE 0 END))) AS COL11,
  
((SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL11) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL12) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL13) ELSE 0 END))-
  
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL11) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL12) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL13) ELSE 0 END))) AS COL12
  
FROM 
  CIS2.VW_DATA_ALL D
--  INNER JOIN CIS2.VW_CL_CUATM A ON (D.CUATM=A.CODUL)
--  INNER JOIN CIS2.VW_CL_CUATM C ON (A.FULL_CODE LIKE '%'||C.CODUL||';%')


CROSS JOIN
(

SELECT '01+02'          AS NR_ROW, '5-6 ani'                                            AS NUME_ROW, 1 AS ORDINE FROM DUAL UNION
SELECT '03+04+05+06'    AS NR_ROW, '7-10 ani'                                           AS NUME_ROW, 2 AS ORDINE FROM DUAL UNION
SELECT '07+08+09+10-11' AS NR_ROW, '11-15 ani'                                          AS NUME_ROW, 3 AS ORDINE FROM DUAL UNION
SELECT '12+13+14'       AS NR_ROW, '16-18 ani'                                          AS NUME_ROW, 4 AS ORDINE FROM DUAL UNION
SELECT '15+16+17+18'    AS NR_ROW, '19 ani si peste'                                    AS NUME_ROW, 5 AS ORDINE FROM DUAL UNION
SELECT '19'             AS NR_ROW, 'Total'                                              AS NUME_ROW, 6 AS ORDINE FROM DUAL UNION
SELECT '20'             AS NR_ROW, 'elevi cu cerinte educationale speciale'             AS NUME_ROW, 7 AS ORDINE FROM DUAL UNION
SELECT '21'             AS NR_ROW, 'elevi cu dizabilitati'                              AS NUME_ROW, 8 AS ORDINE FROM DUAL UNION 
SELECT '30'           AS NR_ROW, 'inclusiv: elevi cu dizabilitati ?are au nevoie de scolarizare adaptata deficien?elor'                              AS NUME_ROW, 8.1 AS ORDINE FROM DUAL UNION  
SELECT '22'             AS NR_ROW, 'Numarul de clase' AS NUME_ROW, 9 AS ORDINE FROM DUAL 


) B


WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 40 AND
  D.CAPITOL IN (1022,1023)
  -- AND
 -- C.PRGS IN 2--
--AND D.CUIIO = 7031914
GROUP BY
--D.CUIIO, 
  B.NUME_ROW, 
  B.ORDINE,
  B.NR_ROW
  
  ORDER BY 
  
  B.ORDINE