SELECT
   CII.ITEM_CODE AS CODUL,
   CII.NAME AS DENUMIRE,
   CII.ITEM_PATH,
   B.NR_ROW,
   B.ORDINE,
   B.ORDINE_2,
  B.NUME_ROW, 

  SUM(CASE WHEN   B.NR_ROW = D.RIND    THEN D.COL2 ELSE 0 END ) AS COL1,
  SUM(CASE WHEN   B.NR_ROW = D.RIND    THEN D.COL3 ELSE 0 END ) AS COL2,
  SUM(CASE WHEN   B.NR_ROW = D.RIND    THEN D.COL4 ELSE 0 END ) AS COL3,
  SUM(CASE WHEN   B.NR_ROW = D.RIND    THEN D.COL5 ELSE 0 END ) AS COL4,
  SUM(CASE WHEN   B.NR_ROW = D.RIND    THEN D.COL6 ELSE 0 END ) AS COL5,
  SUM(CASE WHEN   B.NR_ROW = D.RIND    THEN D.COL7 ELSE 0 END ) AS COL6,
  SUM(CASE WHEN   B.NR_ROW = D.RIND    THEN D.COL8 ELSE 0 END ) AS COL7
  


  
FROM CIS2.VW_DATA_ALL D

        INNER JOIN CIS2.RENIM E ON E.CUIIO = D.CUIIO AND E.CUIIO_VERS = D.CUIIO_VERS    
        INNER JOIN CIS2.MD_RIND MR ON (MR.ID_MD = D.ID_MD) 
       INNER JOIN (
       SELECT
                  CI.ITEM_CODE,
                  CI.ITEM_PATH,
                  MAX(CI.ITEM_CODE_VERS) AS ITEM_CODE_VERS
                FROM
                  VW_CLS_CLASS_ITEM CI
                WHERE
                  CI.CLASS_CODE IN ('COCM') AND
                  CI.ITEM_CODE_VERS <= :pPERIOADA
                GROUP BY
                  CI.ITEM_CODE,
                  CI.ITEM_PATH
       ) CI ON E.COCM =  CI.ITEM_CODE
 
 INNER JOIN VW_CLS_CLASS_ITEM CII ON (CII.CLASS_CODE IN ('COCM') AND CI.ITEM_CODE_VERS=CII.ITEM_CODE_VERS AND CI.ITEM_PATH LIKE '%'||CII.ITEM_CODE||';%')
  

        CROSS JOIN
(

SELECT '01'  AS NR_ROW, 'Total'    AS NUME_ROW,  1 AS ORDINE, '1' AS ORDINE_2 FROM DUAL UNION
SELECT '-'  AS NR_ROW, 'din ei studieaza:'    AS NUME_ROW,  2 AS ORDINE,   '-' AS ORDINE_2 FROM DUAL UNION
SELECT '02'  AS NR_ROW, 'în limba româna'    AS NUME_ROW,   3 AS ORDINE, '2' AS ORDINE_2 FROM  DUAL UNION
SELECT '-'  AS NR_ROW, 'inclusiv în:'    AS NUME_ROW,   4 AS ORDINE , '-' AS ORDINE_2 FROM DUAL  UNION
SELECT '03'  AS NR_ROW, 'clasele 1-4'    AS NUME_ROW,   5 AS ORDINE , '3' AS ORDINE_2 FROM  DUAL  UNION
SELECT '04'  AS NR_ROW, 'clasele 5-9'    AS NUME_ROW,   6 AS ORDINE, '4' AS ORDINE_2 FROM  DUAL UNION
SELECT '05'  AS NR_ROW, 'clasele 10-12'    AS NUME_ROW,   7 AS ORDINE , '5' AS ORDINE_2 FROM  DUAL UNION
SELECT '06'  AS NR_ROW, 'în limba rusa'    AS NUME_ROW,  8 AS ORDINE , '6' AS ORDINE_2 FROM  DUAL  UNION
SELECT '-'  AS NR_ROW, 'inclusiv în:'    AS NUME_ROW,  9 AS ORDINE  , '-' AS ORDINE_2 FROM  DUAL UNION
SELECT '07'  AS NR_ROW, 'clasele 1-4'    AS NUME_ROW,  10 AS ORDINE , '7' AS ORDINE_2 FROM  DUAL UNION
SELECT '08'  AS NR_ROW, 'clasele 5-9'    AS NUME_ROW,  11 AS ORDINE , '8' AS ORDINE_2 FROM  DUAL UNION
SELECT '09'  AS NR_ROW, 'clasele 11-12'    AS NUME_ROW,  12 AS ORDINE , '9' AS ORDINE_2 FROM  DUAL 

 
) B
  
  CROSS JOIN 
 (     
    SELECT 'Forme de Proprietate- Total pe Republica' AS NUME_ROW,            '01' AS NR_ROW, '11-12-13-14-15-16-17-18-19-20-22-23-24-25-26-27-28-29' AS CFP FROM DUAL UNION
    SELECT 'Proprietate proprietatea publica' AS NUME_ROW,                    '02' AS NR_ROW, '11-12-13'          AS CFP FROM DUAL UNION 
    SELECT 'Proprietate proprietatea privata - total' AS NUME_ROW,            '03' AS NR_ROW, '14-15-16-17-18-19-29' AS CFP FROM DUAL     
   

  ) CD


WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024
   
   AND  CI.ITEM_CODE IN ('8704','7094','4874','7614','7774','7994','8064','9994')
  
 GROUP BY
  CII.ITEM_CODE_VERS,
  CII.ITEM_CODE,
  CII.NAME,
  CII.ITEM_PATH,
  B.ORDINE,
  B.ORDINE_2,
  B.NUME_ROW,
  B.NR_ROW