--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
-- COL1, COL2, COL3, COL4, COL5,COL6,COL7,COL8,COL9
--)
SELECT DISTINCT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   ROWNUM AS NR_ROW,
   ROWNUM AS ORDINE,
  '000000000' AS DECIMAL_POS,
  CASE 
  WHEN CODUL = '7184' 
  THEN 'MINISTERUL SANATA?II'
  
  WHEN CODUL = '8704' 
  THEN 'MINISTERUL EDUCA?IEI ?I CERCETARII'
  
  
  ELSE 
  DENUMIRE  END AS NUME_ROW,
   CASE WHEN COL1 = 0 THEN NULL ELSE COL1 END AS COL1,
   CASE WHEN COL2 = 0 THEN NULL ELSE COL2 END AS COL2,
   CASE WHEN COL3 = 0 THEN NULL ELSE COL3 END AS COL3,
   CASE WHEN COL4 = 0 THEN NULL ELSE COL4 END AS COL4,
   CASE WHEN COL5 = 0 THEN NULL ELSE COL5 END AS COL5,
   CASE WHEN COL6 = 0 THEN NULL ELSE COL6 END AS COL6,
   CASE WHEN COL7 = 0 THEN NULL ELSE COL7 END AS COL7,
   CASE WHEN COL8 = 0 THEN NULL ELSE COL8 END AS COL8,
   CASE WHEN COL9 = 0 THEN NULL ELSE COL9 END AS COL9
   
FROM

(
SELECT
  A.DENUMIRE,
  A.CODUL,
  A.FULL_CODE,
  COL1, COL2, COL3, COL4, COL5,COL6,COL7,COL8,COL9
FROM
(
SELECT
  DENUMIRE,
  CODUL,
  FULL_CODE

FROM 
  CIS2.VW_CL_COCM

WHERE
  CODUL IN (0000, 8704,7094,4874,7614,7774,7994,7184,8064)


) A
LEFT JOIN
(
SELECT
  C.FULL_CODE,
  C.DENUMIRE,
  C.CODUL,
  SUM(CASE WHEN D.RIND IN '01' AND D.COL5 > 0 AND D.COL6 > 0 THEN 1 ELSE 0 END) AS COL1,
  SUM(CASE WHEN D.RIND IN '01' AND D.COL5 > 0 AND D.COL6 > 0 AND R.TIP_LOCAL = 1 THEN 1 ELSE 0 END) AS COL2,
  SUM(CASE WHEN D.RIND IN '01' AND D.COL5 > 0 AND D.COL6 > 0 AND R.TIP_LOCAL = 2 THEN 1 ELSE 0 END) AS COL3,
  SUM(CASE WHEN D.CAPITOL IN 1028 THEN D.COL5 ELSE 0 END) AS COL4,
  SUM(CASE WHEN D.CAPITOL IN 1028 AND R.TIP_LOCAL = 1 THEN D.COL5 ELSE 0 END) AS COL5,
  SUM(CASE WHEN D.CAPITOL IN 1028 AND R.TIP_LOCAL = 2 THEN D.COL5 ELSE 0 END) AS COL6,
  
  SUM(CASE WHEN D.CAPITOL IN 1028 THEN D.COL6 ELSE 0 END) AS COL7,
  SUM(CASE WHEN D.CAPITOL IN 1028 AND R.TIP_LOCAL = 1 THEN D.COL6 ELSE 0 END) AS COL8,
  SUM(CASE WHEN D.CAPITOL IN 1028 AND R.TIP_LOCAL = 2 THEN D.COL6 ELSE 0 END) AS COL9
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  INNER JOIN CIS2.VW_CL_COCM A ON (D.COCM=A.CODUL)
  INNER JOIN CIS2.VW_CL_COCM C ON (A.FULL_CODE LIKE '%'||C.CODUL||';%')


WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1028 AND
   R.NTII IN (10,20,21,30,31)
   
GROUP BY
  C.FULL_CODE,
  C.DENUMIRE,
  C.CODUL
) B ON A.FULL_CODE = B.FULL_CODE AND A.CODUL = B.CODUL

ORDER BY A.FULL_CODE
)

