INSERT INTO TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
 COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14
)
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
   1 AS NR_SECTIE,
  'URBAN' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   NR_ROW,
   ORDINE,
  '00000000000000' AS DECIMAL_POS,
   NUME_ROW,
   COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14
   
FROM (

SELECT
  A.NUME_ROW,
  A.NR_ROW,
  A.ORDINE AS ORDINE,
  SUM(A.COL1) AS COL1, SUM(A.COL2) AS COL2, SUM(A.COL3) AS COL3, SUM(A.COL4) AS COL4, SUM(A.COL5) AS COL5, SUM(A.COL6) AS COL6, SUM(A.COL7) AS COL7, SUM(A.COL8) AS COL8, SUM(A.COL9) AS COL9, SUM(A.COL10) AS COL10, SUM(A.COL11) AS COL11, SUM(A.COL12) AS COL12, SUM(A.COL13)AS COL13, SUM(A.COL14) AS COL14

FROM
(
SELECT DISTINCT
  R.DENUMIRE AS NUME_ROW,
  R.CAPITOL,
  R.RIND AS NR_ROW,
  R.ORDINE AS ORDINE,
  R.FORM,
  D.CUIIO,
  D.CUIIO_VERS,
  D.CUATM,
  D.PERIOADA, A.COL1, A.COL2, A.COL3, A.COL4, A.COL5, A.COL6, A.COL7, A.COL8, A.COL9, A.COL10, A.COL11, A.COL12, A.COL13, A.COL14
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.MD_RIND R ON D.CAPITOL = R.CAPITOL AND D.FORM = R.FORM
  LEFT JOIN (
  
  SELECT
  RIND,
  CAPITOL,
  CUIIO,
  CUIIO_VERS,
  CUATM,
  FORM,
  PERIOADA,
  COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14
FROM CIS2.VW_DATA_ALL D

WHERE
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND
   D.CAPITOL = 1022 ) A 
   ON D.CUIIO = A.CUIIO AND D.PERIOADA = A.PERIOADA AND R.CAPITOL = A.CAPITOL AND R.RIND = A.RIND
  
  
WHERE
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  R.FORM = 40 AND
  R.CAPITOL = 1022
  
  
ORDER BY ORDINE
) A
    INNER JOIN CIS2.RENIM B ON (A.CUIIO = B.CUIIO AND A.CUIIO_VERS = B.CUIIO_VERS)
    
WHERE 
  B.TIP_LOCAL = 1 AND
  B.NFI = 2 

GROUP BY
  A.NUME_ROW,
  A.NR_ROW,
  A.ORDINE

)

UNION



SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
   2 AS NR_SECTIE,
  'RURAL' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   NR_ROW,
   ORDINE,
  '00000000000000' AS DECIMAL_POS,
   NUME_ROW,
   COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14
   
FROM (

SELECT
  A.NUME_ROW,
  A.NR_ROW,
  A.ORDINE AS ORDINE,
  SUM(A.COL1) AS COL1, SUM(A.COL2) AS COL2, SUM(A.COL3) AS COL3, SUM(A.COL4) AS COL4, SUM(A.COL5) AS COL5, SUM(A.COL6) AS COL6, SUM(A.COL7) AS COL7, SUM(A.COL8) AS COL8, SUM(A.COL9) AS COL9, SUM(A.COL10) AS COL10, SUM(A.COL11) AS COL11, SUM(A.COL12) AS COL12, SUM(A.COL13)AS COL13, SUM(A.COL14) AS COL14

FROM
(
SELECT DISTINCT
  R.DENUMIRE AS NUME_ROW,
  R.CAPITOL,
  R.RIND AS NR_ROW,
  R.ORDINE AS ORDINE,
  R.FORM,
  D.CUIIO,
  D.CUIIO_VERS,
  D.CUATM,
  D.PERIOADA, A.COL1, A.COL2, A.COL3, A.COL4, A.COL5, A.COL6, A.COL7, A.COL8, A.COL9, A.COL10, A.COL11, A.COL12, A.COL13, A.COL14
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.MD_RIND R ON D.CAPITOL = R.CAPITOL AND D.FORM = R.FORM
  LEFT JOIN (
  
  SELECT
  RIND,
  CAPITOL,
  CUIIO,
  CUIIO_VERS,
  CUATM,
  FORM,
  PERIOADA,
  COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14
FROM CIS2.VW_DATA_ALL D

WHERE
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND
   D.CAPITOL = 1022 ) A 
   ON D.CUIIO = A.CUIIO AND D.PERIOADA = A.PERIOADA AND R.CAPITOL = A.CAPITOL AND R.RIND = A.RIND
  
  
WHERE
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  R.FORM = 40 AND
  R.CAPITOL = 1022
  
  
ORDER BY ORDINE
) A
    INNER JOIN CIS2.RENIM B ON (A.CUIIO = B.CUIIO AND A.CUIIO_VERS = B.CUIIO_VERS)
    
WHERE 
  B.TIP_LOCAL = 2 AND
  B.NFI = 2    

GROUP BY
  A.NUME_ROW,
  A.NR_ROW,
  A.ORDINE

)