INSERT INTO TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
 COL1, COL2, COL3, COL4, COL5, COL6, COL7
)


  SELECT DISTINCT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  D.CODUL AS NR_SECTIE,
   D.LOCALITATE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   CASE 
   
   WHEN D.NUME_ROW = 'din ei studieaza:'
   THEN  '-'||'~'||ROWNUM
   
   WHEN D.NUME_ROW = 'inclusiv în:'
   THEN  '-'||'~'||ROWNUM
   
   
   ELSE 
   D.ORDINE||'~'||ROWNUM  END NR_ROW,
   ROWNUM ORDINE,
  '0000000' AS DECIMAL_POS,
   D.NUME_ROW,
  
   CASE WHEN COL1 = 0 THEN NULL ELSE COL1 END AS COL1,
  CASE WHEN COL2 = 0 THEN NULL ELSE COL2 END AS COL2,
  CASE WHEN COL3 = 0 THEN NULL ELSE COL3 END AS COL3,
  CASE WHEN COL4 = 0 THEN NULL ELSE COL4 END AS COL4,
  CASE WHEN COL5 = 0 THEN NULL ELSE COL5 END AS COL5,
  CASE WHEN COL6 = 0 THEN NULL ELSE COL6 END AS COL6,
  CASE WHEN COL7 = 0 THEN NULL ELSE COL5 END AS COL7
   
FROM

(

SELECT
  C.DENUMIRE AS LOCALITATE,
  C.CODUL,
   B.NR_ROW,
   B.ORDINE,
   B.NUME_ROW, 

  SUM(CASE WHEN  B.NR_ROW = D.RIND    THEN D.COL2 ELSE 0 END ) AS COL1,
  SUM(CASE WHEN  B.NR_ROW = D.RIND    THEN D.COL3 ELSE 0 END ) AS COL2,
  SUM(CASE WHEN  B.NR_ROW = D.RIND    THEN D.COL4 ELSE 0 END ) AS COL3,
  SUM(CASE WHEN  B.NR_ROW = D.RIND   THEN D.COL5 ELSE 0 END ) AS COL4,
  SUM(CASE WHEN  B.NR_ROW = D.RIND   THEN D.COL6 ELSE 0 END ) AS COL5,
  SUM(CASE WHEN  B.NR_ROW = D.RIND   THEN D.COL7 ELSE 0 END ) AS COL6,
  SUM(CASE WHEN  B.NR_ROW = D.RIND    THEN D.COL8 ELSE 0 END ) AS COL7
  


  
FROM CIS2.VW_DATA_ALL D
        INNER JOIN CIS2.MD_RIND MR ON (MR.ID_MD = D.ID_MD)
        INNER JOIN CIS2.RENIM E ON E.CUIIO = D.CUIIO AND E.CUIIO_VERS = D.CUIIO_VERS
        INNER JOIN CIS2.CL_TIP_LOCAL C ON C.CODUL = E.TIP_LOCAL
        
        CROSS JOIN
(

SELECT '01'  AS NR_ROW, 'Total'    AS NUME_ROW,  1 AS ORDINE FROM DUAL UNION
SELECT '-'  AS NR_ROW, 'din ei studieaza:'    AS NUME_ROW,    2 AS ORDINE FROM DUAL UNION
SELECT '02'  AS NR_ROW, 'în limba româna'    AS NUME_ROW,   3 AS ORDINE FROM  DUAL UNION
SELECT '-'  AS NR_ROW, 'inclusiv în:'    AS NUME_ROW,   4 AS ORDINE FROM DUAL  UNION
SELECT '03'  AS NR_ROW, 'clasele 1-4'    AS NUME_ROW,   5 AS ORDINE FROM  DUAL  UNION
SELECT '04'  AS NR_ROW, 'clasele 5-9'    AS NUME_ROW,   6 AS ORDINE FROM  DUAL UNION
SELECT '05'  AS NR_ROW, 'clasele 10-12'    AS NUME_ROW,   7 AS ORDINE FROM  DUAL UNION
SELECT '06'  AS NR_ROW, 'în limba rusa'    AS NUME_ROW,  8 AS ORDINE FROM  DUAL  UNION
SELECT '-'  AS NR_ROW, 'inclusiv în:'    AS NUME_ROW,  9 AS ORDINE FROM  DUAL UNION
SELECT '07'  AS NR_ROW, 'clasele 1-4'    AS NUME_ROW,  10 AS ORDINE FROM  DUAL UNION
SELECT '08'  AS NR_ROW, 'clasele 5-9'    AS NUME_ROW,  11 AS ORDINE FROM  DUAL UNION
SELECT '09'  AS NR_ROW, 'clasele 11-12'    AS NUME_ROW,  12 AS ORDINE FROM  DUAL 

 
) B
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024
   
   GROUP BY
  C.DENUMIRE,
  C.CODUL,
  B.ORDINE,
  B.NUME_ROW,
  B.NR_ROW
  
  
  UNION 
  
  SELECT
  C.DENUMIRE AS LOCALITATE,
  C.CODUL,
   B.NR_ROW,
   B.ORDINE,
   B.NUME_ROW, 

  SUM(CASE WHEN  B.NR_ROW = D.RIND    THEN D.COL2 ELSE 0 END ) AS COL1,
  SUM(CASE WHEN  B.NR_ROW = D.RIND    THEN D.COL3 ELSE 0 END ) AS COL2,
  SUM(CASE WHEN  B.NR_ROW = D.RIND    THEN D.COL4 ELSE 0 END ) AS COL3,
  SUM(CASE WHEN  B.NR_ROW = D.RIND   THEN D.COL5 ELSE 0 END ) AS COL4,
  SUM(CASE WHEN  B.NR_ROW = D.RIND   THEN D.COL6 ELSE 0 END ) AS COL5,
  SUM(CASE WHEN  B.NR_ROW = D.RIND   THEN D.COL7 ELSE 0 END ) AS COL6,
  SUM(CASE WHEN  B.NR_ROW = D.RIND    THEN D.COL8 ELSE 0 END ) AS COL7
  


  
FROM CIS2.VW_DATA_ALL D
        INNER JOIN CIS2.MD_RIND MR ON (MR.ID_MD = D.ID_MD)
        INNER JOIN CIS2.RENIM E ON E.CUIIO = D.CUIIO AND E.CUIIO_VERS = D.CUIIO_VERS
        INNER JOIN CIS2.CL_TIP_LOCAL C ON C.CODUL = E.TIP_LOCAL
        
        CROSS JOIN
(

SELECT '10'  AS NR_ROW, 'în limba ucraineana'    AS NUME_ROW,  14 AS ORDINE FROM DUAL  UNION
SELECT '-'  AS NR_ROW, 'inclusiv în:'    AS NUME_ROW,    15 AS ORDINE FROM DUAL  UNION
SELECT '11'  AS NR_ROW, 'clasele 1-4'    AS NUME_ROW,  16 AS ORDINE FROM DUAL UNION
SELECT '12'  AS NR_ROW, 'clasele 5-9'    AS NUME_ROW,  17 AS ORDINE FROM DUAL UNION
SELECT '13'  AS NR_ROW, 'clasele 10-12'    AS NUME_ROW,  18 AS ORDINE FROM DUAL
 
) B
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024
   AND D.COL1 = 67
   
   GROUP BY
  C.DENUMIRE,
  C.CODUL,
  B.ORDINE,
  B.NUME_ROW,
  B.NR_ROW
  
  
  UNION 
  
  SELECT
  C.DENUMIRE AS LOCALITATE,
  C.CODUL,
   B.NR_ROW,
   B.ORDINE,
   B.NUME_ROW, 

  SUM(CASE WHEN  B.NR_ROW = D.RIND    THEN D.COL2 ELSE 0 END ) AS COL1,
  SUM(CASE WHEN  B.NR_ROW = D.RIND    THEN D.COL3 ELSE 0 END ) AS COL2,
  SUM(CASE WHEN  B.NR_ROW = D.RIND    THEN D.COL4 ELSE 0 END ) AS COL3,
  SUM(CASE WHEN  B.NR_ROW = D.RIND   THEN D.COL5 ELSE 0 END ) AS COL4,
  SUM(CASE WHEN  B.NR_ROW = D.RIND   THEN D.COL6 ELSE 0 END ) AS COL5,
  SUM(CASE WHEN  B.NR_ROW = D.RIND   THEN D.COL7 ELSE 0 END ) AS COL6,
  SUM(CASE WHEN  B.NR_ROW = D.RIND    THEN D.COL8 ELSE 0 END ) AS COL7
  


  
FROM CIS2.VW_DATA_ALL D
        INNER JOIN CIS2.MD_RIND MR ON (MR.ID_MD = D.ID_MD)
        INNER JOIN CIS2.RENIM E ON E.CUIIO = D.CUIIO AND E.CUIIO_VERS = D.CUIIO_VERS
        INNER JOIN CIS2.CL_TIP_LOCAL C ON C.CODUL = E.TIP_LOCAL
        
        CROSS JOIN
(

SELECT '10'  AS NR_ROW, 'în limba bulgara'    AS NUME_ROW,  19 AS ORDINE FROM DUAL  UNION
SELECT '-'  AS NR_ROW, 'inclusiv în:'    AS NUME_ROW,    20 AS ORDINE FROM DUAL  UNION
SELECT '11'  AS NR_ROW, 'clasele 1-4'    AS NUME_ROW,  21 AS ORDINE FROM DUAL UNION
SELECT '12'  AS NR_ROW, 'clasele 5-9'    AS NUME_ROW,  22 AS ORDINE FROM DUAL UNION
SELECT '13'  AS NR_ROW, 'clasele 10-12'    AS NUME_ROW,  23 AS ORDINE FROM DUAL
 
) B
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024
    AND D.COL1 = 160
   GROUP BY
  C.DENUMIRE,
  C.CODUL,
  B.ORDINE,
  B.NUME_ROW,
  B.NR_ROW
  



UNION 

SELECT
  C.DENUMIRE AS LOCALITATE,
  C.CODUL,
   B.NR_ROW,
   B.ORDINE,
   B.NUME_ROW, 

  SUM(CASE WHEN  B.NR_ROW = D.RIND    THEN D.COL2 ELSE 0 END ) AS COL1,
  SUM(CASE WHEN  B.NR_ROW = D.RIND    THEN D.COL3 ELSE 0 END ) AS COL2,
  SUM(CASE WHEN  B.NR_ROW = D.RIND    THEN D.COL4 ELSE 0 END ) AS COL3,
  SUM(CASE WHEN  B.NR_ROW = D.RIND   THEN D.COL5 ELSE 0 END ) AS COL4,
  SUM(CASE WHEN  B.NR_ROW = D.RIND   THEN D.COL6 ELSE 0 END ) AS COL5,
  SUM(CASE WHEN  B.NR_ROW = D.RIND   THEN D.COL7 ELSE 0 END ) AS COL6,
  SUM(CASE WHEN  B.NR_ROW = D.RIND    THEN D.COL8 ELSE 0 END ) AS COL7
  


  
FROM CIS2.VW_DATA_ALL D
        INNER JOIN CIS2.MD_RIND MR ON (MR.ID_MD = D.ID_MD)
        INNER JOIN CIS2.RENIM E ON E.CUIIO = D.CUIIO AND E.CUIIO_VERS = D.CUIIO_VERS
        INNER JOIN CIS2.CL_TIP_LOCAL C ON C.CODUL = E.TIP_LOCAL
        
        CROSS JOIN
(

SELECT '10'  AS NR_ROW, 'în limba engleza'    AS NUME_ROW,  24 AS ORDINE FROM DUAL  UNION
SELECT '-'  AS NR_ROW, 'inclusiv în:'    AS NUME_ROW,    25 AS ORDINE FROM DUAL  UNION
SELECT '11'  AS NR_ROW, 'clasele 1-4'    AS NUME_ROW,  26 AS ORDINE FROM DUAL UNION
SELECT '12'  AS NR_ROW, 'clasele 5-9'    AS NUME_ROW,  27 AS ORDINE FROM DUAL UNION
SELECT '13'  AS NR_ROW, 'clasele 10-12'    AS NUME_ROW,  28 AS ORDINE FROM DUAL
 
) B
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024
    AND D.COL1 = 152
   GROUP BY
  C.DENUMIRE,
  C.CODUL,
  B.ORDINE,
  B.NUME_ROW,
  B.NR_ROW
  


  
 ORDER BY
 CODUL,
  ORDINE
  
  )D
  

  
