--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
-- COL1, COL2, COL3, COL4, COL5
--)

SELECT
   PERIOADA,
   FORM,
   FORM_VERS,
   ID_MDTABLE,
   COD_CUATM,
   NR_SECTIE,
   NUME_SECTIE,
   NR_SECTIE1,
   NUME_SECTIE1,
   NR_SECTIE2,
   NUME_SECTIE2,
   NR_ROW,
   ORDINE,
   DECIMAL_POS,
   NUME_ROW, 
  CASE WHEN COL1 = 0 THEN NULL ELSE COL1 END AS COL1,
  CASE WHEN COL2 = 0 THEN NULL ELSE COL2 END AS COL2,
  CASE WHEN COL3 = 0 THEN NULL ELSE COL3 END AS COL3,
  CASE WHEN COL4 = 0 THEN NULL ELSE COL4 END AS COL4,
  CASE WHEN COL5 = 0 THEN NULL ELSE COL5 END AS COL5
  FROM
  
  (
  
  
SELECT DISTINCT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
   CODUL AS NR_SECTIE,
   LOCAL AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   NR_ROW||'~'||ORDINE AS NR_ROW,
   ORDINE,
  '00000' AS DECIMAL_POS,
   DENUMIRE AS NUME_ROW,
   SUM(COL1) AS COL1, 
   SUM(COL2) AS COL2,
   SUM(COL3) AS COL3,
   SUM(COL4) AS COL4,
   SUM(COL5) AS COL5
  
FROM
(
SELECT
  
  TR.DENUMIRE AS DENUMIRE,
  TR.ORDINE,
  TR.NR_ROW,
  D.CUIIO,
    T.CODUL,
  T.DENUMIRE AS LOCAL,
--  CC.CODUL AS CODUL_CUATM,
--  CC.DENUMIRE DENUMIRE_CUATM,
--  CC.FULL_CODE,
  
  CASE 
    WHEN TR.ORDINE IN (1) THEN 
      SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
    WHEN TR.ORDINE IN (3) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 END))=0) OR
                 (SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END)=SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','10') THEN D.COL2 END))=0) OR
                 (SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END)=SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0) 
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (5) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (6) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (7) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=67)
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (8) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=160)
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (9) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=152)
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (10) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))>0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0)
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (12) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (13) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END)) = 067 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0)
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (14) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END)) = 160 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
       (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))= 0)       )
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
      
      

      
        WHEN TR.ORDINE IN (16) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL1) END)) = 152 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN NVAL(D.COL2) END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL2) END)) > 0 AND
       (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN NVAL(D.COL2) END)) >  0)       )
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
    
  END AS COL1,
  
  
  
  
  CASE 
    WHEN TR.ORDINE IN (1) THEN 
      SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END) 
    WHEN TR.ORDINE IN (3) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 END))=0) OR
                 (SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END)=SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','10') THEN D.COL2 END))=0) OR
                 (SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END)=SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0) 
           THEN
           SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END) 
      END
    WHEN TR.ORDINE IN (5) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) 
      END
    WHEN TR.ORDINE IN (6) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (7) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=67)
           THEN
           SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (8) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=160)
           THEN
           SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (9) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=152)
           THEN
           SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (10) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))>0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0)
           THEN
           SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (12) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (13) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END)) = 067 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0)
           THEN
           SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (14) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END)) = 160 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
       (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))= 0)       )
           THEN
           SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 ELSE 0 END)
      END

      
      
      WHEN TR.ORDINE IN (16) THEN
      
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL1) END)) = 152 AND
      
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN NVAL(D.COL2) END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL2) END))>0 AND
       (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN NVAL(D.COL2) END)) >  0)       )
           THEN
           SUM(CASE WHEN D.RIND IN ('02','06','10') THEN D.COL2 ELSE 0 END)
           
           
      END  
      
    
  END AS COL2,
  
  
  
  
  
  CASE 
    WHEN TR.ORDINE IN (1) THEN 
      SUM(CASE WHEN D.RIND IN ('03','07','11') THEN D.COL2 ELSE 0 END)
    WHEN TR.ORDINE IN (3) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 END))=0) OR
                 (SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END)=SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','10') THEN D.COL2 END))=0) OR
                 (SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END)=SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0) 
           THEN
           SUM(CASE WHEN D.RIND IN ('03','07','11') THEN D.COL2 ELSE 0 END) 
      END
    WHEN TR.ORDINE IN (5) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN ('03') THEN D.COL2 ELSE 0 END) 
      END
    WHEN TR.ORDINE IN (6) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN '07' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (7) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=67)
           THEN
           SUM(CASE WHEN D.RIND IN '11' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (8) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=160)
           THEN
           SUM(CASE WHEN D.RIND IN '11' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (9) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=152)
           THEN
           SUM(CASE WHEN D.RIND IN '11' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (10) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))>0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0)
           THEN
           SUM(CASE WHEN D.RIND IN ('03','07','11') THEN D.COL2 ELSE 0 END) 
      END
    WHEN TR.ORDINE IN (12) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN ('03','07') THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (13) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END)) = 067 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0)
           THEN
           SUM(CASE WHEN D.RIND IN ('07','11') THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (14) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END)) = 160 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
       (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))= 0)       )
           THEN
           SUM(CASE WHEN D.RIND IN ('07','11') THEN D.COL2 ELSE 0 END)
      END
      

    
 WHEN TR.ORDINE IN (16) THEN
 
       CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL1) END)) = 152 AND
      
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN NVAL(D.COL2) END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL2) END))>0 AND
       (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN NVAL(D.COL2) END)) >  0)       )
           THEN
           SUM(CASE WHEN D.RIND IN ('03','07','11') THEN D.COL2 ELSE 0 END)
           
           
      END

    
  END AS COL3,
  
  
  
  
  
  CASE 
    WHEN TR.ORDINE IN (1) THEN 
      SUM(CASE WHEN D.RIND IN ('04','08','12') THEN D.COL2 ELSE 0 END)
    WHEN TR.ORDINE IN (3) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 END))=0) OR
                 (SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END)=SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','10') THEN D.COL2 END))=0) OR
                 (SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END)=SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0) 
           THEN
           SUM(CASE WHEN D.RIND IN ('04','08','12') THEN D.COL2 ELSE 0 END) 
      END
    WHEN TR.ORDINE IN (5) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN ('04') THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (6) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN '08' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (7) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=67)
           THEN
           SUM(CASE WHEN D.RIND IN '12' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (8) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=160)
           THEN
           SUM(CASE WHEN D.RIND IN '12' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (9) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=152)
           THEN
           SUM(CASE WHEN D.RIND IN '12' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (10) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))>0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0)
           THEN
           SUM(CASE WHEN D.RIND IN ('04','08','12') THEN D.COL2 ELSE 0 END) 
      END
    WHEN TR.ORDINE IN (12) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN ('04','08') THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (13) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END)) = 067 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0)
           THEN
           SUM(CASE WHEN D.RIND IN ('08','12') THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (14) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END)) = 160 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
       (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))= 0)       )
           THEN
           SUM(CASE WHEN D.RIND IN ('08','12') THEN D.COL2 ELSE 0 END)
      END
    
    
 
      
    
WHEN TR.ORDINE IN (16) THEN

  CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL1) END)) = 152 AND
      
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN NVAL(D.COL2) END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL2) END))>0 AND
       (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN NVAL(D.COL2) END)) >  0)       )
           THEN
           SUM(CASE WHEN D.RIND IN ('04','08','12') THEN D.COL2 ELSE 0 END)
           

      END
    
  
    
  END AS COL4,
  
  
  
  
  
  CASE 
    WHEN TR.ORDINE IN (1) THEN 
      SUM(CASE WHEN D.RIND IN ('05','09','13') THEN D.COL2 ELSE 0 END)
    WHEN TR.ORDINE IN (3) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 END))=0) OR
                 (SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END)=SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','10') THEN D.COL2 END))=0) OR
                 (SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END)=SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0) 
           THEN
           SUM(CASE WHEN D.RIND IN ('05','09','13') THEN D.COL2 ELSE 0 END) 
      END
    WHEN TR.ORDINE IN (5) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN ('05') THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (6) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN '09' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (7) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=67)
           THEN
           SUM(CASE WHEN D.RIND IN '13' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (8) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=160)
           THEN
           SUM(CASE WHEN D.RIND IN '13' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (9) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=152)
           THEN
           SUM(CASE WHEN D.RIND IN '13' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (10) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))>0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0)
           THEN
           SUM(CASE WHEN D.RIND IN ('05','09','13') THEN D.COL2 ELSE 0 END) 
      END
    WHEN TR.ORDINE IN (12) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN ('05','09') THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (13) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END)) = 067 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0)
           THEN
           SUM(CASE WHEN D.RIND IN ('09','13') THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (14) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END)) = 160 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
       (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))= 0)       )
           THEN
           SUM(CASE WHEN D.RIND IN ('09','13') AND R.NTII NOT IN (60,71,72,73,80) THEN D.COL2 ELSE 0 END)
      END
      
      

      
          WHEN TR.ORDINE IN (16) THEN
          
          
          
       CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL1) END)) = 152 AND
      
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN NVAL(D.COL2) END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL2) END))>0 AND
       (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN NVAL(D.COL2) END)) >  0)       )
           THEN
           SUM(CASE WHEN D.RIND IN ('05','09','13') THEN D.COL2 ELSE 0 END)
           

      END
      
  END AS COL5
  
  
  
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  INNER JOIN CIS2.CL_TIP_LOCAL T ON (T.CODUL = R.TIP_LOCAL)

  CROSS JOIN 
  (
SELECT 'Total'                                             AS DENUMIRE, '1'  AS NR_ROW, 1 AS ORDINE FROM DUAL UNION
SELECT 'din care:'                                         AS DENUMIRE, '-'  AS NR_ROW, 2 AS ORDINE FROM DUAL UNION
SELECT 'predarea numai intr-o singura limba - total'       AS DENUMIRE, '2'  AS NR_ROW, 3 AS ORDINE FROM DUAL UNION
SELECT 'din care:'                                         AS DENUMIRE, '-'  AS NR_ROW, 4 AS ORDINE FROM DUAL UNION
SELECT 'romana'                                            AS DENUMIRE, '3'  AS NR_ROW, 5 AS ORDINE FROM DUAL UNION
SELECT 'rusa'                                              AS DENUMIRE, '4'  AS NR_ROW, 6 AS ORDINE FROM DUAL UNION
SELECT 'ucraineana'                                        AS DENUMIRE, '5'  AS NR_ROW, 7 AS ORDINE FROM DUAL UNION
SELECT 'bulgara'                                           AS DENUMIRE, '6'  AS NR_ROW, 8 AS ORDINE FROM DUAL UNION
SELECT 'engleza'                                           AS DENUMIRE, '7'  AS NR_ROW, 9 AS ORDINE FROM DUAL UNION
SELECT 'predarea in mai multe limbi (scoli mixte) - total' AS DENUMIRE, '8'  AS NR_ROW, 10 AS ORDINE FROM DUAL UNION
SELECT 'din care:'                                         AS DENUMIRE, '-'  AS NR_ROW, 11 AS ORDINE FROM DUAL UNION
SELECT 'romana-rusa'                                       AS DENUMIRE, '9'  AS NR_ROW, 12 AS ORDINE FROM DUAL UNION
SELECT 'ucraineana-rusa'                                   AS DENUMIRE, '10' AS NR_ROW, 13 AS ORDINE FROM DUAL UNION 
SELECT 'bulgara-rusa'                                      AS DENUMIRE, '11' AS NR_ROW, 14 AS ORDINE FROM DUAL UNION
SELECT 'romana-engleza-rusa'                                      AS DENUMIRE, '12' AS NR_ROW, 16 AS ORDINE FROM DUAL

  ) TR
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 
   
 
GROUP BY
  T.CODUL,
  T.DENUMIRE,
  D.CUIIO,
  TR.DENUMIRE,
  TR.NR_ROW,
  TR.ORDINE
  
  
  

ORDER BY
 
  ORDINE
)
GROUP BY
  CODUL,
  LOCAL,
  DENUMIRE,
  ORDINE,
  NR_ROW
ORDER BY
 
  ORDINE
  
  )