INSERT INTO TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
 COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12
)
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  FULL_CODE AS NR_SECTIE,
  DENUMIRE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   ORDINE AS NR_ROW,
   ORDINE,
  '000000000000' AS DECIMAL_POS,
   NUME_ROW, 
   
   --COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12
   
   CASE WHEN COL1 = 0 THEN NULL ELSE COL1 END AS COL1,
  CASE WHEN COL2 = 0 THEN NULL ELSE COL2 END AS COL2,
  CASE WHEN COL3 = 0 THEN NULL ELSE COL3 END AS COL3,
  CASE WHEN COL4 = 0 THEN NULL ELSE COL4 END AS COL4,
  CASE WHEN COL5 = 0 THEN NULL ELSE COL5 END AS COL5,
  CASE WHEN COL6 = 0 THEN NULL ELSE COL6 END AS COL6,
  CASE WHEN COL7 = 0 THEN NULL ELSE COL7 END AS COL7,
  CASE WHEN COL8 = 0 THEN NULL ELSE COL8 END AS COL8,
  CASE WHEN COL9 = 0 THEN NULL ELSE COL9 END AS COL9,         
  CASE WHEN COL10 = 0 THEN NULL ELSE COL10 END AS COL10,
  CASE WHEN COL11 = 0 THEN NULL ELSE COL11 END AS COL11,
  CASE WHEN COL12 = 0 THEN NULL ELSE COL12 END AS COL12   
   
FROM
(
SELECT  
  C.FULL_CODE,
  C.DENUMIRE,
  B.ORDINE,
  B.NUME_ROW,  
  
  
    SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL14) ELSE 0 END) AS COL1,
  
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL1) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL3) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL4) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL5) ELSE 0 END)) AS COL2,
  
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL6) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL7) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL8) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL9) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL10) ELSE 0 END)) AS COL3,
  
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL11) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL12) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL13) ELSE 0 END)) AS COL4,
  
  
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL14) ELSE 0 END) AS COL5,
 
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL1) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL3) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL4) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL5) ELSE 0 END))AS COL6,
 
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL6) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL7) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL8) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL9) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL10) ELSE 0 END)) AS COL7,
  
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL11) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL12) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL13) ELSE 0 END)) AS COL8,
  
  (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL14) ELSE 0 END)-
   SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL14) ELSE 0 END)) AS COL9,
  
((SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL1) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL3) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL4) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL5) ELSE 0 END))- 
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL1) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL3) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL4) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL5) ELSE 0 END))) AS COL10,
 
((SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL6) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL7) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL8) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL9) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL10) ELSE 0 END))-
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL6) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL7) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL8) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL9) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN D.COL10 ELSE 0 END))) AS COL11,
  
((SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL11) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL12) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL13) ELSE 0 END))-
  
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL11) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL12) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL13) ELSE 0 END))) AS COL12
  
FROM 
  CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.VW_CL_CUATM A ON (D.CUATM=A.CODUL)
  INNER JOIN CIS2.VW_CL_CUATM C ON (A.FULL_CODE LIKE '%'||C.CODUL||';%')


CROSS JOIN
(

SELECT '01+02'          AS NR_ROW, '5-6 ani'                                            AS NUME_ROW, 1 AS ORDINE FROM DUAL UNION
SELECT '03+04+05+06'    AS NR_ROW, '7-10 ani'                                           AS NUME_ROW, 2 AS ORDINE FROM DUAL UNION
SELECT '07+08+09+10-11' AS NR_ROW, '11-15 ani'                                          AS NUME_ROW, 3 AS ORDINE FROM DUAL UNION
SELECT '12+13+14'       AS NR_ROW, '16-18 ani'                                          AS NUME_ROW, 4 AS ORDINE FROM DUAL UNION
SELECT '15+16+17+18'    AS NR_ROW, '19 ani si peste'                                    AS NUME_ROW, 5 AS ORDINE FROM DUAL UNION
SELECT '19'             AS NR_ROW, 'Total'                                              AS NUME_ROW, 6 AS ORDINE FROM DUAL UNION
SELECT '20'             AS NR_ROW, 'elevi cu cerinte educationale speciale'             AS NUME_ROW, 7 AS ORDINE FROM DUAL UNION
SELECT '21'             AS NR_ROW, 'elevi cu dizabilitati'                              AS NUME_ROW, 8 AS ORDINE FROM DUAL UNION
SELECT '21.a'           AS NR_ROW, 'inclusiv: elevi cu dizabilitati ?are au nevoie de scolarizare adaptata deficien?elor'                              AS NUME_ROW, 8.1 AS ORDINE FROM DUAL UNION  
SELECT '22'             AS NR_ROW, 'numarul de clase (fara clase cu predare simultana)' AS NUME_ROW, 9 AS ORDINE FROM DUAL 



) B


WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 40 AND
  D.CAPITOL IN (1022,1023) AND
  C.PRGS IN 2 AND
  D.CUIIO IN (SELECT DISTINCT CUIIO FROM CIS2.RENIM WHERE NFI IN 1 AND CUIIO_VERS > 1998)

GROUP BY 
  B.NUME_ROW, 
  B.ORDINE,
  C.FULL_CODE,
  C.DENUMIRE

UNION

SELECT 
 '0000000;9810000;' AS FULL_CODE,
  C.DENUMIRE,
  B.ORDINE,
  B.NUME_ROW,  
  
  
    SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL14) ELSE 0 END) AS COL1,
  
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL1) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL3) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL4) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL5) ELSE 0 END)) AS COL2,
  
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL6) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL7) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL8) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL9) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL10) ELSE 0 END)) AS COL3,
  
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL11) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL12) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 THEN NVAL(D.COL13) ELSE 0 END)) AS COL4,
  
  
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL14) ELSE 0 END) AS COL5,
 
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL1) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL3) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL4) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL5) ELSE 0 END))AS COL6,
 
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL6) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL7) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL8) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL9) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL10) ELSE 0 END)) AS COL7,
  
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL11) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL12) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 THEN NVAL(D.COL13) ELSE 0 END)) AS COL8,
  
  (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL14) ELSE 0 END)-
   SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL14) ELSE 0 END)) AS COL9,
  
((SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL1) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL3) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL4) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL5) ELSE 0 END))- 
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL1) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL3) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL4) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL5) ELSE 0 END))) AS COL10,
 
((SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL6) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL7) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL8) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL9) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL10) ELSE 0 END))-
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL6) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL7) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL8) ELSE 0 END)+ 
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL9) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN D.COL10 ELSE 0 END))) AS COL11,
  
((SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL11) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL12) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1022 AND D.RIND NOT IN '22' THEN NVAL(D.COL13) ELSE 0 END))-
  
 (SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL11) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL12) ELSE 0 END)+
  SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.RIND ||'%' AND D.CAPITOL IN 1023 AND D.RIND NOT IN '22' THEN NVAL(D.COL13) ELSE 0 END))) AS COL12
FROM 
  CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.VW_CL_CUATM A ON (D.CUATM=A.CODUL)
  INNER JOIN CIS2.VW_CL_CUATM C ON (A.FULL_CODE LIKE '%'||C.CODUL||';%')


CROSS JOIN
(

SELECT '01+02'          AS NR_ROW, '5-6 ani'                                            AS NUME_ROW, 1 AS ORDINE FROM DUAL UNION
SELECT '03+04+05+06'    AS NR_ROW, '7-10 ani'                                           AS NUME_ROW, 2 AS ORDINE FROM DUAL UNION
SELECT '07+08+09+10-11' AS NR_ROW, '11-15 ani'                                          AS NUME_ROW, 3 AS ORDINE FROM DUAL UNION
SELECT '12+13+14'       AS NR_ROW, '16-18 ani'                                          AS NUME_ROW, 4 AS ORDINE FROM DUAL UNION
SELECT '15+16+17+18'    AS NR_ROW, '19 ani si peste'                                    AS NUME_ROW, 5 AS ORDINE FROM DUAL UNION
SELECT '19'             AS NR_ROW, 'Total'                                              AS NUME_ROW, 6 AS ORDINE FROM DUAL UNION
SELECT '20'             AS NR_ROW, 'elevi cu cerinte educationale speciale'             AS NUME_ROW, 7 AS ORDINE FROM DUAL UNION
SELECT '21'             AS NR_ROW, 'elevi cu dizabilitati'                              AS NUME_ROW, 8 AS ORDINE FROM DUAL UNION
SELECT '21.a'           AS NR_ROW, 'inclusiv: elevi cu dizabilitati ?are au nevoie de scolarizare adaptata deficien?elor'                              AS NUME_ROW, 8.1 AS ORDINE FROM DUAL UNION  
SELECT '22'             AS NR_ROW, 'numarul de clase (fara clase cu predare simultana)' AS NUME_ROW, 9 AS ORDINE FROM DUAL 



) B


WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 40 AND
  D.CAPITOL IN (1022,1023) AND
  C.CODUL IN 0501000 AND
  D.CUIIO IN (SELECT DISTINCT CUIIO FROM CIS2.RENIM WHERE NFI IN 1 AND CUIIO_VERS > 1998)

GROUP BY 
  B.NUME_ROW, 
  B.ORDINE,
  C.FULL_CODE,
  C.DENUMIRE
)