INSERT INTO TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
 COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14
)
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
   NR_SECTIE,
   NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   NR_ROW,
   ORDINE,
  '000000000000000' AS DECIMAL_POS,
   NUME_ROW,
  CASE WHEN COL1 = 0 THEN NULL ELSE COL1 END AS COL1,
  CASE WHEN COL2 = 0 THEN NULL ELSE COL2 END AS COL2,
  CASE WHEN COL3 = 0 THEN NULL ELSE COL3 END AS COL3,
  CASE WHEN COL4 = 0 THEN NULL ELSE COL4 END AS COL4,
  CASE WHEN COL5 = 0 THEN NULL ELSE COL5 END AS COL5,
  CASE WHEN COL6 = 0 THEN NULL ELSE COL6 END AS COL6,
  CASE WHEN COL7 = 0 THEN NULL ELSE COL7 END AS COL7,
  CASE WHEN COL8 = 0 THEN NULL ELSE COL8 END AS COL8,
  CASE WHEN COL9 = 0 THEN NULL ELSE COL9 END AS COL9,         
  CASE WHEN COL10 = 0 THEN NULL ELSE COL10 END AS COL10,
  CASE WHEN COL11 = 0 THEN NULL ELSE COL11 END AS COL11,
  CASE WHEN COL12 = 0 THEN NULL ELSE COL12 END AS COL12, 
  CASE WHEN COL13 = 0 THEN NULL ELSE COL13 END AS COL13,
  CASE WHEN COL14 = 0 THEN NULL ELSE COL14 END AS COL14   
   
FROM (

SELECT
  C.FULL_CODE NR_SECTIE,
  C.DENUMIRE AS NUME_SECTIE,
  J.DENUMIRE AS NUME_ROW,
  J.RIND AS NR_ROW,
  J.ORDINE,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL1 ELSE NULL END) AS COL1,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL2 ELSE NULL END) AS COL2,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL3 ELSE NULL END) AS COL3,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL4 ELSE NULL END) AS COL4,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL5 ELSE NULL END) AS COL5,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL6 ELSE NULL END) AS COL6,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL7 ELSE NULL END) AS COL7,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL8 ELSE NULL END) AS COL8,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL9 ELSE NULL END) AS COL9,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL10 ELSE NULL END) AS COL10,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL11 ELSE NULL END) AS COL11,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL12 ELSE NULL END) AS COL12,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL13 ELSE NULL END) AS COL13,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL14 ELSE NULL END) AS COL14

FROM 
  CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON D.CUIIO = R.CUIIO AND D.CUIIO_VERS = R.CUIIO_VERS
  INNER JOIN CIS2.VW_CL_CFP B ON (D.CFP = B.CODUL)
  INNER JOIN CIS2.VW_CL_CFP C ON (B.FULL_CODE LIKE '%'||C.CODUL||';%')
  CROSS JOIN (

  SELECT
    DENUMIRE,
    RIND,
    ORDINE
  
  FROM 
    CIS2.MD_RIND

  WHERE
    FORM = 40 AND
    CAPITOL = 1023 
    AND
       CAPITOL_VERS = 2010
       
    
    ) J
    
WHERE
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND
   D.CAPITOL = 1023 AND
   C.CODUL IN (11,12,13,14,16,18,19)
   
GROUP BY
  C.FULL_CODE,
  C.DENUMIRE,
  J.DENUMIRE,
  J.RIND,
  J.ORDINE
  
  
)

WHERE
  NUME_SECTIE LIKE '%PRIVATA%' OR NUME_SECTIE LIKE '%PUBLICA%'