SELECT
   CR.NUME_ROW AS LOCALITATE,
   CR.NR_ROW,
   B.NR_ROW,
   B.ORDINE,
  B.NUME_ROW, 

  SUM(CASE WHEN  B.NR_ROW = D.RIND  AND C.CODUL =  CR.NR_ROW  THEN D.COL2 ELSE 0 END ) AS COL1,
  SUM(CASE WHEN  B.NR_ROW = D.RIND  AND C.CODUL =  CR.NR_ROW  THEN D.COL3 ELSE 0 END ) AS COL2,
  SUM(CASE WHEN  B.NR_ROW = D.RIND  AND C.CODUL =  CR.NR_ROW  THEN D.COL4 ELSE 0 END ) AS COL3,
  SUM(CASE WHEN  B.NR_ROW = D.RIND  AND C.CODUL =  CR.NR_ROW  THEN D.COL5 ELSE 0 END ) AS COL4,
  SUM(CASE WHEN  B.NR_ROW = D.RIND  AND C.CODUL =  CR.NR_ROW  THEN D.COL6 ELSE 0 END ) AS COL5,
  SUM(CASE WHEN  B.NR_ROW = D.RIND  AND C.CODUL =  CR.NR_ROW  THEN D.COL7 ELSE 0 END ) AS COL6,
  SUM(CASE WHEN  B.NR_ROW = D.RIND  AND C.CODUL =  CR.NR_ROW  THEN D.COL8 ELSE 0 END ) AS COL7
  


  
FROM CIS2.VW_DATA_ALL D

        INNER JOIN CIS2.RENIM E ON E.CUIIO = D.CUIIO AND E.CUIIO_VERS = D.CUIIO_VERS    
        INNER JOIN CIS2.MD_RIND MR ON (MR.ID_MD = D.ID_MD) 
     
        INNER JOIN CIS2.CL_TIP_LOCAL C ON C.CODUL = E.TIP_LOCAL
         
        CROSS JOIN
(

SELECT '01'  AS NR_ROW, 'Total'    AS NUME_ROW,  1 AS ORDINE, '1' AS ORDINE_2 FROM DUAL UNION
SELECT '-'  AS NR_ROW, 'din ei studiează:'    AS NUME_ROW,  2 AS ORDINE,   '-' AS ORDINE_2 FROM DUAL UNION
SELECT '02'  AS NR_ROW, 'în limba română'    AS NUME_ROW,   3 AS ORDINE, '2' AS ORDINE_2 FROM  DUAL UNION
SELECT '-'  AS NR_ROW, 'inclusiv în:'    AS NUME_ROW,   4 AS ORDINE , '-' AS ORDINE_2 FROM DUAL  UNION
SELECT '03'  AS NR_ROW, 'clasele 1-4'    AS NUME_ROW,   5 AS ORDINE , '3' AS ORDINE_2 FROM  DUAL  UNION
SELECT '04'  AS NR_ROW, 'clasele 5-9'    AS NUME_ROW,   6 AS ORDINE, '4' AS ORDINE_2 FROM  DUAL UNION
SELECT '05'  AS NR_ROW, 'clasele 10-12'    AS NUME_ROW,   7 AS ORDINE , '5' AS ORDINE_2 FROM  DUAL UNION
SELECT '06'  AS NR_ROW, 'în limba rusă'    AS NUME_ROW,  8 AS ORDINE , '6' AS ORDINE_2 FROM  DUAL  UNION
SELECT '-'  AS NR_ROW, 'inclusiv în:'    AS NUME_ROW,  9 AS ORDINE  , '-' AS ORDINE_2 FROM  DUAL UNION
SELECT '07'  AS NR_ROW, 'clasele 1-4'    AS NUME_ROW,  10 AS ORDINE , '7' AS ORDINE_2 FROM  DUAL UNION
SELECT '08'  AS NR_ROW, 'clasele 5-9'    AS NUME_ROW,  11 AS ORDINE , '8' AS ORDINE_2 FROM  DUAL UNION
SELECT '09'  AS NR_ROW, 'clasele 11-12'    AS NUME_ROW,  12 AS ORDINE , '9' AS ORDINE_2 FROM  DUAL 

 
) B
  
  
CROSS JOIN 
(
SELECT '1'  AS NR_ROW, 'URBAN'    AS NUME_ROW,  1 AS ORDINE FROM DUAL UNION
SELECT '2'  AS NR_ROW, 'RURAL'    AS NUME_ROW,  2 AS ORDINE  FROM DUAL 
) CR

WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024
  
 GROUP BY
  CR.NUME_ROW,
  CR.NR_ROW,
  B.ORDINE,
  B.ORDINE_2,
  B.NUME_ROW,
  B.NR_ROW