SELECT
  C.DENUMIRE AS LOCALITATE,
  C.CODUL,
   B.NR_ROW,
   B.ORDINE,
   B.NUME_ROW, 

  SUM(CASE WHEN  B.NR_ROW = D.RIND    THEN D.COL2 ELSE 0 END ) AS COL1,
  SUM(CASE WHEN  B.NR_ROW = D.RIND    THEN D.COL3 ELSE 0 END ) AS COL2,
  SUM(CASE WHEN  B.NR_ROW = D.RIND    THEN D.COL4 ELSE 0 END ) AS COL3,
  SUM(CASE WHEN  B.NR_ROW = D.RIND   THEN D.COL5 ELSE 0 END ) AS COL4,
  SUM(CASE WHEN  B.NR_ROW = D.RIND   THEN D.COL6 ELSE 0 END ) AS COL5,
  SUM(CASE WHEN  B.NR_ROW = D.RIND   THEN D.COL7 ELSE 0 END ) AS COL6,
  SUM(CASE WHEN  B.NR_ROW = D.RIND    THEN D.COL8 ELSE 0 END ) AS COL7
  


  
FROM CIS2.VW_DATA_ALL D
        INNER JOIN CIS2.MD_RIND MR ON (MR.ID_MD = D.ID_MD)
        INNER JOIN CIS2.RENIM E ON E.CUIIO = D.CUIIO AND E.CUIIO_VERS = D.CUIIO_VERS
        INNER JOIN CIS2.CL_TIP_LOCAL C ON C.CODUL = E.TIP_LOCAL
        
        CROSS JOIN
(

SELECT '10'  AS NR_ROW, 'în limba bulgara'    AS NUME_ROW,  19 AS ORDINE FROM DUAL  UNION
SELECT '-'  AS NR_ROW, 'inclusiv în:'    AS NUME_ROW,    20 AS ORDINE FROM DUAL  UNION
SELECT '11'  AS NR_ROW, 'clasele 1-4'    AS NUME_ROW,  21 AS ORDINE FROM DUAL UNION
SELECT '12'  AS NR_ROW, 'clasele 5-9'    AS NUME_ROW,  22 AS ORDINE FROM DUAL UNION
SELECT '13'  AS NR_ROW, 'clasele 10-12'    AS NUME_ROW,  23 AS ORDINE FROM DUAL
 
) B
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024
   
   GROUP BY
  C.DENUMIRE,
  C.CODUL,
  B.ORDINE,
  B.NUME_ROW,
  B.NR_ROW