--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
-- COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14
--)


SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
   B.NR AS NR_SECTIE,
   B.NUME_SECTIE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   RR.RIND||'~'||B.NR AS NR_ROW,
   RR.ORDINE AS ORDINE,
  '00000000000000' AS DECIMAL_POS,
   RR.DENUMIRE AS NUME_ROW,
 
  
  
  SUM(CASE WHEN B.NTII LIKE '%'|| R.NTII ||'%' THEN COL1 ELSE NULL END) AS COL1,
  SUM(CASE WHEN B.NTII LIKE '%'|| R.NTII ||'%' THEN COL2 ELSE NULL END) AS COL2,
  SUM(CASE WHEN B.NTII LIKE '%'|| R.NTII ||'%' THEN COL3 ELSE NULL END) AS COL3,
  SUM(CASE WHEN B.NTII LIKE '%'|| R.NTII ||'%' THEN COL4 ELSE NULL END) AS COL4,
  SUM(CASE WHEN B.NTII LIKE '%'|| R.NTII ||'%' THEN COL5 ELSE NULL END) AS COL5,
  SUM(CASE WHEN B.NTII LIKE '%'|| R.NTII ||'%' THEN COL6 ELSE NULL END) AS COL6,
  SUM(CASE WHEN B.NTII LIKE '%'|| R.NTII ||'%' THEN COL7 ELSE NULL END) AS COL7,
  SUM(CASE WHEN B.NTII LIKE '%'|| R.NTII ||'%' THEN COL8 ELSE NULL END) AS COL8,
  SUM(CASE WHEN B.NTII LIKE '%'|| R.NTII ||'%' THEN COL9 ELSE NULL END) AS COL9,
  SUM(CASE WHEN B.NTII LIKE '%'|| R.NTII ||'%' THEN COL10 ELSE NULL END) AS COL10,
  SUM(CASE WHEN B.NTII LIKE '%'|| R.NTII ||'%' THEN COL11 ELSE NULL END) AS COL11,
  SUM(CASE WHEN B.NTII LIKE '%'|| R.NTII ||'%' THEN COL12 ELSE NULL END) AS COL12,
  SUM(CASE WHEN B.NTII LIKE '%'|| R.NTII ||'%' THEN COL13 ELSE NULL END) AS COL13,
  SUM(CASE WHEN B.NTII LIKE '%'|| R.NTII ||'%' THEN COL14 ELSE NULL END) AS COL14


FROM
  CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  INNER JOIN CIS2.MD_RIND RR ON RR.ID_MD = D.ID_MD
  CROSS JOIN
    (
     SELECT 1 AS ORDINE, '10' AS NTII, 10 AS NR, 'Scolile primare' AS NUME_SECTIE FROM DUAL UNION
     SELECT 2 AS ORDINE, '20+21' AS NTII, 20 AS NR, 'Gimnazii' AS NUME_SECTIE FROM DUAL UNION
     SELECT 3 AS ORDINE, '30+31' AS NTII, 30 AS NR, 'Licee' AS NUME_SECTIE FROM DUAL UNION
     SELECT 4 AS ORDINE, '40' AS NTII, 40 AS NR, 'Scolile pentru copii cu deficiente in dezvoltarea intelectuala sau fizica' AS NUME_SECTIE FROM DUAL UNION
     SELECT 5 AS ORDINE, '50+60' AS NTII, 50 AS NR, 'Scolile serale' AS NUME_SECTIE FROM DUAL UNION
     SELECT 6 AS ORDINE, '72' AS NTII, 70 AS NR, 'Clase pe linga colegii' AS NUME_SECTIE FROM DUAL ) B
     

WHERE
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND
   D.CAPITOL = 1022
   AND D.CAPITOL_VERS = 2010
   AND
   R.NFI = 2
 
   
GROUP BY
  B.NUME_SECTIE,
  RR.DENUMIRE,
  RR.RIND,
  RR.ORDINE,
  B.NR

  