SELECT
  MR.RIND,
  MR.DENUMIRE,

  SUM(D.COL2) AS COL1,
  SUM(D.COL3) AS COL2,
  SUM(D.COL4) AS COL3,
  SUM(D.COL5) AS COL4,
  SUM(D.COL6) AS COL5,
  SUM(D.COL7) AS COL6,
  SUM(D.COL8) AS COL7

  
FROM CIS2.VW_DATA_ALL D
        INNER JOIN CIS2.MD_RIND MR ON (MR.ID_MD = D.ID_MD)
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024
   
   GROUP BY
   
  MR.RIND,
  MR.DENUMIRE,
  MR.ORDINE
  
  ORDER BY
  MR.ORDINE