--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
-- COL1, COL2, COL3, COL4, COL5
--)
SELECT DISTINCT
--  :pPERIOADA AS PERIOADA,
--  :pFORM AS FORM,
--  :pFORM_VERS AS FORM_VERS,
--  :pID_MDTABLE AS ID_MDTABLE,
--  :pCOD_CUATM AS COD_CUATM,
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   D.ORDINE NR_ROW,
   D.ORDINE,
  '00000' AS DECIMAL_POS,
   D.DENUMIRE AS NUME_ROW,
   --COL1, COL2,COL3,COL4,COL5
    CASE WHEN COL1 = 0 THEN NULL ELSE COL1 END AS COL1,
  CASE WHEN COL2 = 0 THEN NULL ELSE COL2 END AS COL2,
  CASE WHEN COL3 = 0 THEN NULL ELSE COL3 END AS COL3,
  CASE WHEN COL4 = 0 THEN NULL ELSE COL4 END AS COL4,
  CASE WHEN COL5 = 0 THEN NULL ELSE COL5 END AS COL5
   
FROM

(
SELECT
  
  'Total' AS DENUMIRE,
  0 AS ORDINE,
  SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)  AS COL1,
  SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END) AS COL2,
  SUM(CASE WHEN D.RIND IN ('03','07','11') THEN D.COL2 ELSE 0 END) AS COL3,
  SUM(CASE WHEN D.RIND IN ('04','08','12') THEN D.COL2 ELSE 0 END) AS COL4,
  SUM(CASE WHEN D.RIND IN ('05','09','13') THEN D.COL2 ELSE 0 END) AS COL5
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024
   
UNION

SELECT
  'din care' AS DENUMIRE,
   1 AS ORDINE,
   0 AS COL1, 0 AS COL2, 0 AS COL3, 0 AS COL4, 0 AS COL5
FROM DUAL


UNION

SELECT
  'preadarea numai intr-o singura limba - total' AS DENUMIRE,
  2 AS ORDINE,
  COL1,
  COL2,
  COL3,
  COL4,
  COL5
  
FROM (
  SELECT COUNT(CUIIO) AS COL1 FROM (
SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND
   R.NTII NOT IN (60,71,72,73,80)
   
   
GROUP BY
  D.CUIIO
   
HAVING
  (SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END)=
  SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) AND
  
  (SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END)+
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END))=0 ) OR
  
  (SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END)=
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) AND
  
  (SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END)+
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END))=0 ) OR
  
  (SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END)=
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) AND
  
  (SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END)+
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END))=0 ) )
  
) CROSS JOIN

(
SELECT
  SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END) AS COL2,
  SUM(CASE WHEN D.RIND IN ('03','07','11') THEN D.COL2 ELSE 0 END) AS COL3,
  SUM(CASE WHEN D.RIND IN ('04','08','12') THEN D.COL2 ELSE 0 END) AS COL4,
  SUM(CASE WHEN D.RIND IN ('05','09','13') THEN D.COL2 ELSE 0 END) AS COL5
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND D.CUIIO IN
   (
   SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024
   
   
GROUP BY
  D.CUIIO
   
HAVING
  (SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END)=
  SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) AND
  
  (SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END)+
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END))=0 ) OR
  
  (SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END)=
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) AND
  
  (SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END)+
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END))=0 ) OR
  
  (SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END)=
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) AND
  
  (SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END)+
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END))=0 ) ) )


UNION


SELECT
  'romina' AS DENUMIRE,
  3 AS ORDINE,
  COL1,
  COL2,
  COL3,
  COL4,
  COL5
  
FROM (
  SELECT COUNT(CUIIO) AS COL1 FROM (
SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND
   R.NTII NOT IN (60,71,72,73,80)
   
   
GROUP BY
  D.CUIIO
   
HAVING
  (SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END)=
  SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) AND
  
  (SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END)+
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END))=0 ) )
  
) CROSS JOIN

(
SELECT
  SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) AS COL2,
  SUM(CASE WHEN D.RIND IN ('03') THEN D.COL2 ELSE 0 END) AS COL3,
  SUM(CASE WHEN D.RIND IN ('04') THEN D.COL2 ELSE 0 END) AS COL4,
  SUM(CASE WHEN D.RIND IN ('05') THEN D.COL2 ELSE 0 END) AS COL5
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND D.CUIIO IN
   (
   SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024
   
   
GROUP BY
  D.CUIIO
   
HAVING
  (SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END)=
  SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) AND
  
  (SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END)+
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END))=0 ) ) )
  
  
  
UNION

SELECT
  'rusa' AS DENUMIRE,
  4 AS ORDINE,
  COL1,
  COL2,
  COL3,
  COL4,
  COL5
  
FROM (
  SELECT COUNT(CUIIO) AS COL1 FROM (
SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND
   R.NTII NOT IN (60,71,72,73,80)
   
   
GROUP BY
  D.CUIIO
   
HAVING
    
  (SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END)=
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) AND
  
  (SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END)+
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END))=0 ))
  
) CROSS JOIN

(
SELECT
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) AS COL2,
  SUM(CASE WHEN D.RIND IN ('07') THEN D.COL2 ELSE 0 END) AS COL3,
  SUM(CASE WHEN D.RIND IN ('08') THEN D.COL2 ELSE 0 END) AS COL4,
  SUM(CASE WHEN D.RIND IN ('09') THEN D.COL2 ELSE 0 END) AS COL5
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND D.CUIIO IN
   (
   SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024
   
   
GROUP BY
  D.CUIIO
   
HAVING
    
  (SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END)=
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) AND
  
  (SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END)+
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END))=0 )) )
  
UNION

SELECT
  'ucraineana' AS DENUMIRE,
  5 AS ORDINE,
  COL1,
  COL2,
  COL3,
  COL4,
  COL5
  
FROM (
  SELECT COUNT(CUIIO) AS COL1 FROM (
SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND
   R.NTII NOT IN (60,71,72,73,80)
   
   
GROUP BY
  D.CUIIO
   
HAVING 
  (SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END)=
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) AND
  
  (SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END)+
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END))=0 ) AND
  
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL1 ELSE 0 END )= 067 )
  
) CROSS JOIN

(
SELECT
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) AS COL2,
  SUM(CASE WHEN D.RIND IN ('11') THEN D.COL2 ELSE 0 END) AS COL3,
  SUM(CASE WHEN D.RIND IN ('12') THEN D.COL2 ELSE 0 END) AS COL4,
  SUM(CASE WHEN D.RIND IN ('13') THEN D.COL2 ELSE 0 END) AS COL5
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND D.CUIIO IN
   (
   SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024
   
   
GROUP BY
  D.CUIIO
   
HAVING
    
  (SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END)=
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) AND
  
  (SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END)+
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END))=0 ) AND
  
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL1 ELSE 0 END )= 067 ))
  
UNION

SELECT
  'bulgara' AS DENUMIRE,
  6 AS ORDINE,
  COL1,
  COL2,
  COL3,
  COL4,
  COL5
  
FROM (
  SELECT COUNT(CUIIO) AS COL1 FROM (
SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND
   R.NTII NOT IN (60,71,72,73,80)
   
   
GROUP BY
  D.CUIIO
   
HAVING 
  (SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END)=
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) AND
  
  (SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END)+
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END))=0 ) AND
  
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL1 ELSE 0 END )= 160 )
  
) CROSS JOIN

(
SELECT
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) AS COL2,
  SUM(CASE WHEN D.RIND IN ('11') THEN D.COL2 ELSE 0 END) AS COL3,
  SUM(CASE WHEN D.RIND IN ('12') THEN D.COL2 ELSE 0 END) AS COL4,
  SUM(CASE WHEN D.RIND IN ('13') THEN D.COL2 ELSE 0 END) AS COL5
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND D.CUIIO IN
   (
   SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024
   
   
GROUP BY
  D.CUIIO
   
HAVING
    
  (SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END)=
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) AND
  
  (SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END)+
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END))=0 ) AND
  
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL1 ELSE 0 END )= 160 ))
  
UNION

SELECT
  'engleza' AS DENUMIRE,
  7 AS ORDINE,
  COL1,
  COL2,
  COL3,
  COL4,
  COL5
  
FROM (
  SELECT COUNT(CUIIO) AS COL1 FROM (
SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND
   R.NTII NOT IN (60,71,72,73,80)
   
   
GROUP BY
  D.CUIIO
   
HAVING 
  (SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END)=
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) AND
  
  (SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END)+
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END))=0 ) AND
  
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL1 ELSE 0 END )= 152 )
  
) CROSS JOIN

(
SELECT
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) AS COL2,
  SUM(CASE WHEN D.RIND IN ('11') THEN D.COL2 ELSE 0 END) AS COL3,
  SUM(CASE WHEN D.RIND IN ('12') THEN D.COL2 ELSE 0 END) AS COL4,
  SUM(CASE WHEN D.RIND IN ('13') THEN D.COL2 ELSE 0 END) AS COL5
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND D.CUIIO IN
   (
   SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024
   
   
GROUP BY
  D.CUIIO
   
HAVING
    
  (SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END)=
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) AND
  
  (SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END)+
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END))=0 ) AND
  
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL1 ELSE 0 END )= 152 ))
  
UNION

SELECT
  'preadarea in mai multe limbi (scoli mixte) - total' AS DENUMIRE,
  8 AS ORDINE,
  COL1,
  COL2,
  COL3,
  COL4,
  COL5
  
FROM (
  SELECT COUNT(CUIIO) AS COL1 FROM (
SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND
   R.NTII NOT IN (60,71,72,73,80)
   
   
GROUP BY
  D.CUIIO
   
HAVING
   
  ( SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) = 0 ) OR
  
  ( SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) = 0 ) OR
  
  ( SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) = 0 ) OR
  
  SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END)<> 0 AND
   SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) <> 0 AND
   SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END)<> 0 )
  
) CROSS JOIN

(
SELECT
  SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END) AS COL2,
  SUM(CASE WHEN D.RIND IN ('03','07','11') THEN D.COL2 ELSE 0 END) AS COL3,
  SUM(CASE WHEN D.RIND IN ('04','08','12') THEN D.COL2 ELSE 0 END) AS COL4,
  SUM(CASE WHEN D.RIND IN ('05','09','13') THEN D.COL2 ELSE 0 END) AS COL5
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND D.CUIIO IN
   (
   SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024
   
   
GROUP BY
  D.CUIIO
   
HAVING
   
  (SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) = 0 ) OR
  
  SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) = 0  OR
  
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) = 0  OR
  
   SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END)<> 0 AND
   SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) <> 0 AND
   SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END)<> 0

 ) )
 
UNION

SELECT
  'din care' AS DENUMIRE,
   9 AS ORDINE,
   0 AS COL1, 0 AS COL2, 0 AS COL3, 0 AS COL4, 0 AS COL5
FROM DUAL

UNION

SELECT
  'romina - rusa' AS DENUMIRE,
  10 AS ORDINE,
  COL1,
  COL2,
  COL3,
  COL4,
  COL5
  
FROM (
  SELECT COUNT(CUIIO) AS COL1 FROM (
SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND
   R.NTII NOT IN (60,71,72,73,80)
   
   
GROUP BY
  D.CUIIO
  
  HAVING
  SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) = 0
   
 )
  
) CROSS JOIN

(
SELECT
  SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 ELSE 0 END) AS COL2,
  SUM(CASE WHEN D.RIND IN ('03','07') THEN D.COL2 ELSE 0 END) AS COL3,
  SUM(CASE WHEN D.RIND IN ('04','08') THEN D.COL2 ELSE 0 END) AS COL4,
  SUM(CASE WHEN D.RIND IN ('05','09') THEN D.COL2 ELSE 0 END) AS COL5
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND D.CUIIO IN
   (
   SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024
   
   
GROUP BY
  D.CUIIO
  
HAVING
  SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) = 0
   

 ) )

UNION

SELECT
  'ucraineana - rusa' AS DENUMIRE,
  11 AS ORDINE,
  COL1,
  COL2,
  COL3,
  COL4,
  COL5
  
FROM (
  SELECT COUNT(CUIIO) AS COL1 FROM (
SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND
   R.NTII NOT IN (60,71,72,73,80)
   
   
GROUP BY
  D.CUIIO
  
  HAVING
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) = 0 AND
  SUM(CASE WHEN D.RIND IN '10' THEN COL1 ELSE 0 END) = 067
   
 )
  
) CROSS JOIN

(
SELECT
  SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 ELSE 0 END) AS COL2,
  SUM(CASE WHEN D.RIND IN ('07','11') THEN D.COL2 ELSE 0 END) AS COL3,
  SUM(CASE WHEN D.RIND IN ('08','12') THEN D.COL2 ELSE 0 END) AS COL4,
  SUM(CASE WHEN D.RIND IN ('09','13') THEN D.COL2 ELSE 0 END) AS COL5
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND D.CUIIO IN
   (
   SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024
   
   
GROUP BY
  D.CUIIO
  
HAVING
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) = 0 AND
  SUM(CASE WHEN D.RIND IN '10' THEN COL1 ELSE 0 END) = 067
   

 ) )
 
UNION


SELECT
  'bulgara - rusa' AS DENUMIRE,
  12 AS ORDINE,
  COL1,
  COL2,
  COL3,
  COL4,
  COL5
  
FROM (
  SELECT COUNT(CUIIO) AS COL1 FROM (
SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND
   R.NTII NOT IN (60,71,72,73,80)
   
   
GROUP BY
  D.CUIIO
  
  HAVING
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) = 0 AND
  SUM(CASE WHEN D.RIND IN '10' THEN COL1 ELSE 0 END) = 160
   
 )
  
) CROSS JOIN

(
SELECT
  SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 ELSE 0 END) AS COL2,
  SUM(CASE WHEN D.RIND IN ('07','11') THEN D.COL2 ELSE 0 END) AS COL3,
  SUM(CASE WHEN D.RIND IN ('08','12') THEN D.COL2 ELSE 0 END) AS COL4,
  SUM(CASE WHEN D.RIND IN ('09','13') THEN D.COL2 ELSE 0 END) AS COL5
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND D.CUIIO IN
   (
   SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024
   
   
GROUP BY
  D.CUIIO
  
HAVING
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) = 0 AND
  SUM(CASE WHEN D.RIND IN '10' THEN COL1 ELSE 0 END) = 160
   

 ) )
 
UNION


SELECT
  'engleza - rusa' AS DENUMIRE,
  13 AS ORDINE,
  COL1,
  COL2,
  COL3,
  COL4,
  COL5
  
FROM (
  SELECT COUNT(CUIIO) AS COL1 FROM (
SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND
   R.NTII NOT IN (60,71,72,73,80)
   
   
GROUP BY
  D.CUIIO
  
  HAVING
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) = 0 AND
  SUM(CASE WHEN D.RIND IN '10' THEN COL1 ELSE 0 END) = 152
   
 )
  
) CROSS JOIN

(
SELECT
  SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 ELSE 0 END) AS COL2,
  SUM(CASE WHEN D.RIND IN ('07','11') THEN D.COL2 ELSE 0 END) AS COL3,
  SUM(CASE WHEN D.RIND IN ('08','12') THEN D.COL2 ELSE 0 END) AS COL4,
  SUM(CASE WHEN D.RIND IN ('09','13') THEN D.COL2 ELSE 0 END) AS COL5
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 AND D.CUIIO IN
   (
   SELECT DISTINCT
  D.CUIIO
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024
   
   
GROUP BY
  D.CUIIO
  
HAVING
  SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END) <> 0 AND
  SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) = 0 AND
  SUM(CASE WHEN D.RIND IN '10' THEN COL1 ELSE 0 END) = 152
   

 ) )
) D


ORDER BY 
D.ORDINE