INSERT INTO TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
 COL1, COL2, COL3, COL4, COL5
)


  
SELECT DISTINCT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
   B.NR_ROW AS NR_SECTIE,
   B.NUME_ROW AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   D.NR_ROW||'~'||D.ORDINE AS NR_ROW,
   D.ORDINE,
  '00000' AS DECIMAL_POS,
   DENUMIRE AS NUME_ROW,
   SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.NTII ||'%' THEN COL1 ELSE NULL END) AS COL1,
   SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.NTII ||'%' THEN COL2 ELSE NULL END) AS COL2,
   SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.NTII ||'%' THEN COL3 ELSE NULL END ) AS COL3,
   SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.NTII ||'%' THEN COL4 ELSE NULL END) AS COL4,
   SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.NTII ||'%' THEN COL5 ELSE NULL END) AS COL5
  
FROM
(
SELECT
  
  TR.DENUMIRE AS DENUMIRE,
  TR.ORDINE,
  TR.NR_ROW,
  D.CUIIO,
  R.NTII,

  
  CASE 
    WHEN TR.ORDINE IN (1) THEN 
      SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
    WHEN TR.ORDINE IN (3) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 END))=0) OR
                 (SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END)=SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','10') THEN D.COL2 END))=0) OR
                 (SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END)=SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0) 
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (5) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (6) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (7) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=67)
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (8) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=160)
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (9) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=152)
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (10) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))>0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0)
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (12) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (13) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END)) = 067 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0)
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (14) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END)) = 160 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
       (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))= 0)       )
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
      
      

      
        WHEN TR.ORDINE IN (16) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL1) END)) = 152 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN NVAL(D.COL2) END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL2) END)) > 0 AND
       (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN NVAL(D.COL2) END)) >  0)       )
           THEN
           SUM(CASE WHEN D.RIND IN '01' AND R.NTII NOT IN (60,71,72,73,80) THEN 1 ELSE 0 END)
      END
    
  END AS COL1,
  
  
  
  
  CASE 
    WHEN TR.ORDINE IN (1) THEN 
      SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END) 
    WHEN TR.ORDINE IN (3) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 END))=0) OR
                 (SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END)=SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','10') THEN D.COL2 END))=0) OR
                 (SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END)=SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0) 
           THEN
           SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END) 
      END
    WHEN TR.ORDINE IN (5) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN '02' THEN D.COL2 ELSE 0 END) 
      END
    WHEN TR.ORDINE IN (6) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN '06' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (7) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=67)
           THEN
           SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (8) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=160)
           THEN
           SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (9) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=152)
           THEN
           SUM(CASE WHEN D.RIND IN '10' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (10) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))>0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0)
           THEN
           SUM(CASE WHEN D.RIND IN '01' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (12) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (13) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END)) = 067 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0)
           THEN
           SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (14) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END)) = 160 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
       (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))= 0)       )
           THEN
           SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 ELSE 0 END)
      END

      
      
      WHEN TR.ORDINE IN (16) THEN
      
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL1) END)) = 152 AND
      
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN NVAL(D.COL2) END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL2) END))>0 AND
       (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN NVAL(D.COL2) END)) >  0)       )
           THEN
           SUM(CASE WHEN D.RIND IN ('02','06','10') THEN D.COL2 ELSE 0 END)
           
           
      END  
      
    
  END AS COL2,
  
  
  
  
  
  CASE 
    WHEN TR.ORDINE IN (1) THEN 
      SUM(CASE WHEN D.RIND IN ('03','07','11') THEN D.COL2 ELSE 0 END)
    WHEN TR.ORDINE IN (3) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 END))=0) OR
                 (SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END)=SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','10') THEN D.COL2 END))=0) OR
                 (SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END)=SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0) 
           THEN
           SUM(CASE WHEN D.RIND IN ('03','07','11') THEN D.COL2 ELSE 0 END) 
      END
    WHEN TR.ORDINE IN (5) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN ('03') THEN D.COL2 ELSE 0 END) 
      END
    WHEN TR.ORDINE IN (6) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN '07' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (7) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=67)
           THEN
           SUM(CASE WHEN D.RIND IN '11' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (8) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=160)
           THEN
           SUM(CASE WHEN D.RIND IN '11' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (9) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=152)
           THEN
           SUM(CASE WHEN D.RIND IN '11' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (10) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))>0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0)
           THEN
           SUM(CASE WHEN D.RIND IN ('03','07','11') THEN D.COL2 ELSE 0 END) 
      END
    WHEN TR.ORDINE IN (12) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN ('03','07') THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (13) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END)) = 067 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0)
           THEN
           SUM(CASE WHEN D.RIND IN ('07','11') THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (14) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END)) = 160 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
       (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))= 0)       )
           THEN
           SUM(CASE WHEN D.RIND IN ('07','11') THEN D.COL2 ELSE 0 END)
      END
      

    
 WHEN TR.ORDINE IN (16) THEN
 
       CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL1) END)) = 152 AND
      
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN NVAL(D.COL2) END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL2) END))>0 AND
       (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN NVAL(D.COL2) END)) >  0)       )
           THEN
           SUM(CASE WHEN D.RIND IN ('03','07','11') THEN D.COL2 ELSE 0 END)
           
           
      END

    
  END AS COL3,
  
  
  
  
  
  CASE 
    WHEN TR.ORDINE IN (1) THEN 
      SUM(CASE WHEN D.RIND IN ('04','08','12') THEN D.COL2 ELSE 0 END)
    WHEN TR.ORDINE IN (3) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 END))=0) OR
                 (SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END)=SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','10') THEN D.COL2 END))=0) OR
                 (SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END)=SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0) 
           THEN
           SUM(CASE WHEN D.RIND IN ('04','08','12') THEN D.COL2 ELSE 0 END) 
      END
    WHEN TR.ORDINE IN (5) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN ('04') THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (6) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN '08' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (7) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=67)
           THEN
           SUM(CASE WHEN D.RIND IN '12' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (8) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=160)
           THEN
           SUM(CASE WHEN D.RIND IN '12' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (9) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=152)
           THEN
           SUM(CASE WHEN D.RIND IN '12' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (10) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))>0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0)
           THEN
           SUM(CASE WHEN D.RIND IN ('04','08','12') THEN D.COL2 ELSE 0 END) 
      END
    WHEN TR.ORDINE IN (12) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN ('04','08') THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (13) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END)) = 067 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0)
           THEN
           SUM(CASE WHEN D.RIND IN ('08','12') THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (14) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END)) = 160 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
       (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))= 0)       )
           THEN
           SUM(CASE WHEN D.RIND IN ('08','12') THEN D.COL2 ELSE 0 END)
      END
    
    
 
      
    
WHEN TR.ORDINE IN (16) THEN

  CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL1) END)) = 152 AND
      
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN NVAL(D.COL2) END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL2) END))>0 AND
       (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN NVAL(D.COL2) END)) >  0)       )
           THEN
           SUM(CASE WHEN D.RIND IN ('04','08','12') THEN D.COL2 ELSE 0 END)
           

      END
    
  
    
  END AS COL4,
  
  
  
  
  
  CASE 
    WHEN TR.ORDINE IN (1) THEN 
      SUM(CASE WHEN D.RIND IN ('05','09','13') THEN D.COL2 ELSE 0 END)
    WHEN TR.ORDINE IN (3) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 END))=0) OR
                 (SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END)=SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','10') THEN D.COL2 END))=0) OR
                 (SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END)=SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0) 
           THEN
           SUM(CASE WHEN D.RIND IN ('05','09','13') THEN D.COL2 ELSE 0 END) 
      END
    WHEN TR.ORDINE IN (5) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06','10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN ('05') THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (6) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN '09' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (7) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=67)
           THEN
           SUM(CASE WHEN D.RIND IN '13' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (8) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=160)
           THEN
           SUM(CASE WHEN D.RIND IN '13' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (9) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('01') THEN D.COL2 END))=CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END)) AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02','06') THEN D.COL2 END))=0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END))=152)
           THEN
           SUM(CASE WHEN D.RIND IN '13' THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (10) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))>0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))=0) OR
                 (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0)
           THEN
           SUM(CASE WHEN D.RIND IN ('05','09','13') THEN D.COL2 ELSE 0 END) 
      END
    WHEN TR.ORDINE IN (12) THEN
      CASE WHEN (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))>0 AND
                 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))=0)
           THEN
           SUM(CASE WHEN D.RIND IN ('05','09') THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (13) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END)) = 067 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0)
           THEN
           SUM(CASE WHEN D.RIND IN ('09','13') THEN D.COL2 ELSE 0 END)
      END
    WHEN TR.ORDINE IN (14) THEN
      CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 END)) = 160 AND
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 END))>0 AND
       (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 END))= 0)       )
           THEN
           SUM(CASE WHEN D.RIND IN ('09','13') AND R.NTII NOT IN (60,71,72,73,80) THEN D.COL2 ELSE 0 END)
      END
      
      

      
          WHEN TR.ORDINE IN (16) THEN
          
          
          
       CASE WHEN CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL1) END)) = 152 AND
      
      (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN NVAL(D.COL2) END))> 0 AND CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL2) END))>0 AND
       (CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN NVAL(D.COL2) END)) >  0)       )
           THEN
           SUM(CASE WHEN D.RIND IN ('05','09','13') THEN D.COL2 ELSE 0 END)
           

      END
      
  END AS COL5
  
  
  
  
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  

  CROSS JOIN 
  (
SELECT 'Total'                                             AS DENUMIRE, '1'  AS NR_ROW, 1 AS ORDINE FROM DUAL UNION
SELECT 'din care:'                                         AS DENUMIRE, '-'  AS NR_ROW, 2 AS ORDINE FROM DUAL UNION
SELECT 'predarea numai intr-o singura limba - total'       AS DENUMIRE, '2'  AS NR_ROW, 3 AS ORDINE FROM DUAL UNION
SELECT 'din care:'                                         AS DENUMIRE, '-'  AS NR_ROW, 4 AS ORDINE FROM DUAL UNION
SELECT 'romana'                                            AS DENUMIRE, '3'  AS NR_ROW, 5 AS ORDINE FROM DUAL UNION
SELECT 'rusa'                                              AS DENUMIRE, '4'  AS NR_ROW, 6 AS ORDINE FROM DUAL UNION
SELECT 'ucraineana'                                        AS DENUMIRE, '5'  AS NR_ROW, 7 AS ORDINE FROM DUAL UNION
SELECT 'bulgara'                                           AS DENUMIRE, '6'  AS NR_ROW, 8 AS ORDINE FROM DUAL UNION
SELECT 'engleza'                                           AS DENUMIRE, '7'  AS NR_ROW, 9 AS ORDINE FROM DUAL UNION
SELECT 'predarea in mai multe limbi (scoli mixte) - total' AS DENUMIRE, '8'  AS NR_ROW, 10 AS ORDINE FROM DUAL UNION
SELECT 'din care:'                                         AS DENUMIRE, '-'  AS NR_ROW, 11 AS ORDINE FROM DUAL UNION
SELECT 'romana-rusa'                                       AS DENUMIRE, '9'  AS NR_ROW, 12 AS ORDINE FROM DUAL UNION
SELECT 'ucraineana-rusa'                                   AS DENUMIRE, '10' AS NR_ROW, 13 AS ORDINE FROM DUAL UNION 
SELECT 'bulgara-rusa'                                      AS DENUMIRE, '11' AS NR_ROW, 14 AS ORDINE FROM DUAL UNION
SELECT 'romana-engleza-rusa'                                      AS DENUMIRE, '12' AS NR_ROW, 16 AS ORDINE FROM DUAL

  ) TR
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN 1024 
  
  
  
 
GROUP BY
 R.NTII,
 D.CUIIO,
 TR.DENUMIRE,
  TR.NR_ROW,
  TR.ORDINE
  ORDER BY

  TR.ORDINE
) D

CROSS JOIN
(
SELECT '10' AS NR_ROW,'Scolile primare' AS NUME_ROW, 2 AS LENGTH_ROW, 1 AS ORDINE FROM DUAL UNION
SELECT '20+21' AS NR_ROW, 'Gimnazii' AS NUME_ROW, 2 AS LENGTH_ROW, 2 AS ORDINE FROM DUAL UNION 
SELECT '30+31' AS NR_ROW, 'Licee' AS NUME_ROW, 2 AS LENGTH_ROW, 3 AS ORDINE FROM DUAL UNION
SELECT '40' AS NR_ROW, 'Scolile pentru copii cu deficiente in dezvoltarea intelectuala sau fizica' AS NUME_ROW, 2 AS LENGTH_ROW, 4 AS ORDINE FROM DUAL UNION
SELECT '50+60' AS NR_ROW, 'Scolile serale' AS NUME_ROW, 2 AS LENGTH_ROW, 5 AS ORDINE FROM DUAL UNION
SELECT '71+72+73' AS NR_ROW, 'Clase pe linga colegii' AS NUME_ROW, 2 AS LENGTH_ROW, 6 AS ORDINE FROM DUAL


) B

GROUP BY
  B.NR_ROW,
   B.NUME_ROW,
   D.NR_ROW,

   D.ORDINE,
   DENUMIRE,
   B.ORDINE
  
  
  
  
ORDER BY
  ORDINE
