INSERT INTO TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
 COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14
)
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
   FULL_CODE AS NR_SECTIE,
   NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   NR_ROW,
   ROWNUM AS ORDINE,
  '00000000000000' AS DECIMAL_POS,
   NUME_ROW,
  CASE WHEN COL1 = 0 THEN NULL ELSE COL1 END AS COL1,
  CASE WHEN COL2 = 0 THEN NULL ELSE COL2 END AS COL2,
  CASE WHEN COL3 = 0 THEN NULL ELSE COL3 END AS COL3,
  CASE WHEN COL4 = 0 THEN NULL ELSE COL4 END AS COL4,
  CASE WHEN COL5 = 0 THEN NULL ELSE COL5 END AS COL5,
  CASE WHEN COL6 = 0 THEN NULL ELSE COL6 END AS COL6,
  CASE WHEN COL7 = 0 THEN NULL ELSE COL7 END AS COL7,
  CASE WHEN COL8 = 0 THEN NULL ELSE COL8 END AS COL8,
  CASE WHEN COL9 = 0 THEN NULL ELSE COL9 END AS COL9,         
  CASE WHEN COL10 = 0 THEN NULL ELSE COL10 END AS COL10,
  CASE WHEN COL11 = 0 THEN NULL ELSE COL11 END AS COL11,
  CASE WHEN COL12 = 0 THEN NULL ELSE COL12 END AS COL12, 
  CASE WHEN COL13 = 0 THEN NULL ELSE COL13 END AS COL13,
  CASE WHEN COL14 = 0 THEN NULL ELSE COL14 END AS COL14   
   
   
   
   
FROM (

SELECT
  C.FULL_CODE,
  C.DENUMIRE AS NUME_SECTIE,
  C.CODUL AS NR_SECTIE,
  A.NUME_ROW,
  A.NR_ROW,
  A.ORDINE,
  SUM(A.COL1) AS COL1, SUM(A.COL2) AS COL2, SUM(A.COL3) AS COL3, SUM(A.COL4) AS COL4, SUM(A.COL5) AS COL5, SUM(A.COL6) AS COL6, SUM(A.COL7) AS COL7, SUM(A.COL8) AS COL8, SUM(A.COL9) AS COL9, SUM(A.COL10) AS COL10, SUM(A.COL11) AS COL11, SUM(A.COL12) AS COL12, SUM(A.COL13)AS COL13, SUM(A.COL14) AS COL14

FROM
(
SELECT DISTINCT
  R.DENUMIRE AS NUME_ROW,
  R.CAPITOL,
  R.CAPITOL_VERS,
  R.RIND AS NR_ROW,
  R.ORDINE AS ORDINE,
  R.FORM,
  R.FORM_VERS,
  D.CUIIO,
  D.CUATM,
  D.PERIOADA, A.COL1, A.COL2, A.COL3, A.COL4, A.COL5, A.COL6, A.COL7, A.COL8, A.COL9, A.COL10, A.COL11, A.COL12, A.COL13, A.COL14
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.MD_RIND R ON D.CAPITOL = R.CAPITOL AND D.CAPITOL_VERS = R.CAPITOL_VERS AND D.FORM = R.FORM AND D.FORM_VERS = R.FORM_VERS
  LEFT JOIN (
  
  SELECT
  RIND,
  RIND_VERS,
  CAPITOL,
  CAPITOL_VERS,
  CUIIO,
  CUIIO_VERS,
  CUATM,
  FORM,
  FORM_VERS,
  PERIOADA,
  COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14
FROM CIS2.VW_DATA_ALL D

WHERE
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND
   D.CAPITOL = 1023 ) A 
   ON D.CUIIO = A.CUIIO AND D.CUIIO_VERS = A.CUIIO_VERS AND D.PERIOADA = A.PERIOADA AND R.CAPITOL = A.CAPITOL AND R.CAPITOL_VERS = A.CAPITOL_VERS AND R.RIND = A.RIND AND R.RIND_VERS = A.RIND_VERS
   AND A.FORM = D.FORM AND A.FORM_VERS = D.FORM_VERS AND A.RIND_VERS = D.RIND_VERS
  
  
WHERE
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  R.FORM = 40 AND
  R.CAPITOL = 1023
  
  
ORDER BY ORDINE
) A
    INNER JOIN CIS2.VW_CL_CUATM B ON (A.CUATM=B.CODUL)
    INNER JOIN CIS2.VW_CL_CUATM C ON (B.FULL_CODE LIKE '%'||C.CODUL||';%')

WHERE
  C.PRGS IN 2
    

GROUP BY C.FULL_CODE,
  C.DENUMIRE,
  C.CODUL,
  A.NUME_ROW,
  A.NR_ROW,
  A.ORDINE
--ORDER BY C.FULL_CODE, A.ORDINE


UNION


SELECT
 '0000000;9810000;' AS FULL_CODE,
  C.DENUMIRE AS NUME_SECTIE,
  C.CODUL AS NR_SECTIE,
  A.NUME_ROW,
  A.NR_ROW,
  A.ORDINE,
  SUM(A.COL1) AS COL1, SUM(A.COL2) AS COL2, SUM(A.COL3) AS COL3, SUM(A.COL4) AS COL4, SUM(A.COL5) AS COL5, SUM(A.COL6) AS COL6, SUM(A.COL7) AS COL7, SUM(A.COL8) AS COL8, SUM(A.COL9) AS COL9, SUM(A.COL10) AS COL10, SUM(A.COL11) AS COL11, SUM(A.COL12) AS COL12, SUM(A.COL13)AS COL13, SUM(A.COL14) AS COL14

FROM
(
SELECT DISTINCT
  R.DENUMIRE AS NUME_ROW,
  R.CAPITOL,
  R.CAPITOL_VERS,
  R.RIND AS NR_ROW,
  R.ORDINE AS ORDINE,
  R.FORM,
  R.FORM_VERS,
  D.CUIIO,
  D.CUATM,
  D.PERIOADA, A.COL1, A.COL2, A.COL3, A.COL4, A.COL5, A.COL6, A.COL7, A.COL8, A.COL9, A.COL10, A.COL11, A.COL12, A.COL13, A.COL14
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.MD_RIND R ON D.CAPITOL = R.CAPITOL AND D.CAPITOL_VERS = R.CAPITOL_VERS AND D.FORM = R.FORM AND D.FORM_VERS = R.FORM_VERS
  LEFT JOIN (
  
  SELECT
  RIND,
  RIND_VERS,
  CAPITOL,
  CAPITOL_VERS,
  CUIIO,
  CUIIO_VERS,
  CUATM,
  FORM,
  FORM_VERS,
  PERIOADA,
  COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14
FROM CIS2.VW_DATA_ALL D

WHERE
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND
   D.CAPITOL = 1023 ) A 
   ON D.CUIIO = A.CUIIO AND D.CUIIO_VERS = A.CUIIO_VERS AND D.PERIOADA = A.PERIOADA AND R.CAPITOL = A.CAPITOL AND R.CAPITOL_VERS = A.CAPITOL_VERS AND R.RIND = A.RIND AND R.RIND_VERS = A.RIND_VERS
   AND A.FORM = D.FORM AND A.FORM_VERS = D.FORM_VERS AND A.RIND_VERS = D.RIND_VERS
  
  
WHERE
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  R.FORM = 40 AND
  R.CAPITOL = 1023
  
  
ORDER BY ORDINE
) A
    INNER JOIN CIS2.VW_CL_CUATM B ON (A.CUATM=B.CODUL)
    INNER JOIN CIS2.VW_CL_CUATM C ON (B.FULL_CODE LIKE '%'||C.CODUL||';%')

WHERE
  C.CODUL IN 0501000
    

GROUP BY
  C.DENUMIRE,
  C.CODUL,
  A.NUME_ROW,
  A.NR_ROW,
  A.ORDINE
ORDER BY ORDINE

)