SELECT
  TR.ANEXA_D ||', Rind.'||  TR.RIND_DD||' (anul curent) = Rind.'||  TR.RIND_D ||' (anul precedent) : '||
SUM(DISTINCT CASE WHEN A.CAPITOL_CURENT IN (TR.CAPITOL_DD) AND A.PERIOADA_CURENT=:PERIOADA   AND TR.RIND_DD LIKE '%'|| A.RIND_CURENT ||'%' THEN NVAL(A.COL1_CURENT) ELSE 0 END) ||'<> '||
SUM(DISTINCT CASE WHEN A.CAPITOL_PREC   IN (TR.CAPITOL_D)  AND A.PERIOADA_PREC = :PERIOADA-1 AND TR.RIND_D   LIKE '%'|| A.RIND_PREC ||'%'  THEN NVAL(A.COL2_PREC)  ELSE 0 END)
  AS REZULTAT
FROM
(
SELECT
  D.CUIIO,
  DD.PERIOADA AS PERIOADA_CURENT,
  DD.CAPITOL AS CAPITOL_CURENT,
  DD.RIND AS RIND_CURENT,
  DD.COL1 AS COL1_CURENT,
  D.PERIOADA AS PERIOADA_PREC,
  D.CAPITOL AS CAPITOL_PREC,
  D.RIND AS RIND_PREC,
  D.COL2 AS COL2_PREC
FROM

    -- USER_EREPORTING.VW_DATA_ALL_FOR_VALIDATE_FR DD 
     USER_BANCU.FOR_VALIDATE_FR DD
     INNER JOIN CIS2.VW_DATA_ALL_FR D ON DD.CUIIO=D.CUIIO AND DD.FORM = D.FORM --AND DD.CAPITOL =D.CAPITOL 
WHERE
  (DD.PERIOADA IN(:PERIOADA)) AND (D.PERIOADA IN(:PERIOADA-1))AND
  (DD.CUIIO           = :CUIIO          OR :CUIIO= -1)        AND 
  (:CUIIO_VERS        = :CUIIO_VERS     OR :CUIIO_VERS = -1)  AND 
  (DD.FORM            = :FORM           OR :FORM = -1)        AND 
  (DD.FORM_VERS       = :FORM_VERS      OR :FORM_VERS = -1)   AND 
  (DD.CAPITOL         = :CAPITOL        OR :CAPITOL = -1  )   AND 
  (DD.CAPITOL_VERS    = :CAPITOL_VERS   OR :CAPITOL_VERS = -1) 
  AND DD.FORM = 57 AND D.FORM=57 
  AND DD.CAPITOL IN (1090, 1092)  AND D.CAPITOL  IN (1090,1092) 
  AND DD.ID_SCHEMA IN (2) 
) A CROSS JOIN
 (
SELECT '060' AS RIND_DD, '020' AS RIND_D, 1 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION
SELECT '070' AS RIND_DD, '030' AS RIND_D, 2 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION
SELECT '080' AS RIND_DD, '040' AS RIND_D, 3 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION
SELECT '090' AS RIND_DD, '050' AS RIND_D, 4 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION
SELECT '100' AS RIND_DD, '060' AS RIND_D, 5 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION
SELECT '110' AS RIND_DD, '090' AS RIND_D, 6 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION 
SELECT '140' AS RIND_DD, '070' AS RIND_D, 7 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION 
SELECT '150' AS RIND_DD, '080' AS RIND_D, 8 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION
--SELECT '230' AS RIND_DD, '130' AS RIND_D, 9 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION
SELECT '250' AS RIND_DD, '150' AS RIND_D, 10 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION 
SELECT '300' AS RIND_DD, '190' AS RIND_D, 11 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION 
SELECT '310' AS RIND_DD, '200' AS RIND_D, 12 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION
SELECT '320' AS RIND_DD, '220' AS RIND_D, 13 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION
SELECT '330' AS RIND_DD, '230' AS RIND_D, 14 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION 
--SELECT '340' AS RIND_DD, '240' AS RIND_D, 15 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION 
SELECT '380' AS RIND_DD, '270' AS RIND_D, 16 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION
SELECT '390' AS RIND_DD, '280' AS RIND_D, 17 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION
SELECT '540' AS RIND_DD, '330' AS RIND_D, 18 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION 
SELECT '620' AS RIND_DD, '390' AS RIND_D, 19 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION 
SELECT '630' AS RIND_DD, '400' AS RIND_D, 20 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION
SELECT '640' AS RIND_DD, '410' AS RIND_D, 21 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION
SELECT '710' AS RIND_DD, '450' AS RIND_D, 22 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION 
SELECT '720' AS RIND_DD, '460' AS RIND_D, 23 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION 
SELECT '730' AS RIND_DD, '470' AS RIND_D, 24 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION
SELECT '740' AS RIND_DD, '480' AS RIND_D, 25 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION
SELECT '750' AS RIND_DD, '490' AS RIND_D, 26 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION 
SELECT '760' AS RIND_DD, '500' AS RIND_D, 27 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION 
SELECT '770' AS RIND_DD, '510' AS RIND_D, 28 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION
SELECT '780' AS RIND_DD, '520' AS RIND_D, 29 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION
SELECT '790' AS RIND_DD, '540' AS RIND_D, 30 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION 
SELECT '800' AS RIND_DD, '530' AS RIND_D, 31 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION 
SELECT '880' AS RIND_DD, '590' AS RIND_D, 32 AS ORDINE, 1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION

SELECT '010+020' AS RIND_DD, '010' AS RIND_D, 33 AS ORDINE,1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD,  1090 AS CAPITOL_DD FROM DUAL UNION 
--SELECT '220' AS RIND_DD, '100+120' AS RIND_D, 34 AS ORDINE,1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD,  1090 AS CAPITOL_DD FROM DUAL UNION 
SELECT '240' AS RIND_DD, '140+160' AS RIND_D, 35 AS ORDINE,1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD,  1090 AS CAPITOL_DD FROM DUAL UNION
SELECT '260+270' AS RIND_DD, '170+180' AS RIND_D, 36 AS ORDINE,1090 AS CAPITOL_D, 'Anexa1' AS ANEXA_D,'Anexa1' AS  ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION 
--SELECT '350+360' AS RIND_DD, '290' AS RIND_D, 37 AS ORDINE,1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION 
SELECT '410' AS RIND_DD, '250+260' AS RIND_D, 38 AS ORDINE,1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION
SELECT '600+610' AS RIND_DD, '380' AS RIND_D, 39 AS ORDINE,1090 AS CAPITOL_D,'Anexa1' AS ANEXA_D,'Anexa1' AS ANEXA_DD, 1090 AS CAPITOL_DD FROM DUAL UNION 

SELECT '010' AS RIND_DD, '010' AS RIND_D, 40 AS ORDINE,1092 AS CAPITOL_D,'Anexa2' AS ANEXA_D,'Anexa2' AS ANEXA_DD,  1092 AS CAPITOL_DD FROM DUAL UNION 
SELECT '020' AS RIND_DD, '020' AS RIND_D, 41 AS ORDINE,1092 AS CAPITOL_D,'Anexa2' AS ANEXA_D,'Anexa2' AS ANEXA_DD,  1092 AS CAPITOL_DD FROM DUAL UNION
SELECT '030' AS RIND_DD, '030' AS RIND_D, 42 AS ORDINE,1092 AS CAPITOL_D,'Anexa2' AS ANEXA_D,'Anexa2' AS ANEXA_DD,  1092 AS CAPITOL_DD FROM DUAL UNION 
SELECT '040' AS RIND_DD, '040' AS RIND_D, 43 AS ORDINE,1092 AS CAPITOL_D,'Anexa2' AS ANEXA_D,'Anexa2' AS ANEXA_DD,  1092 AS CAPITOL_DD FROM DUAL UNION
SELECT '050' AS RIND_DD, '050' AS RIND_D, 44 AS ORDINE,1092 AS CAPITOL_D,'Anexa2' AS ANEXA_D,'Anexa2' AS ANEXA_DD,  1092 AS CAPITOL_DD FROM DUAL UNION 
SELECT '060' AS RIND_DD, '060' AS RIND_D, 45 AS ORDINE,1092 AS CAPITOL_D,'Anexa2' AS ANEXA_D,'Anexa2' AS ANEXA_DD,  1092 AS CAPITOL_DD FROM DUAL UNION
SELECT '070' AS RIND_DD, '070' AS RIND_D, 46 AS ORDINE,1092 AS CAPITOL_D,'Anexa2' AS ANEXA_D,'Anexa2' AS ANEXA_DD,  1092 AS CAPITOL_DD FROM DUAL UNION 
SELECT '180' AS RIND_DD, '120' AS RIND_D, 47 AS ORDINE,1092 AS CAPITOL_D,'Anexa2' AS ANEXA_D,'Anexa2' AS ANEXA_DD,  1092 AS CAPITOL_DD FROM DUAL 

) TR
GROUP BY
  TR.RIND_DD,
  TR.RIND_D,TR.ANEXA_D
  
  HAVING
SUM(DISTINCT CASE WHEN A.CAPITOL_CURENT IN (TR.CAPITOL_DD) AND A.PERIOADA_CURENT= :PERIOADA   AND TR.RIND_DD  LIKE '%'|| A.RIND_CURENT ||'%'  THEN NVAL(A.COL1_CURENT) ELSE 0 END) <> 
SUM(DISTINCT CASE WHEN A.CAPITOL_PREC  IN (TR.CAPITOL_D)   AND A.PERIOADA_PREC = :PERIOADA-1 AND TR.RIND_D LIKE '%'|| A.RIND_PREC ||'%' THEN NVAL(A.COL2_PREC)  ELSE 0 END)