SELECT DISTINCT
'Rind.'||DD.RIND||':   '||

MAX(CASE WHEN DD.CAPITOL IN (1092) AND DD.PERIOADA= :PERIOADA    THEN NVAL(DD.COL1) ELSE 0 END) ||'<> '||
MAX(CASE WHEN D.CAPITOL  IN (1092) AND D.PERIOADA = :PERIOADA-1  THEN NVAL(D.COL2)  ELSE 0 END)
AS REZULTAT 
FROM

     USER_EREPORTING.VW_DATA_ALL_FOR_VALIDATE_FR DD 
     INNER JOIN CIS2.VW_DATA_ALL_FR D ON DD.CUIIO=DD.CUIIO 
WHERE
  (DD.PERIOADA IN(:PERIOADA))AND  (D.PERIOADA IN(:PERIOADA-1))AND
  (DD.CUIIO           = :CUIIO          OR :CUIIO= -1)        AND 
  (:CUIIO_VERS        = :CUIIO_VERS     OR :CUIIO_VERS = -1)  AND 
  (DD.FORM            = :FORM           OR :FORM = -1)        AND 
  (DD.FORM_VERS       = :FORM_VERS      OR :FORM_VERS = -1)   AND 
  (DD.CAPITOL         = :CAPITOL        OR :CAPITOL = -1  )   AND 
  (DD.CAPITOL_VERS    = :CAPITOL_VERS   OR :CAPITOL_VERS = -1) 
  AND DD.FORM = 57 AND D.FORM=57 
  AND DD.CAPITOL = 1092  AND D.CAPITOL IN 1092            
  AND DD.ID_SCHEMA IN (2) 
  AND DD.RIND NOT IN ('340','360','350','370')
  AND D.RIND  NOT IN ('340','360','350','370')
  ----
   AND DD.NUM IN (1)  
  GROUP BY DD.RIND
  
HAVING
 
MAX(CASE WHEN DD.CAPITOL IN (1092)  AND DD.PERIOADA= :PERIOADA     THEN NVAL(DD.COL1) ELSE 0 END) <> 
MAX(CASE WHEN D.CAPITOL  IN (1092)  AND D.PERIOADA = :PERIOADA-1   THEN NVAL(D.COL2)  ELSE 0 END)
 
   AND
  (
 SELECT
  DISTINCT
  D.CUIIO
FROM
  CIS2.VW_DATA_ALL_FR D
WHERE
  (D.PERIOADA IN (:PERIOADA-1)) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  D.FORM  IN(57) AND     
  D.CAPITOL IN(1092)) IS NOT NULL