--INSERT INTO DATA_ALL_FOR_VALIDATE_FR (
--
--PERIOADA,
--  FORM,        
--  FORM_VERS,
--  CUIIO, 
--  CUIIO_VERS,      
--  PACHET,  
--  ID_MD,          
--  DATA_REG,       
--  ID_USER,       
--  COL1,
--  COL3,          
--  COL2,       
--  COL4,         
--  COL5,         
--  COL6,            
--  COL7,            
--  COL8,            
--  COL9,            
--  COL10,           
--  COL11,           
--  COL12,           
--  COL13,           
--  COL14,           
--  COL15,           
--  COL16,           
--  COL17,           
--  COL18,           
--  COL19,           
--  COL20,           
--  COL21,           
--  COL22,           
--  COL23,           
--  COL24,           
--  COL25,           
--  COL26,           
--  COL27,           
--  COL28,           
--  COL29,           
--  COL30,           
--  T_XML_FORM_ID,
--  CREATED_DATE,
--  ID_SCHEMA    
--  
--)

SELECT 
  PERIOADA,
  FORM,        
  FORM_VERS,
  CUIIO, 
  CUIIO_VERS,      
  PACHET,  
  ID_MD,          
  DATA_REG,       
  ID_USER,       
  COL1,
  COL3,          
  COL2,       
  COL4,         
  COL5,         
  COL6,            
  COL7,            
  COL8,            
  COL9,            
  COL10,           
  COL11,           
  COL12,           
  COL13,           
  COL14,           
  COL15,           
  COL16,           
  COL17,           
  COL18,           
  COL19,           
  COL20,           
  COL21,           
  COL22,           
  COL23,           
  COL24,           
  COL25,           
  COL26,           
  COL27,           
  COL28,           
  COL29,           
  COL30,           
  T_XML_FORM_ID,
  CREATED_DATE,
  ID_SCHEMA    
  
  FROM  DATA_ALL_FOR_VALIDATE_FR
  
  
  WHERE 
  
  FORM = 63 
  AND PERIOADA = 2010
