SELECT DISTINCT 
  'Rind.'||D.RIND||' '||DECODE(CC.NR_COLUMN, '1', 'COL1 ', '2', 'COL2 ')||': '||
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA) AND D.NUM IN (2,3,4) THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2) ELSE 0 END))||'<'||
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA-1) AND D.NUM IN (1,2,3) THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2) ELSE 0 END))
  
  AS REZULTAT

FROM
  VW_DATA_ALL D
  INNER JOIN MD_PERIOADA P ON (D.PERIOADA=P.PERIOADA),             
       (                                                                        
       SELECT '1' AS NR_COLUMN FROM DUAL UNION                                  
       SELECT '2' AS NR_COLUMN FROM DUAL                                 
       ) CC  

WHERE
  (D.PERIOADA IN (:PERIOADA,:PERIOADA-1)) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <> :CAPITOL) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (26)  AND
  D.CAPITOL IN (367,368) --AND
--  P.NUM IN (2,3,4)
  
 GROUP BY CC.NR_COLUMN,D.RIND
 
HAVING
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA) AND D.NUM IN (2,3,4) THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2) ELSE 0 END))<
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA-1) AND D.NUM IN (1,2,3) THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2) ELSE 0 END))