SELECT 
  
D.CUIIO,
D.CUATM,
D.RIND,
SUM(D.COL1) AS COL1,
SUM(D.COL2) AS COL2,
SUM(D.COL3) AS COL3
FROM 
  VW_DATA_ALL D

WHERE
  D.FORM IN (26)                 AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  D.CAPITOL IN (367)            AND 
  D.PERIOADA=:pPERIOADA AND 
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'
  AND D.RIND IN ('11')
  
   
GROUP BY 
D.CUIIO,
D.CUATM,
D.RIND
