SELECT 

D.CUIIO,
D.CUIIO_VERS,
D.CAPITOL,
D.CAPITOL_VERS,
D.FILIAL,
D.RIND,
D.ID_MD,
D.RIND_VERS,
SUM(D.COL1) AS COL1,
SUM(D.COL2) AS COL2,
SUM(D.COL3) AS COL3,
SUM(D.COL4) AS COL4,
SUM(D.COL5) AS COL5,
SUM(D.COL6) AS COL6,
SUM(D.COL7) AS COL7,
SUM(D.COL8) AS COL8,
SUM(D.COL9) AS COL9,
SUM(D.COL10) AS COL10


FROM USER_EREPORTING.VW_DATA_ALL_PRIMIT D

WHERE 
--Acst CUIIO la noi a ajuns in CAP 2 cu date incepand cu filiala 43 dar in pdf sunt mai multe filiale
FORM = 3 
AND PERIOADA = 2009

AND CUIIO = 40462503
 AND CAPITOL = 303
 
 
 GROUP BY 
 
 D.CUIIO,
D.CUIIO_VERS,
D.CAPITOL,
D.CAPITOL_VERS,
D.FILIAL,
D.RIND,
D.ID_MD,
D.RIND_VERS

ORDER BY 
D.FILIAL