        
       SELECT  
       
       'Nu este satisfacuta conditia. '     AS REZULTAT
       






FROM
  CIS2.VW_DATA_ALL D  


WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL<>:CAPITOL) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (44)  AND
  D.CAPITOL IN (405,407) 
  
  HAVING 
  (
  SUM(CASE WHEN D.CAPITOL IN (405) AND TRIM(D.COL31) IN  ('49.41.1') THEN  1 ELSE 0  END) + 
  SUM(CASE WHEN D.CAPITOL IN (405) AND TRIM(D.COL31) IN  ('49.42.1') THEN  1 ELSE 0  END)
)

 > 0
  
  AND 
  
  ( 
  SUM(CASE WHEN D.CAPITOL IN (407) AND TRIM(D.COL31) IN  ('55.1') THEN  1 ELSE 0  END) +
  SUM(CASE WHEN D.CAPITOL IN (407) AND TRIM(D.COL31) IN  ('55.2') THEN  1 ELSE 0  END) +
  SUM(CASE WHEN D.CAPITOL IN (407) AND TRIM(D.COL31) IN  ('55.3') THEN  1 ELSE 0  END) +
  SUM(CASE WHEN D.CAPITOL IN (407) AND TRIM(D.COL31) IN  ('55.9') THEN  1 ELSE 0  END) +
  SUM(CASE WHEN D.CAPITOL IN (407) AND TRIM(D.COL31) IN  ('52.21.24') THEN  1 ELSE 0  END) + 
  SUM(CASE WHEN D.CAPITOL IN (407) AND TRIM(D.COL31) IN  ('52.21.21') THEN  1 ELSE 0  END) +  
  SUM(CASE WHEN D.CAPITOL IN (407) AND TRIM(D.COL31) IN  ('52.21.22') THEN  1 ELSE 0  END) + 
  SUM(CASE WHEN D.CAPITOL IN (407) AND TRIM(D.COL31) IN  ('52.21.23') THEN  1 ELSE 0  END) +
  SUM(CASE WHEN D.CAPITOL IN (407) AND TRIM(D.COL31) IN  ('52.21.24') THEN  1 ELSE 0  END) +
  SUM(CASE WHEN D.CAPITOL IN (407) AND TRIM(D.COL31) IN  ('52.21.25') THEN  1 ELSE 0  END) +
  SUM(CASE WHEN D.CAPITOL IN (407) AND TRIM(D.COL31) IN  ('52.21.29') THEN  1 ELSE 0  END) +
  SUM(CASE WHEN D.CAPITOL IN (407) AND TRIM(D.COL31) IN  ('52.29') THEN  1 ELSE 0  END) +
  SUM(CASE WHEN D.CAPITOL IN (407) AND TRIM(D.COL31) IN  ('61.20.11') THEN  1 ELSE 0  END)       
  
  
   = 0 
   
   )


    
