DROP TABLE USER_BANCU.CLASSIFICATOR_ CASCADE CONSTRAINTS;

CREATE TABLE USER_BANCU.CLASSIFICATOR_CSPM
(
  ORDINE      VARCHAR2(1024 BYTE), 
  CODUL       VARCHAR2(1024 BYTE),
  FULL_NAME   VARCHAR2(1024 BYTE),
  SHORT_NAME  VARCHAR2(1024 BYTE)
)
TABLESPACE TBS_DTI_USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;