SELECT 
R.ISO1_alpha_2,
L.CODUL L_CODUL,
R.CODUL R_CODUL,
L.DENUMIRE L_DENUMIRE,
R.DENUMIRE R_DENUMIRE,
L.GRUPA,
L.ORDINE
FROM

(
SELECT 
TRIM(CODUL)    CODUL,
TRIM(DENUMIRE) DENUMIRE,
TRIM(GRUPA)    GRUPA,
ORDINE   ORDINE
    FROM CIS2.CL_TARI

WHERE 
GRUPA NOT IN ('000')    
    
    ORDER BY 
    ORDINE ) L LEFT JOIN (
    
    
    SELECT 
RINDOUT ISO1_alpha_2,
TRIM(RIND) CODUL,
TRIM(DENUMIRE) DENUMIRE,
ORDINE
 
FROM CIS2.MD_RIND_OUT
WHERE 
ID_MDTABLE = 12100
 
    )  R ON R.DENUMIRE = L.DENUMIRE