SELECT DISTINCT D.UNIT_CODE FROM CIS2.VW_DATA_ALL_GC D WHERE D.FORM_VERS = :pFORM_VERS  AND D.FORM = :pFORM   AND D.PERIOADA = 1045 AND 
    D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND D.FORM IN (62) AND D.CAPITOL IN (1118) AND D.RIND IN ('TIP2') GROUP BY D.UNIT_CODE  HAVING
    CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1118) AND D.RIND IN ('TIP2') THEN  1 ELSE NULL END))>0
    