SELECT
 --  DD.CUIIO,
   RR.NR_ROW,
   RR.NUME_ROW,
   CASE WHEN  CC.CODUL like '%0000' THEN CC.DENUMIRE END AS DENUMIRE,   
 --  CASE WHEN  Substr(CC.CODUL,1,1)||'0000' IS NOT NULL THEN Substr(CC.CODUL,1,1)||'0000' END AS CODUL, 
   CC.CODUL,
   CC.FULL_CODE AS ORDINE,

ROUND(SUM(DD.CD),1)  AS CD,
ROUND(SUM(DD.COL0),1)  AS COL0,

 ROUND(SUM ( CASE WHEN  CC.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN ROUND (DECODE(RR.NR_ROW, 
         '01', (ROUND(NVAL(DD.COL0),1)),
         '02', '100',
         '03',(DD.COL1),
         '04', '100',
         '05',(DD.COL2),
         '06', '100' ,
         '07',(DD.COL3),
         '08','100' ,
         '09',(DD.COL4),
         '10', '100' ),1) END),1)AS COL1,
         
         
          ROUND(SUM ( CASE WHEN  1=1  THEN ROUND (DECODE(RR.NR_ROW, 
         '01', (DD.CD),
         '02', '100',
         '03',(DD.COL1),
         '04', '100',
         '05',(DD.COL2),
         '06', '100' ,
         '07',(DD.COL3),
         '08','100' ,
         '09',(DD.COL4),
         '10', '100' ),1) END),1)AS COL1_MOD,
         
         
          ROUND(SUM  (DECODE(RR.NR_ROW, 
         '01', (DD.CD),
         '02', '100',
         '03',(DD.COL1),
         '04', '100',
         '05',(DD.COL2),
         '06', '100' ,
         '07',(DD.COL3),
         '08','100' ,
         '09',(DD.COL4),
         '10', '100' )),1) AS COL1_MOD_ver1
         
         
         
         
         
FROM 
(



SELECT 
 DISTINCT D.CUIIO, 
 MAX(CASE WHEN D.RIND IN ('8') AND D.CAPITOL IN (1129) THEN D.COL31 END)  AS CAEM2_ACTUALIZAT,
 MAX(SUBSTR(D.CAEM2,2,4))  AS CAEM2,
 D.CUIIO_VERS, 
 D.CUATM, 
 D.FORM,
 D.FORM_VERS,
 D.CUATM_FULL,
 D.PERIOADA,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (100)  AND D.RIND IN ('CD') AND D.COL1 IS NOT NULL THEN  D.COL1 ELSE 0 END))  AS COL0,
 
 -
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN  CIS2.NVAL(D.COL4) END))  AS COL1,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('150') THEN  CIS2.NVAL(D.COL1) END))  AS COL2,
  
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('150','160','170') THEN  CIS2.NVAL(D.COL1) END))- 
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('200') THEN CIS2.NVAL(D.COL1) END))+
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN CIS2.NVAL(D.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN CIS2.NVAL(D.COL1) END)))+
 
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN CIS2.NVAL(D.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN CIS2.NVAL(D.COL1) END)))  AS COL3,
  
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('150','160','170') THEN  CIS2.NVAL(D.COL1) END))- 
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('200') THEN CIS2.NVAL(D.COL1) END))+
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN CIS2.NVAL(D.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN CIS2.NVAL(D.COL1) END)))+
 
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN CIS2.NVAL(D.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN CIS2.NVAL(D.COL1) END)))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('220') THEN CIS2.NVAL(D.COL1) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('240') THEN CIS2.NVAL(D.COL1) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('290') THEN CIS2.NVAL(D.COL1) END))+
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('294') THEN CIS2.NVAL(D.COL1) END))+
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('180') THEN CIS2.NVAL(D.COL1) END))   AS COL4,
 
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (100)  AND D.RIND IN ('CD') THEN  D.COL1 ELSE 0 END))  AS CD,
 
 (SELECT  CASE WHEN DD.COL4 IS NOT NULL THEN DD.COL4 ELSE 0 END 
 FROM
   CIS2.DATA_ALL DD
 WHERE
   DD.PERIOADA IN (D.PERIOADA) AND
   DD.FORM= 64 AND
   DD.ID_MD IN (58791) AND
   DD.CUIIO IN (D.CUIIO)) AS PERS
 
FROM   
    CIS2.VW_DATA_ALL_COEF D       
WHERE
  D.FORM IN (64)             AND 
  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
  D.CAPITOL IN (100,1123,1124,1125,1126,1127,1128,1129) 
--  AND D.CUIIO IN (40996334,41058201,37386492)

 GROUP BY D.CUIIO, D.CUIIO_VERS, D.CUATM, D.FORM,D.FORM_VERS,D.CUATM_FULL,D.PERIOADA
 
HAVING
 SUM(CASE WHEN D.CAPITOL IN (100)  AND D.RIND IN ('CD') THEN  D.COL1 ELSE 0 END)>0
 
) DD



 INNER JOIN CIS2.VW_CL_CAEM2 C ON SUBSTR( C.CODUL,2,4)  = CASE WHEN DD.CAEM2_ACTUALIZAT IS NULL THEN DD.CAEM2 ELSE DD.CAEM2_ACTUALIZAT END
 INNER JOIN CIS2.VW_CL_CAEM2 CC ON  (C.FULL_CODE LIKE '%'||CC.CODUL||';%') 

 CROSS JOIN
  ( 
    SELECT 'Nr. de intreprinderi pe economie'  AS NUME_ROW, '01' AS NR_ROW, 'Col0' AS COL FROM DUAL     
--    SELECT 'Structura (%)'                     AS NUME_ROW, '02' AS NR_ROW, 'Col0' AS COL FROM DUAL UNION
--    SELECT 'Numarul mediu de salariati'        AS NUME_ROW, '03' AS NR_ROW, 'Col1' AS COL FROM DUAL UNION 
--    SELECT 'Structura (%)'                     AS NUME_ROW, '04' AS NR_ROW, 'Col1' AS COL FROM DUAL UNION 
--    SELECT 'Venituri din vinzarie'             AS NUME_ROW, '05' AS NR_ROW, 'Col2' AS COL FROM DUAL UNION 
--    SELECT 'Structura (%)'                     AS NUME_ROW, '06' AS NR_ROW, 'Col2' AS COL FROM DUAL UNION   
--    SELECT 'Valoarea productiei'               AS NUME_ROW, '07' AS NR_ROW, 'Col3' AS COL FROM DUAL UNION 
--    SELECT 'Structura (%)'                     AS NUME_ROW, '08' AS NR_ROW, 'Col3' AS COL FROM DUAL UNION 
--    SELECT 'Valoarea adaugata bruta la costul factorilor'   AS NUME_ROW, '09' AS NR_ROW, 'Col4' AS COL FROM DUAL UNION   
--    SELECT 'Structura (%)'                     AS NUME_ROW, '10' AS NR_ROW, 'Col4' AS COL FROM DUAL     

  ) RR


 WHERE 
  (DD.FORM=:pFORM) AND
  (DD.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (DD.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  DD.PERIOADA IN (:pPERIOADA) 

--  AND DD.CUIIO IN (
--  41295881,
--41296030,
--41296194,
--41296685
--
--  )
 -- AND  CC.CODUL = 'H4941'
GROUP BY 
--  DD.CUIIO,
 RR.NR_ROW,
 RR.NUME_ROW,
CC.CODUL,
CC.DENUMIRE,
CC.FULL_CODE

ORDER BY 
CC.FULL_CODE

