

--DELETE 
--FROM USER_BANCU.TABLE_OUT_TEST;


BEGIN

     --USER_BANCU.PR_CONTROL_LOG (:USER_NANE);
    -- USER_BANCU.PR_DATA_STATUS (:USER_NANE);
   --  USER_BANCU.PR_EXPORT_VARIABLE(:USER_NANE);
   --  USER_BANCU.PR_FORM_CLASIFICATOR(:USER_NANE);
     USER_BANCU.PR_FORM_CUIIO(:USER_NANE);
      USER_BANCU.PR_MD_CAPITOL(:USER_NANE);
   --  USER_BANCU.PR_MD_COLOANA(:USER_NANE);
     USER_BANCU.PR_MD_CONTROL(:USER_NANE);
   --  USER_BANCU.PR_MD_FORM(:USER_NANE);
   --  USER_BANCU.PR_MD_PERIOADA(:USER_NANE);
    -- USER_BANCU.PR_MD_RIND(:USER_NANE);
   --  USER_BANCU.PR_MD_RIND_OUT(:USER_NANE);
   -- USER_BANCU.PR_MD_SECTIE(:USER_NANE);
     --  USER_BANCU.PR_MD_TABLES(:USER_NANE);
   -- USER_BANCU.PR_MD_TIP_PERIOADA(:USER_NANE);
    USER_BANCU.PR_RENIM(:USER_NANE);
   -- USER_BANCU.PR_RENIM_ACCEPT(:USER_NANE);
   -- USER_BANCU.PR_SYS_ACCES_TYPE(:USER_NANE);
   -- USER_BANCU.PR_SYS_INFO(:USER_NANE);
   -- USER_BANCU.PR_SYS_USER(:USER_NANE);
    --USER_BANCU.PR_SYS_USER_ACCES(:USER_NANE);
    --USER_BANCU.PR_USERS_SQL(:USER_NANE);
END;