
SELECT COUNT(*) CNT
 FROM  renim_29_01_2018; 

SELECT *
 FROM  renim_29_01_2018; 

DELETE
 FROM  renim_29_01_2018; 


SELECT *
 FROM  renim_29_01_2018; 


SELECT COUNT(*) CNT
 FROM  renim_29_01_2018; 



CREATE TABLE `RENIM_29_01_2018` (
  `CUIIO` bigint(50) DEFAULT NULL,
  `CUIIO_VERS` bigint(10) DEFAULT NULL,
  `DENUMIRE` varchar(255) DEFAULT NULL,
  `EDIT_USER` bigint(10) DEFAULT NULL,
  `STATUT` varchar(255) DEFAULT NULL,
  `CUATM` varchar(255) DEFAULT NULL,
  `CFP` varchar(255) DEFAULT NULL,
  `CFOJ` varchar(255) DEFAULT NULL,
  `COCM` varchar(255) DEFAULT NULL,
  `CAEM` varchar(255) DEFAULT NULL,
  `BUGET` varchar(255) DEFAULT NULL,
  `TIP` varchar(255) DEFAULT NULL,
  `PROD` varchar(3) DEFAULT NULL,
  `FOR_CUB` varchar(10) DEFAULT NULL,
  `GENMUZEE` varchar(10) DEFAULT NULL,
  `TIPMUZEE` varchar(10) DEFAULT NULL,
  `TIP_LOCAL` varchar(10) DEFAULT NULL,
  `TIP_INST` bigint(10) DEFAULT NULL,
  `CAEM2` varchar(10) DEFAULT NULL,
  `N85_NTL` varchar(10) DEFAULT NULL,
  `N85_NTIIP` varchar(10) DEFAULT NULL,
  `N85_NDIIP` varchar(10) DEFAULT NULL,
  `N85_NPDS` varchar(10) DEFAULT NULL,
  `N85_NRIIP` varchar(10) DEFAULT NULL,
  `N85_NSIIP` varchar(10) DEFAULT NULL,
  `GENMUZEE2` varchar(10) DEFAULT NULL,
  `NFI` bigint(10) DEFAULT NULL,
  `NTII` bigint(10) DEFAULT NULL,
  `NPDS` bigint(10) DEFAULT NULL,
  `ORGANE`  varchar(10) DEFAULT NULL,
  `TIP_INV`  varchar(10) DEFAULT NULL,
  `RENIM_PERS` bigint(10) DEFAULT NULL,
  `ORGANE_COND`  varchar(10) DEFAULT NULL

) ENGINE=InnoDB DEFAULT CHARSET=utf8;



