SELECT DISTINCT
   B.COL1||' < '||
   NVAL(SUM(CASE WHEN D.RIND IN('2002') THEN D.COL1 ELSE 0 END)) 
   
   AS REZULTAT
  
  FROM
  USER_EREPORTING.VW_DATA_ALL_FOR_VALIDATE D
  INNER JOIN  
  (
  SELECT DISTINCT
  CUIIO,
  ANUL,
  NVAL(SUM(CASE WHEN D.RIND IN('201') THEN D.COL3 ELSE 0 END)) AS COL1
  
FROM
  CIS2.VW_DATA_ALL D
  
WHERE
  D.FORM IN 20 AND
  D.CAPITOL IN 1011 AND
  D.RIND IN '201' AND
  D.CUIIO=:CUIIO AND
  D.ANUL IN (SELECT ANUL FROM CIS2.MD_PERIOADA WHERE PERIOADA IN (:PERIOADA))

GROUP BY
  CUIIO,
  ANUL
  
  ) B ON (D.CUIIO=B.CUIIO AND D.ANUL = B.ANUL)
WHERE
  (:PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO              OR :CUIIO = -1) AND
  (:CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS <> :CUIIO_VERS) AND
  (:FORM = :FORM               OR :FORM <> :FORM ) AND
  (:FORM_VERS=:FORM_VERS       OR :FORM_VERS <> :FORM_VERS ) AND
  (:CAPITOL=:CAPITOL           OR :CAPITOL <> :CAPITOL ) AND
  (:CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS <> :CAPITOL_VERS ) AND
  (:ID_MD=:ID_MD               OR :ID_MD = -1) AND 
   
 -- D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('19.1018.2002')
  
  D.FORM = 19
  AND D.CAPITOL = 1018
  AND D.RIND IN ('2002')
  
GROUP BY
  B.COL1

HAVING
B.COL1 <
   NVAL(SUM(CASE WHEN D.RIND IN('2002') THEN D.COL1 ELSE 0 END))