--DECLARE
--
--  CURSOR C IS
--
--SELECT 
--    DF.PERIOADA,
--    DF.FORM,
--    DF.FORM_VERS,
--    DF.ID_MDTABLE,
--    DF.COD_CUATM,
--    DF.NR_SECTIE,
--    DF.NUME_SECTIE,
--    DF.NR_SECTIE1,
--    DF.NUME_SECTIE1,
--    DF.NR_SECTIE2,
--    DF.NUME_SECTIE2,
--    DF.NR_ROW NR_ROW,
--    DF.ORDINE,
--    DF.DECIMAL_POS,
--    DF.NUME_ROW,
--    DF.COL1,
--    DF.COL2,
--    DF.COL3,
--    DF.COL4,
--    DF.COL5,
--    DF.COL6,
--    DF.COL7,
--    DF.COL8,
--    DF.COL9
--     
--FROM 
--(


    SELECT  

--     :pPERIOADA AS PERIOADA,
--    :pFORM AS FORM,
--    :pFORM_VERS AS FORM_VERS,
--    :pID_MDTABLE AS ID_MDTABLE,
--    :pCOD_CUATM AS COD_CUATM,
--    '0' AS NR_SECTIE,
--    '0' AS NUME_SECTIE,
--    '0' AS NR_SECTIE1,
--    '0' AS NUME_SECTIE1,
--    '0' AS NR_SECTIE2,
--    '0' AS NUME_SECTIE2,

     SUM(CASE WHEN D.RIND = VBG.RIND AND  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  THEN D.COL1 ELSE NULL END) ||'~'||VBG.RIND AS NR_ROW, 
     VBG.RIND ORDINE,
    '000000000' AS DECIMAL_POS,
     REPLACE(VBG.DENUMIRE, '<br>') NUME_ROW,
     SUM(CASE WHEN D.RIND = VBG.RIND AND  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  THEN D.COL3 ELSE NULL END) AS COL1,   
     SUM(CASE WHEN D.RIND = VBG.RIND AND  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) THEN D.COL4 ELSE NULL END ) AS COL2, 
     SUM(CASE WHEN D.RIND = VBG.RIND AND  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) THEN D.COL6 ELSE NULL END ) AS COL3, 
     SUM(CASE WHEN D.RIND = VBG.RIND AND  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) THEN D.COL7 ELSE NULL END ) AS COL4, 
     SUM(CASE WHEN D.RIND = VBG.RIND AND  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  THEN D.COL9 ELSE NULL END ) AS COL5, 
     SUM(CASE WHEN D.RIND = VBG.RIND AND  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  THEN D.COL11 ELSE NULL END ) AS COL6, 
     SUM(CASE WHEN D.RIND = VBG.RIND AND  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) THEN D.COL13 ELSE NULL END ) AS COL7, 
     SUM(CASE WHEN D.RIND = VBG.RIND AND  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) THEN D.COL15 ELSE NULL END ) AS COL8, 
     SUM(CASE WHEN D.RIND = VBG.RIND AND  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) THEN D.COL16 ELSE NULL END ) AS COL9 
     --SUM(D.COL16) AS COL10
     
     
     
     
     FROM CIS2.VW_DATA_ALL_GC D 
     
        --    INNER JOIN CIS2.MD_RIND MD ON MD.ID_MD = D.ID_MD
            
         ---   INNER JOIN CIS2.MD_PERIOADA MP ON (MP.PERIOADA = D.PERIOADA AND MP.TIP_PERIOADA = 5)
          
          
         CROSS JOIN (
         
    SELECT 'Bovine - total' AS DENUMIRE, 1 AS ORDINE,  '010' AS RIND FROM DUAL UNION  
    SELECT '  vaci' AS DENUMIRE, 2 AS ORDINE,  '011' AS RIND FROM DUAL UNION   
    SELECT '  tineret 0-6 luni' AS DENUMIRE,3 AS ORDINE,  '012' AS RIND FROM DUAL UNION 
    SELECT '  tineret 6 luni pina la 1 an' AS DENUMIRE, 4 AS ORDINE,  '013' AS RIND FROM DUAL UNION 
    SELECT '  tineret peste 1 an' AS DENUMIRE, 4 AS ORDINE,  '014' AS RIND FROM DUAL UNION   
    SELECT '    din care junci peste 18 luni' AS DENUMIRE, 5 AS ORDINE,  '015' AS RIND FROM DUAL  UNION
    SELECT 'Porcine - total' AS DENUMIRE, 6 AS ORDINE,  '020' AS RIND FROM DUAL   UNION   
    SELECT '  scroafe de baza' AS DENUMIRE,7 AS ORDINE,  '021' AS RIND FROM DUAL  UNION 
    SELECT '  porcine 0-4 luni' AS DENUMIRE,8 AS ORDINE,  '022' AS RIND FROM DUAL  UNION
    SELECT '  porcine peste 4 luni' AS DENUMIRE,9 AS ORDINE,  '023' AS RIND FROM DUAL  UNION
    SELECT '    din care purcele de repr.de  la 9 lun' AS DENUMIRE,10 AS ORDINE,  '024' AS RIND FROM DUAL UNION  
    SELECT 'Ovine - total' AS DENUMIRE,11 AS ORDINE,  '030' AS RIND FROM DUAL  UNION
    SELECT '  oi fatatoare' AS DENUMIRE,12 AS ORDINE,  '031' AS RIND FROM DUAL UNION
    SELECT '  mioare de 1 an si peste' AS DENUMIRE,13 AS ORDINE,  '032' AS RIND FROM DUAL UNION 
    SELECT '  tineret pina la 1 an' AS DENUMIRE,14 AS ORDINE,  '033' AS RIND FROM DUAL    UNION
    SELECT 'Caprine - total' AS DENUMIRE,15 AS ORDINE,  '040' AS RIND FROM DUAL   UNION
    SELECT '  capre fatatoare de 1an si peste' AS DENUMIRE,16 AS ORDINE,  '041' AS RIND FROM DUAL UNION  
    SELECT '  tineret pina la 1 an' AS DENUMIRE,17 AS ORDINE,  '042' AS RIND FROM DUAL UNION 
    SELECT 'Cabaline' AS DENUMIRE,18 AS ORDINE,  '050' AS RIND FROM DUAL UNION
    SELECT '   adulte' AS DENUMIRE,20 AS ORDINE,  '051' AS RIND FROM DUAL UNION
    SELECT 'Gaini si cucosi total' AS DENUMIRE,21 AS ORDINE,  '060' AS RIND FROM DUAL UNION
    SELECT '  gaini ouatoare' AS DENUMIRE,22 AS ORDINE,  '061' AS RIND FROM DUAL  UNION 
    SELECT 'Giste total' AS DENUMIRE,23 AS ORDINE,  '070' AS RIND FROM DUAL  UNION 
    SELECT '  giste adulte' AS DENUMIRE,24 AS ORDINE,  '071' AS RIND FROM DUAL  UNION 
    SELECT 'Rate total' AS DENUMIRE,25 AS ORDINE,  '080' AS RIND FROM DUAL UNION    
    SELECT '  rate adulte' AS DENUMIRE,26 AS ORDINE,  '081' AS RIND FROM DUAL UNION
    SELECT 'Curcani total' AS DENUMIRE,27 AS ORDINE,  '090' AS RIND FROM DUAL UNION
    SELECT '  curcani adulti' AS DENUMIRE,28 AS ORDINE,  '091' AS RIND FROM DUAL UNION
    SELECT 'Iepuri total' AS DENUMIRE,29 AS ORDINE,  '100' AS RIND FROM DUAL UNION 
    SELECT '  iepuri adulti' AS DENUMIRE,30 AS ORDINE,  '101' AS RIND FROM DUAL UNION
    SELECT 'familii de albine' AS DENUMIRE,31 AS ORDINE,  '200' AS RIND FROM DUAL 
         ) VBG
     
          
WHERE 
  
  
 
  
  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)   AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  
  
  GROUP BY 
  VBG.RIND,
  VBG.DENUMIRE,
  VBG.ORDINE
  
  
  
 -- ORDER BY 
 -- VBG.ORDINE

--  ) DF
--  
--  ;
--   
--    BEGIN
--
--  FOR CR IN C
--  
--  LOOP
--   
--    INSERT INTO  CIS2.TABLE_OUT
--    (
--      PERIOADA,
--      FORM,
--      FORM_VERS,
--      ID_MDTABLE,
--      COD_CUATM,
--      NR_SECTIE,
--      NUME_SECTIE,
--      NR_SECTIE1,
--      NUME_SECTIE1,
--      NR_SECTIE2,
--      NUME_SECTIE2,
--      NR_ROW,
--      ORDINE,
--      DECIMAL_POS,
--      NUME_ROW,
--       
--      COL1, COL2, COL3,  COL4, COL5, COL6, COL7, COL8, COL9
--    )
--    VALUES
--    (
--      CR.PERIOADA,
--      CR.FORM,
--      CR.FORM_VERS,
--      CR.ID_MDTABLE,
--      CR.COD_CUATM,
--      CR.NR_SECTIE,
--      CR.NUME_SECTIE,
--      CR.NR_SECTIE1,
--      CR.NUME_SECTIE1,
--      CR.NR_SECTIE2,
--      CR.NUME_SECTIE2,
--      CR.NR_ROW,
--      CR.ORDINE,
--      CR.DECIMAL_POS,
--      CR.NUME_ROW,
--       
--      CR.COL1, CR.COL2, CR.COL3, CR.COL4 , CR.COL5 , CR.COL6, CR.COL7, CR.COL8, CR.COL9 
--    );
--  END LOOP;
--END;
--  
  