SELECT 
        
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
   '0' AS  NR_SECTIE,
    '0' AS NUME_SECTIE,
    '0' AS NR_SECTIE1,
    '0' AS NUME_SECTIE1,
       '0' AS NR_SECTIE2,
        '0' AS NUME_SECTIE2,
        COUNT(DISTINCT CASE WHEN 1=1   AND    MR.RIND IN ('0')  THEN   D.UNIT_CODE  ELSE NULL END)||'~'|| CC.CODUL AS NR_ROW,
        CC.CODUL AS ORDINE,
         '001' AS DECIMAL_POS,
         CC.DENUMIRE AS NUME_ROW,
      --   COUNT(DISTINCT CASE WHEN 1=1   AND    MR.RIND IN ('0')  THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN 1=1   AND    MR.RIND IN ('TIP3')  THEN   D.UNIT_CODE  ELSE NULL END) AS COL1,
         COUNT(DISTINCT CASE WHEN 1=1   AND    MR.RIND IN ('TIP2')  THEN   D.UNIT_CODE  ELSE NULL END) AS COL2,
         COUNT(DISTINCT CASE WHEN 1=1   AND    MR.RIND NOT IN ('TIP2', 'TIP3','0')  THEN   D.UNIT_CODE  ELSE NULL END) AS COL3
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  
  INNER  JOIN CIS2.VW_CL_CUATM C ON D.CUATM = C.CODUL 
  INNER  JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')     
  
    AND CC.PRGS IN ('2')  
  
  
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND

  D.FORM IN (58)  AND
  D.CAPITOL IN (419)
  
 GROUP BY
 
  CC.CODUL,
  CC.DENUMIRE,
  CC.FULL_CODE