

SELECT DISTINCT
  D.CUIIO,
  D.FILIAL,
  D.CAPITOL,
  D.CAPITOL_DEN,
  MR.RIND,
  D.CUATM_FULL,
  D.CFP,
  SUM (D.COL1) AS COL1,
  SUM (D.COL2) AS COL2,
  SUM (D.COL3) AS COL3,
  SUM (D.COL4) AS COL4,
  SUM (D.COL5) AS COL5,
  SUM (D.COL6) AS COL6,
  SUM (D.COL7) AS COL7,
  SUM (D.COL8) AS COL8,
  SUM (D.COL9) AS COL9  
FROM 
  VW_DATA_ALL D
  
            INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD 

WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  
  D.FORM = 3 AND  D.CUIIO = 39060805  
 
GROUP BY
  D.CUIIO,
  D.FILIAL,
  D.CUATM_FULL,
  D.CFP,
  D.CAPITOL,
  D.CAPITOL_DEN,
  MR.RIND
  
  ORDER BY 
  D.CUIIO,
  D.CAPITOL,
  MR.RIND
  
