SELECT 
L.CUIIO,

L.T_XML_FORM_ID,
R.CUIIO R_CUIIO


FROM 
(
SELECT 
 DISTINCT D.CUIIO,
 D.T_XML_FORM_ID 
 FROM USER_EREPORTING.VW_DATA_ALL_PRIMIT D
 
            INNER JOIN CIS2.VW_CL_CUATM C ON C.CODUL = D.CUATM
 
 WHERE 
 (C.FULL_CODE LIKE '%'||:pCOD_CUATM||';%') AND
   D.PERIOADA = 2010 AND 
 
  D.FORM IN (:pFORM)
  
  ) L INNER  JOIN (
  
  SELECT 
 DISTINCT D.CUIIO

 FROM CIS2.VW_DATA_ALL D
 
            INNER JOIN CIS2.VW_CL_CUATM C ON C.CODUL = D.CUATM
 
 WHERE 
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.PERIOADA = 2010 AND 
 
  D.FORM IN (:pFORM)
  
  
  ) R  ON R.CUIIO = L.CUIIO 
  
  WHERE 
  R.CUIIO IS NOT NULL 