


SELECT DISTINCT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,    
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  RIND AS NR_ROW,
   ORDINE,
  '0000000' AS DECIMAL_POS,
D.DENUMIRE AS NUME_ROW,

D.COL1,
D.COL2,
D.COL3,
D.COL4,
D.COL5,
D.COL6,
ROUND(( D.COL7 / P.COL1 ) * 100,1) AS COL7
FROM
(

SELECT
  R.DENUMIRE,
  R.RIND,
  R.ORDINE,
    
  (SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND R.RIND =  D.RIND THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND R.RIND =  D.RIND THEN D.COL2 ELSE 0 END))  AS COL1,
  
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND R.RIND =  D.RIND THEN D.COL1 ELSE 0 END) AS COL2,
  
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND R.RIND =  D.RIND THEN D.COL2 ELSE 0 END) AS COL3,
  
 (SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND R.RIND =  D.RIND THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND R.RIND =  D.RIND THEN D.COL2 ELSE 0 END))  AS COL4,
  
  SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND R.RIND =  D.RIND THEN D.COL1 ELSE 0 END) AS COL5,
  
  SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND R.RIND =  D.RIND THEN D.COL2 ELSE 0 END) AS COL6,
  
 (((SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND R.RIND =  D.RIND THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND R.RIND =  D.RIND THEN D.COL2 ELSE 0 END))/
  
 NOZERO(SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND R.RIND =  D.RIND THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND R.RIND =  D.RIND THEN D.COL2 ELSE 0 END)))) AS COL7
  
  
FROM 
  CIS.VW_DATA_ALL D


CROSS JOIN (

 SELECT     
      RIND,
      DENUMIRE,
     
      ORDINE  
  
    FROM 
     CIS.MD_RIND
  
   WHERE
     CAPITOL = 31 AND    
      RIND NOT IN ('-') AND
      RIND_VERS >=  1040 AND
      STATUT = '1'  
      
      GROUP BY 
      RIND,
      DENUMIRE,
      ORDINE
     
      
      
      
         
    ) R

    
     

     
WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
 ((D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) OR (D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4))  AND
  D.FORM = 6 AND
  D.CAPITOL = 31
  
GROUP BY
  R.DENUMIRE,
  R.RIND,
  R.ORDINE
 ) D   
 
 CROSS JOIN (
 
 SELECT DISTINCT 
      COL1 
    
    FROM 
      CIS.VW_DATA_ALL D
      INNER JOIN (
        
        SELECT DISTINCT
          D.ANUL,
          SUM(CASE 
          WHEN D.NUM IN 1 THEN DD.COL1
          WHEN D.NUM IN 2 THEN DD.COL2
          WHEN D.NUM IN 3 THEN DD.COL3
          WHEN D.NUM IN 4 THEN DD.COL4 END) AS JIP
  
  
  
       FROM 
         CIS.MD_PERIOADA D
         INNER JOIN (
  
       SELECT DISTINCT
         ANUL,
         CASE WHEN NUM IN 3  THEN PERIOADA ELSE 0 END AS COL1,
         CASE WHEN NUM IN 6  THEN PERIOADA ELSE 0 END AS COL2,
         CASE WHEN NUM IN 9  THEN PERIOADA ELSE 0 END AS COL3,
         CASE WHEN NUM IN 12 THEN PERIOADA ELSE 0 END AS COL4
  
      FROM 
        CIS.MD_PERIOADA
  
      WHERE 
        TIP_PERIOADA = 4


  ) DD ON DD.ANUL = D.ANUL
  
WHERE
  PERIOADA = :pPERIOADA

GROUP BY
  D.ANUL
) P ON P.ANUL = D.ANUL
  
WHERE 
  D.PERIOADA = P.JIP AND
  D.CAPITOL = 37  AND
  D.RIND IN ('01') 
 ) P 
 
 ORDER BY 
 D.ORDINE