--DECLARE
--
--  CURSOR C IS
--
--SELECT 
--    DF.PERIOADA,
--    DF.FORM,
--    DF.FORM_VERS,
--    DF.ID_MDTABLE,
--    DF.COD_CUATM,
--    DF.NR_SECTIE,
--    DF.NUME_SECTIE,
--    DF.NR_SECTIE1,
--    DF.NUME_SECTIE1,
--    DF.NR_SECTIE2,
--    DF.NUME_SECTIE2,
--    DF.NR_ROW NR_ROW,
--    DF.ORDINE,
--    DF.DECIMAL_POS,
--    DF.NUME_ROW,
--    DF.COL1,
--    DF.COL2,
--    DF.COL3,
--    DF.COL4,
--    DF.COL5,
--    DF.COL6,
--    DF.COL7
--     
--FROM 
--(




SELECT DISTINCT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,    
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  D.RIND AS NR_ROW,
  D.ORDINE,
  '0000000' AS DECIMAL_POS,
  D.DENUMIRE AS NUME_ROW,

D.COL1,
D.COL2,
D.COL3,
D.COL4,
D.COL5,
D.COL6,
CASE 

WHEN  D.RIND NOT IN ('410','420','430','440','441','450','-') THEN  ROUND(( D.COL7 / P.COL1 ) * 100,1) 
WHEN  D.RIND IN ('440','441','450')  THEN 

ROUND(( D.COL7 / P.COL3 ) * 100,1) 

WHEN  D.RIND IN ('410','420','430')  THEN 

ROUND(( D.COL7 / P.COL2 ) * 100,1)  

ELSE NULL
END 

AS COL7
FROM
(

SELECT
  R.DENUMIRE,
  R.RIND,
  R.ORDINE,
    
  (SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND R.RIND =  D.RIND THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND R.RIND =  D.RIND THEN D.COL2 ELSE 0 END))  AS COL1,
  
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND R.RIND =  D.RIND THEN D.COL1 ELSE 0 END) AS COL2,
  
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND R.RIND =  D.RIND THEN D.COL2 ELSE 0 END) AS COL3,
  
 (SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND R.RIND =  D.RIND THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND R.RIND =  D.RIND THEN D.COL2 ELSE 0 END))  AS COL4,
  
  SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND R.RIND =  D.RIND THEN D.COL1 ELSE 0 END) AS COL5,
  
  SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND R.RIND =  D.RIND THEN D.COL2 ELSE 0 END) AS COL6,
  
 (((SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND R.RIND =  D.RIND THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND R.RIND =  D.RIND THEN D.COL2 ELSE 0 END))/
  
 NOZERO(SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND R.RIND =  D.RIND THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND R.RIND =  D.RIND THEN D.COL2 ELSE 0 END)))) AS COL7
  
  
FROM 
  CIS.VW_DATA_ALL D


CROSS JOIN (

 SELECT     
      RIND,
      DENUMIRE,
     
      ORDINE  
  
    FROM 
     CIS.MD_RIND
  
   WHERE
     CAPITOL = 31 AND    
      RIND NOT IN ('-') AND
      RIND_VERS >=  1040 AND
      STATUT = '1'  
      
      GROUP BY 
      RIND,
      DENUMIRE,
      ORDINE
     
      
      
      
         
    ) R

    
     

     
WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
 ((D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) OR (D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4))  AND
  D.FORM = 6 AND
  D.CAPITOL = 31
  
GROUP BY
  R.DENUMIRE,
  R.RIND,
  R.ORDINE
 ) D   
 
 CROSS JOIN (
 
 SELECT DISTINCT 
     MAX(CASE WHEN D.RIND IN ('01') THEN D.COL1 ELSE NULL END)  COL1,
     MAX(CASE WHEN D.RIND IN ('02') THEN D.COL1 ELSE NULL END)  COL2,
     MAX(CASE WHEN D.RIND IN ('03') THEN D.COL1 ELSE NULL END)  COL3,
     MAX(CASE WHEN D.RIND IN ('04') THEN D.COL1 ELSE NULL END)  COL4
       
    
    FROM 
      CIS.VW_DATA_ALL D
      INNER JOIN (
        
        SELECT DISTINCT
          D.ANUL,
          SUM(CASE 
          WHEN D.NUM IN 1 THEN DD.COL1
          WHEN D.NUM IN 2 THEN DD.COL2
          WHEN D.NUM IN 3 THEN DD.COL3
          WHEN D.NUM IN 4 THEN DD.COL4 END) AS JIP
  
  
  
       FROM 
         CIS.MD_PERIOADA D
         INNER JOIN (
  
       SELECT DISTINCT
         ANUL,
         CASE WHEN NUM IN 3  THEN PERIOADA ELSE 0 END AS COL1,
         CASE WHEN NUM IN 6  THEN PERIOADA ELSE 0 END AS COL2,
         CASE WHEN NUM IN 9  THEN PERIOADA ELSE 0 END AS COL3,
         CASE WHEN NUM IN 12 THEN PERIOADA ELSE 0 END AS COL4
  
      FROM 
        CIS.MD_PERIOADA
  
      WHERE 
        TIP_PERIOADA = 4


  ) DD ON DD.ANUL = D.ANUL
  
WHERE
  PERIOADA = :pPERIOADA

GROUP BY
  D.ANUL
) P ON P.ANUL = D.ANUL
  
WHERE 
  D.PERIOADA = P.JIP AND
  D.CAPITOL = 37  
  
 ) P 
 

 
 
 
-- ) DF
--
--;
--   
--    BEGIN
--
--  FOR CR IN C
--  
--  LOOP
--    INSERT INTO --  USER_BANCU.TABLE_OUT_TEST 
--    
--     CIS2.TABLE_OUT
--    (
--      PERIOADA,
--      FORM,
--      FORM_VERS,
--      ID_MDTABLE,
--      COD_CUATM,
--      NR_SECTIE,
--      NUME_SECTIE,
--      NR_SECTIE1,
--      NUME_SECTIE1,
--      NR_SECTIE2,
--      NUME_SECTIE2,
--      NR_ROW,
--      ORDINE,
--      DECIMAL_POS,
--      NUME_ROW,
--       
--      COL1, COL2, COL3,  COL4, COL5, COL6, COL7 
--    )
--    VALUES
--    (
--      CR.PERIOADA,
--      CR.FORM,
--      CR.FORM_VERS,
--      CR.ID_MDTABLE,
--      CR.COD_CUATM,
--      CR.NR_SECTIE,
--      CR.NUME_SECTIE,
--      CR.NR_SECTIE1,
--      CR.NUME_SECTIE1,
--      CR.NR_SECTIE2,
--      CR.NUME_SECTIE2,
--      CR.NR_ROW,
--      CR.ORDINE,
--      CR.DECIMAL_POS,
--      CR.NUME_ROW,
--       
--      CR.COL1, CR.COL2, CR.COL3, CR.COL4, CR.COL5 , CR.COL6, CR.COL7 
--    );
--  END LOOP;
--END;