SELECT 
   B.ORDINE AS NR_ROW,
   B.ORDINE AS ORDINE,
  '00000000000' AS DECIMAL_POS,
   B.DENUMIRE AS NUME_ROW,
 (SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND NR_ROW LIKE '%'||D.CFP||'%' AND D.RIND IN ('100') THEN NVAL(D.COL1) ELSE 0 END)+
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND NR_ROW LIKE '%'||D.CFP||'%' AND D.RIND IN ('100') THEN NVAL(D.COL2) ELSE 0 END)) AS COL1,
  
  
   (SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND NR_ROW LIKE '%'||D.CFP||'%' AND D.RIND IN ('100') THEN NVAL(D.COL1) + NVAL(D.COL2) ELSE 0 END))
  
  
  AS COL2
  

FROM 
  CIS.VW_DATA_ALL D
  CROSS JOIN
    (SELECT 1 AS ORDINE, '12+13+15+16+17+18+19+20+24+26+28' AS NR_ROW, 'TOTAL imobilizari necorporale si corporale' AS DENUMIRE FROM DUAL UNION
     SELECT 2 AS ORDINE, '12+13' AS NR_ROW, 'publica' AS DENUMIRE FROM DUAL UNION
     SELECT 3 AS ORDINE, '15+16+17+18+19' AS NR_ROW, 'privata' AS DENUMIRE FROM DUAL UNION
     SELECT 4 AS ORDINE, '20' AS NR_ROW, 'mixta (publica si privata), fara participare straina' AS DENUMIRE FROM DUAL UNION
     SELECT 5 AS ORDINE, '24+26' AS NR_ROW, 'straina' AS DENUMIRE FROM DUAL UNION
     SELECT 6 AS ORDINE, '28' AS NR_ROW, 'a intreprindelor mixte' AS DENUMIRE FROM DUAL) B
     

  

  

  
  
  
  
  
  
WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
 ((D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) OR (PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4))  AND
  D.FORM = 6 AND
  D.CAPITOL = 31
  
GROUP BY
  B.DENUMIRE,
  B.ORDINE
 