SELECT DISTINCT 

'Daca in trim curent exista Cap.SR Export rind 01 sau rind 05 atunci exista si in trim precedent.'
  
  
  AS REZULTAT
FROM
  CIS2.VW_DATA_ALL D 
WHERE
  (D.PERIOADA IN (:PERIOADA,:PERIOADA-1)  ) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
 (:CUIIO_VERS=:CUIIO_VERS      OR :CUIIO_VERS <> :CUIIO_VERS) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL=:CAPITOL) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (44)  AND
  D.CAPITOL IN (1)

 HAVING
 ( 
 (
  (

  SUM(CASE WHEN D.PERIOADA IN (:PERIOADA) AND D.CAPITOL IN (1) AND  D.RIND  IN('01')   THEN NVAL(D.COL1) ELSE 0  END)  
  + 
  SUM(CASE WHEN D.PERIOADA IN (:PERIOADA) AND D.CAPITOL IN (1) AND  D.RIND  IN('05')   THEN NVAL(D.COL1) ELSE 0 END)  > 0

  )
  
  AND
  
  
   (

  SUM(CASE WHEN D.PERIOADA IN (:PERIOADA-1) AND D.CAPITOL IN (1) AND  D.RIND  IN('01')   THEN NVAL(D.COL1) ELSE 0 END)  
  + 
  SUM(CASE WHEN D.PERIOADA IN (:PERIOADA-1) AND D.CAPITOL IN (1) AND  D.RIND  IN('05')   THEN NVAL(D.COL1)  ELSE 0 END)  = 0

  )
  
  )
 OR    
(
  (

  SUM(CASE WHEN D.PERIOADA IN (:PERIOADA) AND D.CAPITOL IN (1) AND  D.RIND  IN('01')   THEN NVAL(D.COL1) ELSE 0  END)  
  + 
  SUM(CASE WHEN D.PERIOADA IN (:PERIOADA) AND D.CAPITOL IN (1) AND  D.RIND  IN('05')   THEN NVAL(D.COL1) ELSE 0 END)  = 0

  )
  
  AND
  
  
   (

  SUM(CASE WHEN D.PERIOADA IN (:PERIOADA-1) AND D.CAPITOL IN (1) AND  D.RIND  IN('01')   THEN NVAL(D.COL1) ELSE 0 END)  
  + 
  SUM(CASE WHEN D.PERIOADA IN (:PERIOADA-1) AND D.CAPITOL IN (1) AND  D.RIND  IN('05')   THEN NVAL(D.COL1)  ELSE 0 END)  > 0

  )
  
  ))

  AND
  (
 SELECT
  DISTINCT
  D.CUIIO
FROM
  CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA IN (:PERIOADA-1)) AND
  (D.CUIIO=:CUIIO OR :CUIIO = -1) AND
   D.FORM IN (44)  AND
   D.CAPITOL IN (1)
   
   
   
   ) IS NOT NULL