



SELECT DISTINCT 

'Daca exista col.1 ?i col.2 rândul.1 Import I exista  Cap. SR Import  Cauza 1  si invers '
  
  
  AS REZULTAT
FROM
  CIS2.VW_DATA_ALL_TEMP D 
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL<>:CAPITOL           OR :CAPITOL=:CAPITOL) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (46)  AND
  D.CAPITOL IN (411,404)

 HAVING
  
 (
 
 SUM(CASE WHEN D.CAPITOL IN (411) AND D.RIND IN('1') AND CIS2.NVAL(D.COL4) > 0 AND CIS2.NVAL(D.COL5) > 0  THEN 1 ELSE 0 END)   > 0 
 
 AND 
 
 SUM(CASE WHEN D.CAPITOL IN (404) AND  D.RIND  IN('01') THEN CIS2.NVAL(D.COL1) ELSE 0 END) = 0
 
 )
 
 OR 
 
 
 
 (
 
 SUM(CASE WHEN D.CAPITOL IN (411) AND D.RIND IN('1') AND CIS2.NVAL(D.COL4) > 0 AND CIS2.NVAL(D.COL5) > 0  THEN 1 ELSE 0 END)   = 0 
 
 AND 
 
 SUM(CASE WHEN D.CAPITOL IN (404) AND  D.RIND  IN('01') THEN CIS2.NVAL(D.COL1) ELSE 0 END) > 0
 
 )