SELECT DISTINCT

  SUM(CASE WHEN   D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('46.409.1') AND P.PERIOADA_ANULA = :PERIOADA   AND  D.CUIIO=:CUIIO THEN CIS2.NVAL(D.COL5) ELSE 0 END) ||'<>'||
  SUM(CASE WHEN   D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('44.405.1')  AND  P.PERIOADA_ANULA = :PERIOADA AND    D.CUIIO=:CUIIO  AND P.NUM IN (1,2,3,4) THEN CIS2.NVAL(D.COL5) ELSE 0 END) 
  
  
  AS REZULTAT
FROM
  CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.VW_MD_PERIOADA P ON (D.PERIOADA=P.PERIOADA)   
WHERE
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS<>:CUIIO_VERS     OR D.CUIIO_VERS=:CUIIO_VERS) AND
  (D.FORM <> :FORM               OR D.FORM =:FORM) AND
  (D.FORM_VERS<>:FORM_VERS       OR D.FORM_VERS=:FORM_VERS) AND
  (D.CAPITOL<>:CAPITOL           OR D.CAPITOL=:CAPITOL) AND
  (D.CAPITOL_VERS<>:CAPITOL_VERS OR D.CAPITOL_VERS=:CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  P.PERIOADA_ANULA = :PERIOADA AND
    
  D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('46.409.1')
  OR
  D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('44.405.1')

 



HAVING
  SUM(CASE WHEN   D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('46.409.1') AND P.PERIOADA_ANULA = :PERIOADA   AND  D.CUIIO=:CUIIO THEN CIS2.NVAL(D.COL5) ELSE 0 END) <>
  SUM(CASE WHEN   D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('44.405.1')  AND  P.PERIOADA_ANULA = :PERIOADA AND    D.CUIIO=:CUIIO  AND P.NUM IN (1,2,3,4) THEN CIS2.NVAL(D.COL5) ELSE 0 END) 