


---------------------------

  --  DELETE    
    SELECT *
    FROM USER_BANCU.KATALOG_EI_78_1040;

;

CREATE TABLE USER_BANCU.KATALOG_EI_78_1040
(
  CUIIO       NUMBER,
  CUIIO_VERS  NUMBER,
  STATUT       VARCHAR2(1024 BYTE),
  DENUMIRE    VARCHAR2(1024 BYTE),
  CUATM       VARCHAR2(1024 BYTE),
  CFP         VARCHAR2(1024 BYTE),
  CAEM2       VARCHAR2(1024 BYTE),
  ADRESA       VARCHAR2(1024 BYTE),
  TELEFON       VARCHAR2(1024 BYTE)
  
)
TABLESPACE TBS_DTI_USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;