SELECT 
    DISTINCT D.CUIIO
     
         FROM CIS2.VW_DATA_ALL D 
          INNER JOIN  CIS2.MD_RIND MR ON (MR.ID_MD =  D.ID_MD)
          
            INNER JOIN CIS2.VW_CL_SERVICII SS ON (rtrim(SS.CODUL, '0')=D.COL1 )
          
           INNER JOIN CIS2.RENIM R ON R.CUIIO=D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS
  


   
   WHERE 
  (D.PERIOADA =:pPERIOADA) AND 

  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (44)
  AND
  D.CAPITOL IN (406)
  AND MR.RIND NOT IN ('1')
  AND D.COL1 IN (851,852,853)

  
  GROUP BY 
   D.CUIIO


UNION 



SELECT 
    DISTINCT D.CUIIO
     
         FROM CIS2.VW_DATA_ALL D 
          INNER JOIN  CIS2.MD_RIND MR ON (MR.ID_MD =  D.ID_MD)
          
            INNER JOIN CIS2.VW_CL_SERVICII SS ON (rtrim(SS.CODUL, '0')=D.COL1 )
          
           INNER JOIN CIS2.RENIM R ON R.CUIIO=D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS
  


   
   WHERE 
  (D.PERIOADA =:pPERIOADA) AND 

  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (44)
  AND
  D.CAPITOL IN (405)
  AND MR.RIND NOT IN ('1','2')
  AND D.COL1 IN (851,852,853)

  
  GROUP BY 
   D.CUIIO