
INSERT INTO CIS2.RENIM

(
  CUIIO,
  CUIIO_VERS,
  DENUMIRE,
  EDIT_USER,
  STATUT,
  CUATM,           
  CFP,
  CFOJ,
  COCM,
  CAEM,
  BUGET,
  TIP,
  PROD,
  FOR_CUB,
  GENMUZEE,
  TIPMUZEE,
  TIP_LOCAL,
  TIP_INST,
  CAEM2,
  N85_NTL,
  N85_NTIIP,
  N85_NDIIP,
  N85_NPDS,
  N85_NRIIP,
  N85_NSIIP,
  GENMUZEE2,
  NFI,
  NTII,
  NPDS,
  ORGANE,
  TIP_INV,
  RENIM_PERS,
  ORGANE_COND,
  GEN_INSTITUTIE

)




 SELECT
  TO_NUMBER(TRIM(R.CUIIO)) CUIIO,
  TO_NUMBER(TRIM(R.CUIIO_VERS)) CUIIO_VERS,
  TRIM(R.DENUMIRE)  DENUMIRE,
  1 EDIT_USER,
  '1' STATUT,
  TRIM(R.CUATM) CUATM,           
  R.CFP,
  NULL CFOJ,
  NULL COCM,
  NULL CAEM,
  '0' BUGET,
  '0' TIP,
  NULL PROD,
  NULL FOR_CUB,
  NULL GENMUZEE,
  NULL TIPMUZEE,
  NULL TIP_LOCAL,
  NULL TIP_INST,
  TRIM(R.CAEM2)  CAEM2,
  NULL N85_NTL,
  NULL N85_NTIIP,
  NULL N85_NDIIP,
  NULL N85_NPDS,
  NULL N85_NRIIP,
  NULL N85_NSIIP,
  NULL GENMUZEE2,
  NULL NFI,
  NULL NTII,
  NULL NPDS,
  NULL ORGANE,
  NULL TIP_INV,
  NULL RENIM_PERS,
  NULL ORGANE_COND,
  NULL GEN_INSTITUTIE


FROM 
(

     SELECT
       L.CUIIO,
       L.CUIIO_VERS,
       L.DENUMIREA DENUMIRE,
       L.CUATM,
       L.CAEM2,
       L.CFP

      FROM USER_BANCU.EI_78_1036 L 
               
                LEFT JOIN CIS2.RENIM R ON (R.CUIIO = L.CUIIO AND 
                                            R.CUIIO_VERS = L.CUIIO_VERS) 
      
         WHERE 
         R.CUIIO IS  NULL
         AND R.CUIIO_VERS IS  NULL
         ) R