
--DECLARE
--
--  CURSOR C IS
--
--SELECT 
--    DF.PERIOADA,
--    DF.FORM,
--    DF.FORM_VERS,
--    DF.ID_MDTABLE,
--    DF.COD_CUATM,
--    DF.NR_SECTIE,
--    DF.NUME_SECTIE,
--    DF.NR_SECTIE1,
--    DF.NUME_SECTIE1,
--    DF.NR_SECTIE2,
--    DF.NUME_SECTIE2,
--    DF.NR_ROW NR_ROW,
--    DF.ORDINE,
--    DF.DECIMAL_POS,
--    DF.NUME_ROW,
--    DF.COL1,
--    DF.COL2,
--    DF.COL3,
--    DF.COL4
--    
--  
--
--   
--FROM 
--(

--SELECT
--  --ORDINE,
--  --DENUMIRE  NUME_ROW,
--  --CODUL_SERV,
--  
----    :pPERIOADA AS PERIOADA,
----    :pFORM AS FORM,
----    :pFORM_VERS AS FORM_VERS,
----    :pID_MDTABLE AS ID_MDTABLE,
----    :pCOD_CUATM AS COD_CUATM,
----    '0' AS NR_SECTIE,
----    '0' AS NUME_SECTIE,
----    '0' AS NR_SECTIE1,
----    '0' AS NUME_SECTIE1,
----    '0' AS NR_SECTIE2,
----   '0' AS NUME_SECTIE2,
--   --NR_ROW,
--   
--   CASE WHEN SUBSTR(NR_ROW,1,1) = '~' THEN '0'||NR_ROW ELSE NR_ROW END NR_ROW,   
--      
--   ROWNUM AS ORDINE,
--  '1111' AS DECIMAL_POS,
--   NUME_ROW,
--   COL1,
--  COL2,
--  COL3,
--  COL4
--FROM
--(
SELECT
  
 CASE WHEN rtrim(CODUL_SERV,'0')||'~'||ROWNUM/0.123 IS NULL THEN '0' ELSE rtrim (CODUL_SERV,'0')||'~'||ROWNUM/0.123 END  AS NR_ROW,
 
 
 
-- CASE WHEN rtrim (CODUL_SERV,'0')  IS NULL THEN '0' ELSE rtrim (CODUL_SERV,'0') END  AS NR_ROW,
 
   ORDINE, 
  DENUMIRE  NUME_ROW,
  
  --FULL_CODE,
  COL1,
  COL2,
  COL3,
  COL4
FROM
(

SELECT 
     --SS.CODUL   CODUL_SERV,
     
  --   TTT.CODUL  CODUL_TARI,
 --    TTT.FULL_CODE,
     1 ORDINE,
     SSS.DENUMIRE,
     SSS.CODUL    CODUL_SERV,
     SSS.FULL_CODE,
     
    ROUND((SUM(CASE WHEN  D.CAPITOL IN (409)  AND D.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END )  
    +
    SUM(CASE WHEN  D.CAPITOL IN (410)  AND D.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END ))/1000,1)
    AS COL1,
  
     ROUND((SUM(CASE WHEN  D.CAPITOL IN (409)  AND D.RIND NOT IN ('1','2','-') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END )  
    +
    SUM(CASE WHEN  D.CAPITOL IN (410)  AND D.RIND NOT IN ('1','-') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END ))/1000,1)
    AS COL2,
    
     ROUND((SUM(CASE WHEN  D.CAPITOL IN (411)  AND D.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END )  
    +
    SUM(CASE WHEN  D.CAPITOL IN (403)  AND D.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END ))/1000,1)
    AS COL3,
    
   ROUND((SUM(CASE WHEN  D.CAPITOL IN (411)  AND D.RIND NOT IN ('1','2','-') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END )  
    +
    SUM(CASE WHEN  D.CAPITOL IN (403)  AND D.RIND NOT IN ('1','-') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END ))/1000,1)
    AS COL4
     
      
      FROM CIS2.VW_DATA_ALL D 
       
       INNER JOIN CIS2.VW_CL_SERVICII SS ON (rtrim(SS.CODUL, '0')=D.COL1 ) 
       INNER JOIN   CIS2.VW_CL_SERVICII SSS ON (SS.FULL_CODE LIKE '%' ||SSS.CODUL||';%' )   
 
   
   -------------------------------------------------------------------------------
       
       
   WHERE 
  (D.PERIOADA =:pPERIOADA) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (46)
  AND
 -- D.CAPITOL IN (383,385,384,386)
  D.CAPITOL IN (409,410,411,403)

--  AND TTT.CODUL NOT IN ('000')
  
  --AND D.CUIIO IN (227548)
  
      GROUP BY
      --SS.CODUL, 
       SSS.DENUMIRE,
     SSS.CODUL,
      --TTT.CODUL,
      --(REPLACE (SS.CODUL,'0')),
      --TTT.FULL_CODE,
      SSS.FULL_CODE
      
 UNION
 SELECT
  ORDINE_TARA,
  DENUMIRE,
  CODUL_SERV,
  FULL_CODE,
  COL1,
  COL2,
  COL3,
  COL4
FROM(
SELECT 
     --SS.CODUL   CODUL_SERV,
     
  --   TTT.CODUL  CODUL_TARI,
 --    TTT.FULL_CODE,
     2 ORDINE,
     TTT.ORDINE AS ORDINE_TARA,
      TTT.DENUMIRE,
      SSS.CODUL CODUL_SERV,
      SSS.FULL_CODE,
      
     
   ROUND((SUM(CASE WHEN  D.CAPITOL IN (409)  AND D.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END )  
    +
    SUM(CASE WHEN  D.CAPITOL IN (410)  AND D.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END ))/1000,1)
    AS COL1,
  
     ROUND((SUM(CASE WHEN  D.CAPITOL IN (409)  AND D.RIND NOT IN ('1','2','-') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END )  
    +
    SUM(CASE WHEN  D.CAPITOL IN (410)  AND D.RIND NOT IN ('1','-') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END ))/1000,1)
    AS COL2,
    
     ROUND((SUM(CASE WHEN  D.CAPITOL IN (411)  AND D.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END )  
    +
    SUM(CASE WHEN  D.CAPITOL IN (403)  AND D.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END ))/1000,1)
    AS COL3,
    
   ROUND((SUM(CASE WHEN  D.CAPITOL IN (411)  AND D.RIND NOT IN ('1','2','-') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END )  
    +
    SUM(CASE WHEN  D.CAPITOL IN (403)  AND D.RIND NOT IN ('1','-') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END ))/1000,1)
    AS COL4
     
      
      FROM CIS2.VW_DATA_ALL D 
       
       
       INNER JOIN   CIS2.VW_CL_TARI TT  ON (TT.CODUL=D.COL3)
       INNER JOIN   CIS2.VW_CL_TARI TTT ON (TT.FULL_CODE LIKE '%' ||TTT.CODUL||';%' )   
       
      ---------------------------------------------------------------------
    INNER JOIN CIS2.VW_CL_SERVICII SS ON (rtrim(SS.CODUL, '0')=D.COL1 ) 
   INNER JOIN   CIS2.VW_CL_SERVICII SSS ON (SS.FULL_CODE LIKE '%' ||SSS.CODUL||';%' )   
 
   
   ------------------------------------------------------------------------------- 
       
       
   WHERE 
  (D.PERIOADA =:pPERIOADA) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (46)
  AND
  --D.CAPITOL IN (383,385,384,386)
  D.CAPITOL IN (409,410,411,403)
  

  AND TTT.CODUL NOT IN ('000')
  AND SSS.CODUL NOT IN ('0000000')
  
 -- AND D.CUIIO IN (227548)
  
      GROUP BY
      --SS.CODUL, 
      SSS.CODUL,
      TTT.CODUL,
      --(REPLACE (SS.CODUL,'0')),
      TTT.FULL_CODE,
      SSS.FULL_CODE,
      TTT.ORDINE,
 
      TTT.DENUMIRE
      
    ORDER BY
    TTT.ORDINE 
)
)
 ORDER BY
  CODUL_SERV,
  ORDINE
  
  
  
--)
  

--  ) DF
--  
--  ;
--   
--    BEGIN
--
--  FOR CR IN C
--  
--  LOOP
--    INSERT INTO  -- USER_BANCU.TABLE_OUT_TEST 
--    
--     CIS2.TABLE_OUT
--    (
--      PERIOADA,
--      FORM,
--      FORM_VERS,
--
--      ID_MDTABLE,
--      COD_CUATM,
--      NR_SECTIE,
--      NUME_SECTIE,
--      NR_SECTIE1,
--      NUME_SECTIE1,
--      NR_SECTIE2,
--      NUME_SECTIE2,
--      NR_ROW,
--      ORDINE,
--      DECIMAL_POS,
--      NUME_ROW,
--       
--      COL1, COL2, COL3,  COL4
--    )
--    VALUES
--    (
--      CR.PERIOADA,
--      CR.FORM,
--      CR.FORM_VERS,
--      CR.ID_MDTABLE,
--      CR.COD_CUATM,
--      CR.NR_SECTIE,
--      CR.NUME_SECTIE,
--      CR.NR_SECTIE1,
--      CR.NUME_SECTIE1,
--      CR.NR_SECTIE2,
--      CR.NUME_SECTIE2,
--      CR.NR_ROW,
--      CR.ORDINE,
--      CR.DECIMAL_POS,
--      CR.NUME_ROW,
--       
--      CR.COL1, CR.COL2, CR.COL3, CR.COL4
--    );
--  END LOOP;
--END;
  
  