 SELECT 
    CC.CODUL,
    CC.FULL_CODE,
    CC.DENUMIRE DENUMIRE_CUATM,
    D.CUIIO,
    R.DENUMIRE DENUMIRE_CUIIO, 
    MR.RIND,
    R.DENUMIRE DENUMIRE,
    '1' AS ORDINE, 
    NULL   AS  COL1,
    NULL   AS  COL2,
    NULL   AS  COL3,
    NULL   AS  COL4,
    NULL   AS  COL5,
    D.CUIIO   AS  COL6,
    MAX(CASE WHEN  MR.CAPITOL IN (1) AND MR.RIND IN ('01') AND   CIS2.NVAL(D.COL1) = 1 THEN  1  
             WHEN  MR.CAPITOL IN (1) AND MR.RIND IN ('02') AND   CIS2.NVAL(D.COL1) = 1 THEN  2
             WHEN  MR.CAPITOL IN (1) AND MR.RIND IN ('03') AND   CIS2.NVAL(D.COL1) = 1 THEN  3
             WHEN  MR.CAPITOL IN (1) AND MR.RIND IN ('04') AND   CIS2.NVAL(D.COL1) = 1 THEN  4
             WHEN  MR.CAPITOL IN (1) AND MR.RIND IN ('05') AND   CIS2.NVAL(D.COL1) = 1 THEN  5
             WHEN  MR.CAPITOL IN (1) AND MR.RIND IN ('06') AND   CIS2.NVAL(D.COL1) = 1 THEN  6
             WHEN  MR.CAPITOL IN (1) AND MR.RIND IN ('07') AND   CIS2.NVAL(D.COL1) = 1 THEN  7  
    
    END) COL7

FROM CIS2.DATA_ALL D 
        
        INNER JOIN CIS2.RENIM R ON R.CUIIO=D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS
        INNER JOIN CIS2.VW_CL_CUATM C ON R.CUATM = C.CODUL
        INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD
        INNER  JOIN VW_CL_CUATM CT ON R.CUATM = CT.CODUL
        INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%' )
        
   WHERE 
  (D.PERIOADA =:pPERIOADA) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (CT.FULL_CODE LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (44) AND
  MR.CAPITOL IN (1)
  AND MR.RIND NOT  IN ('0')
  -------------------------------------------------
  GROUP BY 
  CC.CODUL,
  CC.FULL_CODE,
  CC.DENUMIRE, 
  D.CUIIO,
  R.DENUMIRE,
  MR.RIND,
  MR.DENUMIRE
 
 
 