SELECT
   '2' ORDINE, 
--    A.CUATM_CODUL,
--    A.FULL_CODE,
--    A.DENUMIRE_CUATM,
    A.CUIIO, 
    A.SERV_CODUL,
    A.DENUMIRE,
    
    SUM(A.COL1)  AS COL1,
    SUM(A.COL2)  AS COL2,
    SUM(B.COL1)  AS COL3,
    SUM(B.COL2)  AS COL4,
    SUM(A.COL1) - SUM(B.COL1) AS COL5,
    SUM(A.COL2) - SUM(B.COL2) AS COL6
FROM 

(

SELECT 
--    CC.CODUL  CUATM_CODUL,
--    CC.FULL_CODE,
--    CC.DENUMIRE DENUMIRE_CUATM,
    D.CUIIO AS CUIIO,
    SS.CODUL   SERV_CODUL, 
    SS.DENUMIRE||'-'||MAX(R.DENUMIRE) DENUMIRE,
   (SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA) AND  D.CAPITOL IN (409)  AND D.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END )  
    +
    SUM(CASE WHEN  D.PERIOADA IN(:pPERIOADA) AND   D.CAPITOL IN (410)  AND D.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END ))    AS COL1,
    
    (SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA) AND  D.CAPITOL IN (409)  AND D.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL5 ELSE 0 END )  
    +
    SUM(CASE WHEN  D.PERIOADA IN(:pPERIOADA) AND   D.CAPITOL IN (410)  AND D.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL5 ELSE 0 END ))
    AS COL2  
        
FROM
    
     CIS2.VW_DATA_ALL D 
     
    INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)  
    INNER JOIN CIS2.CL_SERVICII SS ON (rtrim(SS.CODUL, '0')=D.COL1 ) 
 
    
--    INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM=C.CODUL) 
--    INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%' )
           
  WHERE 
  (D.PERIOADA IN(:pPERIOADA)) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (46)
  AND
  D.CAPITOL IN (409,410)
  
  AND SS.CODUL <> '0'
 
  
  
  GROUP BY 
--  CC.CODUL,
--  CC.FULL_CODE,
--  CC.DENUMIRE, 
  D.CUIIO,
  SS.CODUL,
  SS.DENUMIRE
 -- R.DENUMIRE
  
  )  A  LEFT JOIN 
  
  (
  
  SELECT 
--    CC.CODUL  CUATM_CODUL,
--    CC.FULL_CODE,
--    CC.DENUMIRE DENUMIRE_CUATM,
    D.CUIIO AS CUIIO,
    SS.CODUL   SERV_CODUL, 
    SS.DENUMIRE||'-'||MAX(R.DENUMIRE) DENUMIRE,
    
  
   (SUM(CASE WHEN   P.PERIOADA_ANULA = :pPERIOADA AND P.NUM IN (1,2,3,4) AND  D.CAPITOL IN (405)  AND D.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END )  
    +
    SUM(CASE WHEN  P.PERIOADA_ANULA = :pPERIOADA AND P.NUM IN (1,2,3,4)  AND  D.CAPITOL IN (406)  AND D.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END ))
    AS COL1,
    
    
   (SUM(CASE WHEN P.PERIOADA_ANULA = :pPERIOADA AND P.NUM IN (1,2,3,4) AND  D.CAPITOL IN (405)  AND D.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL5 ELSE 0 END )  
    +
    SUM(CASE WHEN  P.PERIOADA_ANULA = :pPERIOADA AND P.NUM IN (1,2,3,4)  AND   D.CAPITOL IN (406)  AND D.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL5 ELSE 0 END ))
    AS COL2  
        
 
   
     
          
    FROM
    
     CIS2.VW_DATA_ALL D 
     
    INNER JOIN CIS2.VW_MD_PERIOADA P ON (D.PERIOADA=P.PERIOADA) 
    
      
    INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)  
    INNER JOIN CIS2.CL_SERVICII SS ON (rtrim(SS.CODUL, '0')=D.COL1 ) 
 
    

           
           
   WHERE        
   
   
  (D.FORM = 44) AND
  (D.FORM_VERS = 1004) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  
  (D.FORM IN (44) AND D.CAPITOL IN (405,406)) AND 
 
  
  
  SS.CODUL <> '0'
 
 AND  P.PERIOADA_ANULA = :pPERIOADA
 
 
  GROUP BY 
--  CC.CODUL,
--  CC.FULL_CODE,
--  CC.DENUMIRE, 
  D.CUIIO,
  SS.CODUL,
  SS.DENUMIRE
 -- R.DENUMIRE
  
  
  ) B ON (B.CUIIO = A.CUIIO  AND B.SERV_CODUL  = A.SERV_CODUL)
  
  
  
  GROUP BY 
--    A.CUATM_CODUL,
--    A.FULL_CODE,
--    A.DENUMIRE_CUATM,
    A.CUIIO, 
    A.SERV_CODUL,
    A.DENUMIRE
    
   ORDER BY
    ORDINE