DECLARE

  CURSOR C IS

SELECT 
    DF.PERIOADA,
    DF.FORM,
    DF.FORM_VERS,
    DF.ID_MDTABLE,
    DF.COD_CUATM,
    DF.NR_SECTIE,
    DF.NUME_SECTIE,
    DF.NR_SECTIE1,
    DF.NUME_SECTIE1,
    DF.NR_SECTIE2,
    DF.NUME_SECTIE2,
    DF.NR_ROW NR_ROW,
    DF.ORDINE,
    DF.DECIMAL_POS,
    DF.NUME_ROW,
    DF.COL1,
    DF.COL2,
    DF.COL3,
    DF.COL4,
    DF.COL5,
    DF.COL6,
    DF.COL7
    
  

   
FROM 
(



SELECT 
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
     CUATM_CODUL AS NR_SECTIE,
     CUATM_CODUL||'-'||DENUMIRE_CUATM AS NUME_SECTIE,
    '0' AS NR_SECTIE1,
    '0' AS NUME_SECTIE1,
    '0' AS NR_SECTIE2,
    '0' AS NUME_SECTIE2,
     CUIIO||'~'|| ROWNUM/0.123 NR_ROW,
     ROWNUM  AS ORDINE,
     '0000000' AS DECIMAL_POS,
     DENUMIRE NUME_ROW,
     TO_NUMBER(SERV_CODUL) COL1,
     COL1 COL2,
     COL2 COL3,
     COL3 COL4,
     COL4 COL5,
     COL5 COL6,
     COL6 COL7
FROM
(

SELECT 
   '1' ORDINE,
    B.CUATM_CODUL,
    B.FULL_CODE,
    B.DENUMIRE_CUATM,
    B.CUIIO, 
    B.SERV_CODUL,
    B.DENUMIRE,
    
    SUM(A.COL1)  AS COL1,
    SUM(A.COL2)  AS COL2,
    SUM(B.COL1)  AS COL3,
    SUM(B.COL2)  AS COL4,
    SUM(A.COL1) - SUM(B.COL1) AS COL5,
    SUM(A.COL2) - SUM(B.COL2) AS COL6

FROM 
(
SELECT 
    CC.CODUL  CUATM_CODUL,
    CC.FULL_CODE,
    CC.DENUMIRE DENUMIRE_CUATM,
    00000000 AS CUIIO,
    '0'   SERV_CODUL, 
    SSS.DENUMIRE DENUMIRE,
   (SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA) AND  D.CAPITOL IN (409)  AND D.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END )  
    +
    SUM(CASE WHEN  D.PERIOADA IN(:pPERIOADA) AND   D.CAPITOL IN (410)  AND D.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END ))    AS COL1,
    
    (SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA) AND  D.CAPITOL IN (409)  AND D.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL5 ELSE 0 END )  
    +
    SUM(CASE WHEN  D.PERIOADA IN(:pPERIOADA) AND   D.CAPITOL IN (410)  AND D.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL5 ELSE 0 END ))
    AS COL2  
        
FROM
    
     CIS2.VW_DATA_ALL D 
     
    INNER JOIN CIS2.VW_CL_SERVICII SS ON (rtrim(SS.CODUL, '0')=D.COL1 ) 
    INNER JOIN   CIS2.VW_CL_SERVICII SSS ON (SS.FULL_CODE LIKE '%' ||SSS.CODUL||';%' )
    
    INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM=C.CODUL) 
    INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%' )
           
  WHERE 
  (D.PERIOADA IN(:pPERIOADA)) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (46)
  AND
  D.CAPITOL IN (409,410)
 AND  SSS.CODUL IN ('0000000')
 AND CC.CODUL IN ('0000000')
  GROUP BY 
   CC.CODUL,
  CC.FULL_CODE,
  CC.DENUMIRE, 
  SSS.CODUL,
  SSS.DENUMIRE
  ) A INNER JOIN (
  
  SELECT 
    CC.CODUL  CUATM_CODUL,
    CC.FULL_CODE,
    CC.DENUMIRE DENUMIRE_CUATM,
    00000000 AS CUIIO,
    '0'   SERV_CODUL, 
    SSS.DENUMIRE DENUMIRE,
    
  
   (SUM(CASE WHEN   P.PERIOADA_ANULA = :pPERIOADA AND P.NUM IN (1,2,3,4) AND  D.CAPITOL IN (405)  AND D.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END )  
    +
    SUM(CASE WHEN  P.PERIOADA_ANULA = :pPERIOADA AND P.NUM IN (1,2,3,4)  AND  D.CAPITOL IN (406)  AND D.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END ))
    AS COL1,
    
    
   (SUM(CASE WHEN P.PERIOADA_ANULA = :pPERIOADA AND P.NUM IN (1,2,3,4) AND  D.CAPITOL IN (405)  AND D.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL5 ELSE 0 END )  
    +
    SUM(CASE WHEN  P.PERIOADA_ANULA = :pPERIOADA AND P.NUM IN (1,2,3,4)  AND   D.CAPITOL IN (406)  AND D.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL5 ELSE 0 END ))
    AS COL2  
        
 
   
     
          
    FROM
    
     CIS2.VW_DATA_ALL D 
     
    INNER JOIN CIS2.VW_MD_PERIOADA P ON (D.PERIOADA=P.PERIOADA) 
    INNER JOIN CIS2.VW_CL_SERVICII SS ON (rtrim(SS.CODUL, '0')=D.COL1 ) 
    
    INNER JOIN   CIS2.VW_CL_SERVICII SSS ON (SS.FULL_CODE LIKE '%' ||SSS.CODUL||';%' )
   

            INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM=C.CODUL) 
            
            INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%' )
           
           
   WHERE        
   
  (D.FORM = 44) AND
  (D.FORM_VERS = 1004) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  
  (D.FORM IN (44) AND D.CAPITOL IN (405,406)) AND 
 
  P.PERIOADA_ANULA = :pPERIOADA
 
   AND SSS.CODUL IN ('0000000')
   AND CC.CODUL IN ('0000000')

  GROUP BY  
  SSS.DENUMIRE,
  CC.CODUL,
  CC.FULL_CODE,
  CC.DENUMIRE  
 
  
  )  B ON (B.CUATM_CODUL = B.CUATM_CODUL)
  
  
  
  GROUP BY 
  
     B.CUATM_CODUL,
     B.FULL_CODE,
     B.DENUMIRE_CUATM,
     B.CUIIO,
     B.SERV_CODUL,
     B.DENUMIRE
     
     
     
     
     UNION 
     
     
     SELECT
    '2' ORDINE, 
    B.CUATM_CODUL,
    B.FULL_CODE,
    B.DENUMIRE_CUATM,
    B.CUIIO, 
    B.SERV_CODUL,
    B.DENUMIRE,
    
    SUM(B.COL1)  AS COL1,
    SUM(B.COL2)  AS COL2,
    SUM(A.COL1)  AS COL3,
    SUM(A.COL2)  AS COL4,
    SUM(B.COL1) - SUM(A.COL1) AS COL5,
    SUM(B.COL2) - SUM(A.COL2) AS COL6
FROM 

(

SELECT 
    CC.CODUL  CUATM_CODUL,
    CC.FULL_CODE,
    CC.DENUMIRE DENUMIRE_CUATM,
    D.CUIIO AS CUIIO,
    SS.CODUL   SERV_CODUL, 
    SS.DENUMIRE||'-'||MAX(R.DENUMIRE) DENUMIRE,
   (SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA) AND  D.CAPITOL IN (409)  AND D.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END )  
    +
    SUM(CASE WHEN  D.PERIOADA IN(:pPERIOADA) AND   D.CAPITOL IN (410)  AND D.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END ))    AS COL1,
    
    (SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA) AND  D.CAPITOL IN (409)  AND D.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL5 ELSE 0 END )  
    +
    SUM(CASE WHEN  D.PERIOADA IN(:pPERIOADA) AND   D.CAPITOL IN (410)  AND D.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL5 ELSE 0 END ))
    AS COL2  
        
FROM
    
     CIS2.VW_DATA_ALL D 
     
    INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)  
    INNER JOIN CIS2.CL_SERVICII SS ON (rtrim(SS.CODUL, '0')=D.COL1 ) 
 
    
    INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM=C.CODUL) 
    INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%' )
           
  WHERE 
  (D.PERIOADA IN(:pPERIOADA)) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (46)
  AND
  D.CAPITOL IN (409,410)
  
  AND SS.CODUL <> '0'
 
  
  
  GROUP BY 
  CC.CODUL,
  CC.FULL_CODE,
  CC.DENUMIRE, 
  D.CUIIO,
  SS.CODUL,
  SS.DENUMIRE
 -- R.DENUMIRE
  
  )  A  RIGHT JOIN 
  
  (
  
  SELECT 
   CC.CODUL  CUATM_CODUL,
    CC.FULL_CODE,
    CC.DENUMIRE DENUMIRE_CUATM,
    D.CUIIO AS CUIIO,
    SS.CODUL   SERV_CODUL, 
    SS.DENUMIRE||'-'||MAX(R.DENUMIRE) DENUMIRE,
    
  
   (SUM(CASE WHEN   P.PERIOADA_ANULA = :pPERIOADA AND P.NUM IN (1,2,3,4) AND  D.CAPITOL IN (405)  AND D.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END )  
    +
    SUM(CASE WHEN  P.PERIOADA_ANULA = :pPERIOADA AND P.NUM IN (1,2,3,4)  AND  D.CAPITOL IN (406)  AND D.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END ))
    AS COL1,
    
    
   (SUM(CASE WHEN P.PERIOADA_ANULA = :pPERIOADA AND P.NUM IN (1,2,3,4) AND  D.CAPITOL IN (405)  AND D.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL5 ELSE 0 END )  
    +
    SUM(CASE WHEN  P.PERIOADA_ANULA = :pPERIOADA AND P.NUM IN (1,2,3,4)  AND   D.CAPITOL IN (406)  AND D.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL5 ELSE 0 END ))
    AS COL2  
        
 
   
     
          
    FROM
    
     CIS2.VW_DATA_ALL D 
     
    INNER JOIN CIS2.VW_MD_PERIOADA P ON (D.PERIOADA=P.PERIOADA) 
    
      
    INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)  
    INNER JOIN CIS2.CL_SERVICII SS ON (rtrim(SS.CODUL, '0')=D.COL1 ) 
 
    
    INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM=C.CODUL) 
    INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%' )
           
           
   WHERE        
   
   
  (D.FORM = 44) AND
  (D.FORM_VERS = 1004) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  
  (D.FORM IN (44) AND D.CAPITOL IN (405,406)) AND 
 
  
  
  SS.CODUL <> '0'
 
 AND  P.PERIOADA_ANULA = :pPERIOADA
 
 
  GROUP BY 
  CC.CODUL,
  CC.FULL_CODE,
  CC.DENUMIRE, 
  D.CUIIO,
  SS.CODUL,
  SS.DENUMIRE
 -- R.DENUMIRE
  
  
  ) B ON (B.CUIIO = A.CUIIO AND B.CUATM_CODUL  = A.CUATM_CODUL AND B.SERV_CODUL  = A.SERV_CODUL)
  
  
  
  GROUP BY 
    B.CUATM_CODUL,
    B.FULL_CODE,
    B.DENUMIRE_CUATM,
    B.CUIIO, 
    B.SERV_CODUL,
    B.DENUMIRE
    
   ORDER BY
    ORDINE
    
    )
WHERE 
   
   CUATM_CODUL  IN (
   
   '0000000',
   --'0100000',
    '0110000',
    '0120000',
    '0130000',
    '0140000',
    '0150000',
    --'1111111'
    '3000000',
    '1400000',
    '3400000',
    '3600000',
    '4100000',
    '4300000',
    '4500000',
    '4800000',
    '6200000',
    '7100000',
    '7400000',
    '7800000',
--2222222
    '1000000',
    '2500000',
    '3100000',
    '3800000',
    '5300000',
    '5500000',
    '6000000',
    '6400000',
    '6700000',
    '8000000',
    '8300000',
    '8900000',
    '9200000',
    --3333333
    '1200000',
    '1700000',
    '2100000',
    '2700000',
    '2900000',
    '5700000',
    '8500000',
    '8700000',
    
    '9200000',
    '9601000',
    '9602000',
    '9603000'
)


  AND 
    (
    COL5 IS NOT NULL
    OR 
    COL6 IS NOT NULL
    )
    
    
    AND 
    
    (
    COL5 <> 0
    OR 
    COL6 <> 0
    )

        ORDER BY 
        
        FULL_CODE,
        ORDINE
        
        
        
        
        
        
        ) DF
  
  ;
   
    BEGIN

  FOR CR IN C
  
  LOOP
    INSERT INTO  -- USER_BANCU.TABLE_OUT_TEST 
    
    CIS2.TABLE_OUT
    (
      PERIOADA,
      FORM,
      FORM_VERS,

      ID_MDTABLE,
      COD_CUATM,
      NR_SECTIE,
      NUME_SECTIE,
      NR_SECTIE1,
      NUME_SECTIE1,
      NR_SECTIE2,
      NUME_SECTIE2,
      NR_ROW,
      ORDINE,
      DECIMAL_POS,
      NUME_ROW,
       
      COL1, COL2, COL3,  COL4, COL5, COL6, COL7
    )
    VALUES
    (
      CR.PERIOADA,
      CR.FORM,
      CR.FORM_VERS,
      CR.ID_MDTABLE,
      CR.COD_CUATM,
      CR.NR_SECTIE,
      CR.NUME_SECTIE,
      CR.NR_SECTIE1,
      CR.NUME_SECTIE1,
      CR.NR_SECTIE2,
      CR.NUME_SECTIE2,
      CR.NR_ROW,
      CR.ORDINE,
      CR.DECIMAL_POS,
      CR.NUME_ROW,
       
      CR.COL1, CR.COL2, CR.COL3, CR.COL4, CR.COL5, CR.COL6, CR.COL7
    );
  END LOOP;
--END;