


DECLARE

  CURSOR C IS

SELECT 
    DF.PERIOADA,
    DF.FORM,
    DF.FORM_VERS,
    DF.ID_MDTABLE,
    DF.COD_CUATM,
    DF.NR_SECTIE,
    DF.NUME_SECTIE,
    DF.NR_SECTIE1,
    DF.NUME_SECTIE1,
    DF.NR_SECTIE2,
    DF.NUME_SECTIE2,
    DF.NR_ROW NR_ROW,
    DF.ORDINE,
    DF.DECIMAL_POS,
    DF.NUME_ROW,
    DF.COL1,
    DF.COL2,
    DF.COL3,
    DF.COL4
     
FROM 
(

 SELECT   
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
    '0' AS NR_SECTIE,
    '0' AS NUME_SECTIE,
    '0' AS NR_SECTIE1,
    '0' AS NUME_SECTIE1,
    '0' AS NR_SECTIE2,
    '0' AS NUME_SECTIE2,
     ROWNUM NR_ROW,
     AA.ORDINE  AS ORDINE,
    '1111' AS DECIMAL_POS,
     AA.NUME_ROW AS NUME_ROW,
     ROUND(AA.COL1 / 1000,1)   AS COL1,
     ROUND(AA.COL2 / 1000,1)   AS COL2,
     ROUND(AA.COL3 / 1000,1)   AS COL3,
     ROUND(AA.COL4 / 1000,1)   AS COL4

     FROM
     (

SELECT 
     CD.NR_ROW   AS NR_ROW,
     CD.NR_ROW   AS ORDINE,
     CD.NUME_ROW AS NUME_ROW,
    SUM(CASE WHEN  VC.FUlL_CODE LIKE '%'||CD.CUATM||';%' AND  D.CAPITOL IN (405)  AND D.RIND IN ('1') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END )  AS COL1,
    SUM(CASE WHEN  VC.FUlL_CODE LIKE '%'||CD.CUATM||';%' AND  D.CAPITOL IN (405)  AND D.RIND IN ('1') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END )  AS COL2,
    SUM(CASE WHEN  VC.FUlL_CODE LIKE '%'||CD.CUATM||';%' AND  D.CAPITOL IN (407)  AND D.RIND IN ('1') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END )  AS COL3,
    SUM(CASE WHEN  VC.FUlL_CODE LIKE '%'||CD.CUATM||';%' AND  D.CAPITOL IN (407)  AND D.RIND IN ('1') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END )  AS COL4
 
 FROM
    
     CIS2.VW_DATA_ALL D
      INNER JOIN CIS2.VW_CL_CUATM VC ON (VC.CODUL=D.CUATM)
      CROSS JOIN  
     
(
   SELECT DENUMIRE AS NUME_ROW, RIND AS NR_ROW,RINDOUT AS CUATM
        
        FROM CIS2.MD_RIND_OUT
        WHERE 
        ID_MDTABLE = 8096
   )
   CD
      
      

WHERE 
  (D.PERIOADA =:pPERIOADA) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
   (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (44) AND D.CAPITOL IN (405,407,406,408)
  
  GROUP BY 
    CD.NR_ROW,
    CD.NUME_ROW
      
    ORDER BY 
    CD.NR_ROW
  
  ) AA 
  
   ORDER BY AA.ORDINE
    
    
    ) DF

;
   
    BEGIN

  FOR CR IN C
  
  LOOP
    INSERT INTO --  USER_BANCU.TABLE_OUT_TEST 
    
     CIS2.TABLE_OUT
    (
      PERIOADA,
      FORM,
      FORM_VERS,
      ID_MDTABLE,
      COD_CUATM,
      NR_SECTIE,
      NUME_SECTIE,
      NR_SECTIE1,
      NUME_SECTIE1,
      NR_SECTIE2,
      NUME_SECTIE2,
      NR_ROW,
      ORDINE,
      DECIMAL_POS,
      NUME_ROW,
       
      COL1, COL2, COL3,  COL4
    )
    VALUES
    (
      CR.PERIOADA,
      CR.FORM,
      CR.FORM_VERS,
      CR.ID_MDTABLE,
      CR.COD_CUATM,
      CR.NR_SECTIE,
      CR.NUME_SECTIE,
      CR.NR_SECTIE1,
      CR.NUME_SECTIE1,
      CR.NR_SECTIE2,
      CR.NUME_SECTIE2,
      CR.NR_ROW,
      CR.ORDINE,
      CR.DECIMAL_POS,
      CR.NUME_ROW,
       
      CR.COL1, CR.COL2, CR.COL3, CR.COL4
    );
  END LOOP;
END;



  
  
  
  