



SELECT
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
    '0' AS NR_SECTIE,
    '0' AS NUME_SECTIE,
    '0' AS NR_SECTIE1,
    '0' AS NUME_SECTIE1,
    '0' AS NR_SECTIE2,
   '0' AS NUME_SECTIE2,
    CASE WHEN SUBSTR(NR_ROW,1,1) = '~' THEN '0'||NR_ROW ELSE NR_ROW END NR_ROW,   
   ROWNUM AS ORDINE,
  '1111' AS DECIMAL_POS,
   NUME_ROW,
   ROUND(COL1,1) COL1,
   ROUND(COL2,1) COL2,
  ROUND(COL3,1) COL3,
  ROUND(COL4,1) COL4
FROM
(
SELECT
   CASE WHEN REPLACE (CODUL_SERV,'0')||'~'||ROWNUM/0.123 IS NULL THEN '0' ELSE REPLACE (CODUL_SERV,'0')||'~'||ROWNUM END  AS NR_ROW,
   ORDINE, 
   DENUMIRE  NUME_ROW,
  COL1,
  COL2,
  COL3,
  COL4
FROM
(

SELECT 
    1 ORDINE,
     SSS.DENUMIRE,
     SSS.CODUL    CODUL_SERV,
     SSS.FULL_CODE,
     
   ROUND((SUM(CASE WHEN  MR.CAPITOL IN (405)  AND MR.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END )  
    +
    SUM(CASE WHEN  MR.CAPITOL IN (406)  AND MR.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END ))/1000,1)
    AS COL1,
  
     ROUND((SUM(CASE WHEN  MR.CAPITOL IN (405)  AND MR.RIND NOT IN ('1','2','-') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END )  
    +
    SUM(CASE WHEN  MR.CAPITOL IN (406)  AND MR.RIND NOT IN ('1','-') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END ))/1000,1)
    AS COL2,
    
     ROUND((SUM(CASE WHEN  MR.CAPITOL IN (407)  AND MR.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END )  
    +
    SUM(CASE WHEN  MR.CAPITOL IN (408)  AND MR.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END ))/1000,1)
    AS COL3,
    
   ROUND((SUM(CASE WHEN  MR.CAPITOL IN (407)  AND MR.RIND NOT IN ('1','2','-') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END )  
    +
    SUM(CASE WHEN  MR.CAPITOL IN (408)  AND MR.RIND NOT IN ('1','-') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END ))/1000,1)
    AS COL4
     
      
      FROM CIS2.DATA_ALL D 
        
        INNER JOIN CIS2.RENIM R ON R.CUIIO=D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS
        INNER JOIN CIS2.VW_CL_CUATM C ON R.CUATM = C.CODUL
        INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD
        INNER JOIN   CIS2.VW_CL_SERVICII SS ON ((RTRIM(SS.CODUL,'0') )=D.COL1)     
        INNER JOIN   CIS2.VW_CL_SERVICII SSS ON (SS.FULL_CODE LIKE '%' ||SSS.CODUL||';%' )  
      
   
   WHERE 
  (D.PERIOADA =:pPERIOADA) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (C.FULL_CODE LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (44)
  AND
  MR.CAPITOL IN (405,406,407,408)
  
      GROUP BY
 
       SSS.DENUMIRE,
       SSS.CODUL,
       SSS.FULL_CODE
      
 UNION
 
 SELECT
  ORDINE_TARA,
  DENUMIRE,
  CODUL_SERV,
  FULL_CODE,
  COL1,
  COL2,
  COL3,
  COL4
FROM(
SELECT 
     2 ORDINE,
     TTT.ORDINE AS ORDINE_TARA,
     TTT.DENUMIRE,
     SSS.CODUL CODUL_SERV,
     SSS.FULL_CODE,
     
   ROUND((SUM(CASE WHEN  MR.CAPITOL IN (405)  AND MR.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END )  
    +
    SUM(CASE WHEN  MR.CAPITOL IN (406)  AND MR.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END ))/1000,1)
    AS COL1,
  
     ROUND((SUM(CASE WHEN  MR.CAPITOL IN (405)  AND MR.RIND NOT IN ('1','2','-') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END )  
    +
    SUM(CASE WHEN  MR.CAPITOL IN (406)  AND MR.RIND NOT IN ('1','-') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END ))/1000,1)
    AS COL2,
    
     ROUND((SUM(CASE WHEN  MR.CAPITOL IN (407)  AND MR.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END )  
    +
    SUM(CASE WHEN  MR.CAPITOL IN (408)  AND MR.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END ))/1000,1)
    AS COL3,
    
   ROUND((SUM(CASE WHEN  MR.CAPITOL IN (407)  AND MR.RIND NOT IN ('1','2','-') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END )  
    +
    SUM(CASE WHEN  MR.CAPITOL IN (408)  AND MR.RIND NOT IN ('1','-') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END ))/1000,1)
    AS COL4
     
      
      FROM CIS2.DATA_ALL D 
       
       INNER JOIN   CIS2.RENIM  R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS) 
       INNER JOIN   CIS2.VW_CL_TARI TT  ON (TT.CODUL=D.COL3)
       INNER JOIN   CIS2.VW_CL_TARI TTT ON (TT.FULL_CODE LIKE '%' ||TTT.CODUL||';%' )   
       INNER JOIN   CIS2.VW_CL_CUATM C ON R.CUATM = C.CODUL
       INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD
      
       INNER JOIN CIS2.VW_CL_SERVICII SS ON (rtrim(SS.CODUL, '0')=D.COL1 ) 
       INNER JOIN   CIS2.VW_CL_SERVICII SSS ON (SS.FULL_CODE LIKE '%' ||SSS.CODUL||';%' )   
        
   WHERE 
  (D.PERIOADA =:pPERIOADA) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (C.FULL_CODE LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (44)
  AND
  MR.CAPITOL IN (405,406,407,408)
  AND TTT.CODUL NOT IN ('000')
  AND SSS.CODUL NOT IN ('0000000')
  
      GROUP BY
      SSS.CODUL,
      TTT.CODUL,
      TTT.FULL_CODE,
      SSS.FULL_CODE,
      TTT.ORDINE,
      TTT.DENUMIRE
      
    ORDER BY
    TTT.ORDINE 
)
)
 ORDER BY
  CODUL_SERV,
  ORDINE
)