SELECT 
     --SS.CODUL   CODUL_SERV,
     
  --   TTT.CODUL  CODUL_TARI,
 --    TTT.FULL_CODE,
     1 ORDINE,
     SSS.DENUMIRE,
     SSS.CODUL    CODUL_SERV,
     SSS.FULL_CODE,
     
    ROUND((SUM(CASE WHEN  D.CAPITOL IN (409)  AND D.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END )  
    +
    SUM(CASE WHEN  D.CAPITOL IN (410)  AND D.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END ))/1000,1)
    AS COL1,
  
     ROUND((SUM(CASE WHEN  D.CAPITOL IN (409)  AND D.RIND NOT IN ('1','2','-') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END )  
    +
    SUM(CASE WHEN  D.CAPITOL IN (410)  AND D.RIND NOT IN ('1','-') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END ))/1000,1)
    AS COL2,
    
     ROUND((SUM(CASE WHEN  D.CAPITOL IN (411)  AND D.RIND NOT IN ('1','2','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END )  
    +
    SUM(CASE WHEN  D.CAPITOL IN (403)  AND D.RIND NOT IN ('1','-') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0 END ))/1000,1)
    AS COL3,
    
   ROUND((SUM(CASE WHEN  D.CAPITOL IN (411)  AND D.RIND NOT IN ('1','2','-') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END )  
    +
    SUM(CASE WHEN  D.CAPITOL IN (403)  AND D.RIND NOT IN ('1','-') AND D.COL5 IS NOT NULL THEN D.COL5 ELSE 0 END ))/1000,1)
    AS COL4
     
      
      FROM CIS2.VW_DATA_ALL D 
       
       INNER JOIN CIS2.VW_CL_SERVICII SS ON (rtrim(SS.CODUL, '0')=D.COL1 ) 
       INNER JOIN   CIS2.VW_CL_SERVICII SSS ON (SS.FULL_CODE LIKE '%' ||SSS.CODUL||';%' )   
 
   
   -------------------------------------------------------------------------------
       
       
   WHERE 
  (D.PERIOADA =:pPERIOADA) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (46)
  AND
 -- D.CAPITOL IN (383,385,384,386)
  D.CAPITOL IN (409,410,411,403)

--  AND TTT.CODUL NOT IN ('000')
  
  --AND D.CUIIO IN (227548)
  
      GROUP BY
      --SS.CODUL, 
       SSS.DENUMIRE,
     SSS.CODUL,
      --TTT.CODUL,
      --(REPLACE (SS.CODUL,'0')),
      --TTT.FULL_CODE,
      SSS.FULL_CODE
      
      ORDER BY 
      SSS.FULL_CODE