SELECT 

    D.CUIIO AS CUIIO,
    SS.CODUL   SERV_CODUL, 
    SS.DENUMIRE||'-'||R.DENUMIRE DENUMIRE,
    
  
   (SUM(CASE WHEN   P.PERIOADA_ANULA = :pPERIOADA AND P.NUM IN (1,2,3,4) AND  D.CAPITOL IN (405)  AND D.RIND NOT IN ('1','2','-')  THEN NVAL(D.COL4) ELSE 0 END )  
    +
    SUM(CASE WHEN  P.PERIOADA_ANULA = :pPERIOADA AND P.NUM IN (1,2,3,4)  AND  D.CAPITOL IN (406)  AND D.RIND NOT IN ('1','-') THEN NVAL(D.COL4) ELSE 0 END ))
    AS COL1,
    
    
   (SUM(CASE WHEN P.PERIOADA_ANULA = :pPERIOADA AND P.NUM IN (1,2,3,4) AND  D.CAPITOL IN (405)  AND D.RIND NOT IN ('1','2','-')  THEN NVAL(D.COL5) ELSE 0 END )  
    +
    SUM(CASE WHEN  P.PERIOADA_ANULA = :pPERIOADA AND P.NUM IN (1,2,3,4)  AND   D.CAPITOL IN (406)  AND D.RIND NOT IN ('1','-')   THEN NVAL(D.COL5) ELSE 0 END ))
    AS COL2  
        
 
   
     
          
    FROM
    
     CIS2.VW_DATA_ALL D 
     
    INNER JOIN CIS2.VW_MD_PERIOADA P ON (D.PERIOADA=P.PERIOADA) 
    
      
    INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)  
    INNER JOIN CIS2.CL_SERVICII SS ON (rtrim(SS.CODUL, '0')=D.COL1 ) 
 

           
           
   WHERE        
   
   
  (D.FORM = 44) AND
  (D.FORM_VERS = 1004) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  
  (D.FORM IN (44) AND D.CAPITOL IN (405,406)) AND 
 
  
  
  SS.CODUL <> '0'
 
 AND  P.PERIOADA_ANULA = :pPERIOADA
 
  AND D.CUIIO IN (41066944)
 
 
  GROUP BY 

  D.CUIIO,
  R.DENUMIRE,
  SS.CODUL,
  SS.DENUMIRE