SELECT DISTINCT
                   SUM(CASE WHEN MR.RIND IN ('04') THEN   D.COL1 ELSE NULL END)  AS COL1,
                   SUM(CASE WHEN MR.RIND IN ('05') THEN   D.COL1 ELSE NULL END)  AS COL2,
                   SUM(CASE WHEN MR.RIND IN ('06') THEN   D.COL1 ELSE NULL END)  AS COL3,
                   SUM(CASE WHEN MR.RIND IN ('03') THEN   D.COL1 ELSE NULL END)  AS COL4  
  
FROM 
  CIS.DATA_ALL D
     INNER JOIN CIS.MD_PERIOADA MP ON (MP.PERIOADA = D.PERIOADA)   
     INNER JOIN CIS.MD_RIND MR ON (MR.ID_MD=D.ID_MD)
     INNER JOIN CIS.RENIM RR ON (RR.CUIIO = D.CUIIO AND RR.CUIIO_VERS = D.CUIIO_VERS)
     
     
  INNER JOIN (
  
  SELECT DISTINCT
  D.ANUL,
  SUM(CASE 
  WHEN D.NUM IN 1 THEN DD.COL1
  WHEN D.NUM IN 2 THEN DD.COL2
  WHEN D.NUM IN 3 THEN DD.COL3
  WHEN D.NUM IN 4 THEN DD.COL4 END) AS JIP
  
  
  
FROM 
  CIS.MD_PERIOADA D
  INNER JOIN (
  
  SELECT DISTINCT
  ANUL,
  CASE WHEN NUM IN 3  THEN PERIOADA ELSE 0 END AS COL1,
  CASE WHEN NUM IN 6  THEN PERIOADA ELSE 0 END AS COL2,
  CASE WHEN NUM IN 9  THEN PERIOADA ELSE 0 END AS COL3,
  CASE WHEN NUM IN 12 THEN PERIOADA ELSE 0 END AS COL4
  
FROM 
  CIS.MD_PERIOADA
  
WHERE TIP_PERIOADA = 4


  ) DD ON DD.ANUL = D.ANUL
  
WHERE
  PERIOADA = :pPERIOADA

GROUP BY
  D.ANUL
  
  
) P ON P.ANUL = MP.ANUL
  
WHERE 
  D.PERIOADA = P.JIP AND
  MR.CAPITOL = 37 AND
  D.FORM = 100 AND 
  MR.RIND IN ('04','05','06','03') 
  AND  D.CUIIO = 4 