--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
-- COL1, COL2, COL3,COL4,COL5,COL6,COL7
--)


SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,    
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   R.RIND AS NR_ROW,
   R.ORDINE AS ORDINE,
  '0000000' AS DECIMAL_POS,
   RR.DENUMIRE AS NUME_ROW,
   
   
 (SUM(CASE WHEN D.PERIOADA IN :pPERIOADA AND  R.RIND =  D.RIND THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA AND  R.RIND =  D.RIND THEN D.COL2 ELSE 0 END))  AS COL1,
  
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA AND  R.RIND =  D.RIND THEN D.COL1 ELSE 0 END) AS COL2,
  
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA AND  R.RIND =  D.RIND THEN D.COL2 ELSE 0 END) AS COL3,
  
 (SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-4 AND  R.RIND =  D.RIND THEN D.COL1 ELSE 0 END)+
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-4 AND  R.RIND =  D.RIND THEN D.COL2 ELSE 0 END))  AS COL4,
  
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-4 AND  R.RIND =  D.RIND THEN D.COL1 ELSE 0 END) AS COL5,
  
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-4 AND  R.RIND =  D.RIND THEN D.COL2 ELSE 0 END) AS COL6,
  
  ROUND((((SUM(CASE WHEN D.PERIOADA IN :pPERIOADA AND  R.RIND =  D.RIND THEN D.COL1 ELSE 0 END)+
           SUM(CASE WHEN D.PERIOADA IN :pPERIOADA AND  R.RIND =  D.RIND THEN D.COL2 ELSE 0 END))/
  
 CIS.NOZERO(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-4 AND  R.RIND =  D.RIND THEN D.COL1 ELSE 0 END)+
             SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-4 AND  R.RIND =  D.RIND THEN D.COL2 ELSE 0 END)))/
                (P.COL1))*100,1) AS COL7

FROM 
  CIS.VW_DATA_ALL D
  CROSS JOIN (
  
  SELECT DISTINCT
 COL1
  
FROM 
  CIS.VW_DATA_ALL D
  INNER JOIN (SELECT DISTINCT
  D.ANUL,
  SUM(CASE 
  WHEN D.NUM IN 1 THEN DD.COL1
  WHEN D.NUM IN 2 THEN DD.COL2
  WHEN D.NUM IN 3 THEN DD.COL3
  WHEN D.NUM IN 4 THEN DD.COL4 END) AS JIP
  
  
  
FROM 
  CIS.MD_PERIOADA D
  INNER JOIN (
  
  SELECT DISTINCT
  ANUL,
  CASE WHEN NUM IN 3  THEN PERIOADA ELSE 0 END AS COL1,
  CASE WHEN NUM IN 6  THEN PERIOADA ELSE 0 END AS COL2,
  CASE WHEN NUM IN 9  THEN PERIOADA ELSE 0 END AS COL3,
  CASE WHEN NUM IN 12 THEN PERIOADA ELSE 0 END AS COL4
  
FROM 
  CIS.MD_PERIOADA
  
WHERE TIP_PERIOADA = 4


  ) DD ON DD.ANUL = D.ANUL
  
WHERE
  PERIOADA = :pPERIOADA

GROUP BY
  D.ANUL
) P ON P.ANUL = D.ANUL
  
WHERE 
  D.PERIOADA = P.JIP AND
  D.CAPITOL = 37 AND
  D.RIND IN '04' ) P


CROSS JOIN (
  
   SELECT     
      RIND,
      MAX(RIND_VERS) AS RIND_VERS,
      ORDINE  
  
    FROM 
     CIS.MD_RIND
  
   WHERE
     CAPITOL = 31 AND    
      RIND NOT IN ('410','420','430','440','441','450','-') AND
      RIND_VERS >=  1040 AND
      STATUT = 1  
      GROUP BY RIND, ORDINE 
      ORDER BY ORDINE     
    ) R
    INNER JOIN CIS.MD_RIND RR ON R.RIND=RR.RIND AND R.RIND_VERS=RR.RIND_VERS
     
     
WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  D.PERIOADA IN (:pPERIOADA, :pPERIOADA-4) AND
  D.FORM = 6 AND
  D.CAPITOL = 31
  
GROUP BY
  RR.DENUMIRE,
  R.RIND,
  R.ORDINE,
  P.COL1
  
ORDER BY
  R.ORDINE