SELECT 
             R.RIND AS NR_ROW,
             R.ORDINE AS ORDINE,
         
             R.DENUMIRE AS NUME_ROW,

SUM(CASE WHEN D.PERIOADA IN :pPERIOADA AND  R.RIND =  D.RIND THEN NVAL(D.COL1) + NVAL(D.COL2) ELSE 0 END) AS COL1,
SUM(CASE WHEN D.PERIOADA IN :pPERIOADA AND  R.RIND =  D.RIND THEN D.COL1 ELSE 0 END) AS COL2,
SUM(CASE WHEN D.PERIOADA IN :pPERIOADA AND  R.RIND =  D.RIND THEN D.COL2 ELSE 0 END) AS COL3,
SUM(CASE WHEN D.PERIOADA IN :pPERIOADA - 4 AND  R.RIND =  D.RIND THEN NVAL(D.COL1) + NVAL(D.COL2) ELSE 0 END) AS COL4,



  
SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-4 AND  R.RIND =  D.RIND THEN D.COL1 ELSE 0 END) AS COL5,
  
SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-4 AND  R.RIND =  D.RIND THEN D.COL2 ELSE 0 END) AS COL6,


ROUND(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA AND  R.RIND =  D.RIND THEN NVAL(D.COL1) + NVAL(D.COL2) ELSE 0 END)  /
 CIS.NOZERO(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA - 4 AND  R.RIND =  D.RIND THEN NVAL(D.COL1) + NVAL(D.COL2) ELSE 0 END)),1)  AS COL7
  

             
             

FROM 
  CIS.VW_DATA_ALL D
  CROSS JOIN (
  SELECT   
    
     DENUMIRE,
     RIND,
     ORDINE
    FROM 
     CIS.MD_RIND
  
   WHERE
     CAPITOL = 31 AND    
      RIND NOT IN ('410','420','430','440','441','450','-') AND
      RIND_VERS =  1040 AND
      STATUT = '1'  
    
      ) R     
      
           
WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  D.PERIOADA IN (:pPERIOADA, :pPERIOADA-4) AND
  D.FORM = 6 AND
  D.CAPITOL = 31
  GROUP BY
     R.DENUMIRE,
           R.RIND,
           R.ORDINE