-- INSERT INTO    CIS2.TABLE_OUT
--    (
--      
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
--  COL1,COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11
--  
--    )
--

SELECT 


  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  
   VB.CODUL||'~'||ROWNUM  AS NR_ROW,
   ROWNUM AS ORDINE,
  '00000000000' AS DECIMAL_POS, 
   VB.DENUMIRE AS NUME_ROW,
   CASE WHEN  COL1 = 0 THEN NULL ELSE COL1 END   AS COL1,
   CASE WHEN  COL2 = 0 THEN NULL ELSE COL2 END   AS COL2,
   CASE WHEN  COL3 = 0 THEN NULL ELSE COL3 END   AS COL3,
   CASE WHEN  COL4 = 0 THEN NULL ELSE COL4 END   AS COL4,
   CASE WHEN  COL5 = 0 THEN NULL ELSE COL5 END   AS COL5,
   CASE WHEN  COL6 = 0 THEN NULL ELSE COL6 END   AS COL6,
   CASE WHEN  COL7 = 0 THEN NULL ELSE COL7 END   AS COL7,
   CASE WHEN  COL8 = 0 THEN NULL ELSE COL8 END   AS COL8,
   CASE WHEN  COL9 = 0 THEN NULL ELSE COL9 END   AS COL9,
   CASE WHEN  COL10 = 0 THEN NULL ELSE COL10 END   AS COL10,
   CASE WHEN  COL11 = 0 THEN NULL ELSE COL11 END   AS COL11
   FROM

(
SELECT
   1 ORDINE,
  '1' CODUL,
   'TOTAL PE FORME DE PROPRIETATE' DENUMIRE,
   NULL  AS COL1,
   NULL  AS COL2,
   NULL  AS COL3,
   NULL  AS COL4,
   NULL  AS COL5,
   NULL  AS COL6,
   NULL  AS COL7,
   NULL  AS COL8,
   NULL  AS COL9,
   NULL  AS COL10,
   NULL  AS COL11
FROM   DUAL

UNION ALL  

  SELECT *

FROM(
 SELECT
  2 ORDINE,
   MR.RIND AS NR_ROW,
   MR.DENUMIRE NUME_ROW,
   SUM(CIS2.NVAL(D.COL1)) AS COL1,
   SUM(CIS2.NVAL(D.COL2)) AS COL2,
   SUM(CIS2.NVAL(D.COL3)) AS COL3,
   SUM(CIS2.NVAL(D.COL4)) AS COL4,
   SUM(CIS2.NVAL(D.COL5)) AS COL5,
   SUM(CIS2.NVAL(D.COL6)) AS COL6,
   SUM(CIS2.NVAL(D.COL7)) AS COL7,
   SUM(CIS2.NVAL(D.COL8)) AS COL8,
   SUM(CIS2.NVAL(D.COL9)) AS COL9,
   SUM(CIS2.NVAL(D.COL10)) AS COL10,
   SUM(CIS2.NVAL(D.COL11)) AS COL11
     
   
FROM 
  VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
  INNER JOIN CIS2.VW_CL_CFP C ON (C.CODUL = D.CFP)
  INNER JOIN CIS2.VW_CL_CFP CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
  
  RIGHT JOIN MD_RIND MR ON (D.FORM=MR.FORM AND D.ID_MD=MR.ID_MD AND D.CAPITOL=MR.CAPITOL AND 
  
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')

  
WHERE
  MR.FORM IN (55)                 AND 
  MR.CAPITOL IN (1080) AND 
  CC.CODUL IN ('00')
GROUP BY
  MR.RIND,
  MR.DENUMIRE,
  MR.ORDINE
  
  ORDER BY
  ORDINE,
  MR.ORDINE
  )
  
  UNION ALL 
  
  SELECT
   3 ORDINE,
  '12' CODUL,
   'PROPRIETATEA PUBLICA' DENUMIRE,
   NULL  AS COL1,
   NULL  AS COL2,
   NULL  AS COL3,
   NULL  AS COL4,
   NULL  AS COL5,
   NULL  AS COL6,
   NULL  AS COL7,
   NULL  AS COL8,
   NULL  AS COL9,
   NULL  AS COL10,
   NULL  AS COL11
FROM   DUAL

UNION ALL  

  SELECT *

FROM(
 SELECT
  4 ORDINE,
   MR.RIND AS NR_ROW,
   MR.DENUMIRE NUME_ROW,
   SUM(CIS2.NVAL(D.COL1)) AS COL1,
   SUM(CIS2.NVAL(D.COL2)) AS COL2,
   SUM(CIS2.NVAL(D.COL3)) AS COL3,
   SUM(CIS2.NVAL(D.COL4)) AS COL4,
   SUM(CIS2.NVAL(D.COL5)) AS COL5,
   SUM(CIS2.NVAL(D.COL6)) AS COL6,
   SUM(CIS2.NVAL(D.COL7)) AS COL7,
   SUM(CIS2.NVAL(D.COL8)) AS COL8,
   SUM(CIS2.NVAL(D.COL9)) AS COL9,
   SUM(CIS2.NVAL(D.COL10)) AS COL10,
   SUM(CIS2.NVAL(D.COL11)) AS COL11
     
   
FROM 
  VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
  INNER JOIN CIS2.VW_CL_CFP C ON (C.CODUL = D.CFP)
  INNER JOIN CIS2.VW_CL_CFP CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
  
  RIGHT JOIN MD_RIND MR ON (D.FORM=MR.FORM AND D.ID_MD=MR.ID_MD AND D.CAPITOL=MR.CAPITOL AND 
  
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')

  
WHERE
  MR.FORM IN (55)                 AND 
  MR.CAPITOL IN (1080) AND 
  CC.CODUL IN ('11')
GROUP BY
  MR.RIND,
  MR.DENUMIRE,
  MR.ORDINE
  
  ORDER BY
  ORDINE,
  MR.ORDINE
  ) 
  
  
  
 
  ORDER BY   
  ORDINE,
  CODUL
  
  ) VB 
  