SELECT 

D.CUIIO,
R.GEN_INSTITUTIE,
D.CFP,
D.RIND,
SUM(D.COL1) AS COL1


FROM   CIS2.VW_DATA_ALL D 
   INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND  R.CUIIO_VERS = D.CUIIO_VERS

     
WHERE 
(D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1079)
  
  AND  D.RIND IN ('100') 
  AND  CIS2.NVAL(D.COL1) = 1
 
 GROUP BY 
 D.CUIIO,
 R.GEN_INSTITUTIE,
D.CFP,
D.RIND