SELECT 
        'Completati toate clasificatoarele' REZULTAT,
        SUM(CASE WHEN D.RIND IN ('1.1','1.2','1.3','1.4','1.5','1.6')  THEN CIS2.NVAL(D.COL1) ELSE 0 END) +
SUM(CASE WHEN D.RIND IN ('2.1','2.2','2.3')  THEN CIS2.NVAL(D.COL1) ELSE 0 END) +
SUM(CASE WHEN D.RIND IN ('3.1','3.2''3.3','3.4','3.5','3.6','3.7')  THEN CIS2.NVAL(D.COL1) ELSE 0 END) +
SUM(CASE WHEN D.RIND IN ('4.1','4.2')  THEN CIS2.NVAL(D.COL1) ELSE 0 END) +
SUM(CASE WHEN D.RIND IN ('5.1','5.2')  THEN CIS2.NVAL(D.COL1) ELSE 0 END) AS COL_TEST
            

    FROM CIS2.VW_DATA_ALL D

   WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND      
  
  D.FORM  IN  (17)       AND 
  D.CAPITOL IN (1134)    

  
  
  
  
 HAVING
--  ( 
--  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('1.1','1.2''1.3','1.4','1.5','1.6')  THEN CIS2.NVAL(D.COL1) ELSE 0 END)) > 0
--  AND  
--  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('2.1','2.2','2.3')  THEN CIS2.NVAL(D.COL1) ELSE 0 END)) > 0 
--  AND  
--  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('3.1','3.2''3.3','3.4','3.5','3.6','3.7')  THEN CIS2.NVAL(D.COL1) ELSE 0 END)) > 0
--  AND  
--  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('4.1','4.2')  THEN CIS2.NVAL(D.COL1) ELSE 0 END)) > 0 
--  AND  
--  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('5.1','5.2')  THEN CIS2.NVAL(D.COL1) ELSE 0 END)) > 0 
-- )
--  
--AND 

(
SUM(CASE WHEN D.RIND IN ('1.1','1.2','1.3','1.4','1.5','1.6')  THEN CIS2.NVAL(D.COL1) ELSE 0 END) +
SUM(CASE WHEN D.RIND IN ('2.1','2.2','2.3')  THEN CIS2.NVAL(D.COL1) ELSE 0 END) +
SUM(CASE WHEN D.RIND IN ('3.1','3.2''3.3','3.4','3.5','3.6','3.7')  THEN CIS2.NVAL(D.COL1) ELSE 0 END) +
SUM(CASE WHEN D.RIND IN ('4.1','4.2')  THEN CIS2.NVAL(D.COL1) ELSE 0 END) +
SUM(CASE WHEN D.RIND IN ('5.1','5.2')  THEN CIS2.NVAL(D.COL1) ELSE 0 END) <> 5

)