SELECT

  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1092) AND D.RIND IN ('180') THEN  D.COL2 ELSE NULL END)) ||'<>'||
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1090) AND D.RIND IN ('570') THEN  D.COL2 ELSE NULL END))   
  AS REZULTAT
  
FROM VW_DATA_ALL_FR D


WHERE
  (D.PERIOADA IN (:PERIOADA))   AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (:CUIIO_VERS=:CUIIO_VERS     OR  D.CUIIO_VERS <>  :CUIIO_VERS) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (57)  AND
  D.CAPITOL IN (1092,1090)   

  
HAVING
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1092) AND D.RIND IN ('180') THEN  D.COL2 ELSE NULL END)) <>
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1090) AND D.RIND IN ('570') THEN  D.COL2 ELSE NULL END))

