SELECT DISTINCT

SUM(CASE WHEN D.PERIOADA IN (:PERIOADA)   THEN NVAL(D.COL1) ELSE 0 END) ||'<>'||
SUM(CASE WHEN D.PERIOADA IN (:PERIOADA-1) THEN NVAL(D.COL1) ELSE 0 END)
AS REZULTAT 
FROM
(


SELECT DISTINCT 
  SUM(D.COL2) AS COL1,
  D.PERIOADA
FROM 
  CIS2.VW_DATA_ALL_FR D
WHERE   
  (D.PERIOADA IN(:PERIOADA-1))AND 
  (D.CUIIO           = :CUIIO          OR :CUIIO= -1)        AND 
  (:CUIIO_VERS       = :CUIIO_VERS     OR :CUIIO_VERS   <>  :CUIIO_VERS)  AND 
  (:FORM             = :FORM           OR :FORM  <>  :FORM )        AND 
  (:FORM_VERS        = :FORM_VERS      OR :FORM_VERS  <> :FORM_VERS)   AND 
  (:CAPITOL          = :CAPITOL        OR :CAPITOL  <> :CAPITOL  )   AND 
  (:CAPITOL_VERS     = :CAPITOL_VERS   OR :CAPITOL_VERS  <> :CAPITOL_VERS) 
  AND D.FORM = 63 
  AND D.CAPITOL = 1120
  AND D.RIND IN ('160')

  GROUP BY D.PERIOADA
UNION

SELECT DISTINCT 
SUM(DD.COL1) AS COL1,
 DD.PERIOADA
 FROM

  USER_EREPORTING.VW_DATA_ALL_FOR_VALIDATE_FR DD 

 
WHERE
  (DD.PERIOADA IN(:PERIOADA))AND 
  (DD.CUIIO           = :CUIIO          OR :CUIIO= -1)        AND 
  (:CUIIO_VERS        = :CUIIO_VERS     OR  :CUIIO_VERS        <> :CUIIO_VERS )  AND 
  (DD.FORM            = :FORM           OR :FORM = -1)        AND 
  (DD.FORM_VERS       = :FORM_VERS      OR :FORM_VERS = -1)   AND 
  (DD.CAPITOL         = :CAPITOL        OR :CAPITOL = -1  )   AND 
  (DD.CAPITOL_VERS    = :CAPITOL_VERS   OR :CAPITOL_VERS = -1) 
  AND DD.FORM = 57 
  AND DD.CAPITOL = 1090              
  AND DD.ID_SCHEMA IN (2) 
  AND DD.RIND IN ('600')
  GROUP BY DD.PERIOADA
  
  
  )D
  
  HAVING
 
NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA)   THEN NVAL(D.COL1)  END)) <> 
NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA-1) THEN NVAL(D.COL1)  END))


AND
  (
 SELECT
  DISTINCT
  D.CUIIO
FROM
  CIS2.VW_DATA_ALL_FR D
WHERE
  (D.PERIOADA IN (:PERIOADA-1)) AND
  (D.CUIIO=:CUIIO OR :CUIIO = -1) AND
   D.FORM  IN (63)) IS NOT NULL

