SELECT
  A.KEYID,
  A.SECTOR,
  A.NSTR,
  A.GR1,
  B.GR2,
  B.GR3,
  A.XFILES,
  A.ANUL
FROM
(
SELECT
  D.CUIIO AS KEYID,a
  'F5001' AS SECTOR,
  D.RIND AS NSTR,
  D.COL1 AS GR1,
  NULL AS GR2,
  NULL AS GR3,
  NULL AS XFILES,
  D.ANUL
  
FROM
  VW_DATA_ALL_FR D
WHERE
  D.PERIOADA IN (2007) AND
  D.FORM IN (57) AND
  D.CAPITOL IN (1095) AND 
  D.RIND NOT IN ('4.1','4.2','8.1','9.1','11.1','12.1')
ORDER BY
  D.CUIIO,
  D.RIND
) A
LEFT JOIN
(
SELECT
  D.CUIIO AS KEYID,
  'F5001' AS SECTOR,
  D.RIND AS NSTR,
  NULL AS GR1,
  CASE WHEN D.RIND IN ('4.1','8.1','9.1','a11.1','12.1') THEN D.COL1 END AS GR2,
  CASE WHEN D.RIND IN ('4.2') THEN D.COL1 END AS GR3,
  NULL AS XFILES,
  D.ANUL
  
FROM
  VW_DATA_ALL_FR D
WHERE
  D.PERIOADA IN (2007) AND
  D.FORM IN (57) AND
  D.CAPITOL IN (1095) AND 
  D.RIND IN ('4.1','4.2','8.1','9.1','11.1','12.1')
ORDER BY
  D.CUIIO,
  D.RIND
) B ON (A.KEYID=B.KEYID AND A.NSTR=CASE WHEN LENGTH(A.NSTR) = 1 THEN SUBSTR(B.NSTR,0,1) ELSE SUBSTR(B.NSTR,0,2) END)
UNION ALL
SELECT
  D.CUIIO AS KEYID,
  'F8000' AS SECTOR,
  D.RIND AS NSTR,
  D.COL1 AS GR1,
  D.COL2 AS GR2,
  NULL AS GR3,
  NULL AS XFILES,
  D.ANUL
  
FROM
  VW_DATA_ALL_FR D
WHERE
  D.PERIOADA IN (2007) AND
  D.FORM IN (57) AND
  D.CAPITOL IN (1089)