SELECT
  D.CUIIO AS KEYID,
  'F7000' AS SECTOR,
  D.RIND AS NSTR,
  D.COL1 AS GR1,
  D.COL2 AS GR2,
  D.COL3 AS GR3,
  D.COL4 AS GR4,
  D.COL5 AS GR5,
  D.COL6 AS GR6,
  D.COL7 AS GR7,
  D.COL8 AS GR8,
  NULL AS XFILES,
  D.ANUL
  
FROM
  VW_DATA_ALL_FR D
WHERE
  D.PERIOADA IN (2007) AND
  D.FORM IN (57) AND
  D.CAPITOL IN (1103)
ORDER BY
  D.CUIIO,
  D.RIND