--UPDATE CIS2.MD_CONTROL 
--
--SET SQL_TEXT = REPLACE(SQL_TEXT,'OR :PERIOADA = -1',' ')

SELECT 
CONTROL
--REPLACE(SQL_TEXT,'OR :PERIOADA = -1',' ') AS SQL 
 FROM CIS2.MD_CONTROL
 
WHERE 
--SQL_TEXT LIKE '%OR :PERIOADA = -1%'  
--AND 

SQL_TEXT NOT LIKE '%VW_DATA_ALL_FR%'  
AND 


FORM = 66
--AND CONTROL_VERS = 2010
--AND CONTROL IN ('57-014')
  
