UPDATE CIS2.MD_CONTROL 

SET SQL_TEXT = REPLACE(REPLACE(REPLACE(SQL_TEXT,'OR :PERIOADA = -1',' '),'OR :CUIIO = -1',' '),'OR :FORM = -1','')


--SELECT 
--CONTROL,
--REPLACE(REPLACE(REPLACE(SQL_TEXT,'OR :PERIOADA = -1',' '),'OR :CUIIO = -1',' '),'OR :FORM = -1','') AS SQL 
-- FROM CIS2.MD_CONTROL
 
WHERE 
SQL_TEXT LIKE '%OR :PERIOADA = -1%'  
OR  

SQL_TEXT NOT LIKE '%OR :FORM = -1%'  
OR  


SQL_TEXT LIKE '%OR :CUIIO = -1%'  
--AND 

AND FORM = 63
--AND CONTROL_VERS = 2010
--AND CONTROL IN ('57-014')
  
