CREATE TABLE USER_BANCU.RSF_PR_v1
(
  CUIIO            NUMBER,
 
  DENUMIRE         VARCHAR2(1024 BYTE),
  CUATM       VARCHAR2(1024 BYTE),
  CAEM2          VARCHAR2(1024 BYTE),
 
  CAPITOL_DEN      NVARCHAR2(2000),
  RIND   VARCHAR2(1024 BYTE),
  COL1     VARCHAR2(1024 BYTE),
  COL2        VARCHAR2(1024 BYTE),
  COL3        VARCHAR2(1024 BYTE),
  COL4        VARCHAR2(1024 BYTE)
)
TABLESPACE TBS_DTI_USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;