SELECT *
FROM CIS2.MD_CONTROL
WHERE (
  (INSTR(SQL_TEXT, 'VW_DATA_ALL_FR_TEMP') = 0 OR INSTR(SQL_TEXT, 'VW_DATA_ALL_FR_TEMP') IS NULL)
  AND (INSTR(SQL_TEXT, 'VW_DATA_ALL_FR') = 0 OR INSTR(SQL_TEXT, 'VW_DATA_ALL_FR') IS NULL)
)
AND FORM IN (57, 59, 63, 66);