SELECT 
  D.CONTROL,
  D.CUIIO,
  L.FORMULA,
  D.REZULTAT,
  D.DATA_REG          

    FROM CIS2.CONTROL D 
    
            INNER JOIN  CIS2.MD_CONTROL L ON D.CONTROL = L.CONTROL
    WHERE
    D.FORM = 46 AND D.PERIOADA = 2009
 AND REZULTAT <> 'OK'
 
 ORDER BY
 D.CONTROL DESC
 