SELECT 
D.CUIIO,
D.RIND,
D.CUATM,
SUM(D.COL1) AS COL1
       
FROM 
 cis2.VW_DATA_ALL D
  INNER JOIN cis2.MD_RIND RD ON (D.ID_MD=RD.ID_MD)
  INNER JOIN cis2.RENIM RE ON (D.CUIIO=RE.CUIIO AND D.CUIIO_VERS=RE.CUIIO_VERS)
  INNER JOIN cis2.VW_CL_CFP CF ON (RE.CFP=CF.CODUL)
  INNER JOIN cis2.VW_CL_CFP CCF ON (CF.FULL_CODE LIKE '%'||CCF.CODUL||';%' )
  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (60)                 AND 
  D.CAPITOL IN (1107) 
  AND D.RIND IN ('100')
 -- CC.FULL_CODE LIKE '%'||:pCOD_CUATM||';%'
 
 GROUP BY
 D.CUIIO, 
 D.RIND,
 D.CUATM