SELECT 

MAX(D.CUIIO) CUIIO,
RN.DENUMIRE,
RN.CUATM,
MAX(CASE WHEN R.RIND NOT IN ('ER') THEN  R.RIND END) COL3,
MAX(CASE WHEN R.RIND  IN ('ER') THEN  R.RIND END) COL4,
RN.CFP,
RN.CAEM2,
D.TIP,
D.PACHET



  

   

FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM RN ON (D.CUIIO = RN.CUIIO AND D.CUIIO_VERS = RN.CUIIO_VERS)
  INNER JOIN VW_CL_CUATM CC ON(RN.CUATM = CC.CODUL) 
  INNER JOIN MD_RIND R ON R.ID_MD=D.ID_MD 
  INNER JOIN VW_CL_CFP CP ON (RN.CFP = CP.CODUL)   


WHERE
  D.FORM IN (21)             AND 
  D.FORM_VERS = :PFORM_VERS  AND    
  D.CAPITOL IN (0)     AND 
  D.CUATM_FULL LIKE  '%'||:pCOD_CUATM||';%'AND
  D.PERIOADA = :pPERIOADA   
  --AND D.RIND N
 
  
  
GROUP BY
--D.CUIIO,
RN.DENUMIRE,
RN.CUATM,
RN.CFP,
RN.CAEM2,
D.TIP,
D.PACHET
--R.RIND
ORDER BY
RN.CUATM,
CUIIO
