SELECT DISTINCT
  'Codul CUIIO='||D.CUIIO||' exista deja in sistemul BNS'
  AS REZULTAT

FROM
  CIS2.VW_DATA_ALL D

WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (:CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (:FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS) AND
  (:ID_MD=:ID_MD) AND
  D.CAPITOL_DEN NOT IN ('TITLU')
  AND D.FORM NOT IN (7,8,12)
  AND (CASE WHEN D.FORM IN (21) AND D.CAPITOL IN (357,358) AND COL2 IS NOT NULL THEN 1 ELSE 0 END) NOT IN (1)
  
  --CUIIO = 1844740 AND PERIOADA = 2009 AND FORM = 21