--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,
--  
--  COL1, COL2, COL3, COL4 , COL5
--)


SELECT
--  :pPERIOADA AS PERIOADA,                                                    
--  :pFORM AS FORM,                                                            
--  :pFORM_VERS AS FORM_VERS,                                                  
--  :pID_MDTABLE AS ID_MDTABLE,                                                
--  :pCOD_CUATM AS COD_CUATM,                                                  
--  '0' AS NR_SECTIE,                                                         
--  '0' AS NUME_SECTIE,                                                        
--  '0' AS NR_SECTIE1,
--  '0' AS NUME_SECTIE1,
--  '0' AS NR_SECTIE2,
--  '0' AS NUME_SECTIE2,
   NR_ROW AS NR_ROW,  
   ORDINE AS ORDINE,
  '00000' AS DECIMAL_POS,
   DENUMIRE,
   ROUND(COL1,1) AS COL1, ROUND(COL2,1) AS COL2, ROUND(COL3,1) AS COL3, ROUND(COL4,1) AS COL4, ROUND(COL5,1) AS COL5
FROM (

--strat 1 
SELECT
   0 NR_ROW,
   0 ORDINE,
  'Cifra de afeceri (venitul din vinzari) - total:'DENUMIRE,
  CC.FULL_CODE,
  ROUND(SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA THEN COL1 END),1) AS COL1,
  ROUND(SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 THEN COL1 END),1) AS COL2,
  ROUND(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA THEN D.COL1 ELSE 0 END),1) AS COL3,
  ROUND(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-1 THEN D.COL1 ELSE 0 END),1) AS COL4,
  ROUND(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-12 THEN D.COL1 ELSE 0 END),1) AS COL5
  
  
FROM 
  CIS.VW_DATA_ALL_COEF D
  
  INNER JOIN  CIS.VW_CL_CAEM2 C ON (C.CODUL = D.CAEM2)
  INNER JOIN CIS.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
  


WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  FORM = 4 AND
  CAPITOL = 4 AND
  RIND = '10' AND
  (
  C.CODUL LIKE 'H49%'
  OR 
  C.CODUL LIKE 'H50%'
  OR 
  C.CODUL LIKE 'H51%'
  OR 
  C.CODUL LIKE 'H52%'
  OR 
  C.CODUL LIKE 'H53%'
  OR 
  C.CODUL LIKE 'J58%'
   OR 
  C.CODUL LIKE 'J61%'
  OR 
  C.CODUL LIKE 'J62%'
  OR 
  C.CODUL LIKE 'J63%'
  OR 
  C.CODUL LIKE 'L68%'
  OR 
  C.CODUL LIKE 'M69%'
  OR 
  C.CODUL LIKE 'M70%'
  OR 
  C.CODUL LIKE 'M71%'
    OR 
  C.CODUL LIKE 'M72%'
     OR 
  C.CODUL LIKE 'M73%'
       OR 
  C.CODUL LIKE 'M74%'
         OR 
  C.CODUL LIKE 'N77%'
           OR 
  C.CODUL LIKE 'N78%'
             OR 
  C.CODUL LIKE 'N80%'
  OR 
  C.CODUL LIKE 'N82%'
  ----------------------------
  
  
  OR 
  C.CODUL LIKE  'N811%'
  
   OR 
  C.CODUL LIKE   'N812%'
  
     OR 
  C.CODUL LIKE  'N813%'
  
  ) 
  
  AND (
  D.CAEM2 NOT LIKE 'N772%' AND
  D.CAEM2 NOT LIKE 'M742%'
  
  )
  AND 
   (D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 OR 
     D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA-1 
     OR 
     D.PERIOADA IN (:pPERIOADA-12)    
     
     )
     
    AND  CC.CODUL LIKE '%00000'
     
     GROUP BY 
       CC.CODUL,
       CC.DENUMIRE,
       CC.FULL_CODE
-- end 1
union 

--  START 2

SELECT
   1 NR_ROW,
   1 ORDINE,
  'TRANSPORT SI DEPOZITARE(49+50+51+52+53)'DENUMIRE,
  CC.FULL_CODE,
  ROUND(SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA THEN COL1 END),1) AS COL1,
  ROUND(SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 THEN COL1 END),1) AS COL2,
  ROUND(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA THEN D.COL1 ELSE 0 END),1) AS COL3,
  ROUND(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-1 THEN D.COL1 ELSE 0 END),1) AS COL4,
  ROUND(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-12 THEN D.COL1 ELSE 0 END),1) AS COL5
  
  
FROM 
  CIS.VW_DATA_ALL_COEF D
  
  INNER JOIN  CIS.VW_CL_CAEM2 C ON (C.CODUL = D.CAEM2)
  INNER JOIN CIS.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
  


WHERE
 (D.FORM=:pFORM) AND

 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  FORM = 4 AND
  CAPITOL = 4 AND
  RIND = '10' AND
  (
  C.CODUL LIKE 'H49%'
  OR 
  C.CODUL LIKE 'H50%'
  OR 
  C.CODUL LIKE 'H51%'
  OR 
  C.CODUL LIKE 'H52%'
  OR 
  C.CODUL LIKE 'H53%'

  
  ) 
  
  AND (
  D.CAEM2 NOT LIKE 'N772%' AND
  D.CAEM2 NOT LIKE 'M742%'
  
  )
  AND 
   (D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 OR 
     D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA-1 
     OR 
     D.PERIOADA IN (:pPERIOADA-12)    
     
     )
     
    AND  CC.CODUL LIKE '%00000'
     
     GROUP BY 
       CC.CODUL,
       CC.DENUMIRE,
       CC.FULL_CODE
-- END 2 
       UNION 
--START 3

       
     SELECT
   2 NR_ROW,
   2 ORDINE,

  'Transporturi terestre si transporturi prin conducte (49=49.1+49.2+49.3+49.4+49.5):'DENUMIRE,
  CC.FULL_CODE,
  ROUND(SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA THEN COL1 END),1) AS COL1,
  ROUND(SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 THEN COL1 END),1) AS COL2,
  ROUND(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA THEN D.COL1 ELSE 0 END),1) AS COL3,
  ROUND(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-1 THEN D.COL1 ELSE 0 END),1) AS COL4,
  ROUND(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-12 THEN D.COL1 ELSE 0 END),1) AS COL5
  
  
FROM 
  CIS.VW_DATA_ALL_COEF D
  
  INNER JOIN  CIS.VW_CL_CAEM2 C ON (C.CODUL = D.CAEM2)
  INNER JOIN CIS.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
  


WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  FORM = 4 AND
  CAPITOL = 4 AND
  RIND = '10' AND
  (
  C.CODUL LIKE 'H49%'
  ) 
  
  AND (
  D.CAEM2 NOT LIKE 'N772%' AND
  D.CAEM2 NOT LIKE 'M742%'
  
  )
  AND 
   (D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 OR 
     D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA-1 
     OR 
     D.PERIOADA IN (:pPERIOADA-12)    
     
     )
     
    AND  CC.CODUL LIKE '%00000'
     
     GROUP BY 
       CC.CODUL,
       CC.DENUMIRE,
       CC.FULL_CODE
     --END 3
     
     UNION 
     --STAT 4
          SELECT 
ORDINE,
NR_ROW,
    
      CODUL||'-'|| DENUMIRE DENUMIRE,
     FULL_CODE,
       COL1 AS  COL1,
       COL2 AS COL2,
       COL3 AS COL3,
       COL4 AS COL4,
       COL5  AS COL5 
FROM 


(

SELECT 
    ROWNUM +2  ORDINE,
    ROWNUM +2 NR_ROW,
    CODUL,
      DENUMIRE,
     FULL_CODE,
       COL1 AS COL1,
       COL2 AS COL2,
       COL3 AS COL3,
       COL4 AS COL4,
       COL5  AS COL5 
       
       FROM


(
SELECT CC.CODUL,
       CC.DENUMIRE,
       CC.FULL_CODE,
       ROUND(SUM(L.COL1),1) AS COL1,
       ROUND(SUM(L.COL2),1) AS COL2,
       ROUND(SUM(L.COL3),1) AS COL3,
       ROUND(SUM(L.COL4),1) AS COL4,
       ROUND(SUM(L.COL5),1) AS COL5  

FROM CIS.VW_CL_CAEM2 C 
            LEFT JOIN (
            
            SELECT
  C.CODUL,
  C.DENUMIRE,
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA THEN COL1 END) AS COL1,
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 THEN COL1 END) AS COL2,
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA THEN D.COL1 ELSE 0 END) AS COL3,
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-1 THEN D.COL1 ELSE 0 END) AS COL4,
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-12 THEN D.COL1 ELSE 0 END) AS COL5
  
  
FROM 
  CIS.VW_DATA_ALL_COEF D
  
  INNER JOIN  CIS.VW_CL_CAEM2 C ON (C.CODUL = D.CAEM2)
  --INNER JOIN CIS.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
  


WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  FORM = 4 AND
  CAPITOL = 4 AND
  RIND = '10' AND
  
  
   (D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 OR 
     D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA-1 
     OR 
     D.PERIOADA IN (:pPERIOADA-12)    
     
     )
     
AND (
  D.CAEM2 NOT LIKE 'N772%' AND
  D.CAEM2 NOT LIKE 'M742%'
  
  )
  
  
     
     GROUP BY 
       C.CODUL,
       C.DENUMIRE,
       C.FULL_CODE
       
       ORDER BY 
       C.FULL_CODE
            ) L ON L.CODUL = C.CODUL
              INNER JOIN CIS.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')


WHERE
1=1 AND 
(
  CC.CODUL LIKE 'H49%'
  OR 
  CC.CODUL LIKE 'H50%'
  OR 
  CC.CODUL LIKE 'H51%'
  OR 
  CC.CODUL LIKE 'H52%'
  OR 
  CC.CODUL LIKE 'H53%'
)


AND CC.CODUL NOT IN '00000'
GROUP BY
CC.CODUL,
       CC.DENUMIRE,
       CC.FULL_CODE
 

ORDER BY 
CC.FULL_CODE

) )

     --END 4  
     UNION
       --START 5
       SELECT
   35 NR_ROW,
   35 ORDINE,

  'INFORMATII SI TELECOMUNICATII (CU EXCEPTIA ACTIVITATII DE PRODUCTIE CINEMATOGRAFICA, VIDEO SI DE PROGRAME DE TELEVIZIUNE; ÎNREGISTRARI AUDIO SI ACTIVITATII DE EDITARE MUZICALA, ACTIVITATI DE DIFUZARE SI TRANSMITERE DE PROGRAME)(58+61+62+63)'DENUMIRE,
  CC.FULL_CODE,
  ROUND(SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA THEN COL1 END),1) AS COL1,
  ROUND(SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 THEN COL1 END),1) AS COL2,
  ROUND(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA THEN D.COL1 ELSE 0 END),1) AS COL3,
  ROUND(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-1 THEN D.COL1 ELSE 0 END),1) AS COL4,
  ROUND(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-12 THEN D.COL1 ELSE 0 END),1) AS COL5
  
  
FROM 
  CIS.VW_DATA_ALL_COEF D
  
  INNER JOIN  CIS.VW_CL_CAEM2 C ON (C.CODUL = D.CAEM2)
  INNER JOIN CIS.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
  


WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  FORM = 4 AND
  CAPITOL = 4 AND
  RIND = '10' AND
  (
  C.CODUL LIKE 'J58%'
  OR 
  C.CODUL LIKE 'J61%'
  
  OR 
  C.CODUL LIKE 'J62%'
  
  OR 
  C.CODUL LIKE 'J63%'
  ) 
  
  AND (
  D.CAEM2 NOT LIKE 'N772%' AND
  D.CAEM2 NOT LIKE 'M742%'
  
  )
  AND 
   (D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 OR 
     D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA-1 
     OR 
     D.PERIOADA IN (:pPERIOADA-12)    
     
     )
     
    AND  CC.CODUL LIKE '%00000'
     
     GROUP BY 
       CC.CODUL,
       CC.DENUMIRE,
       CC.FULL_CODE
       --END 5 
     
    UNION 
    
    --start 6
    
         SELECT 
ORDINE,
NR_ROW,
    
      CODUL||'-'|| DENUMIRE DENUMIRE,
     FULL_CODE,
       COL1 AS  COL1,
       COL2 AS COL2,
       COL3 AS COL3,
       COL4 AS COL4,
       COL5  AS COL5 
FROM 


(

SELECT 
    ROWNUM + 37  ORDINE,
    ROWNUM + 37 NR_ROW,
    CODUL,
      DENUMIRE,
     FULL_CODE,
       COL1 AS COL1,
       COL2 AS COL2,
       COL3 AS COL3,
       COL4 AS COL4,
       COL5  AS COL5 
       
       FROM


(
SELECT CC.CODUL,
       CC.DENUMIRE,
       CC.FULL_CODE,
       ROUND(SUM(L.COL1),1) AS COL1,
       ROUND(SUM(L.COL2),1) AS COL2,
       ROUND(SUM(L.COL3),1) AS COL3,
       ROUND(SUM(L.COL4),1) AS COL4,
       ROUND(SUM(L.COL5),1) AS COL5  

FROM CIS.VW_CL_CAEM2 C 
            LEFT JOIN (
            
            SELECT
  C.CODUL,
  C.DENUMIRE,
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA THEN COL1 END) AS COL1,
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 THEN COL1 END) AS COL2,
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA THEN D.COL1 ELSE 0 END) AS COL3,
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-1 THEN D.COL1 ELSE 0 END) AS COL4,
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-12 THEN D.COL1 ELSE 0 END) AS COL5
  
  
FROM 
  CIS.VW_DATA_ALL_COEF D
  
  INNER JOIN  CIS.VW_CL_CAEM2 C ON (C.CODUL = D.CAEM2)
  --INNER JOIN CIS.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
  


WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  FORM = 4 AND
  CAPITOL = 4 AND
  RIND = '10' AND
  
  
   (D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 OR 
     D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA-1 
     OR 
     D.PERIOADA IN (:pPERIOADA-12)    
     
     )
     
AND (
  D.CAEM2 NOT LIKE 'N772%' AND
  D.CAEM2 NOT LIKE 'M742%'
  
  )
  
  
     
     GROUP BY 
       C.CODUL,
       C.DENUMIRE,
       C.FULL_CODE
       
       ORDER BY 
       C.FULL_CODE
            ) L ON L.CODUL = C.CODUL
              INNER JOIN CIS.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')


WHERE
1=1 AND 
(
  CC.CODUL LIKE 'J58%'
  OR 
  CC.CODUL LIKE 'J61%'
  OR 
  CC.CODUL LIKE 'J62%'
  OR 
  CC.CODUL LIKE 'J63%'
  OR 
  CC.CODUL LIKE 'L68%'
)


AND CC.CODUL NOT IN '00000'
GROUP BY
CC.CODUL,
       CC.DENUMIRE,
       CC.FULL_CODE
 

ORDER BY 
CC.FULL_CODE

) )
 
    --ende 6 
    union 
       --start 7
       SELECT
   72 NR_ROW,
   72 ORDINE,

  'ACTIVITATI PROFESIONALE, STIINTIFICE SI TEHNICE (CU EXCEPTIA ACTIVITATII VETERINARE) (69+70+71+72+73+74)'DENUMIRE,
  CC.FULL_CODE,
  ROUND(SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA THEN COL1 END),1) AS COL1,
  ROUND(SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 THEN COL1 END),1) AS COL2,
  ROUND(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA THEN D.COL1 ELSE 0 END),1) AS COL3,
  ROUND(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-1 THEN D.COL1 ELSE 0 END),1) AS COL4,
  ROUND(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-12 THEN D.COL1 ELSE 0 END),1) AS COL5
  
  
FROM 
  CIS.VW_DATA_ALL_COEF D
  
  INNER JOIN  CIS.VW_CL_CAEM2 C ON (C.CODUL = D.CAEM2)
  INNER JOIN CIS.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
  


WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  FORM = 4 AND
  CAPITOL = 4 AND
  RIND = '10' AND
  (
  C.CODUL LIKE 'M69%'
  OR 
  C.CODUL LIKE 'M70%'
  
  OR 
  C.CODUL LIKE 'M71%'
  
  OR 
  C.CODUL LIKE 'M72%'
  
  OR 
  C.CODUL LIKE 'M73%'
  
  OR 
  C.CODUL LIKE 'M74%'
  
  
  ) 
  
  AND (
  D.CAEM2 NOT LIKE 'N772%' AND
  D.CAEM2 NOT LIKE 'M742%'
  
  )
  AND 
   (D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 OR 
     D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA-1 
     OR 
     D.PERIOADA IN (:pPERIOADA-12)    
     
     )
     
    AND  CC.CODUL LIKE '%00000'
     
     GROUP BY 
       CC.CODUL,
       CC.DENUMIRE,
       CC.FULL_CODE
       --end 7
       UNION  
      --START 8 
           SELECT 
ORDINE,
NR_ROW,
    
      CODUL||'-'|| DENUMIRE DENUMIRE,
     FULL_CODE,
       COL1 AS  COL1,
       COL2 AS COL2,
       COL3 AS COL3,
       COL4 AS COL4,
       COL5  AS COL5 
FROM 


(

SELECT 
    ROWNUM + 74  ORDINE,
    ROWNUM + 74 NR_ROW,
    CODUL,
      DENUMIRE,
     FULL_CODE,
       COL1 AS COL1,
       COL2 AS COL2,
       COL3 AS COL3,
       COL4 AS COL4,
       COL5  AS COL5 
       
       FROM


(
SELECT CC.CODUL,
       CC.DENUMIRE,
       CC.FULL_CODE,
       ROUND(SUM(L.COL1),1) AS COL1,
       ROUND(SUM(L.COL2),1) AS COL2,
       ROUND(SUM(L.COL3),1) AS COL3,
       ROUND(SUM(L.COL4),1) AS COL4,
       ROUND(SUM(L.COL5),1) AS COL5  

FROM CIS.VW_CL_CAEM2 C 
            LEFT JOIN (
            
            SELECT
  C.CODUL,
  C.DENUMIRE,
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA THEN COL1 END) AS COL1,
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 THEN COL1 END) AS COL2,
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA THEN D.COL1 ELSE 0 END) AS COL3,
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-1 THEN D.COL1 ELSE 0 END) AS COL4,
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-12 THEN D.COL1 ELSE 0 END) AS COL5
  
  
FROM 
  CIS.VW_DATA_ALL_COEF D
  
  INNER JOIN  CIS.VW_CL_CAEM2 C ON (C.CODUL = D.CAEM2)
  --INNER JOIN CIS.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
  


WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  FORM = 4 AND
  CAPITOL = 4 AND
  RIND = '10' AND
  
  
   (D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 OR 
     D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA-1 
     OR 
     D.PERIOADA IN (:pPERIOADA-12)    
     
     )
     
AND (
  D.CAEM2 NOT LIKE 'N772%' AND
  D.CAEM2 NOT LIKE 'M742%'
  
  )
  
  
     
     GROUP BY 
       C.CODUL,
       C.DENUMIRE,
       C.FULL_CODE
       
       ORDER BY 
       C.FULL_CODE
            ) L ON L.CODUL = C.CODUL
              INNER JOIN CIS.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')


WHERE
1=1 AND 
(
  C.CODUL LIKE 'M69%'
  OR 
  C.CODUL LIKE 'M70%'
  
  OR 
  C.CODUL LIKE 'M71%'
  
  OR 
  C.CODUL LIKE 'M72%'
  
  OR 
  C.CODUL LIKE 'M73%'
  
  OR 
  C.CODUL LIKE 'M74%'
)


AND CC.CODUL NOT IN '00000'
GROUP BY
CC.CODUL,
       CC.DENUMIRE,
       CC.FULL_CODE
 

ORDER BY 
CC.FULL_CODE

) )

      -- END 8
     union 
     
     -- START 9
      SELECT
   105 NR_ROW,
   105 ORDINE,

  'ACTIVITATI DE SERVICII ADMINISTRATIVE SI ACTIVITATI DE SERVICII SUPORT (CU EXCEPTIA ACTIVITATII AGENTIILOR TURISTICE SI ALE TUROPERATORILOR)(77+78+80+81+82)'DENUMIRE,
  CC.FULL_CODE,
  ROUND(SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA THEN COL1 END),1) AS COL1,
  ROUND(SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 THEN COL1 END),1) AS COL2,
  ROUND(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA THEN D.COL1 ELSE 0 END),1) AS COL3,
  ROUND(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-1 THEN D.COL1 ELSE 0 END),1) AS COL4,
  ROUND(SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-12 THEN D.COL1 ELSE 0 END),1) AS COL5
  
  
FROM 
  CIS.VW_DATA_ALL_COEF D
  
  INNER JOIN  CIS.VW_CL_CAEM2 C ON (C.CODUL = D.CAEM2)
  INNER JOIN CIS.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
  


WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  FORM = 4 AND
  CAPITOL = 4 AND
  RIND = '10' AND
  (
  
  C.CODUL LIKE 'N77%'
  OR 
  C.CODUL LIKE 'N78%'
  
  OR 
  C.CODUL LIKE 'N80%'
  
  OR 
  C.CODUL LIKE 'N81%'
  
  OR 
  C.CODUL LIKE 'N82%'
  

  ) 
  
  AND (
  D.CAEM2 NOT LIKE 'N772%' AND
  D.CAEM2 NOT LIKE 'M742%'
  
  )
  AND 
   (D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 OR 
     D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA-1 
     OR 
     D.PERIOADA IN (:pPERIOADA-12)    
     
     )
     
    AND  CC.CODUL LIKE '%00000'
     
     GROUP BY 
       CC.CODUL,
       CC.DENUMIRE,
       CC.FULL_CODE
     --END 9
     UNION 
     --START 10
     
          SELECT 
ORDINE,
NR_ROW,
    
      CODUL||'-'|| DENUMIRE DENUMIRE,
     FULL_CODE,
       COL1 AS  COL1,
       COL2 AS COL2,
       COL3 AS COL3,
       COL4 AS COL4,
       COL5  AS COL5 
FROM 


(

SELECT 
    ROWNUM + 110  ORDINE,
    ROWNUM + 110 NR_ROW,
    CODUL,
      DENUMIRE,
     FULL_CODE,
       COL1 AS COL1,
       COL2 AS COL2,
       COL3 AS COL3,
       COL4 AS COL4,
       COL5  AS COL5 
       
       FROM


(
SELECT CC.CODUL,
       CC.DENUMIRE,
       CC.FULL_CODE,
       ROUND(SUM(L.COL1),1) AS COL1,
       ROUND(SUM(L.COL2),1) AS COL2,
       ROUND(SUM(L.COL3),1) AS COL3,
       ROUND(SUM(L.COL4),1) AS COL4,
       ROUND(SUM(L.COL5),1) AS COL5  

FROM CIS.VW_CL_CAEM2 C 
            LEFT JOIN (
            
            SELECT
  C.CODUL,
  C.DENUMIRE,
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA THEN COL1 END) AS COL1,
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 THEN COL1 END) AS COL2,
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA THEN D.COL1 ELSE 0 END) AS COL3,
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-1 THEN D.COL1 ELSE 0 END) AS COL4,
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-12 THEN D.COL1 ELSE 0 END) AS COL5
  
  
FROM 
  CIS.VW_DATA_ALL_COEF D
  
  INNER JOIN  CIS.VW_CL_CAEM2 C ON (C.CODUL = D.CAEM2)
  --INNER JOIN CIS.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
  


WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  FORM = 4 AND
  CAPITOL = 4 AND
  RIND = '10' AND
  
  
   (D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 OR 
     D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA-1 
     OR 
     D.PERIOADA IN (:pPERIOADA-12)    
     
     )
     
AND (
  D.CAEM2 NOT LIKE 'N772%' AND
  D.CAEM2 NOT LIKE 'M742%'
  
  )
  
  
     
     GROUP BY 
       C.CODUL,
       C.DENUMIRE,
       C.FULL_CODE
       
       ORDER BY 
       C.FULL_CODE
            ) L ON L.CODUL = C.CODUL
              INNER JOIN CIS.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')


WHERE
1=1 AND 
(
  C.CODUL LIKE 'N77%'
  OR 
  C.CODUL LIKE 'N78%'
  
  OR 
  C.CODUL LIKE 'N80%'
  
  OR 
  C.CODUL LIKE 'N81%'
  
  OR 
  C.CODUL LIKE 'N82%'
)


AND CC.CODUL NOT IN '00000'
GROUP BY
CC.CODUL,
       CC.DENUMIRE,
       CC.FULL_CODE
 

ORDER BY 
CC.FULL_CODE

) )

     --END -100

        
     )
     
     
     WHERE 
     DENUMIRE NOT IN ('H4900-Transporturi terestre si transporturi prin conducte','M0000-ACTIVITATI PROFESIONALE, STIINTIFICE SI TEHNICE','N0000-ACTIVITATI DE SERVICII ADMINISTRATIVE SI ACTIVITATI DE SERVICII SUPORT')
     ORDER BY 
     ORDINE
     
     