SELECT 

DISTINCT D.CUIIO,
  

 SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA)  AND D.CAPITOL IN (0) AND D.RIND IN ('01','02','03','04','05','06','07','10','11','12') THEN TO_NUMBER(D.RIND) ELSE 0 END) AS COL3,
 SUM(CASE WHEN D.PERIOADA IN :pPERIOADA - 1  AND D.CAPITOL IN (0) AND D.RIND IN ('01','02','03','04','05','06','07','10','11','12') THEN TO_NUMBER(D.RIND) ELSE 0 END) AS COL4,
 SUM(CASE WHEN D.PERIOADA IN :pPERIOADA   AND D.CAPITOL IN (0) AND D.RIND IN ('CD','(CD)') THEN D.COL1 ELSE 0 END) AS COL5,
 SUM(DISTINCT CASE WHEN D.PERIOADA IN :pPERIOADA  AND D.CAPITOL IN (0) THEN D.PACHET ELSE 0 END) AS COL6,
  
   SUM(CASE WHEN  D.CAPITOL IN (4) AND D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA AND D.RIND IN '10' THEN D.COL1 ELSE 0 END) AS COL7,
  
   SUM(CASE WHEN D.CAPITOL IN (4) AND D.PERIOADA IN :pPERIOADA AND D.RIND IN '10' THEN D.COL1 ELSE 0 END) AS COL8,
    
   SUM(CASE WHEN  D.CAPITOL IN (4) AND D.PERIOADA IN :pPERIOADA-1 AND D.RIND IN '10' THEN D.COL1 ELSE 0 END) AS COL9
 
 

FROM CIS.VW_DATA_ALL D


               
               
WHERE
  (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
  D.FORM = 4 AND
  
  (  D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA OR
     D.PERIOADA IN (:pPERIOADA, :pPERIOADA-1 ))
AND 
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' 
  
  AND
  D.CAPITOL IN (0,4)
  
--   AND D.CUIIO IN (26844)
  
  
 GROUP BY
 D.CUIIO