SELECT
 

  R.CODUL,
  R.NUME_ROW,
--  CC.FULL_CODE,
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA THEN COL1 END) AS COL1,
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 THEN COL1 END) AS COL2,
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA THEN D.COL1 ELSE 0 END) AS COL3,
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-1 THEN D.COL1 ELSE 0 END) AS COL4,
  SUM(CASE WHEN D.PERIOADA IN :pPERIOADA-12 THEN D.COL1 ELSE 0 END) AS COL5
  
  
FROM 
  CIS.VW_DATA_ALL_COEF D
  
  INNER JOIN  CIS.VW_CL_CAEM2 C ON (C.CODUL = D.CAEM2)
 -- INNER JOIN CIS.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
 CROSS JOIN (
 SELECT '00000' AS CODUL, 'TOTAL PE ACTIVITATI' NUME_ROW, 0 NR_ROW, '00000' GRUPA
FROM DUAL
 ) R 
  


WHERE
 (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  FORM = 4 AND
  CAPITOL = 4 AND
  RIND = '10' AND
--  (
--  CC.CODUL LIKE 'H49%'
--  
--  ) AND
  
   (D.PERIOADA BETWEEN FLOOR((:pPERIOADA-12)/12)*12 AND :pPERIOADA-12 OR 
     D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA OR
     D.PERIOADA IN :pPERIOADA-1 
     OR 
     D.PERIOADA IN (:pPERIOADA-12)    
     
     )
     
     GROUP BY 
  R.CODUL,
  R.NUME_ROW
       
       ORDER BY 
   R.CODUL