--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,
--  
--  COL1, COL2, COL3, COL4, COL5, COL6, COL7 , COL8, COL9,
--   COL10, COL11, COL12, COL13, COL14, COL15, COL16 , COL17, COL18, COL19 , COL20, COL21, 
--   COL22, COL23, COL24, COL25, COL26  
--)


SELECT     
--  :pPERIOADA AS PERIOADA,                                                    
--  :pFORM AS FORM,                                                            
--  :pFORM_VERS AS FORM_VERS,                                                  
--  :pID_MDTABLE AS ID_MDTABLE,                                                
--  :pCOD_CUATM AS COD_CUATM,                                                  
--  '0' AS NR_SECTIE,                                                         
--  '0' AS NUME_SECTIE,                                                        
--  '0' AS NR_SECTIE1,
--  '0' AS NUME_SECTIE1,
--  '0' AS NR_SECTIE2,
--  '0' AS NUME_SECTIE2,     
  
   R.CUIIO,
   R.DENUMIRE||'CUATM '||R.CUATM ||' CAEM: '||R.CAEM2||')' AS NUME_ROW,   
--   R.CUIIO AS ORDINE,
--   '00000000000000000000000000' AS DECIMAL_POS,
--   R.DENUMIRE||'CUATM '||R.CUATM ||' CAEM: '||R.CAEM2||')' AS NUME_ROW,
   
 TO_NUMBER(R.CUATM) AS CUATM,
 SUBSTR(R.CAEM2,2,4) AS CAEM2,
 CASE WHEN SUM(L.COL1) = 0 THEN NULL ELSE SUM(L.COL1) END   AS COL1,
 CASE WHEN SUM(L.COL2) = 0 THEN NULL ELSE SUM(L.COL2) END   AS COL2,
 CASE WHEN SUM(L.COL3) = 0 THEN NULL ELSE SUM(L.COL3) END   AS COL3,
 CASE WHEN SUM(L.COL4) = 0 THEN NULL ELSE SUM(L.COL4) END   AS COL4,
 CASE WHEN SUM(L.COL5) = 0 THEN NULL ELSE SUM(L.COL5) END   AS COL5,
 CASE WHEN SUM(L.COL6) = 0 THEN NULL ELSE SUM(L.COL6) END   AS COL6,
 CASE WHEN SUM(L.COL7) = 0 THEN NULL ELSE SUM(L.COL7) END   AS COL7,
 CASE WHEN SUM(L.COL8) = 0 THEN NULL ELSE SUM(L.COL8) END   AS COL8,
 CASE WHEN SUM(L.COL9) = 0 THEN NULL ELSE SUM(L.COL9) END   AS COL9,
 CASE WHEN SUM(L.COL10) = 0 THEN NULL ELSE SUM(L.COL10) END   AS COL10,
 CASE WHEN SUM(L.COL11) = 0 THEN NULL ELSE SUM(L.COL11) END   AS COL11,
 CASE WHEN SUM(L.COL12) = 0 THEN NULL ELSE SUM(L.COL12) END   AS COL12,
 CASE WHEN SUM(L.COL13) = 0 THEN NULL ELSE SUM(L.COL13) END   AS COL13,
 CASE WHEN SUM(L.COL14) = 0 THEN NULL ELSE SUM(L.COL14) END   AS COL14,
 CASE WHEN SUM(L.COL15) = 0 THEN NULL ELSE SUM(L.COL15) END   AS COL15,
 CASE WHEN SUM(L.COL16) = 0 THEN NULL ELSE SUM(L.COL16) END   AS COL16,
 CASE WHEN SUM(L.COL17) = 0 THEN NULL ELSE SUM(L.COL17) END   AS COL17,
 CASE WHEN SUM(L.COL18) = 0 THEN NULL ELSE SUM(L.COL18) END   AS COL18,
 CASE WHEN SUM(L.COL19) = 0 THEN NULL ELSE SUM(L.COL19) END   AS COL19,
 CASE WHEN SUM(L.COL20) = 0 THEN NULL ELSE SUM(L.COL20) END   AS COL20,
 CASE WHEN SUM(L.COL21) = 0 THEN NULL ELSE SUM(L.COL21) END   AS COL21,
 CASE WHEN SUM(L.COL22) = 0 THEN NULL ELSE SUM(L.COL22) END   AS COL22,
 CASE WHEN SUM(L.COL23) = 0 THEN NULL ELSE SUM(L.COL23) END   AS COL23,
 CASE WHEN SUM(L.COL24) = 0 THEN NULL ELSE SUM(L.COL24) END   AS COL24
 
 
           
      FROM

(

SELECT     
           R.CUIIO,
           R.CUIIO_VERS,
           R.DENUMIRE,
           FC.FORM,
           R.CUATM,
           R.CFP,
           R.CFOJ,
           R.CAEM2
           
      FROM (SELECT FC.CUIIO,
                   FC.CUIIO_VERS,
                   FC.FORM,
                   FC.FORM_VERS,
                   FC.STATUT
              FROM CIS.FORM_CUIIO  FC
                   INNER JOIN (  SELECT CUIIO, MAX (CUIIO_VERS) CUIIO_VERS
                                   FROM CIS.FORM_CUIIO
                                  WHERE FORM IN (4) AND CUIIO_VERS <= :pPERIOADA
                               GROUP BY CUIIO) BB
                       ON (    BB.CUIIO = FC.CUIIO
                           AND BB.CUIIO_VERS = FC.CUIIO_VERS)
             WHERE FC.FORM IN (4) AND FC.STATUT <> '3') FC
             
           INNER JOIN CIS.RENIM R
               ON (R.CUIIO = FC.CUIIO AND R.CUIIO_VERS = FC.CUIIO_VERS)
               
                INNER JOIN CIS.VW_CL_CUATM C ON C.CODUL = R.CUATM
               
    WHERE
    1=1
     
     AND  C.FULL_CODE LIKE '%'||:pCOD_CUATM||';%' 
     
     ) R  LEFT JOIN (
     
     SELECT 

DISTINCT D.CUIIO,
  

SUM(CASE WHEN D.CAPITOL IN (4) AND MP.NUM = 1 AND D.RIND IN '10' THEN D.COL1 ELSE 0 END) AS COL1,
    
   SUM(CASE WHEN  D.CAPITOL IN (4) AND MP.NUM = 1 AND D.RIND IN '10' THEN D.COL2 ELSE 0 END) AS COL2,

   SUM(CASE WHEN D.CAPITOL IN (4) AND MP.NUM = 2 AND D.RIND IN '10' THEN D.COL1 ELSE 0 END) AS COL3,
    
   SUM(CASE WHEN  D.CAPITOL IN (4) AND MP.NUM = 2 AND D.RIND IN '10' THEN D.COL2 ELSE 0 END) AS COL4,

 SUM(CASE WHEN D.CAPITOL IN (4) AND MP.NUM = 3 AND D.RIND IN '10' THEN D.COL1 ELSE 0 END) AS COL5,
    
   SUM(CASE WHEN  D.CAPITOL IN (4) AND MP.NUM = 3 AND D.RIND IN '10' THEN D.COL2 ELSE 0 END) AS COL6,

  
   SUM(CASE WHEN D.CAPITOL IN (4) AND MP.NUM = 4 AND D.RIND IN '10' THEN D.COL1 ELSE 0 END) AS COL7,
    
   SUM(CASE WHEN  D.CAPITOL IN (4) AND MP.NUM = 4 AND D.RIND IN '10' THEN D.COL2 ELSE 0 END) AS COL8,
   
    SUM(CASE WHEN D.CAPITOL IN (4) AND MP.NUM = 5 AND D.RIND IN '10' THEN D.COL1 ELSE 0 END) AS COL9,
    
   SUM(CASE WHEN  D.CAPITOL IN (4) AND MP.NUM = 5 AND D.RIND IN '10' THEN D.COL2 ELSE 0 END) AS COL10,
   
     SUM(CASE WHEN D.CAPITOL IN (4) AND MP.NUM = 6 AND D.RIND IN '10' THEN D.COL1 ELSE 0 END) AS COL11,
    
   SUM(CASE WHEN  D.CAPITOL IN (4) AND MP.NUM = 6 AND D.RIND IN '10' THEN D.COL2 ELSE 0 END) AS COL12,
   
   SUM(CASE WHEN D.CAPITOL IN (4) AND MP.NUM = 7 AND D.RIND IN '10' THEN D.COL1 ELSE 0 END) AS COL13,
    
   SUM(CASE WHEN  D.CAPITOL IN (4) AND MP.NUM = 7 AND D.RIND IN '10' THEN D.COL2 ELSE 0 END) AS COL14,
   
   
   SUM(CASE WHEN D.CAPITOL IN (4) AND MP.NUM = 8 AND D.RIND IN '10' THEN D.COL1 ELSE 0 END) AS COL15,
    
   SUM(CASE WHEN  D.CAPITOL IN (4) AND MP.NUM = 8 AND D.RIND IN '10' THEN D.COL2 ELSE 0 END) AS COL16,
   
    SUM(CASE WHEN D.CAPITOL IN (4) AND MP.NUM = 9 AND D.RIND IN '10' THEN D.COL1 ELSE 0 END) AS COL17,
    
   SUM(CASE WHEN  D.CAPITOL IN (4) AND MP.NUM = 9 AND D.RIND IN '10' THEN D.COL2 ELSE 0 END) AS COL18,
 

  SUM(CASE WHEN D.CAPITOL IN (4) AND MP.NUM = 10 AND D.RIND IN '10' THEN D.COL1 ELSE 0 END) AS COL19,
    
   SUM(CASE WHEN  D.CAPITOL IN (4) AND MP.NUM = 10 AND D.RIND IN '10' THEN D.COL2 ELSE 0 END) AS COL20,
 

   SUM(CASE WHEN D.CAPITOL IN (4) AND MP.NUM = 11 AND D.RIND IN '10' THEN D.COL1 ELSE 0 END) AS COL21,
    
   SUM(CASE WHEN  D.CAPITOL IN (4) AND MP.NUM = 11 AND D.RIND IN '10' THEN D.COL2 ELSE 0 END) AS COL22,
   
    SUM(CASE WHEN D.CAPITOL IN (4) AND MP.NUM = 12 AND D.RIND IN '10' THEN D.COL1 ELSE 0 END) AS COL23,
    
   SUM(CASE WHEN  D.CAPITOL IN (4) AND MP.NUM = 12 AND D.RIND IN '10' THEN D.COL2 ELSE 0 END) AS COL24

FROM CIS.VW_DATA_ALL D


                INNER JOIN (
                SELECT
P.NUM,
P.PERIOADA

 
FROM CIS2.MD_PERIOADA P
            INNER JOIN (


SELECT
P.ANUL,
P.PERIOADA,
P.NUM,
P.TIP_PERIOADA
 
FROM CIS2.MD_PERIOADA P

WHERE
P.PERIOADA = :pPERIOADA 


GROUP BY 
P.ANUL,
P.PERIOADA,
P.NUM, 
P.TIP_PERIOADA

) L ON  P.ANUL = L.ANUL  AND P.TIP_PERIOADA = 4
                
                ) MP ON (MP.PERIOADA = D.PERIOADA) 


               
               
WHERE
  (D.FORM=:pFORM) AND
 (D.FORM_VERS=:pFORM_VERS) AND
 (:pID_MDTABLE=:pID_MDTABLE) AND
  D.FORM = 4 
  
--  AND D.PERIOADA IN (:pPERIOADA)
AND 
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' 
  
  AND
  D.CAPITOL IN (0,4)
  
  -- AND D.CUIIO IN (297922)
  
  
 GROUP BY
 D.CUIIO
     
     ) L ON R.CUIIO = L.CUIIO 
     
     
     
     GROUP BY 
     
      R.CUIIO,
          
           R.DENUMIRE,
         
           R.CUATM,
         
           R.CAEM2