CREATE USER SPOTLIGHT
  IDENTIFIED BY  oracle
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 4 Roles for SPOTLIGHT 
  GRANT CWM_USER TO SPOTLIGHT;
  GRANT DATAPUMP_EXP_FULL_DATABASE TO SPOTLIGHT;
  GRANT RESOURCE TO SPOTLIGHT;
  GRANT SELECT_CATALOG_ROLE TO SPOTLIGHT;
  ALTER USER SPOTLIGHT DEFAULT ROLE ALL;
  -- 12 System Privileges for SPOTLIGHT 
  GRANT ALTER SESSION TO SPOTLIGHT;
  GRANT CREATE CLUSTER TO SPOTLIGHT;
  GRANT CREATE DATABASE LINK TO SPOTLIGHT;
  GRANT CREATE DIMENSION TO SPOTLIGHT;
  GRANT CREATE MATERIALIZED VIEW TO SPOTLIGHT;
  GRANT CREATE SEQUENCE TO SPOTLIGHT;
  GRANT CREATE SESSION TO SPOTLIGHT;
  GRANT CREATE SYNONYM TO SPOTLIGHT;
  GRANT CREATE TABLE TO SPOTLIGHT;
  GRANT CREATE VIEW TO SPOTLIGHT;
  GRANT QUERY REWRITE TO SPOTLIGHT;
  GRANT UNLIMITED TABLESPACE TO SPOTLIGHT;
  -- 3 Object Privileges for SPOTLIGHT 
    GRANT READ ON DIRECTORY DATA_FILE_DIR TO SPOTLIGHT;
    GRANT EXECUTE ON SYS.DBMS_STATS TO SPOTLIGHT;
    GRANT READ, WRITE ON DIRECTORY LOG_FILE_DIR TO SPOTLIGHT;