CREATE USER REGISTRU
  IDENTIFIED BY  oracle
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 4 Roles for REGISTRU 
  GRANT CWM_USER TO REGISTRU;
  GRANT DATAPUMP_EXP_FULL_DATABASE TO REGISTRU;
  GRANT RESOURCE TO REGISTRU;
  GRANT SELECT_CATALOG_ROLE TO REGISTRU;
  ALTER USER REGISTRU DEFAULT ROLE ALL;
  -- 12 System Privileges for REGISTRU 
  GRANT ALTER SESSION TO REGISTRU;
  GRANT CREATE CLUSTER TO REGISTRU;
  GRANT CREATE DATABASE LINK TO REGISTRU;
  GRANT CREATE DIMENSION TO REGISTRU;
  GRANT CREATE MATERIALIZED VIEW TO REGISTRU;
  GRANT CREATE SEQUENCE TO REGISTRU;
  GRANT CREATE SESSION TO REGISTRU;
  GRANT CREATE SYNONYM TO REGISTRU;
  GRANT CREATE TABLE TO REGISTRU;
  GRANT CREATE VIEW TO REGISTRU;
  GRANT QUERY REWRITE TO REGISTRU;
  GRANT UNLIMITED TABLESPACE TO REGISTRU;
  -- 3 Object Privileges for REGISTRU 
    GRANT READ ON DIRECTORY DATA_FILE_DIR TO REGISTRU;
    GRANT EXECUTE ON SYS.DBMS_STATS TO REGISTRU;
    GRANT READ, WRITE ON DIRECTORY LOG_FILE_DIR TO REGISTRU;