CREATE TABLE REGISTRU.FINAL_REGISTRU_MD
(
  IDNO            NUMBER,
  DATA_REG        DATE,
  DEN_COM         VARCHAR2(1024 BYTE),
  FORMA_ORG       VARCHAR2(1024 BYTE),
  ADRESA          VARCHAR2(1024 BYTE),
  LIST_COND       VARCHAR2(1024 BYTE),
  LISTA_FOND      NVARCHAR2(2000),
  GEN_ACT_NE_LIC  VARCHAR2(1024 BYTE),
  GEN_ACT_LIC     VARCHAR2(1024 BYTE),
  STATUTUL        VARCHAR2(1024 BYTE),
  DATA_CREATE     DATE,
  FACEBOOK        VARCHAR2(1024 BYTE),
  LINKEDIN        VARCHAR2(1024 BYTE),
  WEBSITE         VARCHAR2(1024 BYTE)
)
TABLESPACE TBS_DTI_USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE OR REPLACE TRIGGER REGISTRU.TRG_MD_DATA_CREATE_FINAL
BEFORE INSERT OR UPDATE ON REGISTRU.FINAL_REGISTRU_MD FOR EACH ROW
BEGIN
  :NEW.DATA_CREATE := SYSDATE;
END;