DROP USER SPOTLIGHT CASCADE;

CREATE USER SPOTLIGHT
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for SPOTLIGHT 
  GRANT CONNECT TO SPOTLIGHT;
  ALTER USER SPOTLIGHT DEFAULT ROLE ALL;
  -- 202 System Privileges for SPOTLIGHT 
  GRANT ADMINISTER ANY SQL TUNING SET TO SPOTLIGHT;
  GRANT ADMINISTER DATABASE TRIGGER TO SPOTLIGHT;
  BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'SPOTLIGHT', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => FALSE);
END;
/
  GRANT ADMINISTER SQL MANAGEMENT OBJECT TO SPOTLIGHT;
  GRANT ADMINISTER SQL TUNING SET TO SPOTLIGHT;
  GRANT ADVISOR TO SPOTLIGHT;
  GRANT ALTER ANY ASSEMBLY TO SPOTLIGHT;
  GRANT ALTER ANY CLUSTER TO SPOTLIGHT;
  GRANT ALTER ANY CUBE TO SPOTLIGHT;
  GRANT ALTER ANY CUBE DIMENSION TO SPOTLIGHT;
  GRANT ALTER ANY DIMENSION TO SPOTLIGHT;
  GRANT ALTER ANY EDITION TO SPOTLIGHT;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'SPOTLIGHT',
  GRANT_OPTION => FALSE);
END;
/
  GRANT ALTER ANY INDEX TO SPOTLIGHT;
  GRANT ALTER ANY INDEXTYPE TO SPOTLIGHT;
  GRANT ALTER ANY LIBRARY TO SPOTLIGHT;
  GRANT ALTER ANY MATERIALIZED VIEW TO SPOTLIGHT;
  GRANT ALTER ANY MINING MODEL TO SPOTLIGHT;
  GRANT ALTER ANY OPERATOR TO SPOTLIGHT;
  GRANT ALTER ANY OUTLINE TO SPOTLIGHT;
  GRANT ALTER ANY PROCEDURE TO SPOTLIGHT;
  GRANT ALTER ANY ROLE TO SPOTLIGHT;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE,
  GRANTEE      => 'SPOTLIGHT',
  GRANT_OPTION => FALSE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE_SET,
  GRANTEE      => 'SPOTLIGHT',
  GRANT_OPTION => FALSE);
END;
/
  GRANT ALTER ANY SEQUENCE TO SPOTLIGHT;
  GRANT ALTER ANY SQL PROFILE TO SPOTLIGHT;
  GRANT ALTER ANY TABLE TO SPOTLIGHT;
  GRANT ALTER ANY TRIGGER TO SPOTLIGHT;
  GRANT ALTER ANY TYPE TO SPOTLIGHT;
  GRANT ALTER DATABASE TO SPOTLIGHT;
  GRANT ALTER PROFILE TO SPOTLIGHT;
  GRANT ALTER RESOURCE COST TO SPOTLIGHT;
  GRANT ALTER ROLLBACK SEGMENT TO SPOTLIGHT;
  GRANT ALTER SESSION TO SPOTLIGHT;
  GRANT ALTER SYSTEM TO SPOTLIGHT;
  GRANT ALTER TABLESPACE TO SPOTLIGHT;
  GRANT ALTER USER TO SPOTLIGHT;
  GRANT ANALYZE ANY TO SPOTLIGHT;
  GRANT ANALYZE ANY DICTIONARY TO SPOTLIGHT;
  GRANT AUDIT ANY TO SPOTLIGHT;
  GRANT AUDIT SYSTEM TO SPOTLIGHT;
  GRANT BACKUP ANY TABLE TO SPOTLIGHT;
  GRANT BECOME USER TO SPOTLIGHT;
  GRANT CHANGE NOTIFICATION TO SPOTLIGHT;
  GRANT COMMENT ANY MINING MODEL TO SPOTLIGHT;
  GRANT COMMENT ANY TABLE TO SPOTLIGHT;
  GRANT CREATE ANY ASSEMBLY TO SPOTLIGHT;
  GRANT CREATE ANY CLUSTER TO SPOTLIGHT;
  GRANT CREATE ANY CONTEXT TO SPOTLIGHT;
  GRANT CREATE ANY CUBE TO SPOTLIGHT;
  GRANT CREATE ANY CUBE BUILD PROCESS TO SPOTLIGHT;
  GRANT CREATE ANY CUBE DIMENSION TO SPOTLIGHT;
  GRANT CREATE ANY DIMENSION TO SPOTLIGHT;
  GRANT CREATE ANY DIRECTORY TO SPOTLIGHT;
  GRANT CREATE ANY EDITION TO SPOTLIGHT;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'SPOTLIGHT',
  GRANT_OPTION => FALSE);
END;
/
  GRANT CREATE ANY INDEX TO SPOTLIGHT;
  GRANT CREATE ANY INDEXTYPE TO SPOTLIGHT;
  GRANT CREATE ANY JOB TO SPOTLIGHT;
  GRANT CREATE ANY LIBRARY TO SPOTLIGHT;
  GRANT CREATE ANY MATERIALIZED VIEW TO SPOTLIGHT;
  GRANT CREATE ANY MEASURE FOLDER TO SPOTLIGHT;
  GRANT CREATE ANY MINING MODEL TO SPOTLIGHT;
  GRANT CREATE ANY OPERATOR TO SPOTLIGHT;
  GRANT CREATE ANY OUTLINE TO SPOTLIGHT;
  GRANT CREATE ANY PROCEDURE TO SPOTLIGHT;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE,
  GRANTEE      => 'SPOTLIGHT',
  GRANT_OPTION => FALSE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE_SET,
  GRANTEE      => 'SPOTLIGHT',
  GRANT_OPTION => FALSE);
END;
/
  GRANT CREATE ANY SEQUENCE TO SPOTLIGHT;
  GRANT CREATE ANY SQL PROFILE TO SPOTLIGHT;
  GRANT CREATE ANY SYNONYM TO SPOTLIGHT;
  GRANT CREATE ANY TABLE TO SPOTLIGHT;
  GRANT CREATE ANY TRIGGER TO SPOTLIGHT;
  GRANT CREATE ANY TYPE TO SPOTLIGHT;
  GRANT CREATE ANY VIEW TO SPOTLIGHT;
  GRANT CREATE ASSEMBLY TO SPOTLIGHT;
  GRANT CREATE CLUSTER TO SPOTLIGHT;
  GRANT CREATE CUBE TO SPOTLIGHT;
  GRANT CREATE CUBE BUILD PROCESS TO SPOTLIGHT;
  GRANT CREATE CUBE DIMENSION TO SPOTLIGHT;
  GRANT CREATE DATABASE LINK TO SPOTLIGHT;
  GRANT CREATE DIMENSION TO SPOTLIGHT;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'SPOTLIGHT',
  GRANT_OPTION => FALSE);
END;
/
  GRANT CREATE EXTERNAL JOB TO SPOTLIGHT;
  GRANT CREATE INDEXTYPE TO SPOTLIGHT;
  GRANT CREATE JOB TO SPOTLIGHT;
  GRANT CREATE LIBRARY TO SPOTLIGHT;
  GRANT CREATE MATERIALIZED VIEW TO SPOTLIGHT;
  GRANT CREATE MEASURE FOLDER TO SPOTLIGHT;
  GRANT CREATE MINING MODEL TO SPOTLIGHT;
  GRANT CREATE OPERATOR TO SPOTLIGHT;
  GRANT CREATE PROCEDURE TO SPOTLIGHT;
  GRANT CREATE PROFILE TO SPOTLIGHT;
  GRANT CREATE PUBLIC DATABASE LINK TO SPOTLIGHT;
  GRANT CREATE PUBLIC SYNONYM TO SPOTLIGHT;
  GRANT CREATE ROLE TO SPOTLIGHT;
  GRANT CREATE ROLLBACK SEGMENT TO SPOTLIGHT;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'SPOTLIGHT',
  GRANT_OPTION => FALSE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'SPOTLIGHT',
  GRANT_OPTION => FALSE);
END;
/
  GRANT CREATE SEQUENCE TO SPOTLIGHT;
  GRANT CREATE SESSION TO SPOTLIGHT;
  GRANT CREATE SYNONYM TO SPOTLIGHT;
  GRANT CREATE TABLE TO SPOTLIGHT;
  GRANT CREATE TABLESPACE TO SPOTLIGHT;
  GRANT CREATE TRIGGER TO SPOTLIGHT;
  GRANT CREATE TYPE TO SPOTLIGHT;
  GRANT CREATE USER TO SPOTLIGHT;
  GRANT CREATE VIEW TO SPOTLIGHT;
  GRANT DEBUG ANY PROCEDURE TO SPOTLIGHT;
  GRANT DEBUG CONNECT SESSION TO SPOTLIGHT;
  GRANT DELETE ANY CUBE DIMENSION TO SPOTLIGHT;
  GRANT DELETE ANY MEASURE FOLDER TO SPOTLIGHT;
  GRANT DELETE ANY TABLE TO SPOTLIGHT;
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'SPOTLIGHT',
  ADMIN_OPTION => FALSE);
END;
/
  GRANT DROP ANY ASSEMBLY TO SPOTLIGHT;
  GRANT DROP ANY CLUSTER TO SPOTLIGHT;
  GRANT DROP ANY CONTEXT TO SPOTLIGHT;
  GRANT DROP ANY CUBE TO SPOTLIGHT;
  GRANT DROP ANY CUBE BUILD PROCESS TO SPOTLIGHT;
  GRANT DROP ANY CUBE DIMENSION TO SPOTLIGHT;
  GRANT DROP ANY DIMENSION TO SPOTLIGHT;
  GRANT DROP ANY DIRECTORY TO SPOTLIGHT;
  GRANT DROP ANY EDITION TO SPOTLIGHT;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'SPOTLIGHT',
  GRANT_OPTION => FALSE);
END;
/
  GRANT DROP ANY INDEX TO SPOTLIGHT;
  GRANT DROP ANY INDEXTYPE TO SPOTLIGHT;
  GRANT DROP ANY LIBRARY TO SPOTLIGHT;
  GRANT DROP ANY MATERIALIZED VIEW TO SPOTLIGHT;
  GRANT DROP ANY MEASURE FOLDER TO SPOTLIGHT;
  GRANT DROP ANY MINING MODEL TO SPOTLIGHT;
  GRANT DROP ANY OPERATOR TO SPOTLIGHT;
  GRANT DROP ANY OUTLINE TO SPOTLIGHT;
  GRANT DROP ANY PROCEDURE TO SPOTLIGHT;
  GRANT DROP ANY ROLE TO SPOTLIGHT;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE,
  GRANTEE      => 'SPOTLIGHT',
  GRANT_OPTION => FALSE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE_SET,
  GRANTEE      => 'SPOTLIGHT',
  GRANT_OPTION => FALSE);
END;
/
  GRANT DROP ANY SEQUENCE TO SPOTLIGHT;
  GRANT DROP ANY SQL PROFILE TO SPOTLIGHT;
  GRANT DROP ANY SYNONYM TO SPOTLIGHT;
  GRANT DROP ANY TABLE TO SPOTLIGHT;
  GRANT DROP ANY TRIGGER TO SPOTLIGHT;
  GRANT DROP ANY TYPE TO SPOTLIGHT;
  GRANT DROP ANY VIEW TO SPOTLIGHT;
  GRANT DROP PROFILE TO SPOTLIGHT;
  GRANT DROP PUBLIC DATABASE LINK TO SPOTLIGHT;
  GRANT DROP PUBLIC SYNONYM TO SPOTLIGHT;
  GRANT DROP ROLLBACK SEGMENT TO SPOTLIGHT;
  GRANT DROP TABLESPACE TO SPOTLIGHT;
  GRANT DROP USER TO SPOTLIGHT;
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'SPOTLIGHT',
  ADMIN_OPTION => FALSE);
END;
/
  GRANT EXECUTE ANY ASSEMBLY TO SPOTLIGHT;
  GRANT EXECUTE ANY CLASS TO SPOTLIGHT;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'SPOTLIGHT',
  GRANT_OPTION => FALSE);
END;
/
  GRANT EXECUTE ANY INDEXTYPE TO SPOTLIGHT;
  GRANT EXECUTE ANY LIBRARY TO SPOTLIGHT;
  GRANT EXECUTE ANY OPERATOR TO SPOTLIGHT;
  GRANT EXECUTE ANY PROCEDURE TO SPOTLIGHT;
  GRANT EXECUTE ANY PROGRAM TO SPOTLIGHT;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE,
  GRANTEE      => 'SPOTLIGHT',
  GRANT_OPTION => FALSE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE_SET,
  GRANTEE      => 'SPOTLIGHT',
  GRANT_OPTION => FALSE);
END;
/
  GRANT EXECUTE ANY TYPE TO SPOTLIGHT;
  GRANT EXECUTE ASSEMBLY TO SPOTLIGHT;
  GRANT EXPORT FULL DATABASE TO SPOTLIGHT;
  GRANT FLASHBACK ANY TABLE TO SPOTLIGHT;
  GRANT FLASHBACK ARCHIVE ADMINISTER TO SPOTLIGHT;
  GRANT FORCE ANY TRANSACTION TO SPOTLIGHT;
  GRANT FORCE TRANSACTION TO SPOTLIGHT;
  GRANT GLOBAL QUERY REWRITE TO SPOTLIGHT;
  GRANT GRANT ANY OBJECT PRIVILEGE TO SPOTLIGHT;
  GRANT GRANT ANY PRIVILEGE TO SPOTLIGHT;
  GRANT GRANT ANY ROLE TO SPOTLIGHT;
  GRANT IMPORT FULL DATABASE TO SPOTLIGHT;
  GRANT INSERT ANY CUBE DIMENSION TO SPOTLIGHT;
  GRANT INSERT ANY MEASURE FOLDER TO SPOTLIGHT;
  GRANT INSERT ANY TABLE TO SPOTLIGHT;
  GRANT LOCK ANY TABLE TO SPOTLIGHT;
  GRANT MANAGE ANY FILE GROUP TO SPOTLIGHT;
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'SPOTLIGHT',
  ADMIN_OPTION => FALSE);
END;
/
  GRANT MANAGE FILE GROUP TO SPOTLIGHT;
  GRANT MANAGE SCHEDULER TO SPOTLIGHT;
  GRANT MANAGE TABLESPACE TO SPOTLIGHT;
  GRANT MERGE ANY VIEW TO SPOTLIGHT;
  GRANT ON COMMIT REFRESH TO SPOTLIGHT;
  GRANT QUERY REWRITE TO SPOTLIGHT;
  GRANT READ ANY FILE GROUP TO SPOTLIGHT;
  GRANT RESTRICTED SESSION TO SPOTLIGHT;
  GRANT RESUMABLE TO SPOTLIGHT;
  GRANT SELECT ANY CUBE TO SPOTLIGHT;
  GRANT SELECT ANY CUBE DIMENSION TO SPOTLIGHT;
  GRANT SELECT ANY DICTIONARY TO SPOTLIGHT;
  GRANT SELECT ANY MINING MODEL TO SPOTLIGHT;
  GRANT SELECT ANY SEQUENCE TO SPOTLIGHT;
  GRANT SELECT ANY TABLE TO SPOTLIGHT;
  GRANT SELECT ANY TRANSACTION TO SPOTLIGHT;
  GRANT UNDER ANY TABLE TO SPOTLIGHT;
  GRANT UNDER ANY TYPE TO SPOTLIGHT;
  GRANT UNDER ANY VIEW TO SPOTLIGHT;
  GRANT UNLIMITED TABLESPACE TO SPOTLIGHT;
  GRANT UPDATE ANY CUBE TO SPOTLIGHT;
  GRANT UPDATE ANY CUBE BUILD PROCESS TO SPOTLIGHT;
  GRANT UPDATE ANY CUBE DIMENSION TO SPOTLIGHT;
  GRANT UPDATE ANY TABLE TO SPOTLIGHT;
  -- 32 Object Privileges for SPOTLIGHT 
    GRANT SELECT ON SYS.COL$ TO SPOTLIGHT;
    GRANT SELECT ON SYS.DBA_DATA_FILES TO SPOTLIGHT;
    GRANT SELECT ON SYS.DBA_EXTENTS TO SPOTLIGHT;
    GRANT SELECT ON SYS.DBA_FREE_SPACE TO SPOTLIGHT;
    GRANT SELECT ON SYS.DBA_HIST_ACTIVE_SESS_HISTORY TO SPOTLIGHT;
    GRANT SELECT ON SYS.DBA_INDEXES TO SPOTLIGHT;
    GRANT SELECT ON SYS.DBA_IND_COLUMNS TO SPOTLIGHT;
    GRANT SELECT ON SYS.DBA_JOBS TO SPOTLIGHT;
    GRANT SELECT ON SYS.DBA_JOBS_RUNNING TO SPOTLIGHT;
    GRANT SELECT ON SYS.DBA_OBJECTS TO SPOTLIGHT;
    GRANT SELECT ON SYS.DBA_TABLES TO SPOTLIGHT;
    GRANT SELECT ON SYS.DBA_TAB_COLUMNS TO SPOTLIGHT;
    GRANT SELECT ON SYS.DBA_TAB_PRIVS TO SPOTLIGHT;
    GRANT SELECT ON SYS.DBA_TEMP_FILES TO SPOTLIGHT;
    GRANT SELECT ON SYS.DBA_USERS TO SPOTLIGHT;
    GRANT EXECUTE ON SYS.DBMS_JOB TO SPOTLIGHT;
    GRANT EXECUTE ON SYS.DBMS_LOB TO SPOTLIGHT;
    GRANT EXECUTE ON SYS.DBMS_MONITOR TO SPOTLIGHT;
    GRANT EXECUTE ON SYS.DBMS_RESULT_CACHE TO SPOTLIGHT;
    GRANT SELECT ON SYS.FET$ TO SPOTLIGHT;
    GRANT SELECT ON SYS.FILE$ TO SPOTLIGHT;
    GRANT SELECT ON SYS.OBJ$ TO SPOTLIGHT;
    GRANT READ ON DIRECTORY QUEST_SOO_ADUMP_DIR TO SPOTLIGHT;
    GRANT READ ON DIRECTORY QUEST_SOO_BDUMP_DIR TO SPOTLIGHT;
    GRANT READ ON DIRECTORY QUEST_SOO_CDUMP_DIR TO SPOTLIGHT;
    GRANT READ ON DIRECTORY QUEST_SOO_UDUMP_DIR TO SPOTLIGHT;
    GRANT SELECT ON SYS.SEG$ TO SPOTLIGHT;
    GRANT SELECT ON SYS.TS$ TO SPOTLIGHT;
    GRANT SELECT ON SYS.UET$ TO SPOTLIGHT;
    GRANT SELECT ON SYS.UNDO$ TO SPOTLIGHT;
    GRANT SELECT ON SYS.USER$ TO SPOTLIGHT;
    GRANT EXECUTE ON SYS.UTL_FILE TO SPOTLIGHT;
