   SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   B.NR AS NR_ROW,
   B.ORDINE AS ORDINE,
  '0000000000000000' AS DECIMAL_POS,
   B.NUME_SECTIE AS NUME_ROW,  
   
   CASE WHEN COL1 = 0 THEN NULL ELSE COL1 END AS COL1,
   CASE WHEN COL2 = 0 THEN NULL ELSE COL2 END AS COL2,
   CASE WHEN COL3 = 0 THEN NULL ELSE COL3 END AS COL3,
   CASE WHEN COL4 = 0 THEN NULL ELSE COL4 END AS COL4,
   CASE WHEN COL5 = 0 THEN NULL ELSE COL5 END AS COL5,
   CASE WHEN COL6 = 0 THEN NULL ELSE COL6 END AS COL6,
   CASE WHEN COL7 = 0 THEN NULL ELSE COL7 END AS COL7,
   CASE WHEN COL8 = 0 THEN NULL ELSE COL8 END AS COL8,
   CASE WHEN COL9 = 0 THEN NULL ELSE COL9 END AS COL9,
   CASE WHEN COL10 = 0 THEN NULL ELSE COL10 END AS COL10,
   CASE WHEN COL11 = 0 THEN NULL ELSE COL11 END AS COL11,
   CASE WHEN COL12 = 0 THEN NULL ELSE COL12 END AS COL12,
   CASE WHEN COL13 = 0 THEN NULL ELSE COL13 END AS COL13,
   CASE WHEN COL14 = 0 THEN NULL ELSE COL14 END AS COL14,
   CASE WHEN COL15 = 0 THEN NULL ELSE COL15 END AS COL15,
   CASE WHEN COL16 = 0 THEN NULL ELSE COL16 END AS COL16
   
   FROM
   (
   
   ;
   ----------------------------------------------
   
   CASE WHEN COL1 = 0 THEN NULL ELSE COL1 END AS COL1,
   CASE WHEN COL2 = 0 THEN NULL ELSE COL2 END AS COL2,
   CASE WHEN COL3 = 0 THEN NULL ELSE COL3 END AS COL3,
   CASE WHEN COL4 = 0 THEN NULL ELSE COL4 END AS COL4,
   CASE WHEN COL5 = 0 THEN NULL ELSE COL5 END AS COL5,
   CASE WHEN COL6 = 0 THEN NULL ELSE COL6 END AS COL6,
   CASE WHEN COL7 = 0 THEN NULL ELSE COL7 END AS COL7