SELECT
   PERIOADA,
   FORM,
   FORM_VERS,
   ID_MDTABLE,
   COD_CUATM,
   NR_SECTIE,
   NUME_SECTIE,
   NR_SECTIE1,
   NUME_SECTIE1,
   NR_SECTIE2,
   NUME_SECTIE2,
   NR_ROW,
   ORDINE,
   DECIMAL_POS,
   NUME_ROW, 
   
   
   
   CASE WHEN COL1 = 0 THEN NULL ELSE COL1 END AS COL1,
   CASE WHEN COL2 = 0 THEN NULL ELSE COL2 END AS COL2,
   CASE WHEN COL3 = 0 THEN NULL ELSE COL3 END AS COL3,
   CASE WHEN COL4 = 0 THEN NULL ELSE COL4 END AS COL4,
   CASE WHEN COL5 = 0 THEN NULL ELSE COL5 END AS COL5,
   CASE WHEN COL6 = 0 THEN NULL ELSE COL6 END AS COL6,
   CASE WHEN COL7 = 0 THEN NULL ELSE COL7 END AS COL7,
   CASE WHEN COL8 = 0 THEN NULL ELSE COL8 END AS COL8,
   CASE WHEN COL9 = 0 THEN NULL ELSE COL9 END AS COL9,
   CASE WHEN COL10 = 0 THEN NULL ELSE COL10 END AS COL10,
   CASE WHEN COL11 = 0 THEN NULL ELSE COL11 END AS COL11,
   CASE WHEN COL12 = 0 THEN NULL ELSE COL12 END AS COL12,
   CASE WHEN COL13 = 0 THEN NULL ELSE COL13 END AS COL13
  
 FROM
(