
  

    SELECT 
    '1' ORDINE,
    CC.CODUL,
    CC.DENUMIRE,
    CC.FULL_CODE,
--    R.DENUMIRE DENUMIRE,
--    CC.DENUMIRE CUATM_DENUMIRE,
    SUM(D.COL11) AS COL11,
    SUM(D.COL12) AS COL12,
    SUM(D.COL13) AS COL13,
   SUM(NVAL(D.COL11)+NVAL(D.COL12)+NVAL(D.COL13)) COL6  
  
FROM 
  CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
  INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM=C.CODUL)
  INNER JOIN CIS2.VW_CL_CUATM CC ON  C.FULL_CODE LIKE '%'||CC.CODUL||';%'
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 40 AND 
  R.NTII IN (30,31) AND
  
  D.CAPITOL IN 1022 
  
  --AND CC.CODUL IN ('0000000')
  
  AND CC.PRGS IN  ('2')
  AND D.CAPITOL IN 1022 
  AND D.RIND IN ('19')
  
  GROUP BY 
 -- R.DENUMIRE,
--  CC.DENUMIRE,
 -- D.CUIIO
  CC.FULL_CODE,
  CC.CODUL,
   CC.DENUMIRE
  
  
 
 
 UNION 
 
 SELECT *
FROM

(
SELECT 
    '2' ORDINE,

    R.DENUMIRE DENUMIRE,
    C.DENUMIRE CUATM_DENUMIRE,
     C.FULL_CODE,
    SUM(D.COL11) AS COL11,
    SUM(D.COL12) AS COL12,
    SUM(D.COL13) AS COL13,
    SUM(NVAL(D.COL11)+NVAL(D.COL12)+NVAL(D.COL13)) COL6  
  
FROM 
  CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
  INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM=C.CODUL)
 -- INNER JOIN CIS2.VW_CL_CUATM CC ON  C.FULL_CODE LIKE '%'||CC.CODUL||';%'
  
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 40 AND 
  R.NTII IN (30,31) AND
  
  D.CAPITOL IN 1022 
  AND D.RIND IN ('19')
  

  
  
  GROUP BY 
   D.CUIIO,
   C.FULL_CODE,
   R.DENUMIRE,
   C.DENUMIRE 
   
   ORDER BY
   C.FULL_CODE,
   D.CUIIO
   )
     
   
   ORDER BY 
   
   
   FULL_CODE,
   ORDINE  