SELECT  

DISTINCT D.CUIIO,
CASE WHEN SUBSTR(C.CODUL,1,2) = '01'  

  THEN 'MUN.CHISINAU' ELSE C.CODUL   END AS CODUL,
R.DENUMIRE,
R.CUATM,
C.FULL_CODE,
SUM(CASE WHEN D.CAPITOL = 1022 AND D.RIND IN ('19') THEN NVAL(D.COL1) + NVAL(D.COL3) + NVAL(D.COL4) + NVAL(D.COL5) ELSE NULL END) AS COL1,
SUM(CASE WHEN D.CAPITOL = 1022 AND D.RIND IN ('19') THEN NVAL(D.COL1) + NVAL(D.COL6) + NVAL(D.COL7) + NVAL(D.COL8) + NVAL(D.COL9) + NVAL(D.COL10) ELSE NULL END) AS COL2,
SUM(CASE WHEN D.CAPITOL = 1022 AND D.RIND IN ('19') THEN NVAL(D.COL11) + NVAL(D.COL12) + NVAL(D.COL13) ELSE NULL END) AS COL3,
SUM(CASE WHEN D.CAPITOL = 1022 AND D.RIND IN ('19') THEN NVAL(D.COL14) ELSE NULL END) AS COL4

 
FROM CIS2.VW_DATA_ALL D

 INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
   INNER JOIN  CIS2.VW_CL_CUATM C ON C.CODUL = D.CUATM 

WHERE 
  (D.PERIOADA =:pPERIOADA)
  AND D.FORM = 40

GROUP BY 
D.CUIIO,
R.DENUMIRE,
R.CUATM,
SUBSTR(C.CODUL,1,2),
C.CODUL,
C.FULL_CODE

ORDER BY 
C.FULL_CODE
