SELECT
R.DENUMIRE_RAION,
L.CUIIO,
L.DENUMIRE,
--L.CODUL_MODIF,
L.CUATM,
L.DENUMIRE_CUATM,
L.COL1,
L.COL2,
L.COL3,
L.COL4 
FROM 
(

SELECT  
DISTINCT D.CUIIO,
SUBSTR(C.CODUL,1,2) AS CODUL_MODIF,
R.DENUMIRE,
R.CUATM,
C.DENUMIRE DENUMIRE_CUATM,
C.FULL_CODE,
SUM(CASE WHEN D.CAPITOL = 1022 AND D.RIND IN ('19') THEN NVAL(D.COL1) + NVAL(D.COL3) + NVAL(D.COL4) + NVAL(D.COL5) ELSE NULL END) AS COL1,
SUM(CASE WHEN D.CAPITOL = 1022 AND D.RIND IN ('19') THEN NVAL(D.COL6) + NVAL(D.COL7) + NVAL(D.COL8) + NVAL(D.COL9) + NVAL(D.COL10) ELSE NULL END) AS COL2,
SUM(CASE WHEN D.CAPITOL = 1022 AND D.RIND IN ('19') THEN NVAL(D.COL11) + NVAL(D.COL12) + NVAL(D.COL13) ELSE NULL END) AS COL3,
SUM(CASE WHEN D.CAPITOL = 1022 AND D.RIND IN ('19') THEN NVAL(D.COL14) ELSE NULL END) AS COL4

 
FROM CIS2.VW_DATA_ALL D

 INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
   INNER JOIN  CIS2.VW_CL_CUATM C ON C.CODUL = D.CUATM 

WHERE 
  (D.PERIOADA =:pPERIOADA)
  AND D.FORM = 40

GROUP BY 
D.CUIIO,
R.DENUMIRE,
R.CUATM,
SUBSTR(C.CODUL,1,2),
C.CODUL,
C.FULL_CODE,
C.DENUMIRE

ORDER BY 
C.FULL_CODE
) L LEFT JOIN (

       SELECT  
       C.CODUL,
       SUBSTR(C.CODUL,1,2) AS CODUL_MODIF,
       C.DENUMIRE  DENUMIRE_RAION
       FROM  CIS2.VW_CL_CUATM C
       
       WHERE 
       C.PRGS IN ('2')
       AND C.CODUL NOT IN '0000000'
) R ON R.CODUL_MODIF = L.CODUL_MODIF