


SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
   D.CODUL AS NR_SECTIE,
   D.LOCALITATE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   D.RIND AS NR_ROW,
   ORDINE,
  '00000000000000' AS DECIMAL_POS,
   CASE WHEN D.RIND IN ('20','21') THEN REPLACE(D.DENUMIRE, 'Fete', 'Baieti') ELSE D.DENUMIRE END AS NUME_ROW,
   
   --COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14
   CASE WHEN COL1 = 0 THEN NULL ELSE COL1 END AS COL1,
  CASE WHEN COL2 = 0 THEN NULL ELSE COL2 END AS COL2,
  CASE WHEN COL3 = 0 THEN NULL ELSE COL3 END AS COL3,
  CASE WHEN COL4 = 0 THEN NULL ELSE COL4 END AS COL4,
  CASE WHEN COL5 = 0 THEN NULL ELSE COL5 END AS COL5,
  CASE WHEN COL6 = 0 THEN NULL ELSE COL6 END AS COL6,
  CASE WHEN COL7 = 0 THEN NULL ELSE COL7 END AS COL7,
  CASE WHEN COL8 = 0 THEN NULL ELSE COL8 END AS COL8,
  CASE WHEN COL9 = 0 THEN NULL ELSE COL9 END AS COL9,         
  CASE WHEN COL10 = 0 THEN NULL ELSE COL10 END AS COL10,
  CASE WHEN COL11 = 0 THEN NULL ELSE COL11 END AS COL11,
  CASE WHEN COL12 = 0 THEN NULL ELSE COL12 END AS COL12, 
  CASE WHEN COL13 = 0 THEN NULL ELSE COL13 END AS COL13,
  CASE WHEN COL14 = 0 THEN NULL ELSE COL14 END AS COL14   
  
FROM  
(
SELECT
  C.DENUMIRE AS LOCALITATE,
  C.CODUL,
  R.DENUMIRE,
  R.RIND,
  R.ORDINE,
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1022 THEN D.COL1 END))-
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1023 THEN D.COL1 END)) AS COL1,
  
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1022 THEN D.COL2 END))-
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1023 THEN D.COL2 END)) AS COL2,
  
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1022 THEN D.COL3 END))-
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1023 THEN D.COL3 END)) AS COL3,
  
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1022 THEN D.COL4 END))-
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1023 THEN D.COL4 END)) AS COL4,
  
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1022 THEN D.COL5 END))-
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1023 THEN D.COL5 END)) AS COL5,
  
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1022 THEN D.COL6 END))-
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1023 THEN D.COL6 END)) AS COL6,
  
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1022 THEN D.COL7 END))-
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1023 THEN D.COL7 END)) AS COL7,
  
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1022 THEN D.COL8 END))-
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1023 THEN D.COL8 END)) AS COL8,
  
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1022 THEN D.COL9 END))-
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1023 THEN D.COL9 END)) AS COL9,
  
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1022 THEN D.COL10 END))-
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1023 THEN D.COL10 END)) AS COL10,
  
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1022 THEN D.COL11 END))-
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1023 THEN D.COL11 END)) AS COL11,
  
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1022 THEN D.COL12 END))-
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1023 THEN D.COL12 END)) AS COL12,
  
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1022 THEN D.COL13 END))-
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1023 THEN D.COL13 END)) AS COL13,
  
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1022 THEN D.COL14 END))-
  CIS2.NVAL(SUM(CASE WHEN D.RIND = R.RIND AND D.CAPITOL IN 1023 THEN D.COL14 END)) AS COL14
  
FROM 
  CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM E ON E.CUIIO = D.CUIIO AND E.CUIIO_VERS = D.CUIIO_VERS
  INNER JOIN CIS2.CL_TIP_LOCAL C ON C.CODUL = E.TIP_LOCAL
  CROSS JOIN (
      SELECT
        DENUMIRE,
        RIND,
        ORDINE
  
      FROM
        CIS2.MD_RIND
  
    WHERE
       CAPITOL = 1023 AND
       RIND NOT IN ('22','23')) R

WHERE
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND  
   D.FORM = 40 AND
   D.CAPITOL IN (1022,1023) AND
   E.TIP_LOCAL IN (1,2)
  
GROUP BY
  C.DENUMIRE,
  C.CODUL,
  R.DENUMIRE,
  R.RIND,
  R.ORDINE  
) D
  
ORDER BY CODUL, ORDINE