SELECT DISTINCT 
  'Col.'||C.COL||': '|| 
  SUM(CASE WHEN D.RIND IN ('2000') THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2) ELSE 0 END) ||' < '||
  SUM(CASE WHEN D.RIND IN ('2300','2400','2500') THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2) ELSE 0 END)
  AS REZULTAT
--Rind 2000  Col.1, 2 >= Rind (2300+2400+2500)  Col.1, 2
FROM
  VW_DATA_ALL D,
  (
    SELECT 1 AS COL FROM DUAL UNION
    SELECT 2 AS COL FROM DUAL
  ) C

WHERE
  (D.PERIOADA=:PERIOADA         ) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (1)  AND
  D.CAPITOL in (1) AND
  D.RIND IN('2000','2300','2400','2500')
GROUP BY
  C.COL
  
HAVING
  SUM(CASE WHEN D.RIND     IN('2000') THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2) ELSE 0 END) < 
  SUM(CASE WHEN D.RIND  IN ('2300','2400','2500') THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2) ELSE 0 END)