--CAP.STOC Col.1 = Col.2 (trim-1)
SELECT 
    'Rind.'||D.RIND||': '||
    NVAL(SUM(CASE WHEN D.PERIOADA IN :PERIOADA  THEN D.COL1 ELSE 0 END))||' <> '||
    NVAL(SUM(CASE WHEN D.PERIOADA IN :PERIOADA-1  THEN D.COL2 ELSE 0 END)) AS REZULTAT

FROM
  CIS.VW_DATA_ALL D 

INNER JOIN 
  ( 
SELECT D.CUIIO, D.ID_MD,D.RIND, D.RIND_VERS
 FROM
  CIS.VW_DATA_ALL D
  WHERE 
   (D.PERIOADA IN(:PERIOADA-1)) AND
   (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
   (:CUIIO_VERS=:CUIIO_VERS      OR :CUIIO_VERS <> :CUIIO_VERS ) AND
   (D.FORM = :FORM               OR :FORM = -1) AND
   (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
   (:CAPITOL =:CAPITOL           OR :CAPITOL <> :CAPITOL) AND
   (:CAPITOL_VERS =:CAPITOL_VERS OR :CAPITOL_VERS <> :CAPITOL_VERS) AND
   (:ID_MD = :ID_MD              OR  :ID_MD <> :ID_MD ) AND
   D.FORM = 1 AND
   D.CAPITOL = 1
   AND D.RIND NOT IN ('2600','2000','2200')
   AND (D.COL2 <> 0 OR D.COL2 IS NOT NULL)  
   
   
   )DDD ON (DDD.CUIIO = D.CUIIO  AND DDD.ID_MD = D.ID_MD AND D.RIND = DDD.RIND AND  D.RIND_VERS  = DDD.RIND_VERS)
      
   
  WHERE 
  (D.PERIOADA IN(:PERIOADA-1,:PERIOADA )) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
 ( :CUIIO_VERS=:CUIIO_VERS      OR :CUIIO_VERS <> :CUIIO_VERS ) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL = :CAPITOL           OR :CAPITOL <> :CAPITOL ) AND
  (:CAPITOL_VERS =:CAPITOL_VERS  OR :CAPITOL_VERS <> :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
   D.FORM = 1 AND
   D.CAPITOL = 1
   
   AND D.RIND NOT IN ('2600','2000','2200')
 
   
   GROUP BY 
   D.RIND
   
   
   
   
   HAVING (
   (NVAL(SUM(CASE WHEN D.PERIOADA IN :PERIOADA  THEN D.COL1 ELSE 0 END)) <
   (NVAL(SUM(CASE WHEN D.PERIOADA IN :PERIOADA-1   THEN D.COL2 ELSE 0 END))*0.9)
  
  OR
  
   NVAL(SUM(CASE WHEN D.PERIOADA IN :PERIOADA  THEN D.COL1 ELSE 0 END)) >
  (NVAL(SUM(CASE WHEN D.PERIOADA IN :PERIOADA-1 THEN D.COL2 ELSE 0 END))*1.1) )) 