SELECT
--CAP.STOC Col.1 = Col.2 (trim-1)
  'RIND '||D.RIND||' - col.1 : '||
  CIS.NVAL(SUM(CASE WHEN D.CAPITOL IN (1) AND D.PERIOADA IN (:PERIOADA)   THEN  NVAL(D.COL1) ELSE NULL END)) ||' <> : col.2 - '||
  CIS.NVAL(SUM(CASE WHEN D.CAPITOL IN (1) AND D.PERIOADA IN (:PERIOADA-1)  THEN  NVAL(D.COL2) ELSE NULL END))   
  AS REZULTAT
  
FROM VW_DATA_ALL D


WHERE
  (D.PERIOADA IN (:PERIOADA,:PERIOADA-1 ))   AND
  (D.CUIIO =:CUIIO               OR :CUIIO = -1) AND 
  (:CUIIO_VERS =  :CUIIO_VERS     OR :CUIIO_VERS <>  :CUIIO_VERS) AND
  (D.FORM = :FORM               OR :FORM = -1) AND  
  (D.FORM_VERS=:FORM_VERS       OR  D.FORM_VERS <>  :FORM_VERS) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (:CAPITOL_VERS=:CAPITOL_VERS  OR :CAPITOL_VERS <>  :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (1)  AND
  D.CAPITOL IN (1)   
 
 AND D.RIND NOT  IN ('2600','2000','2200')
 
 
GROUP BY 
D.RIND
  


HAVING
  SUM(CASE WHEN D.CAPITOL IN (1) AND D.PERIOADA IN (:PERIOADA)   THEN   NVAL(D.COL1) ELSE 0 END) <> 
  SUM(CASE WHEN D.CAPITOL IN (1) AND D.PERIOADA IN (:PERIOADA-1)  THEN  NVAL(D.COL2) ELSE 0 END)   

AND
  (
  SELECT
  DISTINCT
  D.CUIIO
FROM
  CIS.VW_DATA_ALL D
WHERE
  (D.PERIOADA IN (:PERIOADA)) AND
  (D.CUIIO=:CUIIO ) AND
   D.FORM  IN(1) 
   AND
   D.CAPITOL IN (1)   
   AND D.RIND NOT  IN ('2600','2000','2200')
   
   
   ) IS NOT NULL