
SELECT DISTINCT 
  'Col.'||C.COL||': '|| 
  'Rind.0100='||SUM(CASE WHEN D.RIND IN('0100') THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2) ELSE 0 END) ||', dar '||
  'Rind.0200='||SUM(CASE WHEN D.RIND IN('0190') THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2) ELSE 0 END)
  AS REZULTAT

FROM
  VW_DATA_ALL_TEMP D,
  (
    SELECT 1 AS COL FROM DUAL
  ) C

WHERE
  (D.PERIOADA=:PERIOADA         ) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (1)  AND
  D.CAPITOL in (2) AND
  D.RIND IN('0100','0200')
GROUP BY
  C.COL
  
HAVING
  SUM(CASE WHEN D.RIND IN('0100') THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2) ELSE 0 END) > 0 AND
  SUM(CASE WHEN D.RIND IN('0200') THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2) ELSE 0 END) =  0
